# Article 6. Responsibility {.unnumbered}

### (720 ILCS 5/6-1) (from Ch. 38, par. 6-1)
## Sec. 6-1. Infancy.
<p>No person shall be convicted of any offense unless he had attained his 13th birthday at the time the offense was committed.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/6-2) (from Ch. 38, par. 6-2)
## Sec. 6-2. Insanity.
<p class='subsection'>\(a) A person is not criminally responsible for conduct if at the time of such conduct, as a result of mental disease or mental defect, he lacks substantial capacity to appreciate the criminality of his conduct.</p><p class='subsection'>\(b) The terms "mental disease or mental defect" do not include an abnormality manifested only by repeated criminal or otherwise antisocial conduct.</p><p class='subsection'>\(c) A person who, at the time of the commission of a criminal offense, was not insane but was suffering from a mental illness, is not relieved of criminal responsibility for his conduct and may be found guilty but mentally ill.</p><p class='subsection'>\(d) For purposes of this Section, "mental illness" or "mentally ill" means a substantial disorder of thought, mood, or behavior which afflicted a person at the time of the commission of the offense and which impaired that person's judgment, but not to the extent that he is unable to appreciate the wrongfulness of his behavior.</p><p class='subsection'>\(e) When the defense of insanity has been presented during the trial, the burden of proof is on the defendant to prove by clear and convincing evidence that the defendant is not guilty by reason of insanity. However, the burden of proof remains on the State to prove beyond a reasonable doubt each of the elements of each of the offenses charged, and, in a jury trial where the insanity defense has been presented, the jury must be instructed that it may not consider whether the defendant has met his burden of proving that he is not guilty by reason of insanity until and unless it has first determined that the State has proven the defendant guilty beyond a reasonable doubt of the offense with which he is charged.</p><p>(Source: P.A. 89-404, eff. 8-20-95; 90-593, eff. 6-19-98.)</p>### (720 ILCS 5/6-3) (from Ch. 38, par. 6-3)
## Sec. 6-3. Intoxicated or drugged condition.
<p>A person who is in an intoxicated or drugged condition is criminally responsible for conduct unless such condition is involuntarily produced and deprives him of substantial capacity either to appreciate the criminality of his conduct or to conform his conduct to the requirements of law.</p><p>(Source: P.A. 92-466, eff. 1-1-02.)</p>### (720 ILCS 5/6-4) (from Ch. 38, par. 6-4)
## Sec. 6-4. Affirmative Defense.
<p>A defense based upon any of the provisions of Article 6 is an affirmative defense except that mental illness is not an affirmative defense, but an alternative plea or finding that may be accepted, under appropriate evidence, when the affirmative defense of insanity is raised or the plea of guilty but mentally ill is made.</p><p>(Source: P.A. 82-553.)</p>