# Article 26. Disorderly Conduct {.unnumbered}

### (720 ILCS 5/26-1) (from Ch. 38, par. 26-1)
## Sec. 26-1. Disorderly conduct.
<p class='subsection'>\(a) A person commits disorderly conduct when he or she knowingly:</p><p class='paragraph'>\(1) Does any act in such unreasonable manner as to alarm or disturb another and to provoke a breach of the peace;</p><p class='paragraph'>\(2) Transmits or causes to be transmitted in any manner to the fire department of any city, town, village or fire protection district a false alarm of fire, knowing at the time of the transmission that there is no reasonable ground for believing that the fire exists;</p><p class='paragraph'>\(3) Transmits or causes to be transmitted in any manner to another a false alarm to the effect that a bomb or other explosive of any nature or a container holding poison gas, a deadly biological or chemical contaminant, or radioactive substance is concealed in a place where its explosion or release would endanger human life, knowing at the time of the transmission that there is no reasonable ground for believing that the bomb, explosive or a container holding poison gas, a deadly biological or chemical contaminant, or radioactive substance is concealed in the place;</p><p class='paragraph'>\(3.5) Transmits or causes to be transmitted in any manner a threat of destruction of a school building or school property, or a threat of violence, death, or bodily harm directed against persons at a school, school function, or school event, whether or not school is in session;</p><p class='paragraph'>\(4) Transmits or causes to be transmitted in any manner to any peace officer, public officer or public employee a report to the effect that an offense will be committed, is being committed, or has been committed, knowing at the time of the transmission that there is no reasonable ground for believing that the offense will be committed, is being committed, or has been committed;</p><p class='paragraph'>\(5) Transmits or causes to be transmitted in any manner a false report to any public safety agency without the reasonable grounds necessary to believe that transmitting the report is necessary for the safety and welfare of the public; or</p><p class='paragraph'>\(6) Calls the number "911" or transmits or causes to be transmitted in any manner to a public safety agency for the purpose of making or transmitting a false alarm or complaint and reporting information when, at the time the call or transmission is made, the person knows there is no reasonable ground for making the call or transmission and further knows that the call or transmission could result in the emergency response of any public safety agency;</p><p class='paragraph'>\(7) Transmits or causes to be transmitted in any manner a false report to the Department of Children and Family Services under Section 4 of the Abused and Neglected Child Reporting Act;</p><p class='paragraph'>\(8) Transmits or causes to be transmitted in any manner a false report to the Department of Public Health under the Nursing Home Care Act, the Specialized Mental Health Rehabilitation Act of 2013, the ID/DD Community Care Act, or the MC/DD Act;</p><p class='paragraph'>\(9) Transmits or causes to be transmitted in any manner to the police department or fire department of any municipality or fire protection district, or any privately owned and operated ambulance service, a false request for an ambulance, emergency medical technician-ambulance or emergency medical technician-paramedic knowing at the time there is no reasonable ground for believing that the assistance is required;</p><p class='paragraph'>\(10) Transmits or causes to be transmitted in any manner a false report under Article II of Public Act 83-1432;</p><p class='paragraph'>\(11) Enters upon the property of another and for a lewd or unlawful purpose deliberately looks into a dwelling on the property through any window or other opening in it; or</p><p class='paragraph'>\(12) While acting as a collection agency as defined in the Collection Agency Act or as an employee of the collection agency, and while attempting to collect an alleged debt, makes a telephone call to the alleged debtor which is designed to harass, annoy or intimidate the alleged debtor.</p><p class='subsection'>\(b) Sentence. A violation of subsection (a)(1) of this Section is a Class C misdemeanor. A violation of subsection (a)(5) or (a)(11) of this Section is a Class A misdemeanor. A violation of subsection (a)(8) or (a)(10) of this Section is a Class B misdemeanor. A violation of subsection (a)(2), (a)(3.5), (a)(4), (a)(6), (a)(7), or (a)(9) of this Section is a Class 4 felony. A violation of subsection (a)(3) of this Section is a Class 3 felony, for which a fine of not less than $3,000 and no more than $10,000 shall be assessed in addition to any other penalty imposed.</p><p>A violation of subsection (a)(12) of this Section is a Business Offense and shall be punished by a fine not to exceed $3,000. A second or subsequent violation of subsection (a)(7) or (a)(5) of this Section is a Class 4 felony. A third or subsequent violation of subsection (a)(11) of this Section is a Class 4 felony.</p><p class='subsection'>\(c) In addition to any other sentence that may be imposed, a court shall order any person convicted of disorderly conduct to perform community service for not less than 30 and not more than 120 hours, if community service is available in the jurisdiction and is funded and approved by the county board of the county where the offense was committed. In addition, whenever any person is placed on supervision for an alleged offense under this Section, the supervision shall be conditioned upon the performance of the community service.</p><p>This subsection does not apply when the court imposes a sentence of incarceration.</p><p class='subsection'>\(d) In addition to any other sentence that may be imposed, the court shall order any person convicted of disorderly conduct under paragraph (3) of subsection (a) involving a false alarm of a threat that a bomb or explosive device has been placed in a school that requires an emergency response to reimburse the unit of government that employs the emergency response officer or officers that were dispatched to the school for the cost of the response. If the court determines that the person convicted of disorderly conduct that requires an emergency response to a school is indigent, the provisions of this subsection (d) do not apply.</p><p class='subsection'>\(e) In addition to any other sentence that may be imposed, the court shall order any person convicted of disorderly conduct under paragraph (3.5) or (6) of subsection (a) to reimburse the public agency for the reasonable costs of the emergency response by the public agency up to $10,000. If the court determines that the person convicted of disorderly conduct under paragraph (3.5) or (6) of subsection (a) is indigent, the provisions of this subsection (e) do not apply.</p><p class='subsection'>\(f) For the purposes of this Section, "emergency response" means any condition that results in, or could result in, the response of a public official in an authorized emergency vehicle, any condition that jeopardizes or could jeopardize public safety and results in, or could result in, the evacuation of any area, building, structure, vehicle, or of any other place that any person may enter, or any incident requiring a response by a police officer, a firefighter, a State Fire Marshal employee, or an ambulance.</p><p>(Source: P.A. 101-238, eff. 1-1-20 .)</p>### (720 ILCS 5/26-1.1)
## Sec. 26-1.1. False report of theft and other losses.
<p class='subsection'>\(a) A person who knowingly makes a false report of a theft, destruction, damage or conversion of any property to a law enforcement agency or other governmental agency with the intent to defraud an insurer is guilty of a Class A misdemeanor.</p><p class='subsection'>\(b) A person convicted of a violation of this Section a second or subsequent time is guilty of a Class 4 felony.</p><p>(Source: P.A. 97-597, eff. 1-1-12.)</p>### (720 ILCS 5/26-2) (from Ch. 38, par. 26-2)
## Sec. 26-2. Interference with emergency communication.
<p class='subsection'>\(a) A person commits interference with emergency communication when he or she knowingly, intentionally and without lawful justification interrupts, disrupts, impedes, or otherwise interferes with the transmission of a communication over a citizens band radio channel, the purpose of which communication is to inform or inquire about an emergency.</p><p class='subsection'>\(b) For the purpose of this Section, "emergency" means a condition or circumstance in which an individual is or is reasonably believed by the person transmitting the communication to be in imminent danger of serious bodily injury or in which property is or is reasonably believed by the person transmitting the communication to be in imminent danger of damage or destruction.</p><p class='subsection'>\(c) Sentence.</p><p class='paragraph'>\(1) Interference with emergency communication is a Class B misdemeanor, except as otherwise provided in paragraph (2).</p><p class='paragraph'>\(2) Interference with emergency communication, where serious bodily injury or property loss in excess of $1,000 results, is a Class A misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26-3) (from Ch. 38, par. 26-3)
## Sec. 26-3. Use of a facsimile machine in unsolicited advertising or fund-raising.
<p class='subsection'>\(a) Definitions:</p><p class='paragraph'>\(1) "Facsimile machine" means a device which is capable of sending or receiving facsimiles of documents through connection with a telecommunications network.</p><p class='paragraph'>\(2) "Person" means an individual, public or private corporation, unit of government, partnership or unincorporated association.</p><p class='subsection'>\(b) A person commits use of a facsimile machine in unsolicited advertising or fund-raising when he or she knowingly uses a facsimile machine to send or cause to be sent to another person a facsimile of a document containing unsolicited advertising or fund-raising material, except to a person which the sender knows or under all of the circumstances reasonably believes has given the sender permission, either on a case by case or continuing basis, for the sending of the material.</p><p class='subsection'>\(c) Sentence. Any person who violates subsection (b) is guilty of a petty offense and shall be fined an amount not to exceed $500.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26-4) (from Ch. 38, par. 26-4)
## Sec. 26-4. Unauthorized video recording and live video transmission.
<p class='subsection'>\(a) It is unlawful for any person to knowingly make a video record or transmit live video of  another person without that person's consent in a restroom, tanning bed, tanning salon, locker room, changing room, or hotel bedroom.</p><p class='subsection'>\(a-5) It is unlawful for any person to knowingly make a video record or transmit live video of another person in that other person's residence without that person's consent.</p><p class='subsection'>\(a-6) It is unlawful for any person to knowingly make a video record or transmit live video of another person in that other person's residence without that person's consent when the recording or transmission is made outside that person's residence by use of an audio or video device that records or transmits from a remote location.</p><p class='subsection'>\(a-10) It is unlawful for any person to knowingly make a video record or transmit live video of another person's intimate parts  for the purpose of viewing the body of or the undergarments worn by that other person without that person's consent. For the purposes of this subsection (a-10), "intimate parts" means the fully unclothed, partially unclothed, or transparently clothed genitals, pubic area, anus, or if the person is female, a partially or fully exposed nipple, including exposure through transparent clothing.</p><p class='subsection'>\(a-15) It is unlawful for any person to place or cause to be placed a device that makes a video record or transmits a live video in a restroom, tanning bed, tanning salon, locker room, changing room, or hotel bedroom with the intent to make a video record or transmit live video of another person without that person's consent.</p><p class='subsection'>\(a-20) It is unlawful for any person to place or cause to be placed a device that makes a video record or transmits a live video with the intent to make a video record or transmit live video of another person in that other person's residence without that person's consent.</p><p class='subsection'>\(a-25) It is unlawful for any person to, by any means, knowingly disseminate, or permit to be disseminated, a video record or live video that he or she knows to have been made or transmitted in violation of (a), (a-5), (a-6), (a-10), (a-15), or (a-20).</p><p class='subsection'>\(b) Exemptions. The following activities shall be exempt from the provisions of this Section:</p><p class='paragraph'>\(1) The making of a video record or transmission of live video by law enforcement officers pursuant to a criminal investigation, which is otherwise lawful;</p><p class='paragraph'>\(2) The making of a video record or transmission of live video by correctional officials for security reasons or for investigation of alleged misconduct involving a person committed to the Department of Corrections; and</p><p class='paragraph'>\(3) The making of a video record or transmission of live video in a locker room by a reporter or news medium, as those terms are defined in Section 8-902 of the Code of Civil Procedure, where the reporter or news medium has been granted access to the locker room by an appropriate authority for the purpose of conducting interviews.</p><p class='subsection'>\(c) The provisions of this Section do not apply to any sound recording or transmission of an oral conversation made as the result of the making of a video record or transmission of live video, and to which Article 14 of this Code applies.</p><p class='subsection'>\(d) Sentence.</p><p class='paragraph'>\(1) A violation of subsection (a-15) or (a-20) is a Class A misdemeanor.</p><p class='paragraph'>\(2) A violation of subsection (a), (a-5), (a-6), or</p><p class='subsection'>\(a-10) is a Class 4 felony.</p><p class='paragraph'>\(3) A violation of subsection (a-25) is a Class 3 felony.</p><p class='paragraph'>\(4) A violation of subsection (a), (a-5), (a-6),</p><p class='subsection'>\(a-10), (a-15) or (a-20) is a Class 3 felony if the victim is a person under 18 years of age or if the violation is committed by an individual who is required to register as a sex offender under the Sex Offender Registration Act.</p><p class='paragraph'>\(5) A violation of subsection (a-25) is a Class 2 felony if the victim is a person under 18 years of age or if the violation is committed by an individual who is required to register as a sex offender under the Sex Offender Registration Act.</p><p class='subsection'>\(e) For purposes of this Section:</p><p class='paragraph'>\(1) "Residence" includes a rental dwelling, but does not include stairwells, corridors, laundry facilities, or additional areas in which the general public has access.</p><p class='paragraph'>\(2) "Video record" means and includes any videotape, photograph, film, or other electronic or digital recording of a still or moving visual image; and "live video" means and includes any real-time or contemporaneous electronic or digital transmission of a still or moving visual image.</p><p>(Source: P.A. 102-567, eff. 1-1-22 .)</p>### (720 ILCS 5/26-4.5)
## Sec. 26-4.5. Consumer communications privacy.
<p class='subsection'>\(a) For purposes of this Section, "communications company" means any person or organization which owns, controls, operates or manages any company which provides information or entertainment electronically to a household, including but not limited to a cable or community antenna television system.</p><p class='subsection'>\(b) It shall be unlawful for a communications company to:</p><p class='paragraph'>\(1) install and use any equipment which would allow a communications company to visually observe or listen to what is occurring in an individual subscriber's household without the knowledge or permission of the subscriber;</p><p class='paragraph'>\(2) provide any person or public or private organization with a list containing the name of a subscriber, unless the communications company gives notice thereof to the subscriber;</p><p class='paragraph'>\(3) disclose the television viewing habits of any individual subscriber without the subscriber's consent; or</p><p class='paragraph'>\(4) install or maintain a home-protection scanning device in a dwelling as part of a communication service without the express written consent of the occupant.</p><p class='subsection'>\(c) Sentence. A violation of this Section is a business offense, punishable by a fine not to exceed $10,000 for each violation.</p><p class='subsection'>\(d) Civil liability. Any person who has been injured by a violation of this Section may commence an action in the circuit court for damages against any communications company which has committed a violation. If the court awards damages, the plaintiff shall be awarded costs.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26-5)
<p>(This Section was renumbered as Section 48-1 by P.A. 97-1108.)</p>## Sec. 26-5. (Renumbered).
<p>(Source: P.A. 96-226, eff. 8-11-09; 96-712, eff. 1-1-10; 96-1000, eff. 7-2-10; 96-1091, eff. 1-1-11. Renumbered by P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26-6)
## Sec. 26-6. Disorderly conduct at a funeral or memorial service.
<p class='subsection'>\(a) The General Assembly finds and declares that due to the unique nature of funeral and memorial services and the heightened opportunity for extreme emotional distress on such occasions, the purpose of this Section is to protect the privacy and ability to mourn of grieving families directly before, during, and after a funeral or memorial service.</p><p class='subsection'>\(b) For purposes of this Section:</p><p class='paragraph'>\(1) "Funeral" means the ceremonies, rituals, processions, and memorial services held at a funeral site in connection with the burial, cremation, or memorial of a deceased person.</p><p class='paragraph'>\(2) "Funeral site" means a church, synagogue, mosque, funeral home, mortuary, cemetery, gravesite, mausoleum, or other place at which a funeral is conducted or is scheduled to be conducted within the next 30 minutes or has been conducted within the last 30 minutes.</p><p class='subsection'>\(c) A person commits the offense of disorderly conduct at a funeral or memorial service when he or she:</p><p class='paragraph'>\(1) engages, with knowledge of the existence of a funeral site, in any loud singing, playing of music, chanting, whistling, yelling, or noisemaking with, or without, noise amplification including, but not limited to, bullhorns, auto horns, and microphones within 300 feet of any ingress or egress of that funeral site, where the volume of such singing, music, chanting, whistling, yelling, or noisemaking is likely to be audible at and disturbing to the funeral site;</p><p class='paragraph'>\(2) displays, with knowledge of the existence of a funeral site and within 300 feet of any ingress or egress of that funeral site, any visual images that convey fighting words or actual or veiled threats against any other person; or</p><p class='paragraph'>\(3) with knowledge of the existence of a funeral site, knowingly obstructs, hinders, impedes, or blocks another person's entry to or exit from that funeral site or a facility containing that funeral site, except that the owner or occupant of property may take lawful actions to exclude others from that property.</p><p class='subsection'>\(d) Disorderly conduct at a funeral or memorial service is a Class C misdemeanor. A second or subsequent violation is a Class 4 felony.</p><p class='subsection'>\(e) If any clause, sentence, section, provision, or part of this Section or the application thereof to any person or circumstance is adjudged to be unconstitutional, the remainder of this Section or its application to persons or circumstances other than those to which it is held invalid, is not affected thereby.</p><p>(Source: P.A. 97-359, eff. 8-15-11.)</p>### (720 ILCS 5/26-7)
## Sec. 26-7. Disorderly conduct with a laser or laser pointer.
<p class='subsection'>\(a) Definitions. For the purposes of this Section:</p><p>"Aircraft" means any contrivance now known or hereafter invented, used, or designed for navigation of or flight in the air, but excluding parachutes.</p><p>"Laser" means both of the following:</p><p class='paragraph'>\(1) any device that utilizes the natural oscillations of atoms or molecules between energy levels for generating coherent electromagnetic radiation in the ultraviolet, visible, or infrared region of the spectrum and when discharged exceeds one milliwatt continuous wave;</p><p class='paragraph'>\(2) any device designed or used to amplify electromagnetic radiation by simulated emission that is visible to the human eye.</p><p>"Laser pointer" means a hand-held device that emits light amplified by the stimulated emission of radiation that is visible to the human eye.</p><p>"Laser sight" means a laser pointer that can be attached to a firearm and can be used to improve the accuracy of the firearm.</p><p class='subsection'>\(b) A person commits disorderly conduct with a laser or laser pointer when he or she intentionally or knowingly:</p><p class='paragraph'>\(1) aims an operating laser pointer at a person he or she knows or reasonably should know to be a peace officer; or</p><p class='paragraph'>\(2) aims and discharges a laser or other device that creates visible light into the cockpit of an aircraft that is in the process of taking off, landing, or is in flight.</p><p class='subsection'>\(c) Paragraph (2) of subsection (b) does not apply to the following individuals who aim and discharge a laser or other device at an aircraft:</p><p class='paragraph'>\(1) an authorized individual in the conduct of research and development or flight test operations conducted by an aircraft manufacturer, the Federal Aviation Administration, or any other person authorized by the Federal Aviation Administration to conduct this research and development or flight test operations; or</p><p class='paragraph'>\(2) members or elements of the Department of Defense or Department of Homeland Security acting in an official capacity for the purpose of research, development, operations, testing, or training.</p><p class='subsection'>\(d) Sentence. Disorderly conduct with a laser or laser pointer is a Class A misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>