# Article 7. Justifiable Use Of Force; Exoneration {.unnumbered}

### (720 ILCS 5/7-1) (from Ch. 38, par. 7-1)
## Sec. 7-1. Use of force in defense of person.
<p class='subsection'>\(a) A person is justified in the use of force against another when and to the extent that he reasonably believes that such conduct is necessary to defend himself or another against such other's imminent use of unlawful force. However, he is justified in the use of force which is intended or likely to cause death or great bodily harm only if he reasonably believes that such force is necessary to prevent imminent death or great bodily harm to himself or another, or the commission of a forcible felony.</p><p class='subsection'>\(b) In no case shall any act involving the use of force justified under this Section give rise to any claim or liability brought by or on behalf of any person acting within the definition of "aggressor" set forth in Section 7-4 of this Article, or the estate, spouse, or other family member of such a person, against the person or estate of the person using such justified force, unless the use of force involves willful or wanton misconduct.</p><p>(Source: P.A. 93-832, eff. 7-28-04 .)</p>### (720 ILCS 5/7-2) (from Ch. 38, par. 7-2)
## Sec. 7-2. Use of force in defense of dwelling.
<p class='subsection'>\(a) A person is justified in the use of force against another when and to the extent that he reasonably believes that such conduct is necessary to prevent or terminate such other's unlawful entry into or attack upon a dwelling. However, he is justified in the use of force which is intended or likely to cause death or great bodily harm only if:</p><p class='paragraph'>\(1) The entry is made or attempted in a violent, riotous, or tumultuous manner, and he reasonably believes that such force is necessary to prevent an assault upon, or offer of personal violence to, him or another then in the dwelling, or</p><p class='paragraph'>\(2) He reasonably believes that such force is necessary to prevent the commission of a felony in the dwelling.</p><p class='subsection'>\(b) In no case shall any act involving the use of force justified under this Section give rise to any claim or liability brought by or on behalf of any person acting within the definition of "aggressor" set forth in Section 7-4 of this Article, or the estate, spouse, or other family member of such a person, against the person or estate of the person using such justified force, unless the use of force involves willful or wanton misconduct.</p><p>(Source: P.A. 93-832, eff. 7-28-04.)</p>### (720 ILCS 5/7-3) (from Ch. 38, par. 7-3)
## Sec. 7-3. Use of force in defense of other property.
<p class='subsection'>\(a) A person is justified in the use of force against another when and to the extent that he reasonably believes that such conduct is necessary to prevent or terminate such other's trespass on or other tortious or criminal interference with either real property (other than a dwelling) or personal property, lawfully in his possession or in the possession of another who is a member of his immediate family or household or of a person whose property he has a legal duty to protect. However, he is justified in the use of force which is intended or likely to cause death or great bodily harm only if he reasonably believes that such force is necessary to prevent the commission of a forcible felony.</p><p class='subsection'>\(b) In no case shall any act involving the use of force justified under this Section give rise to any claim or liability brought by or on behalf of any person acting within the definition of "aggressor" set forth in Section 7-4 of this Article, or the estate, spouse, or other family member of such a person, against the person or estate of the person using such justified force, unless the use of force involves willful or wanton misconduct.</p><p>(Source: P.A. 93-832, eff. 7-28-04.)</p>### (720 ILCS 5/7-4) (from Ch. 38, par. 7-4)
## Sec. 7-4. Use of force by aggressor.
<p>The justification described in the preceding Sections of this Article is not available to a person who:</p><p class='subsection'>\(a) is attempting to commit, committing, or escaping after the commission of, a forcible felony; or</p><p class='subsection'>\(b) initially provokes the use of force against himself, with the intent to use such force as an excuse to inflict bodily harm upon the assailant; or</p><p class='subsection'>\(c) otherwise initially provokes the use of force against himself, unless:</p><p class='paragraph'>\(1) such force is so great that he reasonably believes that he is in imminent danger of death or great bodily harm, and that he has exhausted every reasonable means to escape such danger other than the use of force which is likely to cause death or great bodily harm to the assailant; or</p><p class='paragraph'>\(2) in good faith, he withdraws from physical contact with the assailant and indicates clearly to the assailant that he desires to withdraw and terminate the use of force, but the assailant continues or resumes the use of force.</p><p>(Source: Laws 1961, p. 1983 .)</p>### (720 ILCS 5/7-5) (from Ch. 38, par. 7-5)
## Sec. 7-5. Peace officer's use of force in making arrest.
<p class='subsection'>\(a) A peace officer, or any person whom he has summoned or directed to assist him, need not retreat or desist from efforts to make a lawful arrest because of resistance or threatened resistance to the arrest. He is justified in the use of any force which he reasonably believes, based on the totality of the circumstances, to be necessary to effect the arrest and of any force which he reasonably believes, based on the totality of the circumstances, to be necessary to defend himself or another from bodily harm while making the arrest. However, he is justified in using force likely to cause death or great bodily harm only when: (i) he reasonably believes, based on the totality of the circumstances, that such force is necessary to prevent death or great bodily harm to himself or such other person; or (ii) when he reasonably believes, based on the totality of the circumstances, both that:</p><p class='paragraph'>\(1) Such force is necessary to prevent the arrest from being defeated by resistance or escape and the officer reasonably believes that the person to be arrested is likely to cause great bodily harm to another; and</p><p class='paragraph'>\(2) The person to be arrested committed or attempted a forcible felony which involves the infliction or threatened infliction of great bodily harm or is attempting to escape by use of a deadly weapon, or otherwise indicates that he will endanger human life or inflict great bodily harm unless arrested without delay.</p><p>As used in this subsection, "retreat" does not mean tactical repositioning or other de-escalation tactics.</p><p>A peace officer is not justified in using force likely to cause death or great bodily harm when there is no longer an imminent threat of great bodily harm to the officer or another.</p><p class='subsection'>\(a-5) Where feasible, a peace officer shall, prior to the use of force, make reasonable efforts to identify himself or herself as a peace officer and to warn that deadly force may be used.</p><p class='subsection'>\(a-10) A peace officer shall not use deadly force against a person based on the danger that the person poses to himself or herself if a reasonable officer would believe the person does not pose an imminent threat of death or great bodily harm to the peace officer or to another person.</p><p class='subsection'>\(a-15) A peace officer shall not use deadly force against a person who is suspected of committing a property offense, unless that offense is terrorism or unless deadly force is otherwise authorized by law.</p><p class='subsection'>\(b) A peace officer making an arrest pursuant to an invalid warrant is justified in the use of any force which he would be justified in using if the warrant were valid, unless he knows that the warrant is invalid.</p><p class='subsection'>\(c) The authority to use physical force conferred on peace officers by this Article is a serious responsibility that shall be exercised judiciously and with respect for human rights and dignity and for the sanctity of every human life.</p><p class='subsection'>\(d) Peace officers shall use deadly force only when reasonably necessary in defense of human life. In determining whether deadly force is reasonably necessary, officers shall evaluate each situation in light of the totality of circumstances of each case, including, but not limited to, the proximity in time of the use of force to the commission of a forcible felony, and the reasonable feasibility of safely apprehending a subject at a later time, and shall use other available resources and techniques, if reasonably safe and feasible to a reasonable officer.</p><p class='subsection'>\(e) The decision by a peace officer to use force shall be evaluated carefully and thoroughly, in a manner that reflects the gravity of that authority and the serious consequences of the use of force by peace officers, in order to ensure that officers use force consistent with law and agency policies.</p><p class='subsection'>\(f) The decision by a peace officer to use force shall be evaluated from the perspective of a reasonable officer in the same situation, based on the totality of the circumstances known to or perceived by the officer at the time of the decision, rather than with the benefit of hindsight, and that the totality of the circumstances shall account for occasions when officers may be forced to make quick judgments about using force.</p><p class='subsection'>\(g) Law enforcement agencies are encouraged to adopt and develop policies designed to protect individuals with physical, mental health, developmental, or intellectual disabilities, or individuals who are significantly more likely to experience greater levels of physical force during police interactions, as these disabilities may affect the ability of a person to understand or comply with commands from peace officers.</p><p class='subsection'>\(h) As used in this Section:</p><p class='paragraph'>\(1) "Deadly force" means any use of force that creates a substantial risk of causing death or great bodily harm, including, but not limited to, the discharge of a firearm.</p><p class='paragraph'>\(2) A threat of death or serious bodily injury is</p><p>"imminent" when, based on the totality of the circumstances, a reasonable officer in the same situation would believe that a person has the present ability, opportunity, and apparent intent to immediately cause death or great bodily harm to the peace officer or another person. An imminent harm is not merely a fear of future harm, no matter how great the fear and no matter how great the likelihood of the harm, but is one that, from appearances, must be instantly confronted and addressed.</p><p class='paragraph'>\(3) "Totality of the circumstances" means all facts known to the peace officer at the time, or that would be known to a reasonable officer in the same situation, including the conduct of the officer and the subject leading up to the use of deadly force.</p><p>(Source: P.A. 101-652, eff. 7-1-21; 102-28, eff. 6-25-21; 102-687, eff. 12-17-21.)</p>### (720 ILCS 5/7-5.5)
## Sec. 7-5.5. Prohibited use of force by a peace officer.
<p class='subsection'>\(a) A peace officer, or any other person acting under the color of law, shall not use a chokehold or restraint above the shoulders with risk of asphyxiation in the performance of his or her duties, unless deadly force is justified under this Article.</p><p class='subsection'>\(b) A peace officer, or any other person acting under the color of law, shall not use a chokehold or restraint above the shoulders with risk of asphyxiation, or any lesser contact with the throat or neck area of another, in order to prevent the destruction of evidence by ingestion.</p><p class='subsection'>\(c) As used in this Section, "chokehold" means applying any direct pressure to the throat, windpipe, or airway of another. "Chokehold" does not include any holding involving contact with the neck that is not intended to reduce the intake of air such as a headlock where the only pressure applied is to the head.</p><p class='subsection'>\(d) As used in this Section, "restraint above the shoulders with risk of positional asphyxiation" means a use of a technique used to restrain a person above the shoulders, including the neck or head, in a position which interferes with the person's ability to breathe after the person no longer poses a threat to the officer or any other person.</p><p class='subsection'>\(e) A peace officer, or any other person acting under the color of law, shall not:</p><p class='item'>\(i) use force as punishment or retaliation;</p><p class='item'>\(ii) discharge kinetic impact projectiles and all other non-lethal or less-lethal projectiles in a manner that targets the head, neck, groin, anterior pelvis, or back;</p><p class='item'>\(iii) discharge conducted electrical weapons in a manner that targets the head, chest, neck, groin, or anterior pelvis;</p><p class='item'>\(iv) discharge firearms or kinetic impact projectiles indiscriminately into a crowd;</p><p class='item'>\(v) use chemical agents or irritants for crowd control, including pepper spray and tear gas, prior to issuing an order to disperse in a sufficient manner to allow for the order to be heard and repeated if necessary, followed by sufficient time and space to allow compliance with the order unless providing such time and space would unduly place an officer or another person at risk of death or great bodily harm; or</p><p class='item'>\(vi) use chemical agents or irritants, including pepper spray and tear gas, prior to issuing an order in a sufficient manner to ensure the order is heard, and repeated if necessary, to allow compliance with the order unless providing such time and space would unduly place an officer or another person at risk of death or great bodily harm.</p><p>(Source: P.A. 101-652, eff. 7-1-21; 102-28, eff. 6-25-21; 102-687, eff. 12-17-21.)</p>### (720 ILCS 5/7-6) (from Ch. 38, par. 7-6)
## Sec. 7-6. Private person's use of force in making arrest.
<p class='subsection'>\(a) A private person who makes, or assists another private person in making a lawful arrest is justified in the use of any force which he would be justified in using if he were summoned or directed by a peace officer to make such arrest, except that he is justified in the use of force likely to cause death or great bodily harm only when he reasonably believes that such force is necessary to prevent death or great bodily harm to himself or another.</p><p class='subsection'>\(b) A private person who is summoned or directed by a peace officer to assist in making an arrest which is unlawful, is justified in the use of any force which he would be justified in using if the arrest were lawful, unless he knows that the arrest is unlawful.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/7-7) (from Ch. 38, par. 7-7)
## Sec. 7-7. Private person's use of force in resisting arrest.
<p>A person is not authorized to use force to resist an arrest which he knows is being made either by a peace officer or by a private person summoned and directed by a peace officer to make the arrest, even if he believes that the arrest is unlawful and the arrest in fact is unlawful.</p><p>(Source: P.A. 86-1475.)</p>### (720 ILCS 5/7-8) (from Ch. 38, par. 7-8)
## Sec. 7-8. Force likely to cause death or great bodily harm.
<p class='subsection'>\(a) Force which is likely to cause death or great bodily harm, within the meaning of Sections 7-5 and 7-6 includes:</p><p class='paragraph'>\(1) The firing of a firearm in the direction of the person to be arrested, even though no intent exists to kill or inflict great bodily harm; and</p><p class='paragraph'>\(2) The firing of a firearm at a vehicle in which the person to be arrested is riding.</p><p class='subsection'>\(b) A peace officer's discharge of a firearm using ammunition designed to disable or control an individual without creating the likelihood of death or great bodily harm shall not be considered force likely to cause death or great bodily harm within the meaning of Sections 7-5 and 7-6.</p><p>(Source: P.A. 90-138, eff. 1-1-98.)</p>### (720 ILCS 5/7-9) (from Ch. 38, par. 7-9)
## Sec. 7-9. Use of force to prevent escape.
<p class='subsection'>\(a) A peace officer or other person who has an arrested person in his custody is justified in the use of force, except deadly force, to prevent the escape of the arrested person from custody as he would be justified in using if he were arresting such person.</p><p class='subsection'>\(b) A guard or other peace officer is justified in the use of force which he reasonably believes to be necessary to prevent the escape from a penal institution of a person whom the officer reasonably believes to be lawfully detained in such institution under sentence for an offense or awaiting trial or commitment for an offense.</p><p class='subsection'>\(c) Deadly force shall not be used to prevent escape under this Section unless, based on the totality of the circumstances, deadly force is necessary to prevent death or great bodily harm to himself or such other person.</p><p>(Source: P.A. 101-652, eff. 7-1-21 .)</p>### (720 ILCS 5/7-10) (from Ch. 38, par. 7-10)
## Sec. 7-10. Execution of death sentence.
<p>A public officer who, in the exercise of his official duty, puts a person to death pursuant to a sentence of a court of competent jurisdiction, is justified if he acts in accordance with the sentence pronounced and the law prescribing the procedure for execution of a death sentence.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/7-11) (from Ch. 38, par. 7-11)
## Sec. 7-11. Compulsion.
<p class='subsection'>\(a) A person is not guilty of an offense, other than an offense punishable with death, by reason of conduct that he or she performs under the compulsion of threat or menace of the imminent infliction of death or great bodily harm, if he or she reasonably believes death or great bodily harm will be inflicted upon him or her, or upon his or her spouse or child, if he or she does not perform that conduct.</p><p class='subsection'>\(b) A married woman is not entitled, by reason of the presence of her husband, to any presumption of compulsion or to any defense of compulsion, except that stated in subsection (a).</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/7-12) (from Ch. 38, par. 7-12)
## Sec. 7-12. Entrapment.
<p>A person is not guilty of an offense if his or her conduct is incited or induced by a public officer or employee, or agent of either, for the purpose of obtaining evidence for the prosecution of that person. However, this Section is inapplicable if the person was pre-disposed to commit the offense and the public officer or employee, or agent of either, merely affords to that person the opportunity or facility for committing an offense.</p><p>(Source: P.A. 89-332, eff. 1-1-96.)</p>### (720 ILCS 5/7-13) (from Ch. 38, par. 7-13)
## Sec. 7-13. Necessity.
<p>Conduct which would otherwise be an offense is justifiable by reason of necessity if the accused was without blame in occasioning or developing the situation and reasonably believed such conduct was necessary to avoid a public or private injury greater than the injury which might reasonably result from his own conduct.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/7-14) (from Ch. 38, par. 7-14)
## Sec. 7-14. Affirmative defense.
<p>A defense of justifiable use of force, or of exoneration, based on the provisions of this Article is an affirmative defense.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/7-15)
## Sec. 7-15. Duty to render aid.
<p>It is the policy of the State of Illinois that all law enforcement officers must, as soon as reasonably practical, determine if a person is injured, whether as a result of a use of force or otherwise, and render medical aid and assistance consistent with training and request emergency medical assistance if necessary. "Render medical aid and assistance" includes, but is not limited to, (i) performing emergency life-saving procedures such as cardiopulmonary resuscitation or the administration of an automated external defibrillator; and (ii) the making of arrangements for the carrying of such person to a physician, surgeon, or hospital for medical or surgical treatment if it is apparent that treatment is necessary, or if such carrying is requested by the injured person.</p><p>(Source: P.A. 101-652, eff. 7-1-21; 102-28, eff. 6-25-21.)</p>### (720 ILCS 5/7-16)
## Sec. 7-16. Duty to intervene.
<p class='subsection'>\(a) A peace officer, or any other person acting under the color of law who has an opportunity to intervene, shall have an affirmative duty to intervene to prevent or stop another peace officer in his or her presence from using any unauthorized force or force that exceeds the degree of force permitted, if any, without regard for chain of command.</p><p class='subsection'>\(b) A peace officer, or any other person acting under the color of law, who intervenes as required by this Section shall report the intervention to the person designated/identified by the law enforcement entity in a manner prescribed by the agency. The report required by this Section must include the date, time, and place of the occurrence; the identity, if known, and description of the participants; and a description of the intervention actions taken and whether they were successful. In no event shall the report be submitted more than 5 days after the incident.</p><p class='subsection'>\(c) A member of a law enforcement agency shall not discipline nor retaliate in any way against a peace officer for intervening as required in this Section or for reporting unconstitutional or unlawful conduct, or for failing to follow what the officer reasonably believes is an unconstitutional or unlawful directive.</p><p>(Source: P.A. 101-652, eff. 7-1-21; 102-28, eff. 6-25-21.)</p>### (720 ILCS 5/Tit. III heading)
<p>TITLE III.</p><p>SPECIFIC OFFENSES</p>### (720 ILCS 5/Tit. III Pt. A heading)
<p>PART A.</p><p>INCHOATE OFFENSES</p>