# Article 30. Treason And Related Offenses {.unnumbered}

### (720 ILCS 5/30-1) (from Ch. 38, par. 30-1)
## Sec. 30-1. Treason.
<p class='subsection'>\(a) A person owing allegiance to this State commits treason when he or she knowingly:</p><p class='paragraph'>\(1) levies war against this State; or</p><p class='paragraph'>\(2) adheres to the enemies of this State, giving them aid or comfort.</p><p class='subsection'>\(b) No person may be convicted of treason except on the testimony of 2 witnesses to the same overt act, or on his confession in open court.</p><p class='subsection'>\(c) Sentence. Treason is a Class X felony for which an offender may be sentenced to death under Section 5-5-3 of the Unified Code of Corrections.</p><p>(Source: P.A. 80-1099 .)</p>### (720 ILCS 5/30-2) (from Ch. 38, par. 30-2)
## Sec. 30-2. Misprision of treason.
<p class='subsection'>\(a) A person owing allegiance to this State commits misprision of treason when he or she knowingly conceals or withholds his or her knowledge that another has committed treason against this State.</p><p class='subsection'>\(b) Sentence.</p><p>Misprision of treason is a Class 4 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/30-3) (from Ch. 38, par. 30-3)
## Sec. 30-3. Advocating overthrow of Government.
<p>A person who advocates, or with knowledge of its contents knowingly publishes, sells or distributes any document which advocates or with knowledge of its purpose, knowingly becomes a member of any organization which advocates the overthrow or reformation of the existing form of government of this State by violence or unlawful means commits a Class 3 felony.</p><p>(Source: P.A. 77-2638.)</p>