# Article 15. Definitions {.unnumbered}

### (720 ILCS 5/15-1) (from Ch. 38, par. 15-1)
## Sec. 15-1. Property.
<p>As used in this Part C, "property" means anything of value. Property includes real estate, money, commercial instruments, admission or transportation tickets, written instruments representing or embodying rights concerning anything of value, labor, or services, or otherwise of value to the owner; things growing on, affixed to, or found on land, or part of or affixed to any building; electricity, gas and water; telecommunications services; birds, animals and fish, which ordinarily are kept in a state of confinement; food and drink; samples, cultures, microorganisms, specimens, records, recordings, documents, blueprints, drawings, maps, and whole or partial copies, descriptions, photographs, computer programs or data, prototypes or models thereof, or any other articles, materials, devices, substances and whole or partial copies, descriptions, photographs, prototypes, or models thereof which constitute, represent, evidence, reflect or record a secret scientific, technical, merchandising, production or management information, design, process, procedure, formula, invention, or improvement.</p><p>(Source: P.A. 88-75.)</p>### (720 ILCS 5/15-2) (from Ch. 38, par. 15-2)
## Sec. 15-2. Owner.
<p>As used in this Part C, "owner" means a person, other than the offender, who has possession of or any other interest in the property involved, even though such interest or possession is unlawful, and without whose consent the offender has no authority to exert control over the property.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/15-3) (from Ch. 38, par. 15-3)
## Sec. 15-3. Permanent deprivation.
<p>As used in this Part C, to "permanently deprive" means to:</p><p class='subsection'>\(a) Defeat all recovery of the property by the owner; or</p><p class='subsection'>\(b) Deprive the owner permanently of the beneficial use of the property; or</p><p class='subsection'>\(c) Retain the property with intent to restore it to the owner only if the owner purchases or leases it back, or pays a reward or other compensation for its return; or</p><p class='subsection'>\(d) Sell, give, pledge, or otherwise transfer any interest in the property or subject it to the claim of a person other than the owner.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/15-4) (from Ch. 38, par. 15-4)
## Sec. 15-4. Deception.
<p>As used in this Part C "deception" means knowingly to:</p><p class='subsection'>\(a) Create or confirm another's impression which is false and which the offender does not believe to be true; or</p><p class='subsection'>\(b) Fail to correct a false impression which the offender previously has created or confirmed; or</p><p class='subsection'>\(c) Prevent another from acquiring information pertinent to the disposition of the property involved; or</p><p class='subsection'>\(d) Sell or otherwise transfer or encumber property, failing to disclose a lien, adverse claim, or other legal impediment to the enjoyment of the property, whether such impediment is or is not valid, or is or is not a matter of official record; or</p><p class='subsection'>\(e) Promise performance which the offender does not intend to perform or knows will not be performed. Failure to perform standing alone is not evidence that the offender did not intend to perform.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/15-5) (from Ch. 38, par. 15-5)
## Sec. 15-5. Threat.
<p>As used in this Part C, "threat" means a menace, however communicated, to:</p><p class='subsection'>\(a) Inflict physical harm on the person threatened or any other person or on property; or</p><p class='subsection'>\(b) Subject any person to physical confinement or restraint; or</p><p class='subsection'>\(c) Commit any criminal offense; or</p><p class='subsection'>\(d) Accuse any person of a criminal offense; or</p><p class='subsection'>\(e) Expose any person to hatred, contempt or ridicule; or</p><p class='subsection'>\(f) Harm the credit or business repute of any person; or</p><p class='subsection'>\(g) Reveal any information sought to be concealed by the person threatened; or</p><p class='subsection'>\(h) Take action as an official against anyone or anything, or withhold official action, or cause such action or withholding; or</p><p class='item'>\(i) Bring about or continue a strike, boycott or other similar collective action if the property is not demanded or received for the benefit of the group which he purports to represent; or</p><p class='subsection'>\(j) Testify or provide information or withhold testimony or information with respect to another's legal claim or defense; or</p><p class='subsection'>\(k) Inflict any other harm which would not benefit the offender.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/15-6) (from Ch. 38, par. 15-6)
## Sec. 15-6. Stolen property.
<p>As used in this Part C, "stolen property" means property over which control has been obtained by theft.</p><p>(Source: Laws 1961, p. 1983 .)</p>### (720 ILCS 5/15-7) (from Ch. 38, par. 15-7)
## Sec. 15-7. Obtain.
<p>As used in this Part C, "obtain" means:</p><p class='subsection'>\(a) In relation to property, to bring about a transfer of interest or possession, whether to the offender or to another, and</p><p class='subsection'>\(b) In relation to labor or services, to secure the performance thereof.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/15-8) (from Ch. 38, par. 15-8)
## Sec. 15-8. Obtains control.
<p>As used in this Part C, the phrase "obtains or exerts control" over property, includes but is not limited to the taking, carrying away, or the sale, conveyance, or transfer of title to, or interest in, or possession of property.</p><p>(Source: Laws 1961, p. 1983 .)</p>### (720 ILCS 5/15-9) (from Ch. 38, par. 15-9)
## Sec. 15-9. Value.
<p>As used in this Part C, the "value" of property consisting of any commercial instrument or any written instrument representing or embodying rights concerning anything of value, labor, or services or otherwise of value to the owner shall be:</p><p class='subsection'>\(a) The "market value" of such instrument if such instrument is negotiable and has a market value; and</p><p class='subsection'>\(b) The "actual value" of such instrument if such instrument is not negotiable or is otherwise without a market value. For the purpose of establishing such "actual value", the interest of any owner or owners entitled to part or all of the property represented by such instrument, by reason of such instrument, may be shown, even if another "owner" may be named in the complaint, information or indictment.</p><p>(Source: Laws 1967, p. 2849.)</p>### (720 ILCS 5/15-10)
## Sec. 15-10. Governmental property.
<p>As used in this Part C, "governmental property" means funds or other property owned by the State, a unit of local government, or a school district.</p><p>(Source: P.A. 94-134, eff. 1-1-06.)</p>