# Ch. 11, Article IV. Crashes {.unnumbered}

### (625 ILCS 5/11-401) (from Ch. 95 1/2, par. 11-401)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-401. Motor vehicle crashes involving death or personal injuries.
<p class='subsection'>\(a) The driver of any vehicle involved in a motor vehicle crashes  resulting in personal injury to or death of any person shall immediately stop such vehicle at the scene of such crash, or as close thereto as possible and shall then forthwith return to, and in every event shall remain at the scene of the crash until the requirements of Section 11-403 have been fulfilled. Every such stop shall be made without obstructing traffic more than is necessary.</p><p class='subsection'>\(b) Any person who has failed to stop or to comply with the requirements of paragraph (a) shall, as soon as possible but in no case later than one-half hour after such motor vehicle crash, or, if hospitalized and incapacitated from reporting at any time during such period, as soon as possible but in no case later than one-half  hour after being discharged from the hospital, report the place of the crash, the date, the approximate time, the driver's name and address, the registration number of the vehicle driven, and the names of all other occupants of such vehicle, at a police station or sheriff's office near the place where such crash occurred. No report made as required under this paragraph shall be used, directly or indirectly, as a basis for the prosecution of any violation of paragraph (a).</p><p class='subsection'>\(b-1) Any person arrested for violating this Section is subject to chemical testing of his or her blood, breath, other bodily substance, or urine for the presence of alcohol, other drug or drugs, intoxicating compound or compounds, or any combination thereof, as provided in Section 11-501.1, if the testing occurs within 12 hours of the time of the occurrence of the crash that led to his or her arrest. The person's driving privileges are subject to statutory summary suspension under Section 11-501.1 if he or she fails testing or statutory summary revocation under Section 11-501.1 if he or she refuses to undergo the testing.</p><p>For purposes of this Section, personal injury shall mean any injury requiring immediate professional treatment in a medical facility or doctor's office.</p><p class='subsection'>\(c) Any person failing to comply with paragraph (a) shall be guilty of a Class 4 felony.</p><p class='subsection'>\(d) Any person failing to comply with paragraph (b) is guilty of a Class 2 felony if the motor vehicle crash does not result in the death of any person. Any person failing to comply with paragraph (b) when the crash results in the death of any person is guilty of a Class 1  felony.</p><p class='subsection'>\(e) The Secretary of State shall revoke the driving privilege of any person convicted of a violation of this Section.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-402) (from Ch. 95 1/2, par. 11-402)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-402. Motor vehicle crash involving damage to vehicle.
<p class='subsection'>\(a) The driver of any vehicle involved in a motor vehicle crash  resulting only in damage to a vehicle which is driven or attended by any person shall immediately stop such vehicle at the scene of such motor vehicle crash  or as close thereto as possible, but shall forthwith return to and in every event shall remain at the scene of such motor vehicle crash until the requirements of Section 11-403 have been fulfilled. A driver does not violate this Section if the driver moves the vehicle as soon as possible off the highway to the nearest safe location on an exit ramp shoulder, a frontage road, the nearest suitable cross street, or other suitable location that does not obstruct traffic and remains at that location until the driver has fulfilled the requirements of Section 11-403. Every such stop shall be made without obstructing traffic more than is necessary. If a damaged vehicle is obstructing traffic lanes, the driver of the vehicle must make every reasonable effort to move the vehicle or have it moved so as not to block the traffic lanes.</p><p>Any person failing to comply with this Section shall be guilty of a Class A misdemeanor.</p><p class='subsection'>\(b) Upon conviction of a violation of this Section, the court shall make a finding as to whether the damage to a vehicle is in excess of $1,000, and in such case a statement of this finding shall be reported to the Secretary of State with the report of conviction as required by Section 6-204 of this Code. Upon receipt of such report of conviction and statement of finding that the damage to a vehicle is in excess of $1,000, the Secretary of State shall suspend the driver's license or any nonresident's driving privilege.</p><p class='subsection'>\(c) If any peace officer or highway authority official finds (i) a vehicle standing upon a highway or toll highway in violation of a prohibition, limitation, or restriction on stopping, standing, or parking imposed under this Code or (ii) a disabled vehicle that obstructs the roadway of a highway or toll highway, the peace officer or highway authority official is authorized to move the vehicle or to require the operator of the vehicle to move the vehicle to the shoulder of the road, to a position where parking is permitted, or to public parking or storage premises. The removal may be performed by, or under the direction of, the peace officer or highway authority official or may be contracted for by local authorities. After the vehicle has been removed, the peace officer or highway authority official shall follow appropriate procedures, as provided in Section 4-203 of this Code.</p><p class='subsection'>\(d) A towing service, its officers, and its employees are not liable for loss of or damages to any real or personal property that occurs as the result of the removal or towing of any vehicle under subsection (c), as provided in subsection (b) of Section 4-213.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-403) (from Ch. 95 1/2, par. 11-403)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-403. Duty to give information and render aid.
<p>The driver of any vehicle involved in a motor vehicle crash  resulting in injury to or death of any person or damage to any vehicle which is driven or attended by any person shall give the driver's name, address, registration number and owner of the vehicle the driver is operating and shall upon request and if available exhibit such driver's license to the person struck or the driver or occupant of or person attending any vehicle collided with and shall render to any person injured in such crash reasonable assistance, including the carrying or the making of arrangements for the carrying of such person to a physician, surgeon or hospital for medical or surgical treatment, if it is apparent that such treatment is necessary or if such carrying is requested by the injured person.</p><p>If none of the persons entitled to information pursuant to this Section is in condition to receive and understand such information and no police officer is present, such driver after rendering reasonable assistance shall forthwith report such motor vehicle crash at the nearest office of a duly authorized police authority, disclosing the information required by this Section.</p><p>Any person failing to comply with this Section shall be guilty of a Class A misdemeanor.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-404) (from Ch. 95 1/2, par. 11-404)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-404. Duty upon damaging unattended vehicle or other property.
<p class='subsection'>\(a) The driver of any vehicle which collides with or is involved in a motor vehicle crash with any vehicle which is unattended, or other property, resulting in any damage to such other vehicle or property shall immediately stop and shall then and there either locate and notify the operator or owner of such vehicle or other property of the driver's name, address, registration number and owner of the vehicle the driver was operating or shall attach securely in a conspicuous place on or in the vehicle or other property struck a written notice giving the driver's name, address, registration number and owner of the vehicle the driver was driving and shall without unnecessary delay notify the nearest office of a duly authorized police authority and shall make a written report of such crash when and as required in Section 11-406. Every such stop shall be made without obstructing traffic more than is necessary. If a damaged vehicle is obstructing traffic lanes, the driver of the vehicle must make every reasonable effort to move the vehicle or have it moved so as not to block the traffic lanes.</p><p class='subsection'>\(b) Any person failing to comply with this Section shall be guilty of a Class A misdemeanor.</p><p class='subsection'>\(c) If any peace officer or highway authority official finds (i) a vehicle standing upon a highway or toll highway in violation of a prohibition, limitation, or restriction on stopping, standing, or parking imposed under this Code or (ii) a disabled vehicle that obstructs the roadway of a highway or toll highway, the peace officer or highway authority official is authorized to move the vehicle or to require the operator of the vehicle to move the vehicle to the shoulder of the road, to a position where parking is permitted, or to public parking or storage premises. The removal may be performed by, or under the direction of, the peace officer or highway authority official or may be contracted for by local authorities. After the vehicle has been removed, the peace officer or highway authority official shall follow appropriate procedures, as provided in Section 4-203 of this Code.</p><p class='subsection'>\(d) A towing service, its officers, and its employees are not liable for loss of or damages to any real or personal property that occurs as the result of the removal or towing of any vehicle under subsection (c), as provided in subsection (b) of Section 4-213.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-406)
## Sec. 11-406. (Repealed).
<p>(Source: P.A. 95-754, eff. 1-1-09. Repealed by P.A. 102-560, eff. 8-20-21.)</p>### (625 ILCS 5/11-407) (from Ch. 95 1/2, par. 11-407)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-407. Immediate notice of crash.
<p class='subsection'>\(a) The driver of a vehicle which is in any manner involved in a crash described in Section 11-406 of this Chapter shall, if no police officer is present, give notice of the crash by the fastest available means of communication to the local police department if such crash  occurs within a municipality or otherwise to the nearest office of the county sheriff or nearest headquarters of the Illinois State Police.</p><p class='subsection'>\(b) Whenever the driver of a vehicle is physically incapable of giving immediate notice of a crash as required in Subsection (a) and there was another occupant in the vehicle at the time of the crash capable of doing so, that occupant must give notice as required in Subsection (a).</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-408) (from Ch. 95 1/2, par. 11-408)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-408. Police to report motor vehicle crash investigations.
<p class='subsection'>\(a) Every law enforcement officer who investigates a motor vehicle crash  for which a report is required by this Article or who prepares a written report as a result of an investigation either at the time and scene of such motor vehicle crash or thereafter by interviewing participants or witnesses shall forward a written report of such motor vehicle crash  to the Administrator on forms provided by the Administrator under Section 11-411 within 10 days after investigation of the motor vehicle crash, or within such other time as is prescribed by the Administrator. Such written reports and the information contained in those reports required to be forwarded by law enforcement officers shall not be held confidential by the reporting law enforcement officer or agency. The Secretary of State may also disclose notations of crash involvement maintained on individual driving records. However, the Administrator or the Secretary of State may require a supplemental written report from the reporting law enforcement officer.</p><p class='subsection'>\(b) The Department at its discretion may require a supplemental written report from the reporting law enforcement officer on a form supplied by the Department to be submitted directly to the Department. Such supplemental report may be used only for crash studies and statistical or analytical purposes under Section 11-412 or 11-414 of this Code.</p><p class='subsection'>\(c) The Department at its discretion may provide for in-depth investigations of crashes involving Department employees or other motor vehicle crashes by individuals or special investigation groups, including but not limited to police officers, photographers, engineers, doctors, mechanics, and as a result of the investigation may require the submission of written reports, photographs, charts, sketches, graphs, or a combination of all. Such individual written reports, photographs, charts, sketches, or graphs may be used only for crash  studies and statistical or analytical purposes under Section 11-412 or 11-414 of this Code.</p><p class='subsection'>\(d) On and after July 1, 1997, law enforcement officers who have reason to suspect that the motor vehicle crash was the result of a driver's loss of consciousness due to a medical condition, as defined by the Driver's License Medical Review Law of 1992, or the result of any medical condition that impaired the driver's ability to safely operate a motor vehicle shall notify the Secretary of this determination. The Secretary, in conjunction with the Driver's License Medical Advisory Board, shall determine by administrative rule the temporary conditions not required to be reported under the provisions of this Section. The Secretary shall, in conjunction with the Illinois State Police and representatives of local and county law enforcement agencies, promulgate any rules necessary and develop the procedures and documents that may be required to obtain written, electronic, or other agreed upon methods of notification to implement the provisions of this Section.</p><p class='subsection'>\(e) Law enforcement officers reporting under the provisions of subsection (d) of this Section shall enjoy the same immunities granted members of the Driver's License Medical Advisory Board under Section 6-910 of this Code.</p><p class='subsection'>\(f) All information furnished to the Secretary under subsection (d) of this Section shall be deemed confidential and for the privileged use of the Secretary in accordance with the provisions of subsection (j) of Section 2-123 of this Code.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-409) (from Ch. 95 1/2, par. 11-409)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-409. False motor vehicle crash reports or notices.
<p>Any person who provides information in an oral or written report required by this Code with knowledge or reason to believe that such information is false shall be guilty of a Class C misdemeanor.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-410)
## Sec. 11-410. (Repealed).
<p>(Source: P.A. 83-831. Repealed by P.A. 102-560, eff. 8-20-21.)</p>### (625 ILCS 5/11-411) (from Ch. 95 1/2, par. 11-411)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-411. Crash report forms.
<p class='subsection'>\(a) The Administrator must prepare and upon request supply to police departments, sheriffs and other appropriate agencies or individuals, forms for written crash reports as required hereunder, suitable with respect to the persons required to make such reports and the purposes to be served. The written reports must call for sufficiently detailed information to disclose with reference to a vehicle crash the cause, conditions then existing, and the persons and vehicles involved or any other data concerning such crash that may be required for a complete analysis of all related circumstances and events leading to the crash or subsequent to the occurrence.</p><p class='subsection'>\(b) Every crash report required to be made in writing must be made on an approved form or in an approved electronic format provided by the Administrator and must contain all the information required therein unless that information is not available. The Department shall adopt any rules necessary to implement this subsection (b).</p><p class='subsection'>\(c) Should special crash studies be required by the Administrator, the Administrator may provide the supplemental forms for the special studies.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-412) (from Ch. 95 1/2, par. 11-412)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-412. Motor vehicle crash reports confidential.
<p class='subsection'>\(a) All required written motor vehicle crash reports and supplemental reports shall be without prejudice to the individual so reporting and shall be for the confidential use of the Department and the Secretary of State and, in the case of second division vehicles operated under certificate of convenience and necessity issued by the Illinois Commerce Commission, of the Commission, except that the Administrator or the Secretary of State or the Commission may disclose the identity of a person involved in a motor vehicle crash  when such identity is not otherwise known or when such person denies his presence at such motor vehicle crash and the Department shall disclose the identity of the insurance carrier, if any, upon demand. The Secretary of State may also disclose notations of crash involvement maintained on individual driving records.</p><p class='subsection'>\(b) Upon written request, the Department shall furnish copies of its written crash reports or any supplemental reports to federal, State, and local agencies that are engaged in highway safety research and studies and to any person or entity that has a contractual agreement with the Department or a federal, State, or local agency to complete a highway safety research and study for the Department or the federal, State, or local agency. Reports furnished to any agency, person, or entity other than the Secretary of State or the Illinois Commerce Commission may be used only for statistical or analytical purposes and shall be held confidential by that agency, person, or entity. These reports shall be exempt from inspection and copying under the Freedom of Information Act and shall not be used as evidence in any trial, civil or criminal, arising out of a motor vehicle crash, except that the Administrator shall furnish upon demand of any person who has, or claims to have, made such a written or supplemental report, or upon demand of any court, a certificate showing that a specified written crash report or supplemental report has or has not been made to the Administrator solely to prove a compliance or a failure to comply with the requirement that such a written or supplemental report be made to the Administrator.</p><p class='subsection'>\(c) Upon written request, the Department shall furnish motor vehicle crash data to a federal, State, or local agency, the Secretary of State, the Illinois Commerce Commission, or any other person or entity under Section 11-417 of this Code.</p><p class='subsection'>\(d) The Department at its discretion may provide for in-depth investigations of crashes involving Department employees or other motor vehicle crashes. A written report describing the preventability of such a crash may be prepared to enhance the safety of Department employees or the traveling public. Such reports and the information contained in those reports and any opinions expressed in the review of the crash as to the preventability of the crash shall be for the privileged use of the Department and held confidential and shall not be obtainable or used in any civil or criminal proceeding.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-413) (from Ch. 95 1/2, par. 11-413)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-413. Coroners to report.
<p>All coroners shall on or before the 10th day of each month report in writing to the Administrator the death of any person within their respective jurisdiction, during the preceding calendar month, as the result of a traffic crash giving the time and place of the crash and the circumstances relating thereto.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-414) (from Ch. 95 1/2, par. 11-414)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-414. Department to tabulate and analyze motor vehicle crash  reports.
<p>The Department shall tabulate and may analyze all written motor vehicle crash reports received in compliance with this Code and shall publish annually or at more frequent intervals motor vehicle crash data. The Department:</p><p class='paragraph'>\(1) (blank);</p><p class='paragraph'>\(2) shall, upon written request, make available to the public motor vehicle crash data that shall be distributed under Sections 11-412 and 11-417 of this Code;</p><p class='paragraph'>\(3) may conduct special investigations of motor vehicle crashes and may solicit supplementary reports from drivers, owners, police departments, sheriffs, coroners, or any other individual. Failure of any individual to submit a supplementary report subjects such individual to the same penalties for failure to report as designated under Section 11-406.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-415) (from Ch. 95 1/2, par. 11-415)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-415. Municipalities may require traffic crash reports.
<p>Municipalities may by ordinance require that the driver or owner of a vehicle involved in a traffic crash file with the designated municipal office a written report of such crash. All such reports shall be for the confidential use of the municipal office and subject to the provisions of Section 11-412.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-416) (from Ch. 95 1/2, par. 11-416)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-416. Furnishing copies - Fees.
<p>The Illinois State Police may furnish copies of an Illinois State Police Traffic Crash Report that has been investigated by the Illinois State Police and shall be paid a fee of $5 for each such copy, or in the case of a crash which was investigated by a crash  reconstruction officer or crash reconstruction team, a fee of $20 shall be paid. These fees shall be deposited into the State Police Services Fund.</p><p>Other State law enforcement agencies or law enforcement agencies of local authorities may furnish copies of traffic crash reports prepared by such agencies and may receive a fee not to exceed $5 for each copy or in the case of a crash which was investigated by a crash  reconstruction officer or crash reconstruction team, the State or local law enforcement agency may receive a fee not to exceed $20.</p><p>Any written crash report required or requested to be furnished the Administrator shall be provided without cost or fee charges authorized under this Section or any other provision of law.</p><p>(Source: P.A. 101-571, eff. 8-23-19; 102-538, eff. 8-20-21; 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/11-417)
<p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 11-417. Motor vehicle crash report and motor vehicle crash data.
<p class='subsection'>\(a) Upon written request and payment of the required fee, the Department shall make available to the public motor vehicle crash data received in compliance with this Code. The Department shall adopt any rules necessary to establish a fee schedule for motor vehicle crash data made available under Section 11-414 of this Code.</p><p class='subsection'>\(b) The Department shall provide copies of a written motor vehicle crash report or motor vehicle crash data without any cost or fees authorized under any provision of law to a federal, State, or local agency, the Secretary of State, the Illinois Commerce Commission, or any other person or entity that has a contractual agreement with the Department or a federal, State, or local agency to complete a highway safety research and study for the Department or the federal, State, or local agency.</p><p class='subsection'>\(c) All fees collected under this Section shall be placed in the Road Fund to be used, subject to appropriation, for the costs associated with motor vehicle crash records and motor vehicle crash data.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>