# Article 36.5. Vehicle Impoundment {.unnumbered}

<p>(Source: P.A. 96-1551, eff. 7-1-11.)</p>### (720 ILCS 5/36-10)
## Sec. 36-10. Applicability; savings clause.
<p class='subsection'>\(a) The changes made to this Article by Public Act 100-512 and Public Act 100-699 only apply to property seized on and after July 1, 2018.</p><p class='subsection'>\(b) The changes made to this Article by Public Act 100-699 are subject to Section 4 of the Statute on Statutes.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/36.5-5)
## Sec. 36.5-5. Vehicle impoundment.
<p class='subsection'>\(a) In addition to any other penalty, fee or forfeiture provided by law, a peace officer who arrests a person for a violation of Section 10-9, 11-14, 11-14.1, 11-14.3, 11-14.4, 11-18, or 11-18.1 of this Code or related municipal ordinance, may tow and impound any vehicle used by the person in the commission of the violation. The person arrested for one or more such violations shall be charged a $1,000 fee, to be paid to the law enforcement agency that made the arrest or its designated representative. The person may recover the vehicle from the impound after a minimum of 2 hours after arrest upon payment of the fee.</p><p class='subsection'>\(b) $500 of the fee shall be distributed to the law enforcement agency whose peace officers made the arrest, for the costs incurred by the law enforcement agency to investigate and to tow and impound the vehicle. Upon the defendant's conviction of one or more of the violations in connection with which the vehicle was impounded and the fee imposed under this Section, the remaining $500 of the fee shall be deposited into the Specialized Services for Survivors of Human Trafficking Fund and disbursed in accordance with subsections (d), (e), and (f) of Section 5-9-1.21 of the Unified Code of Corrections.</p><p class='subsection'>\(c) Upon the presentation by the defendant of a signed court order showing that the defendant has been acquitted of all of the violations in connection with which a vehicle was impounded and a fee imposed under this Section, or that the charges against the defendant for those violations have been dismissed, the law enforcement agency shall refund the $1,000 fee to the defendant.</p><p>(Source: P.A. 97-333, eff. 8-12-11; 97-897, eff. 1-1-13; 97-1109, eff. 1-1-13; 98-463, eff. 8-16-13; 98-1013, eff. 1-1-15 .)</p>