# Article 21.2. Interference With A Public Institution of Education {.unnumbered}

<p>(Source: P.A. 96-807, eff. 1-1-10.)</p>### (720 ILCS 5/21.2-1) (from Ch. 38, par. 21.2-1)
## Sec. 21.2-1. 
<p>The General Assembly, in recognition of unlawful campus and school disorders across the nation which are disruptive of the educational process, dangerous to the health and safety of persons, damaging to public and private property, and which divert the use of institutional facilities from the primary function of education, establishes by this Act criminal penalties for conduct declared in this Article to be unlawful. However, this Article does not modify or supersede any other law relating to damage to persons or property, nor does it prevent a public institution of education from establishing restrictions upon the availability or use of any building or other facility owned, operated or controlled by the institution to preserve their dedication to education, nor from establishing standards of scholastic and behavioral conduct reasonably relevant to the missions, processes and functions of the institution, nor from invoking appropriate discipline or expulsion for violations of such standards.</p>
<p>(Source: P.A. 96-807, eff. 1-1-10.)</p>### (720 ILCS 5/21.2-2) (from Ch. 38, par. 21.2-2)
## Sec. 21.2-2. Interference with a public institution of education.
<p>A person commits interference with a public institution of education when he or she, on the campus of a public institution of education, or at or in any building or other facility owned, operated or controlled by the institution, without authority from the institution he or she, through force or violence, actual or threatened:</p><p class='paragraph'>\(1) knowingly denies to a trustee, school board member, superintendent, principal, employee, student or invitee of the institution:</p><p class='subparagraph'>\(A) Freedom of movement at that place; or</p><p class='subparagraph'>\(B) Use of the property or facilities of the institution; or</p><p class='subparagraph'>\(C) The right of ingress or egress to the property or facilities of the institution; or</p><p class='paragraph'>\(2) knowingly impedes, obstructs, interferes with or disrupts:</p><p class='subparagraph'>\(A) the performance of institutional duties by a trustee, school board member, superintendent, principal, or employee of the institution; or</p><p class='subparagraph'>\(B) the pursuit of educational activities, as determined or prescribed by the institution, by a trustee, school board member, superintendent, principal, employee, student or invitee of the institution; or</p><p class='paragraph'>\(3) knowingly occupies or remains in or at any building, property or other facility owned, operated or controlled by the institution after due notice to depart.</p><p>(Source: P.A. 96-807, eff. 1-1-10; 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/21.2-3) (from Ch. 38, par. 21.2-3)
## Sec. 21.2-3.
<p>Nothing in this Article prevents lawful assembly of the trustees, school board members, superintendent, principal, employees, students or invitees of a public institution of  education, or prevents orderly petition for redress of grievances.</p>
<p>(Source: P.A. 96-807, eff. 1-1-10.)</p>### (720 ILCS 5/21.2-4) (from Ch. 38, par. 21.2-4)
## Sec. 21.2-4. Sentence.
<p>A person convicted of violation of this Article commits a Class C misdemeanor for the first offense and for a second or subsequent offense commits a Class B misdemeanor. If the interference with the public institution of education is accompanied by a threat of personal injury or property damage, the person commits a Class 3 felony and may be sentenced to a term of imprisonment of not less than 2 years and not more than 10 years and may be prosecuted for intimidation in accordance with Section 12-6 of this Code.</p><p>(Source: P.A. 96-807, eff. 1-1-10.)</p>### (720 ILCS 5/21.2-5) (from Ch. 38, par. 21.2-5)
## Sec. 21.2-5.
<p>For the purposes of this Article the words and phrases described in this Section have the meanings designated in this Section, except when a particular context clearly requires a different meaning.</p>
<p>"Public institution of education" means an educational organization located in this State which provides an organized elementary, secondary, or post-high school educational program, and which is supported in whole or in part by appropriations of the General Assembly, a unit of local government or school district.</p><p>A person has received "due notice" if he, or the group of which he is a part, has been given oral or written notice from an authorized representative of the public institution of education in a manner reasonably designated to inform him, or the group of which he is a part, that he or they should cease such action or depart from such premises. The notice may also be given by a printed or written notice forbidding entry conspicuously posted or exhibited at the main entrance of the building or other facility, or the forbidden part thereof.</p><p>"Force or violence" includes, but is not limited to, use of one's person, individually or in concert with others, to impede access to or movement within or otherwise to interfere with the conduct of the authorized activities of the public institution of education, its trustees, school board members, superintendent, principal, employees, students or invitees.</p><p>(Source: P.A. 96-807, eff. 1-1-10.)</p>### (720 ILCS 5/21.2-6) (from Ch. 38, par. 21.2-6)
## Sec. 21.2-6. 
<p>If any provision of this Act or the application thereof to any person or circumstances is held invalid, such invalidity shall not affect other provisions or applications of the Act which can be given effect without the invalid provision or application, and to this end the provisions of this Act are declared severable.</p>
<p>(Source: P.A. 76-1582 .)</p>