# Article 47. Nuisance {.unnumbered}

### (720 ILCS 5/47-5)
## Sec. 47-5. Public nuisance.
<p>It is a public nuisance:</p><p class='paragraph'>\(1) To cause or allow the carcass of an animal or offal, filth, or a noisome substance to be collected, deposited, or to remain in any place to the prejudice of others.</p><p class='paragraph'>\(2) To throw or deposit offal or other offensive matter or the carcass of a dead animal in a water course, lake, pond, spring, well, or common sewer, street, or public highway.</p><p class='paragraph'>\(3) To corrupt or render unwholesome or impure the water of a spring, river, stream, pond, or lake to the injury or prejudice of others.</p><p class='paragraph'>\(4) To obstruct or impede, without legal authority, the passage of a navigable river or waters.</p><p class='paragraph'>\(5) To obstruct or encroach upon public highways, private ways, streets, alleys, commons, landing places, and ways to burying places.</p><p class='paragraph'>\(6) To carry on the business of manufacturing gunpowder, nitroglycerine, or other highly explosive substances, or mixing or grinding the materials for those substances, in a building within 20 rods of a valuable building erected at the time the business is commenced.</p><p class='paragraph'>\(7) To establish powder magazines near incorporated towns, at a point different from that appointed according to law by the corporate authorities of the town, or within 50 rods of an occupied dwelling house.</p><p class='paragraph'>\(8) To erect, continue, or use a building or other place for the exercise of a trade, employment, or manufacture that, by occasioning noxious exhalations, offensive smells, or otherwise, is offensive or dangerous to the health of individuals or of the public.</p><p class='paragraph'>\(9) To advertise wares or occupation by painting notices of the wares or occupation on or affixing them to fences or other private property, or on rocks or other natural objects, without the consent of the owner, or if in the highway or other public place, without permission of the proper authorities.</p><p class='paragraph'>\(10) To permit a well drilled for oil, gas, salt water disposal, or any other purpose in connection with the production of oil and gas to remain unplugged after the well is no longer used for the purpose for which it was drilled.</p><p class='paragraph'>\(11) To construct or operate a salt water pit or oil field refuse pit, commonly called a "burn out pit", so that salt water, brine, or oil field refuse or other waste liquids may escape from the pit in a manner except by the evaporation of the salt water or brine or by the burning of the oil field waste or refuse.</p><p class='paragraph'>\(12) To permit concrete bases, discarded machinery, and materials to remain around an oil or gas well, or to fail to fill holes, cellars, slush pits, and other excavations made in connection with the well or to restore the surface of the lands surrounding the well to its condition before the drilling of the well, upon abandonment of the oil or gas well.</p><p class='paragraph'>\(13) To permit salt water, oil, gas, or other wastes from a well drilled for oil, gas, or exploratory purposes to escape to the surface, or into a mine or coal seam, or into an underground fresh water supply, or from one underground stratum to another.</p><p class='paragraph'>\(14) To harass, intimidate, or threaten a person who is about to sell or lease or has sold or leased a residence or other real property or is about to buy or lease or has bought or leased a residence or other real property, when the harassment, intimidation, or threat relates to a person's attempt to sell, buy, or lease a residence, or other real property, or refers to a person's sale, purchase, or lease of a residence or other real property.</p><p class='paragraph'>\(15) To store, dump, or permit the accumulation of debris, refuse, garbage, trash, tires, buckets, cans, wheelbarrows, garbage cans, or other containers in a manner that may harbor mosquitoes, flies, insects, rodents, nuisance birds, or other animal pests that are offensive, injurious, or dangerous to the health of individuals or the public.</p><p class='paragraph'>\(16) To create a condition, through the improper maintenance of a swimming pool or wading pool, or by causing an action that alters the condition of a natural body of water, so that it harbors mosquitoes, flies, or other animal pests that are offensive, injurious, or dangerous to the health of individuals or the public.</p><p class='paragraph'>\(17) To operate a tanning facility without a valid permit under the Tanning Facility Permit Act.</p><p>Nothing in this Section shall be construed to prevent the corporate authorities of a city, village, or incorporated town, or the county board of a county, from declaring what are nuisances and abating them within their limits. Counties have that authority only outside the corporate limits of a city, village, or incorporated town.</p><p>(Source: P.A. 89-234, eff. 1-1-96.)</p>### (720 ILCS 5/47-10)
## Sec. 47-10. Dumping garbage.
<p>It is unlawful for a person to dump or place garbage or another offensive substance within the corporate limits of a city, village, or incorporated town other than (1) the city, village, or incorporated town within the corporate limits of which the garbage or other offensive substance originated or (2) a city, village, or incorporated town that has contracted with the city, village, or incorporated town within which the garbage originated, for the joint collection and disposal of garbage; nor shall the garbage or other offensive substance be dumped or placed within a distance of one mile of the corporate limits of any other city, village, or incorporated town.</p><p>A person violating this Section is guilty of a petty offense.</p><p>(Source: P.A. 89-234, eff. 1-1-96.)</p>### (720 ILCS 5/47-15)
## Sec. 47-15. Dumping garbage upon real property.
<p class='subsection'>\(a) It is unlawful for a person to dump, deposit, or place garbage, rubbish, trash, or refuse upon real property not owned by that person without the consent of the owner or person in possession of the real property.</p><p class='subsection'>\(b) A person who violates this Section is liable to the owner or person in possession of the real property on which the garbage, rubbish, trash, or refuse is dumped, deposited, or placed for the reasonable costs incurred by the owner or person in possession for cleaning up and properly disposing of the garbage, rubbish, trash, or refuse, and for reasonable attorneys' fees.</p><p class='subsection'>\(c) A person violating this Section is guilty of a Class B misdemeanor for which the court must impose a minimum fine of $500. A second conviction for an offense committed after the first conviction is a Class A misdemeanor for which the court must impose a minimum fine of $500. A third or subsequent violation, committed after a second conviction, is a Class 4 felony for which the court must impose a minimum fine of $500. A person who violates this Section and who has an equity interest in a motor vehicle used in violation of this Section is presumed to have the financial resources to pay the minimum fine not exceeding his or her equity interest in the vehicle. Personal property used by a person in violation of this Section shall on the third or subsequent conviction of the person be forfeited to the county where the violation occurred and disposed of at a public sale. Before the forfeiture, the court shall conduct a hearing to determine whether property is subject to forfeiture under this Section. At the forfeiture hearing the State has the burden of establishing by a preponderance of the evidence that property is subject to forfeiture under this Section. Property seized or forfeited under this Section is subject to reporting under the Seizure and Forfeiture Reporting Act.</p><p class='subsection'>\(d) The statutory minimum fine required by subsection (c) is not subject to reduction or suspension unless the defendant is indigent. If the defendant files a motion with the court asserting his or her inability to pay the mandatory fine required by this Section, the court must set a hearing on the motion before sentencing. The court must require an affidavit signed by the defendant containing sufficient information to ascertain the assets and liabilities of the defendant. If the court determines that the defendant is indigent, the court must require that the defendant choose either to pay the minimum fine of $500 or to perform 100 hours of community service.</p><p>(Source: P.A. 100-512, eff. 7-1-18 .)</p>### (720 ILCS 5/47-20)
## Sec. 47-20. Unplugged well.
<p>It is a Class A misdemeanor for a person to permit a water well, located on property owned by him or her, to be in an unplugged condition at any time after the abandonment of the well for obtaining water. No well is in an unplugged condition, however, that is plugged in conformity with the rules and regulations of the Department of Natural Resources issued under Section 6 and Section 19 of the Illinois Oil and Gas Act. This Section does not apply to a well drilled or used for observation or any other purpose in connection with the development or operation of a gas storage project.</p><p>(Source: P.A. 89-234, eff. 1-1-96; 89-445, eff. 2-7-96.)</p>### (720 ILCS 5/47-25)
## Sec. 47-25. Penalties.
<p>Whoever causes, erects, or continues a nuisance described in this Article, for the first offense, is guilty of a petty offense and shall be fined not exceeding $100, and for a subsequent offense is guilty of a Class B misdemeanor. Every nuisance described in this Article, when a conviction for that nuisance is had, may, by order of the court before which the conviction is had, be abated by the sheriff or other proper officer, at the expense of the defendant. It is not a defense to a proceeding under this Section that the nuisance is erected or continued by virtue or permission of a law of this State.</p><p>(Source: P.A. 89-234, eff. 1-1-96.)</p>