# Article 49. Miscellaneous Offenses {.unnumbered}

<p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/49-1)
## Sec. 49-1. Flag desecration.
<p class='subsection'>\(a) Definition. As used in this Section:</p><p>"Flag", "standard", "color" or "ensign" shall include any flag, standard, color, ensign or any picture or representation of either thereof, made of any substance or represented on any substance and of any size evidently purporting to be either of said flag, standard, color or ensign of the United States of America, or a picture or a representation of either thereof, upon which shall be shown the colors, the stars, and the stripes, in any number of either thereof, of the flag, colors, standard, or ensign of the United States of America.</p><p class='subsection'>\(b) A person commits flag desecration when he or she knowingly:</p><p class='paragraph'>\(1) for exhibition or display, places or causes to be placed any word, figure, mark, picture, design, drawing, or any advertisement of any nature, upon any flag, standard, color or ensign of the United States or State flag of this State or ensign;</p><p class='paragraph'>\(2) exposes or causes to be exposed to public view any such flag, standard, color or ensign, upon which has been printed, painted or otherwise placed, or to which has been attached, appended, affixed, or annexed, any word, figure, mark, picture, design or drawing or any advertisement of any nature;</p><p class='paragraph'>\(3) exposes to public view, manufactures, sells, exposes for sale, gives away, or has in possession for sale or to give away or for use for any purpose, any article or substance, being an article of merchandise, or a receptacle of merchandise or article or thing for carrying or transporting merchandise upon which has been printed, painted, attached, or otherwise placed a representation of any such flag, standard, color, or ensign, to advertise, call attention to, decorate, mark or distinguish the article or substance on which so placed; or</p><p class='paragraph'>\(4) publicly mutilates, defaces, defiles, tramples, or intentionally displays on the ground or floor any such flag, standard, color or ensign.</p><p class='subsection'>\(c) All prosecutions under this Section shall be brought by any person in the name of the People of the State of Illinois, against any person or persons violating any of the provisions of this Section, before any circuit court. The State's Attorneys shall see that this Section is enforced in their respective counties, and shall prosecute all offenders on receiving information of the violation of this Section. Sheriffs, deputy sheriffs, and police officers shall inform against and prosecute all persons whom there is probable cause to believe are guilty of violating this Section. One-half of the amount recovered in any penal action under this Section shall be paid to the person making and filing the complaint in the action, and the remaining 1/2 to the school fund of the county in which the conviction is obtained.</p><p class='subsection'>\(d) All prosecutions under this Section shall be commenced within six months from the time the offense was committed, and not afterwards.</p><p class='subsection'>\(e) Sentence. A violation of paragraphs (1) through (3) of subsection (b) is a Class C misdemeanor. A violation of paragraph (4) of subsection (b) is a Class 4 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/49-1.5)
## Sec. 49-1.5. Draft card mutilation.
<p class='subsection'>\(a) A person commits draft card mutilation when he or she knowingly destroys or mutilates a valid registration certificate or any other valid certificate issued under the federal "Military Selective Service Act of 1967".</p><p class='subsection'>\(b) Sentence. Draft card mutilation is a Class 4 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/49-2)
## Sec. 49-2. Business use of military terms.
<p class='subsection'>\(a) It is unlawful for any person, concern, firm or corporation to use in the name, or description of the name, of any privately operated mercantile establishment which may or may not be engaged principally in the buying and selling of equipment or materials of the Government of the United States or any of its departments, agencies or military services, the terms "Army", "Navy", "Marine", "Coast Guard", "Government", "GI", "PX" or any terms denoting a branch of the government, either independently or in connection or conjunction with any other word or words, letter or insignia which import or imply that the products so described are or were made for the United States government or in accordance with government specifications or requirements, or of government materials, or that these products have been disposed of by the United States government as surplus or rejected stock.</p><p class='subsection'>\(b) Sentence. A violation of this Section is a petty offense with a fine of not less than $25.00 nor more than $500 for the first conviction, and not less than $500 or more than $1000 for each subsequent conviction.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/49-3)
## Sec. 49-3. Governmental uneconomic practices.
<p class='subsection'>\(a) It is unlawful for the State of Illinois, any political subdivision thereof, or any municipality therein, or any officer, agent or employee of the State of Illinois, any political subdivision thereof or any municipality therein, to sell to or procure for sale or have in its or his or her possession or under its or his or her control for sale to any officer, agent or employee of the State or any political subdivision thereof or municipality therein any article, material, product or merchandise of whatsoever nature, excepting meals, public services and such specialized appliances and paraphernalia as may be required for the safety or health of such officers, agents or employees.</p><p class='subsection'>\(b) The provisions of this Section shall not apply to the State, any political subdivision thereof or municipality therein, nor to any officer, agent or employee of the State, or of any such subdivision or municipality while engaged in any recreational, health, welfare, relief, safety or educational activities furnished by the State, or any such political subdivision or municipality.</p><p class='subsection'>\(c) Sentence. A violation of this Section is a Class B misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/49-4)
## Sec. 49-4. Sale of maps.
<p class='subsection'>\(a) The sale of current Illinois publications or highway maps published by the Secretary of State is prohibited except where provided by law.</p><p class='subsection'>\(b) Sentence. A violation of this Section is a Class B misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/49-5)
## Sec. 49-5. Video movie sales and rentals rating violation.
<p class='subsection'>\(a) Definitions. As used in this Section, unless the context otherwise requires:</p><p>"Person" means an individual, corporation, partnership, or any other legal or commercial entity.</p><p>"Official rating" means an official rating of the</p><p>Motion Picture Association of America.</p><p>"Video movie" means a videotape or video disc copy of a motion picture film.</p><p class='subsection'>\(b) A person may not sell at retail or rent, or attempt to sell at retail or rent, a video movie in this State unless the official rating of the motion picture from which it is copied is clearly displayed on the outside of any cassette, case, jacket, or other covering of the video movie.</p><p class='subsection'>\(c) This Section does not apply to any video movie of a motion picture which:</p><p class='paragraph'>\(1) has not been given an official rating; or</p><p class='paragraph'>\(2) has been altered in any way subsequent to receiving an official rating.</p><p class='subsection'>\(d) Sentence. A violation of this Section is a Class C misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/49-6)
## Sec. 49-6. Container label obliteration prohibited.
<p class='subsection'>\(a) No person shall sell or offer for sale any product, article or substance in a container on which any statement of weight, quantity, quality, grade, ingredients or identification of the manufacturer, supplier or processor is obliterated by any other labeling unless the other labeling correctly restates the obliterated statement.</p><p class='subsection'>\(b) This Section does not apply to any obliteration which is done in order to comply with subsection (c) of this Section.</p><p class='subsection'>\(c) No person shall utilize any used container for the purpose of sale of any product, article or substance unless the original marks of identification, weight, grade, quality and quantity have first been obliterated.</p>