# Article 33a. Armed Violence {.unnumbered}

### (720 ILCS 5/33A-1) (from Ch. 38, par. 33A-1)
## Sec. 33A-1. Legislative intent and definitions.
<p class='subsection'>\(a) Legislative findings. The legislature finds and declares the following:</p><p class='paragraph'>\(1) The use of a dangerous weapon in the commission of a felony offense poses a much greater threat to the public health, safety, and general welfare, than when a weapon is not used in the commission of the offense.</p><p class='paragraph'>\(2) Further, the use of a firearm greatly facilitates the commission of a criminal offense because of the more lethal nature of a firearm and the greater perceived threat produced in those confronted by a person wielding a firearm. Unlike other dangerous weapons such as knives and clubs, the use of a firearm in the commission of a criminal felony offense significantly escalates the threat and the potential for bodily harm, and the greater range of the firearm increases the potential for harm to more persons. Not only are the victims and bystanders at greater risk when a firearm is used, but also the law enforcement officers whose duty is to confront and apprehend the armed suspect.</p><p class='paragraph'>\(3) Current law does contain offenses involving the use or discharge of a gun toward or against a person, such as aggravated battery with a firearm, aggravated discharge of a firearm, and reckless discharge of a firearm; however, the General Assembly has legislated greater penalties for the commission of a felony while in possession of a firearm because it deems such acts as more serious.</p><p class='subsection'>\(b) Legislative intent.</p><p class='paragraph'>\(1) In order to deter the use of firearms in the commission of a felony offense, the General Assembly deems it appropriate for a greater penalty to be imposed when a firearm is used or discharged in the commission of an offense than the penalty imposed for using other types of weapons and for the penalty to increase on more serious offenses.</p><p class='paragraph'>\(2) With the additional elements of the discharge of a firearm and great bodily harm inflicted by a firearm being added to armed violence and other serious felony offenses, it is the intent of the General Assembly to punish those elements more severely during commission of a felony offense than when those elements stand alone as the act of the offender.</p><p class='paragraph'>\(3) It is the intent of the 91st General Assembly that should Public Act 88-680 be declared unconstitutional for a violation of Article 4, Section 8 of the 1970 Constitution of the State of Illinois, the amendatory changes made by Public Act 88-680 to Article 33A of the Criminal Code of 1961 and which are set forth as law in this amendatory Act of the 91st General Assembly are hereby reenacted by this amendatory Act of the 91st General Assembly.</p><p class='subsection'>\(c) Definitions.</p><p class='paragraph'>\(1) "Armed with a dangerous weapon". A person is considered armed with a dangerous weapon for purposes of this Article, when he or she carries on or about his or her person or is otherwise armed with a Category I, Category II, or Category III weapon.</p><p class='paragraph'>\(2) A Category I weapon is a handgun, sawed-off shotgun, sawed-off rifle, any other firearm small enough to be concealed upon the person, semiautomatic firearm, or machine gun. A Category II weapon is any other rifle, shotgun, spring gun, other firearm, stun gun or taser as defined in paragraph (a) of Section 24-1 of this Code, knife with a blade of at least 3 inches in length, dagger, dirk, switchblade knife, stiletto, axe, hatchet, or other deadly or dangerous weapon or instrument of like character. As used in this subsection (b) "semiautomatic firearm" means a repeating firearm that utilizes a portion of the energy of a firing cartridge to extract the fired cartridge case and chamber the next round and that requires a separate pull of the trigger to fire each cartridge.</p><p class='paragraph'>\(3) A Category III weapon is a bludgeon, black-jack, slungshot, sand-bag, sand-club, metal knuckles, billy, or other dangerous weapon of like character.</p><p>(Source: P.A. 91-404, eff. 1-1-00; 91-696, eff. 4-13-00.)</p>### (720 ILCS 5/33A-2) (from Ch. 38, par. 33A-2)
## Sec. 33A-2. Armed violence-Elements of the offense.
<p class='subsection'>\(a) A person commits armed violence when, while armed with a dangerous weapon, he commits any felony defined by Illinois Law, except first degree murder, attempted first degree murder, intentional homicide of an unborn child, second degree murder, involuntary manslaughter, reckless homicide, predatory criminal sexual assault of a child, aggravated battery of a child as described in Section 12-4.3 or subdivision (b)(1) of Section 12-3.05, home invasion, or any offense that makes the possession or use of a dangerous weapon either an element of the base offense, an aggravated or enhanced version of the offense, or a mandatory sentencing factor that increases the sentencing range.</p><p class='subsection'>\(b) A person commits armed violence when he or she personally discharges a firearm that is a Category I or Category II weapon while committing any felony defined by Illinois law, except first degree murder, attempted first degree murder, intentional homicide of an unborn child, second degree murder, involuntary manslaughter, reckless homicide, predatory criminal sexual assault of a child, aggravated battery of a child as described in Section 12-4.3 or subdivision (b)(1) of Section 12-3.05, home invasion, or any offense that makes the possession or use of a dangerous weapon either an element of the base offense, an aggravated or enhanced version of the offense, or a mandatory sentencing factor that increases the sentencing range.</p><p class='subsection'>\(c) A person commits armed violence when he or she personally discharges a firearm that is a Category I or Category II weapon that proximately causes great bodily harm, permanent disability, or permanent disfigurement or death to another person while committing any felony defined by Illinois law, except first degree murder, attempted first degree murder, intentional homicide of an unborn child, second degree murder, involuntary manslaughter, reckless homicide, predatory criminal sexual assault of a child, aggravated battery of a child as described in Section 12-4.3 or subdivision (b)(1) of Section 12-3.05, home invasion, or any offense that makes the possession or use of a dangerous weapon either an element of the base offense, an aggravated or enhanced version of the offense, or a mandatory sentencing factor that increases the sentencing range.</p><p class='subsection'>\(d) This Section does not apply to violations of the Fish and Aquatic Life Code or the Wildlife Code.</p><p>(Source: P.A. 95-688, eff. 10-23-07; 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/33A-3) (from Ch. 38, par. 33A-3)
## Sec. 33A-3. Sentence.
<p class='subsection'>\(a) Violation of Section 33A-2(a) with a Category I weapon is a Class X felony for which the defendant shall be sentenced to a minimum term of imprisonment of 15 years.</p><p class='subsection'>\(a-5) Violation of Section 33A-2(a) with a Category II weapon is a Class X felony for which the defendant shall be sentenced to a minimum term of imprisonment of 10 years.</p><p class='subsection'>\(b) Violation of Section 33A-2(a) with a Category III weapon is a Class 2 felony or the felony classification provided for the same act while unarmed, whichever permits the greater penalty. A second or subsequent violation of Section 33A-2(a) with a Category III weapon is a Class 1 felony or the felony classification provided for the same act while unarmed, whichever permits the greater penalty.</p><p class='subsection'>\(b-5) Violation of Section 33A-2(b) with a firearm that is a Category I or Category II weapon is a Class X felony for which the defendant shall be sentenced to a minimum term of imprisonment of 20 years.</p><p class='subsection'>\(b-10) Violation of Section 33A-2(c) with a firearm that is a Category I or Category II weapon is a Class X felony for which the defendant shall be sentenced to a term of imprisonment of not less than 25 years nor more than 40 years.</p><p class='subsection'>\(c) Unless sentencing under subsection (a) of Section 5-4.5-95 of the Unified Code of Corrections (730 ILCS 5/5-4.5-95) is applicable, any person who violates subsection (a) or (b) of Section 33A-2 with a firearm, when that person has been convicted in any state or federal court of 3 or more of the following offenses: treason, first degree murder, second degree murder, predatory criminal sexual assault of a child, aggravated criminal sexual assault, criminal sexual assault, robbery, burglary, arson, kidnaping, aggravated battery resulting in great bodily harm or permanent disability or disfigurement, a violation of the Methamphetamine Control and Community Protection Act, or a violation of Section 401(a) of the Illinois Controlled Substances Act, when the third offense was committed after conviction on the second, the second offense was committed after conviction on the first, and the violation of Section 33A-2 was committed after conviction on the third, shall be sentenced to a term of imprisonment of not less than 25 years nor more than 50 years.</p><p class='subsection'>\(c-5) Except as otherwise provided in paragraph (b-10) or (c) of this Section, a person who violates Section 33A-2(a) with a firearm that is a Category I weapon or Section 33A-2(b) in any school, in any conveyance owned, leased, or contracted by a school to transport students to or from school or a school related activity, or on the real property comprising any school or public park, and where the offense was related to the activities of an organized gang, shall be sentenced to a term of imprisonment of not less than the term set forth in subsection (a) or (b-5) of this Section, whichever is applicable, and not more than 30 years. For the purposes of this subsection (c-5), "organized gang" has the meaning ascribed to it in Section 10 of the Illinois Streetgang Terrorism Omnibus Prevention Act.</p><p class='subsection'>\(d) For armed violence based upon a predicate offense listed in this subsection (d) the court shall enter the sentence for armed violence to run consecutively to the sentence imposed for the predicate offense. The offenses covered by this provision are:</p><p class='item'>\(i) solicitation of murder,</p><p class='item'>\(ii) solicitation of murder for hire,</p><p class='item'>\(iii) heinous battery as described in Section 12-4.1 or subdivision (a)(2) of Section 12-3.05,</p><p class='item'>\(iv) aggravated battery of a senior citizen as described in Section 12-4.6 or subdivision (a)(4) of Section 12-3.05,</p><p class='item'>\(v) (blank),</p><p class='item'>\(vi) a violation of subsection (g) of Section 5 of the Cannabis Control Act,</p><p class='item'>\(vii) cannabis trafficking,</p><p class='item'>\(viii) a violation of subsection (a) of Section 401 of the Illinois Controlled Substances Act,</p><p class='item'>\(ix) controlled substance trafficking involving a Class X felony amount of controlled substance under Section 401 of the Illinois Controlled Substances Act,</p><p class='subsection'>\(x) calculated criminal drug conspiracy,</p><p class='subsection'>\(xi) streetgang criminal drug conspiracy, or</p><p class='subsection'>\(xii) a violation of the Methamphetamine Control and</p><p>Community Protection Act.</p><p>(Source: P.A. 95-688, eff. 10-23-07; 95-1052, eff. 7-1-09; 96-1551, eff. 7-1-11 .)</p>