# Article 37. Property Forfeiture {.unnumbered}

### (720 ILCS 5/37-1) (from Ch. 38, par. 37-1)
## Sec. 37-1. Maintaining Public Nuisance.
<p>Any building used in the commission of offenses prohibited by Sections 9-1, 10-1, 10-2, 11-14, 11-15, 11-16, 11-17, 11-20, 11-20.1, 11-20.1B, 11-20.3, 11-21, 11-22, 12-5.1, 16-1, 20-2, 23-1, 23-1(a)(1), 24-1(a)(7), 24-3, 28-1, 28-3, 31-5 or 39A-1, or subdivision (a)(1), (a)(2)(A), or (a)(2)(B) of Section 11-14.3, of this Code, or prohibited by the Illinois Controlled Substances Act, the Methamphetamine Control and Community Protection Act, or the Cannabis Control Act, or used in the commission of an inchoate offense relative to any of the aforesaid principal offenses, or any real property erected, established, maintained, owned, leased, or used by a streetgang for the purpose of conducting streetgang related activity as defined in Section 10 of the Illinois Streetgang Terrorism Omnibus Prevention Act is a public nuisance.</p><p class='subsection'>\(b) Sentence. A person convicted of knowingly maintaining such a public nuisance commits a Class A misdemeanor. Each subsequent offense under this Section is a Class 4 felony.</p><p>(Source: P.A. 96-1551, eff. 7-1-11; 97-1150, eff. 1-25-13.)</p>### (720 ILCS 5/37-2) (from Ch. 38, par. 37-2)
## Sec. 37-2. Enforcement of lien upon public nuisance.
<p>Any building, used in the commission of an offense specified in Section 37-1 of this Act with the intentional, knowing, reckless or negligent permission of the owner thereof, or the agent of the owner managing the building, shall, together with the underlying real estate, all fixtures and other property used to commit such an offense, be subject to a lien and may be sold to pay any unsatisfied judgment that may be recovered and any unsatisfied fine that may be levied under any Section of this Article and to pay to any person not maintaining the nuisance his damages as a consequence of the nuisance; provided, that the lien herein created shall not affect the rights of any purchaser, mortgagee, judgment creditor or other lien holder arising prior to the filing of a notice of such lien in the office of the recorder of the county in which the real estate subject to the lien is located, or in the office of the registrar of titles of such county if that real estate is registered under "An Act concerning land titles" approved May 1, 1897, as amended; which notice shall definitely describe the real estate and property involved, the nature and extent of the lien claimed, and the facts upon which the same is based. An action to enforce such lien may be commenced in any circuit court by the State's Attorney of the county of the nuisance or by the person suffering damages or both, except that a person seeking to recover damages must pursue his remedy within 6 months after the damages are sustained or his cause of action becomes thereafter exclusively enforceable by the State's Attorney of the county of the nuisance.</p><p>(Source: P.A. 83-358.)</p>### (720 ILCS 5/37-3) (from Ch. 38, par. 37-3)
## Sec. 37-3. Revocation of licenses, permits and certificates.
<p>All licenses, permits or certificates issued by the State of Illinois or any subdivision or political agency thereof authorizing the serving of food or liquor on any premises found to constitute a public nuisance as described in Section 37-1 shall be void and shall be revoked by the issuing authority; and no license, permit or certificate so revoked shall be reissued for such premises for a period of 60 days thereafter; nor shall any person convicted of knowingly maintaining such nuisance be reissued such license, permit or certificate for one year from his conviction. No license, permit or certificate shall be revoked pursuant to this Section without a full hearing conducted by the commission or agency which issued the license.</p><p>(Source: Laws 1965, p. 403.)</p>### (720 ILCS 5/37-4) (from Ch. 38, par. 37-4)
## Sec. 37-4. Abatement of nuisance.) The Attorney General of this State or the State's Attorney of the county wherein the nuisance exists may commence an action to abate a public nuisance as described in Section 37-1 of this Act, in the name of the People of the State of Illinois, in the circuit court. Upon being satisfied by affidavits or other sworn evidence that an alleged public nuisance exists, the court may without notice or bond enter a temporary restraining order or preliminary injunction to enjoin any defendant from maintaining such nuisance and may enter an order restraining any defendant from removing or interfering with all property used in connection with the public nuisance. If during the proceedings and hearings upon the merits, which shall be in the manner of "An Act in relation to places used for the purpose of using, keeping or selling controlled substances or cannabis", approved July 5, 1957, the existence of the nuisance is established, and it is found that such nuisance was maintained with the intentional, knowing, reckless or negligent permission of the owner or the agent of the owner managing the building, the court shall enter an order restraining all persons from maintaining or permitting such nuisance and from using the building for a period of one year thereafter, except that an owner, lessee or other occupant thereof may use such place if the owner shall give bond with sufficient security or surety approved by the court, in an amount between $1,000 and $5,000 inclusive, payable to the People of the State of Illinois, and including a condition that no offense specified in Section 37-1 of this Act shall be committed at, in or upon the property described and a condition that the principal obligor and surety assume responsibility for any fine, costs or damages resulting from such an offense thereafter.
<p>(Source: P.A. 83-342.)</p>### (720 ILCS 5/37-5) (from Ch. 38, par. 37-5)
## Sec. 37-5. Enforcement by private person.
<p>A private person may, after 30 days and within 90 days of giving the Attorney General and the State's Attorney of the county of nuisance written notice by certified or registered mail of the fact that a public nuisance as described in Section 37-1 of this Act, commence an action pursuant to Section 37-4 of this Act, provided that the Attorney General or the State's Attorney of the county of nuisance has not already commenced said action.</p><p>(Source: Laws 1965, p. 403.)</p>