# Article 24.8. Air Rifles {.unnumbered}

<p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/24.8-0.1)
## Sec. 24.8-0.1. Definitions.
<p>As used in this Article:</p><p>"Air rifle" means and includes any air gun, air pistol, spring gun, spring pistol, B-B gun, paint ball gun, pellet gun or any implement that is not a firearm which impels a breakable paint ball containing washable marking colors or, a pellet constructed of hard plastic, steel, lead or other hard materials with a force that reasonably is expected to cause bodily harm.</p><p>"Dealer" means any person, copartnership, association or corporation engaged in the business of selling at retail or renting any of the articles included in the definition of "air rifle".</p><p>"Municipalities" include cities, villages, incorporated towns and townships.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/24.8-1)
## Sec. 24.8-1. Selling, renting, or transferring air rifles to children.
<p class='subsection'>\(a) A dealer commits selling, renting, or transferring air rifles to children when he or she sells, lends, rents, gives or otherwise transfers an air rifle to any person under the age of 13 years where the dealer knows or has cause to believe the person to be under 13 years of age or where the dealer has failed to make reasonable inquiry relative to the age of the person and the person is under 13 years of age.</p><p class='subsection'>\(b) A person commits selling, renting, or transferring air rifles to children when he or she sells, gives, lends, or otherwise transfers any air rifle to any person under 13 years of age except where the relationship of parent and child, guardian and ward or adult instructor and pupil, exists between this person and the person under 13 years of age, or where the person stands in loco parentis to the person under 13 years of age.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/24.8-2)
## Sec. 24.8-2. Carrying or discharging air rifles on public streets.
<p class='subsection'>\(a) A person under 13 years of age commits carrying or discharging air rifles on public streets when he or she carries any air rifle on the public streets, roads, highways or public lands within this State, unless the person under 13 years of age carries the air rifle unloaded.</p><p class='subsection'>\(b) A person commits carrying or discharging air rifles on public streets when he or she discharges any air rifle from or across any street, sidewalk, road, highway or public land or any public place except on a safely constructed target range.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/24.8-3)
## Sec. 24.8-3. Permissive possession of an air rifle by a person under 13 years of age.
<p>Notwithstanding any provision of this Article, it is lawful for any person under 13 years of age to have in his or her possession any air rifle if it is:</p><p class='paragraph'>\(1) Kept within his or her house of residence or other private enclosure;</p><p class='paragraph'>\(2) Used by the person and he or she is a duly enrolled member of any club, team or society organized for educational purposes and maintaining as part of its facilities or having written permission to use an indoor or outdoor rifle range under the supervision guidance and instruction of a responsible adult and then only if the air rifle is actually being used in connection with the activities of the club team or society under the supervision of a responsible adult; or</p><p class='paragraph'>\(3) Used in or on any private grounds or residence under circumstances when the air rifle is fired, discharged or operated in a manner as not to endanger persons or property and then only if it is used in a manner as to prevent the projectile from passing over any grounds or space outside the limits of the grounds or residence.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/24.8-4)
## Sec. 24.8-4. Permissive sales.
<p>The provisions of this Article do not prohibit sales of air rifles:</p><p class='paragraph'>\(1) By wholesale dealers or jobbers;</p><p class='paragraph'>\(2) To be shipped out of the State; or</p><p class='paragraph'>\(3) To be used at a target range operated in accordance with Section 24.8-3 of this Article or by members of the Armed Services of the United States or Veterans' organizations.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/24.8-5)
## Sec. 24.8-5. Sentence.
<p>A violation of this Article is a petty offense. The Illinois State Police or any sheriff or police officer shall seize, take, remove or cause to be removed at the expense of the owner, any air rifle sold or used in any manner in violation of this Article.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/24.8-6)
## Sec. 24.8-6. Municipal regulation.
<p>The provisions of any ordinance enacted by any municipality which impose greater restrictions or limitations in respect to the sale and purchase, use or possession of air rifles as herein defined than are imposed by this Article, are not invalidated nor affected by this Article.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>