# Article 4. Criminal Act And Mental State {.unnumbered}

### (720 ILCS 5/4-1) (from Ch. 38, par. 4-1)
## Sec. 4-1. Voluntary act.
<p>A material element of every offense is a voluntary act, which includes an omission to perform a duty which the law imposes on the offender and which he is physically capable of performing.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/4-2) (from Ch. 38, par. 4-2)
## Sec. 4-2. Possession as voluntary act.
<p>Possession is a voluntary act if the offender knowingly procured or received the thing possessed, or was aware of his control thereof for a sufficient time to have been able to terminate his possession.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/4-3) (from Ch. 38, par. 4-3)
## Sec. 4-3. Mental state.
<p class='subsection'>\(a) A person is not guilty of an offense, other than an offense which involves absolute liability, unless, with respect to each element described by the statute defining the offense, he acts while having one of the mental states described in Sections 4-4 through 4-7.</p><p class='subsection'>\(b) If the statute defining an offense prescribed a particular mental state with respect to the offense as a whole, without distinguishing among the elements thereof, the prescribed mental state applies to each such element. If the statute does not prescribe a particular mental state applicable to an element of an offense (other than an offense which involves absolute liability), any mental state defined in Sections 4-4, 4-5 or 4-6 is applicable.</p><p class='subsection'>\(c) Knowledge that certain conduct constitutes an offense, or knowledge of the existence, meaning, or application of the statute defining an offense, is not an element of the offense unless the statute clearly defines it as such.</p><p>(Source: Laws 1961, p. 1983 .)</p>### (720 ILCS 5/4-4) (from Ch. 38, par. 4-4)
## Sec. 4-4. Intent.
<p>A person intends, or acts intentionally or with intent, to accomplish a result or engage in conduct described by the statute defining the offense, when his conscious objective or purpose is to accomplish that result or engage in that conduct.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/4-5) (from Ch. 38, par. 4-5)
## Sec. 4-5. Knowledge.
<p>A person knows, or acts knowingly or with knowledge of:</p><p class='subsection'>\(a) The nature or attendant circumstances of his or her conduct, described by the statute defining the offense, when he or she is consciously aware that his or her conduct is of that nature or that those circumstances exist. Knowledge of a material fact includes awareness of the substantial probability that the fact exists.</p><p class='subsection'>\(b) The result of his or her conduct, described by the statute defining the offense, when he or she is consciously aware that that result is practically certain to be caused by his conduct.</p><p>Conduct performed knowingly or with knowledge is performed wilfully, within the meaning of a statute using the term "willfully", unless the statute clearly requires another meaning.</p><p>When the law provides that acting knowingly suffices to establish an element of an offense, that element also is established if a person acts intentionally.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/4-6) (from Ch. 38, par. 4-6)
## Sec. 4-6. Recklessness.
<p>A person is reckless or acts recklessly when that person consciously disregards a substantial and unjustifiable risk that circumstances exist or that a result will follow, described by the statute defining the offense, and that  disregard constitutes a gross deviation from the standard of care that a reasonable person would exercise in the situation. An act performed recklessly is performed wantonly, within the meaning of a statute using the term "wantonly", unless the statute clearly requires another meaning.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/4-7) (from Ch. 38, par. 4-7)
## Sec. 4-7. Negligence.
<p>A person is negligent, or acts negligently, when that person fails to be aware of a substantial and unjustifiable risk that circumstances exist or a result will follow, described by the statute defining the offense, and that  failure constitutes a substantial deviation from the standard of care that  a reasonable person would exercise in the situation.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/4-8) (from Ch. 38, par. 4-8)
## Sec. 4-8. Ignorance or mistake.
<p class='subsection'>\(a) A person's ignorance or mistake as to a matter of either fact or law, except as provided in Section 4-3(c) above, is a defense if it negatives the existence of the mental state which the statute prescribes with respect to an element of the offense.</p><p class='subsection'>\(b) A person's reasonable belief that his conduct does not constitute an offense is a defense if:</p><p class='paragraph'>\(1) the offense is defined by an administrative regulation or order which is not known to him and has not been published or otherwise made reasonably available to him, and he could not have acquired such knowledge by the exercise of due diligence pursuant to facts known to him; or</p><p class='paragraph'>\(2) he acts in reliance upon a statute which later is determined to be invalid; or</p><p class='paragraph'>\(3) he acts in reliance upon an order or opinion of an Illinois Appellate or Supreme Court, or a United States appellate court later overruled or reversed; or</p><p class='paragraph'>\(4) he acts in reliance upon an official interpretation of the statute, regulation or order defining the offense, made by a public officer or agency legally authorized to interpret such statute.</p><p class='subsection'>\(c) Although a person's ignorance or mistake of fact or law, or reasonable belief, described in this Section 4-8 is a defense to the offense charged, he may be convicted of an included offense of which he would be guilty if the fact or law were as he believed it to be.</p><p class='subsection'>\(d) A defense based upon this Section 4-8 is an affirmative defense.</p><p>(Source: P.A. 98-463, eff. 8-16-13.)</p>### (720 ILCS 5/4-9) (from Ch. 38, par. 4-9)
## Sec. 4-9. Absolute liability.
<p>A person may be guilty of an offense without having, as to each element thereof, one of the mental states described in Sections 4-4 through 4-7 if the offense is a misdemeanor which is not punishable by incarceration or by a fine exceeding $1,000, or the statute defining the offense clearly indicates a legislative purpose to impose absolute liability for the conduct described.</p><p>(Source: P.A. 96-1198, eff. 1-1-11.)</p>