# Article 33e. Public Contracts {.unnumbered}

### (720 ILCS 5/33E-1) (from Ch. 38, par. 33E-1)
## Sec. 33E-1. Interference with public contracting.
<p>It is the finding of the General Assembly that the cost to the public is increased and the quality of goods, services and construction paid for by public monies is decreased when contracts for such goods, services or construction are obtained by any means other than through independent noncollusive submission of bids or offers by individual contractors or suppliers, and the evaluation of those bids or offers by the governmental unit pursuant only to criteria publicly announced in advance.</p><p>(Source: P.A. 85-1295.)</p>### (720 ILCS 5/33E-2) (from Ch. 38, par. 33E-2)
## Sec. 33E-2. Definitions.
<p>In this Act:</p><p class='subsection'>\(a) "Public contract" means any contract for goods, services or construction let to any person with or without bid by any unit of State or local government.</p><p class='subsection'>\(b) "Unit of State or local government" means the State, any unit of state government or agency thereof, any county or municipal government or committee or agency thereof, or any other entity which is funded by or expends tax dollars or the proceeds of publicly guaranteed bonds.</p><p class='subsection'>\(c) "Change order" means a change in a contract term other than as specifically provided for in the contract which authorizes or necessitates any increase or decrease in the cost of the contract or the time to completion.</p><p class='subsection'>\(d) "Person" means any individual, firm, partnership, corporation, joint venture or other entity, but does not include a unit of State or local government.</p><p class='subsection'>\(e) "Person employed by any unit of State or local government" means any employee of a unit of State or local government and any person defined in subsection (d) who is authorized by such unit of State or local government to act on its behalf in relation to any public contract.</p><p class='subsection'>\(f) "Sheltered market" has the meaning ascribed to it in Section 8b of the Business Enterprise for Minorities, Women, and Persons with Disabilities Act; except that, with respect to State contracts set aside for award to service-disabled veteran-owned small businesses and veteran-owned small businesses pursuant to Section 45-57 of the Illinois Procurement Code, "sheltered market" means procurements pursuant to that Section.</p><p class='subsection'>\(g) "Kickback" means any money, fee, commission, credit, gift, gratuity, thing of value, or compensation of any kind which is provided, directly or indirectly, to any prime contractor, prime contractor employee, subcontractor, or subcontractor employee for the purpose of improperly obtaining or rewarding favorable treatment in connection with a prime contract or in connection with a subcontract relating to a prime contract.</p><p class='subsection'>\(h) "Prime contractor" means any person who has entered into a public contract.</p><p class='item'>\(i) "Prime contractor employee" means any officer, partner, employee, or agent of a prime contractor.</p><p class='item'>\(i-5) "Stringing" means knowingly structuring a contract or job order to avoid the contract or job order being subject to competitive bidding requirements.</p><p class='subsection'>\(j) "Subcontract" means a contract or contractual action entered into by a prime contractor or subcontractor for the purpose of obtaining goods or services of any kind under a prime contract.</p><p class='subsection'>\(k) "Subcontractor" (1) means any person, other than the prime contractor, who offers to furnish or furnishes any goods or services of any kind under a prime contract or a subcontract entered into in connection with such prime contract; and (2) includes any person who offers to furnish or furnishes goods or services to the prime contractor or a higher tier subcontractor.</p><p class='subsection'>\(l) "Subcontractor employee" means any officer, partner, employee, or agent of a subcontractor.</p><p>(Source: P.A. 100-391, eff. 8-25-17.)</p>### (720 ILCS 5/33E-3) (from Ch. 38, par. 33E-3)
## Sec. 33E-3. Bid-rigging.
<p>A person commits the offense of bid-rigging when he knowingly agrees with any person who is, or but for such agreement would be, a competitor of such person concerning any bid submitted or not submitted by such person or another to a unit of State or local government when with the intent that the bid submitted or not submitted will result in the award of a contract to such person or another and he either (1) provides such person or receives from another information concerning the price or other material term or terms of the bid which would otherwise not be disclosed to a competitor in an independent noncollusive submission of bids or (2) submits a bid that is of such a price or other material term or terms that he does not intend the bid to be accepted.</p><p>Bid-rigging is a Class 3 felony. Any person convicted of this offense or any similar offense of any state or the United States which contains the same elements as this offense shall be barred for 5 years from the date of conviction from contracting with any unit of State or local government. No corporation shall be barred from contracting with any unit of State or local government as a result of a conviction under this Section of any employee or agent of such corporation if the employee so convicted is no longer employed by the corporation and: (1) it has been finally adjudicated not guilty or (2) if it demonstrates to the governmental entity with which it seeks to contract and that entity finds that the commission of the offense was neither authorized, requested, commanded, nor performed by a director, officer or a high managerial agent in behalf of the corporation as provided in paragraph (2) of subsection (a) of Section 5-4 of this Code.</p><p>(Source: P.A. 86-150.)</p>### (720 ILCS 5/33E-4) (from Ch. 38, par. 33E-4)
## Sec. 33E-4. Bid rotating.
<p>A person commits the offense of bid rotating when, pursuant to any collusive scheme or agreement with another, he engages in a pattern over time (which, for the purposes of this Section, shall include at least 3 contract bids within a period of 10 years, the most recent of which occurs after the effective date of this amendatory Act of 1988) of submitting sealed bids to units of State or local government with the intent that the award of such bids rotates, or is distributed among, persons or business entities which submit bids on a substantial number of the same contracts. Bid rotating is a Class 2 felony. Any person convicted of this offense or any similar offense of any state or the United States which contains the same elements as this offense shall be permanently barred from contracting with any unit of State or local government. No corporation shall be barred from contracting with any unit of State or local government as a result of a conviction under this Section of any employee or agent of such corporation if the employee so convicted is no longer employed by the corporation and: (1) it has been finally adjudicated not guilty or (2) if it demonstrates to the governmental entity with which it seeks to contract and that entity finds that the commission of the offense was neither authorized, requested, commanded, nor performed by a director, officer or a high managerial agent in behalf of the corporation as provided in paragraph (2) of subsection (a) of Section 5-4 of this Code.</p><p>(Source: P.A. 86-150.)</p>### (720 ILCS 5/33E-5) (from Ch. 38, par. 33E-5)
## Sec. 33E-5. Acquisition or disclosure of bidding information by public official. (a) Any person who is an official of or employed by any unit of State or local government who knowingly opens a sealed bid at a time or place other than as specified in the invitation to bid or as otherwise designated by the State or unit of local government, or outside the presence of witnesses required by the applicable statute or ordinance, commits a Class 4 felony.
<p class='subsection'>\(b) Any person who is an official of or employed by any unit of State or local government who knowingly discloses to any interested person any information related to the terms of a sealed bid whether that information is acquired through a violation of subsection (a) or by any other means except as provided by law or necessary to the performance of such official's or employee's responsibilities relating to the bid, commits a Class 3 felony.</p><p class='subsection'>\(c) It shall not constitute a violation of subsection (b) of this Section for any person who is an official of or employed by any unit of State or local government to make any disclosure to any interested person where such disclosure is also made generally available to the public.</p><p class='subsection'>\(d) This Section only applies to contracts let by sealed bid.</p><p>(Source: P.A. 86-150.)</p>### (720 ILCS 5/33E-6) (from Ch. 38, par. 33E-6)
## Sec. 33E-6. Interference with contract submission and award by public official.
<p class='subsection'>\(a) Any person who is an official of or employed by any unit of State or local government who knowingly conveys, either directly or indirectly, outside of the publicly available official invitation to bid, pre-bid conference, solicitation for contracts procedure or such procedure used in any sheltered market procurement adopted pursuant to law or ordinance by that unit of government, to any person any information concerning the specifications for such contract or the identity of any particular potential subcontractors, when inclusion of such information concerning the specifications or contractors in the bid or offer would influence the likelihood of acceptance of such bid or offer, commits a Class 4 felony. It shall not constitute a violation of this subsection to convey information intended to clarify plans or specifications regarding a public contract where such disclosure of information is also made generally available to the public.</p><p class='subsection'>\(b) Any person who is an official of or employed by any unit of State or local government who, either directly or indirectly, knowingly informs a bidder or offeror that the bid or offer will be accepted or executed only if specified individuals are included as subcontractors commits a Class 3 felony.</p><p class='subsection'>\(c) It shall not constitute a violation of subsection (a) of this Section where any person who is an official of or employed by any unit of State or local government follows procedures established (i) by federal, State or local minority or female owned business enterprise programs or (ii) pursuant to Section 45-57 of the Illinois Procurement Code.</p><p class='subsection'>\(d) Any bidder or offeror who is the recipient of communications from the unit of government which he reasonably believes to be proscribed by subsections (a) or (b), and fails to inform either the Attorney General or the State's Attorney for the county in which the unit of government is located, commits a Class A misdemeanor.</p><p class='subsection'>\(e) Any public official who knowingly awards a contract based on criteria which were not publicly disseminated via the invitation to bid, when such invitation to bid is required by law or ordinance, the pre-bid conference, or any solicitation for contracts procedure or such procedure used in any sheltered market procurement procedure adopted pursuant to statute or ordinance, commits a Class 3 felony.</p><p class='subsection'>\(f) It shall not constitute a violation of subsection (a) for any person who is an official of or employed by any unit of State or local government to provide to any person a copy of the transcript or other summary of any pre-bid conference where such transcript or summary is also made generally available to the public.</p><p>(Source: P.A. 97-260, eff. 8-5-11.)</p>### (720 ILCS 5/33E-7) (from Ch. 38, par. 33E-7)
## Sec. 33E-7. Kickbacks.
<p class='subsection'>\(a) A person violates this Section when he knowingly either:</p><p class='paragraph'>\(1) provides, attempts to provide or offers to provide any kickback;</p><p class='paragraph'>\(2) solicits, accepts or attempts to accept any kickback; or</p><p class='paragraph'>\(3) includes, directly or indirectly, the amount of any kickback prohibited by paragraphs (1) or (2) of this subsection (a) in the contract price charged by a subcontractor to a prime contractor or a higher tier subcontractor or in the contract price charged by a prime contractor to any unit of State or local government for a public contract.</p><p class='subsection'>\(b) Any person violates this Section when he has received an offer of a kickback, or has been solicited to make a kickback, and fails to report it to law enforcement officials, including but not limited to the Attorney General or the State's Attorney for the county in which the contract is to be performed.</p><p class='subsection'>\(c) A violation of subsection (a) is a Class 3 felony. A violation of subsection (b) is a Class 4 felony.</p><p class='subsection'>\(d) Any unit of State or local government may, in a civil action, recover a civil penalty from any person who knowingly engages in conduct which violates paragraph (3) of subsection (a) of this Section in twice the amount of each kickback involved in the violation. This subsection (d) shall in no way limit the ability of any unit of State or local government to recover monies or damages regarding public contracts under any other law or ordinance. A civil action shall be barred unless the action is commenced within 6 years after the later of (1) the date on which the conduct establishing the cause of action occurred or (2) the date on which the unit of State or local government knew or should have known that the conduct establishing the cause of action occurred.</p><p>(Source: P.A. 85-1295.)</p>### (720 ILCS 5/33E-8) (from Ch. 38, par. 33E-8)
## Sec. 33E-8. Bribery of inspector employed by contractor.
<p class='subsection'>\(a) A person commits bribery of an inspector when he offers to any person employed by a contractor or subcontractor on any public project contracted for by any unit of State or local government any property or other thing of value with the intent that such offer is for the purpose of obtaining wrongful certification or approval of the quality or completion of any goods or services supplied or performed in the course of work on such project. Violation of this subsection is a Class 4 felony.</p><p class='subsection'>\(b) Any person employed by a contractor or subcontractor on any public project contracted for by any unit of State or local government who accepts any property or other thing of value knowing that such was intentionally offered for the purpose of influencing the certification or approval of the quality or completion of any goods or services supplied or performed under subcontract to that contractor, and either before or afterwards issues such wrongful certification, commits a Class 3 felony. Failure to report such offer to law enforcement officials, including but not limited to the Attorney General or the State's Attorney for the county in which the contract is performed, constitutes a Class 4 felony.</p><p>(Source: P.A. 85-1295.)</p>### (720 ILCS 5/33E-9) (from Ch. 38, par. 33E-9)
## Sec. 33E-9. Change orders.
<p>Any change order authorized under this Section shall be made in writing. Any person employed by and authorized by any unit of State or local government to approve a change order to any public contract who knowingly grants that approval without first obtaining from the unit of State or local government on whose behalf the contract was signed, or from a designee authorized by that unit of State or local government, a determination in writing that (1) the circumstances said to necessitate the change in performance were not reasonably foreseeable at the time the contract was signed, or (2) the change is germane to the original contract as signed, or (3) the change order is in the best interest of the unit of State or local government and authorized by law, commits a Class 4 felony. The written determination and the written change order resulting from that determination shall be preserved in the contract's file which shall be open to the public for inspection. This Section shall only apply to a change order or series of change orders which authorize or necessitate an increase or decrease in either the cost of a public contract by a total of $25,000 or more or the time of completion by a total of 180 days or more.</p><p>(Source: P.A. 102-1119, eff. 1-23-23.)</p>### (720 ILCS 5/33E-10) (from Ch. 38, par. 33E-10)
## Sec. 33E-10. Rules of evidence.
<p class='subsection'>\(a) The certified bid is prima facie evidence of the bid.</p><p class='subsection'>\(b) It shall be presumed that in the absence of practices proscribed by this Article 33E, all persons who submit bids in response to an invitation to bid by any unit of State or local government submit their bids independent of all other bidders, without information obtained from the governmental entity outside the invitation to bid, and in a good faith effort to obtain the contract.</p><p>(Source: P.A. 85-1295.)</p>### (720 ILCS 5/33E-11) (from Ch. 38, par. 33E-11)
## Sec. 33E-11. (a) Every bid submitted to and public contract executed pursuant to such bid by the State or a unit of local government shall contain a certification by the prime contractor that the prime contractor is not barred from contracting with any unit of State or local government as a result of a violation of either Section 33E-3 or 33E-4 of this Article. The State and units of local government shall provide the appropriate forms for such certification.
<p class='subsection'>\(b) A contractor who knowingly makes a false statement, material to the certification, commits a Class 3 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/33E-12) (from Ch. 38, par. 33E-12)
## Sec. 33E-12. It shall not constitute a violation of any provisions of this Article for any person who is an official of or employed by a unit of State or local government to (1) disclose the name of any person who has submitted a bid in response to or requested plans or specifications regarding an invitation to bid or who has been awarded a public contract to any person or, (2) to convey information concerning acceptable alternatives or substitute to plans or specifications if such information is also made generally available to the public and mailed to any person who has submitted a bid in response to or requested plans or specifications regarding an invitation to bid on a public contract or, (3) to negotiate with the lowest responsible bidder a reduction in only the price term of the bid.
<p>(Source: P.A. 86-150.)</p>### (720 ILCS 5/33E-13) (from Ch. 38, par. 33E-13)
## Sec. 33E-13. Contract negotiations under the Local Government Professional Services Selection Act shall not be subject to the provisions of this Article.
<p>(Source: P.A. 87-855.)</p>### (720 ILCS 5/33E-14)
## Sec. 33E-14. False statements on vendor applications.
<p class='subsection'>\(a) A person commits false statements on vendor applications when he or she knowingly makes any false statement or report with the intent to influence in any way the action of any unit of local government or school district in considering a vendor application.</p><p class='subsection'>\(b) Sentence. False statements on vendor applications is a Class 3 felony.</p><p>(Source: P.A. 99-78, eff. 7-20-15.)</p>### (720 ILCS 5/33E-15)
## Sec. 33E-15. False entries.
<p class='subsection'>\(a) An officer, agent, or employee of, or anyone who is affiliated in any capacity with any unit of local government or school district commits false entries when he or she makes a false entry in any book, report, or statement of any unit of local government or school district with the intent to defraud the unit of local government or school district.</p><p class='subsection'>\(b) Sentence. False entries is a Class 3 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/33E-16)
## Sec. 33E-16. Misapplication of funds.
<p class='subsection'>\(a) An officer, director, agent, or employee of, or affiliated in any capacity with any unit of local government or school district commits misapplication of funds when he or she knowingly misapplies any of the moneys, funds, or credits of the unit of local government or school district.</p><p class='subsection'>\(b) Sentence. Misapplication of funds is a Class 3 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/33E-17)
## Sec. 33E-17. Unlawful participation.
<p>Whoever, being an officer, director, agent, or employee of, or affiliated in any capacity with any unit of local government or school district participates, shares in, or receiving directly or indirectly any money, profit, property, or benefit through any contract with the unit of local government or school district, with the intent to defraud the unit of local government or school district is guilty of a Class 3 felony.</p><p>(Source: P.A. 90-800, eff. 1-1-99.)</p>### (720 ILCS 5/33E-18)
## Sec. 33E-18. Unlawful stringing of bids.
<p class='subsection'>\(a) A person commits unlawful stringing of bids when he or she, with the intent to evade the bidding requirements of any unit of local government or school district, knowingly strings or assists in stringing or attempts to string any contract or job order with the unit of local government or school district.</p><p class='subsection'>\(b) Sentence. Unlawful stringing of bids is a Class 4 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13; 98-756, eff. 7-16-14.)</p>