# Article 38. Criminally Operated Businesses {.unnumbered}

### (720 ILCS 5/38-1) (from Ch. 38, par. 38-1)
## Sec. 38-1. Forfeiture of charter and revocation of certificate.
<p>The State's Attorney is authorized to institute civil proceedings in the Circuit Court to forfeit the charter of a corporation organized under the laws of this State or to revoke the certificate authorizing a foreign corporation to conduct business in this State. The Court may order the charter forfeited or the certificate revoked upon finding (a) that a director, officer, employee, agent or stockholder acting in behalf of the corporation has, in conducting the corporation's affairs, purposely engaged in a persistent course of intimidation, coercion, bribery or other such illegal conduct with the intent to compel other persons, firms, or corporations to deal with such corporation, and (b) that for the prevention of future illegal conduct of the same character, the public interest requires the charter of the corporation to be forfeited and the corporation to be dissolved or the certificate to be revoked.</p><p>(Source: Laws 1965, p. 1222.)</p>### (720 ILCS 5/38-2) (from Ch. 38, par. 38-2)
## Sec. 38-2. Enjoining operation of a business.
<p>The State's Attorney is authorized to institute civil proceedings in the Circuit Court to enjoin the operation of any business other than a corporation, including a partnership, joint venture or sole proprietorship. The Court may grant the injunction upon finding that (a) any person in control of any such business, who may be a partner in a partnership, a participant in a joint venture, the owner of a sole proprietorship, an employee or agent of any such business, or a person who, in fact, exercises control over the operations of any such business, has, in conducting its business affairs, purposely engaged in a persistent course of intimidation, coercion, bribery or other such illegal conduct with the intent to compel other persons, firms, or corporations to deal with such business, and (b) that for the prevention of future illegal conduct of the same character, the public interest requires the operation of the business to be enjoined.</p><p>(Source: Laws 1965, p. 1222.)</p>### (720 ILCS 5/38-3) (from Ch. 38, par. 38-3)
## Sec. 38-3. Institution and conduct of proceedings.
<p class='subsection'>\(a) The proceedings authorized by Section 38-1 may be instituted against a corporation in any county in which it is doing business and the proceedings shall be conducted in accordance with the Civil Practice Law and all existing and future amendments of that Law and the Supreme Court Rules now or hereafter adopted in relation to that Law. Such proceedings shall be deemed additional to any other proceeding authorized by law for the purpose of forfeiting the charter of a corporation or revoking the certificate of a foreign corporation.</p>
<p class='subsection'>\(b) The proceedings authorized by Section 38-2 may be instituted against a business other than a corporation in any county in which it is doing business and the proceedings shall be conducted in accordance with the Civil Practice Law and all existing and future amendments of that Law and the Supreme Court Rules now or hereafter adopted in relation to that Law.</p><p class='subsection'>\(c) Whenever proceedings are instituted against a corporation or business pursuant to Section 38-1 or 38-2, the State's Attorney shall give written notice of the institution of such proceedings to the corporation or business against which the proceedings are brought.</p><p>(Source: P.A. 82-783.)</p>