# Article 12a. Violent Video Games {.unnumbered}

<p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12A-1)
## Sec. 12A-1. Short title. 
<p>This Article may be cited as the Violent Video Games Law.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12A-5)
## Sec. 12A-5. Findings.
<p class='subsection'>\(a) The General Assembly finds that minors who play violent video games are more likely to:</p><p class='paragraph'>\(1) Exhibit violent, asocial, or aggressive behavior.</p><p class='paragraph'>\(2) Experience feelings of aggression.</p><p class='paragraph'>\(3) Experience a reduction of activity in the frontal lobes of the brain which is responsible for controlling behavior.</p><p class='subsection'>\(b) While the video game industry has adopted its own voluntary standards describing which games are appropriate for minors, those standards are not adequately enforced.</p><p class='subsection'>\(c) Minors are capable of purchasing and do purchase violent video games.</p><p class='subsection'>\(d) The State has a compelling interest in assisting parents in protecting their minor children from violent video games.</p><p class='subsection'>\(e) The State has a compelling interest in preventing violent, aggressive, and asocial behavior.</p><p class='subsection'>\(f) The State has a compelling interest in preventing psychological harm to minors who play violent video games.</p><p class='subsection'>\(g) The State has a compelling interest in eliminating any societal factors that may inhibit the physiological and neurological development of its youth.</p><p class='subsection'>\(h) The State has a compelling interest in facilitating the maturation of Illinois' children into law-abiding, productive adults.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12A-10)
## Sec. 12A-10. Definitions. 
<p>For the purposes of this Article, the following terms have the following meanings:</p><p class='subsection'>\(a) "Video game retailer" means a person who sells or rents video games to the public.</p><p class='subsection'>\(b) "Video game" means an object or device that stores recorded data or instructions, receives data or instructions generated by a person who uses it, and, by processing the data or instructions, creates an interactive game capable of being played, viewed, or experienced on or through a computer, gaming system, console, or other technology.</p><p class='subsection'>\(c) "Minor" means a person under 18 years of age.</p><p class='subsection'>\(d) "Person" includes but is not limited to an individual, corporation, partnership, and association.</p><p class='subsection'>\(e) "Violent" video games include depictions of or simulations of human-on-human violence in which the player kills or otherwise causes serious physical harm to another human. "Serious physical harm" includes depictions of death, dismemberment, amputation, decapitation, maiming, disfigurement, mutilation of body parts, or rape.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12A-15)
## Sec. 12A-15. Restricted sale or rental of violent video games.
<p class='subsection'>\(a) A person who sells, rents, or permits to be sold or rented, any violent video game to any minor, commits a petty offense for which a fine of $1,000 may be imposed.</p><p class='subsection'>\(b) A person who sells, rents, or permits to be sold or rented any violent video game via electronic scanner must program the electronic scanner to prompt sales clerks to check identification before the sale or rental transaction is completed. A person who violates this subsection (b) commits a petty offense for which a fine of $1,000 may be imposed.</p><p class='subsection'>\(c) A person may not sell or rent, or permit to be sold or rented, any violent video game through a self-scanning checkout mechanism. A person who violates this subsection (c) commits a petty offense for which a fine of $1,000 may be imposed.</p><p class='subsection'>\(d) A retail sales clerk shall not be found in violation of this Section unless he or she has complete knowledge that the party to whom he or she sold or rented a violent video game was a minor and the clerk sold or rented the video game to the minor with the specific intent to do so.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12A-20)
## Sec. 12A-20. Affirmative defenses.
<p>In any prosecution arising under this Article, it is an affirmative defense:</p><p class='paragraph'>\(1) that the defendant was a family member of the minor for whom the video game was purchased. "Family member" for the purpose of this Section, includes a parent, sibling, grandparent, aunt, uncle, or first cousin;</p><p class='paragraph'>\(2) that the minor who purchased the video game exhibited a draft card, driver's license, birth certificate or other official or apparently official document purporting to establish that the minor was 18 years of age or older, which the defendant reasonably relied on and reasonably believed to be authentic;</p><p class='paragraph'>\(3) for the video game retailer, if the retail sales clerk had complete knowledge that the party to whom he or she sold or rented a violent video game was a minor and the clerk sold or rented the video game to the minor with the specific intent to do so; or</p><p class='paragraph'>\(4) that the video game sold or rented was pre-packaged and rated EC, E10+, E, or T by the Entertainment Software Ratings Board.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12A-25)
## Sec. 12A-25. Labeling of violent video games.
<p class='subsection'>\(a) Video game retailers shall label all violent video games as defined in this Article, with a solid white "18" outlined in black. The "18" shall have dimensions of no less than 2 inches by 2 inches. The "18" shall be displayed on the front face of the video game package.</p><p class='subsection'>\(b) A retailer's failure to comply with this Section is a petty offense punishable by a fine of $500 for the first 3 violations, and $1,000 for every subsequent violation.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>