# Article 28. Gambling And Related Offenses {.unnumbered}

### (720 ILCS 5/28-1) (from Ch. 38, par. 28-1)
## Sec. 28-1. Gambling.
<p class='subsection'>\(a) A person commits gambling when he or she:</p><p class='paragraph'>\(1) knowingly plays a game of chance or skill for money or other thing of value, unless excepted in subsection (b) of this Section;</p><p class='paragraph'>\(2) knowingly makes a wager upon the result of any game, contest, or any political nomination, appointment or election;</p><p class='paragraph'>\(3) knowingly operates, keeps, owns, uses, purchases, exhibits, rents, sells, bargains for the sale or lease of, manufactures or distributes any gambling device;</p><p class='paragraph'>\(4) contracts to have or give himself or herself or another the option to buy or sell, or contracts to buy or sell, at a future time, any grain or other commodity whatsoever, or any stock or security of any company, where it is at the time of making such contract intended by both parties thereto that the contract to buy or sell, or the option, whenever exercised, or the contract resulting therefrom, shall be settled, not by the receipt or delivery of such property, but by the payment only of differences in prices thereof; however, the issuance, purchase, sale, exercise, endorsement or guarantee, by or through a person registered with the Secretary of State pursuant to Section 8 of the Illinois Securities Law of 1953, or by or through a person exempt from such registration under said Section 8, of a put, call, or other option to buy or sell securities which have been registered with the Secretary of State or which are exempt from such registration under Section 3 of the Illinois Securities Law of 1953 is not gambling within the meaning of this paragraph (4);</p><p class='paragraph'>\(5) knowingly owns or possesses any book, instrument or apparatus by means of which bets or wagers have been, or are, recorded or registered, or knowingly possesses any money which he has received in the course of a bet or wager;</p><p class='paragraph'>\(6) knowingly sells pools upon the result of any game or contest of skill or chance, political nomination, appointment or election;</p><p class='paragraph'>\(7) knowingly sets up or promotes any lottery or sells, offers to sell or transfers any ticket or share for any lottery;</p><p class='paragraph'>\(8) knowingly sets up or promotes any policy game or sells, offers to sell or knowingly possesses or transfers any policy ticket, slip, record, document or other similar device;</p><p class='paragraph'>\(9) knowingly drafts, prints or publishes any lottery ticket or share, or any policy ticket, slip, record, document or similar device, except for such activity related to lotteries, bingo games and raffles authorized by and conducted in accordance with the laws of Illinois or any other state or foreign government;</p><p class='paragraph'>\(10) knowingly advertises any lottery or policy game, except for such activity related to lotteries, bingo games and raffles authorized by and conducted in accordance with the laws of Illinois or any other state;</p><p class='paragraph'>\(11) knowingly transmits information as to wagers, betting odds, or changes in betting odds by telephone, telegraph, radio, semaphore or similar means; or knowingly installs or maintains equipment for the transmission or receipt of such information; except that nothing in this subdivision (11) prohibits transmission or receipt of such information for use in news reporting of sporting events or contests; or</p><p class='paragraph'>\(12) knowingly establishes, maintains, or operates an</p><p>Internet site that permits a person to play a game of chance or skill for money or other thing of value by means of the Internet or to make a wager upon the result of any game, contest, political nomination, appointment, or election by means of the Internet. This item (12) does not apply to activities referenced in items (6), (6.1), (8), (8.1), and (15) of subsection (b) of this Section.</p><p class='subsection'>\(b) Participants in any of the following activities shall not be convicted of gambling:</p><p class='paragraph'>\(1) Agreements to compensate for loss caused by the happening of chance including without limitation contracts of indemnity or guaranty and life or health or accident insurance.</p><p class='paragraph'>\(2) Offers of prizes, award or compensation to the actual contestants in any bona fide contest for the determination of skill, speed, strength or endurance or to the owners of animals or vehicles entered in such contest.</p><p class='paragraph'>\(3) Pari-mutuel betting as authorized by the law of this State.</p><p class='paragraph'>\(4) Manufacture of gambling devices, including the acquisition of essential parts therefor and the assembly thereof, for transportation in interstate or foreign commerce to any place outside this State when such transportation is not prohibited by any applicable Federal law; or the manufacture, distribution, or possession of video gaming terminals, as defined in the Video Gaming Act, by manufacturers, distributors, and terminal operators licensed to do so under the Video Gaming Act.</p><p class='paragraph'>\(5) The game commonly known as "bingo", when conducted in accordance with the Bingo License and Tax Act.</p><p class='paragraph'>\(6) Lotteries when conducted by the State of Illinois in accordance with the Illinois Lottery Law. This exemption includes any activity conducted by the Department of Revenue to sell lottery tickets pursuant to the provisions of the Illinois Lottery Law and its rules.</p><p class='paragraph'>\(6.1) The purchase of lottery tickets through the</p><p>Internet for a lottery conducted by the State of Illinois under the program established in Section 7.12 of the Illinois Lottery Law.</p><p class='paragraph'>\(7) Possession of an antique slot machine that is neither used nor intended to be used in the operation or promotion of any unlawful gambling activity or enterprise. For the purpose of this subparagraph (b)(7), an antique slot machine is one manufactured 25 years ago or earlier.</p><p class='paragraph'>\(8) Raffles and poker runs when conducted in accordance with the Raffles and Poker Runs Act.</p><p class='paragraph'>\(8.1) The purchase of raffle chances for a raffle conducted in accordance with the Raffles and Poker Runs Act.</p><p class='paragraph'>\(9) Charitable games when conducted in accordance with the Charitable Games Act.</p><p class='paragraph'>\(10) Pull tabs and jar games when conducted under the</p><p>Illinois Pull Tabs and Jar Games Act.</p><p class='paragraph'>\(11) Gambling games when authorized by the Illinois</p><p>Gambling Act.</p><p class='paragraph'>\(12) Video gaming terminal games at a licensed establishment, licensed truck stop establishment, licensed large truck stop establishment, licensed fraternal establishment, or licensed veterans establishment when conducted in accordance with the Video Gaming Act.</p><p class='paragraph'>\(13) Games of skill or chance where money or other things of value can be won but no payment or purchase is required to participate.</p><p class='paragraph'>\(14) Savings promotion raffles authorized under</p><p>Section 5g of the Illinois Banking Act, Section 7008 of the Savings Bank Act, Section 42.7 of the Illinois Credit Union Act, Section 5136B of the National Bank Act (12 U.S.C. 25a), or Section 4 of the Home Owners' Loan Act (12 U.S.C. 1463).</p><p class='paragraph'>\(15) Sports wagering when conducted in accordance with the Sports Wagering Act.</p><p class='subsection'>\(c) Sentence.</p><p>Gambling is a Class A misdemeanor. A second or subsequent conviction under subsections (a)(3) through (a)(12), is a Class 4 felony.</p><p class='subsection'>\(d) Circumstantial evidence.</p><p>In prosecutions under this Section circumstantial evidence shall have the same validity and weight as in any criminal prosecution.</p><p>(Source: P.A. 101-31, Article 25, Section 25-915, eff. 6-28-19; 101-31, Article 35, Section 35-80, eff. 6-28-19; 101-109, eff. 7-19-19; 102-558, eff. 8-20-21.)</p>### (720 ILCS 5/28-1.1) (from Ch. 38, par. 28-1.1)
## Sec. 28-1.1. Syndicated gambling.
<p class='subsection'>\(a) Declaration of Purpose. Recognizing the close relationship between professional gambling and other organized crime, it is declared to be the policy of the legislature to restrain persons from engaging in the business of gambling for profit in this State. This Section shall be liberally construed and administered with a view to carrying out this policy.</p><p class='subsection'>\(b) A person commits syndicated gambling when he or she operates a "policy game" or engages in the business of bookmaking.</p><p class='subsection'>\(c) A person "operates a policy game" when he or she knowingly uses any premises or property for the purpose of receiving or knowingly does receive from what is commonly called "policy":</p><p class='paragraph'>\(1) money from a person other than the bettor or player whose bets or plays are represented by the money; or</p><p class='paragraph'>\(2) written "policy game" records, made or used over any period of time, from a person other than the bettor or player whose bets or plays are represented by the written record.</p><p class='subsection'>\(d) A person engages in bookmaking when he or she knowingly receives or accepts more than five bets or wagers upon the result of any trials or contests of skill, speed or power of endurance or upon any lot, chance, casualty, unknown or contingent event whatsoever, which bets or wagers shall be of such size that the total of the amounts of money paid or promised to be paid to the bookmaker on account thereof shall exceed $2,000. Bookmaking is the receiving or accepting of bets or wagers regardless of the form or manner in which the bookmaker records them.</p><p class='subsection'>\(e) Participants in any of the following activities shall not be convicted of syndicated gambling:</p><p class='paragraph'>\(1) Agreements to compensate for loss caused by the happening of chance including without limitation contracts of indemnity or guaranty and life or health or accident insurance;</p><p class='paragraph'>\(2) Offers of prizes, award or compensation to the actual contestants in any bona fide contest for the determination of skill, speed, strength or endurance or to the owners of animals or vehicles entered in the contest;</p><p class='paragraph'>\(3) Pari-mutuel betting as authorized by law of this</p><p>State;</p><p class='paragraph'>\(4) Manufacture of gambling devices, including the acquisition of essential parts therefor and the assembly thereof, for transportation in interstate or foreign commerce to any place outside this State when the transportation is not prohibited by any applicable Federal law;</p><p class='paragraph'>\(5) Raffles and poker runs when conducted in accordance with the Raffles and Poker Runs Act;</p><p class='paragraph'>\(6) Gambling games conducted on riverboats, in casinos, or at organization gaming facilities when authorized by the Illinois Gambling Act;</p><p class='paragraph'>\(7) Video gaming terminal games at a licensed establishment, licensed truck stop establishment, licensed large truck stop establishment, licensed fraternal establishment, or licensed veterans establishment when conducted in accordance with the Video Gaming Act; and</p><p class='paragraph'>\(8) Savings promotion raffles authorized under</p><p>Section 5g of the Illinois Banking Act, Section 7008 of the Savings Bank Act, Section 42.7 of the Illinois Credit Union Act, Section 5136B of the National Bank Act (12 U.S.C. 25a), or Section 4 of the Home Owners' Loan Act (12 U.S.C. 1463).</p><p class='subsection'>\(f) Sentence. Syndicated gambling is a Class 3 felony.</p><p>(Source: P.A. 101-31, eff. 6-28-19.)</p>### (720 ILCS 5/28-2) (from Ch. 38, par. 28-2)
## Sec. 28-2. Definitions.
<p class='subsection'>\(a) A "gambling device" is any clock, tape machine, slot machine or other machines or device for the reception of money or other thing of value on chance or skill or upon the action of which money or other thing of value is staked, hazarded, bet, won, or lost; or any mechanism, furniture, fixture, equipment, or other device designed primarily for use in a gambling place. A "gambling device" does not include:</p><p class='paragraph'>\(1) A coin-in-the-slot operated mechanical device played for amusement which rewards the player with the right to replay such mechanical device, which device is so constructed or devised as to make such result of the operation thereof depend in part upon the skill of the player and which returns to the player thereof no money, property, or right to receive money or property.</p><p class='paragraph'>\(2) Vending machines by which full and adequate return is made for the money invested and in which there is no element of chance or hazard.</p><p class='paragraph'>\(3) A crane game. For the purposes of this paragraph</p><p class='paragraph'>\(3), a "crane game" is an amusement device involving skill, if it rewards the player exclusively with merchandise contained within the amusement device proper and limited to toys, novelties, and prizes other than currency, each having a wholesale value which is not more than $25.</p><p class='paragraph'>\(4) A redemption machine. For the purposes of this paragraph (4), a "redemption machine" is a single-player or multi-player amusement device involving a game, the object of which is throwing, rolling, bowling, shooting, placing, or propelling a ball or other object that is either physical or computer generated on a display or with lights into, upon, or against a hole or other target that is either physical or computer generated on a display or with lights, or stopping, by physical, mechanical, or electronic means, a moving object that is either physical or computer generated on a display or with lights into, upon, or against a hole or other target that is either physical or computer generated on a display or with lights, provided that all of the following conditions are met:</p><p class='subparagraph'>\(A) The outcome of the game is predominantly determined by the skill of the player.</p><p class='subparagraph'>\(B) The award of the prize is based solely upon the player's achieving the object of the game or otherwise upon the player's score.</p><p class='subparagraph'>\(C) Only merchandise prizes are awarded.</p><p class='subparagraph'>\(D) The wholesale value of prizes awarded in lieu of tickets or tokens for single play of the device does not exceed $25.</p><p class='subparagraph'>\(E) The redemption value of tickets, tokens, and other representations of value, which may be accumulated by players to redeem prizes of greater value, for a single play of the device does not exceed $25.</p><p class='paragraph'>\(5) Video gaming terminals at a licensed establishment, licensed truck stop establishment, licensed large truck stop establishment, licensed fraternal establishment, or licensed veterans establishment licensed in accordance with the Video Gaming Act.</p><p class='subsection'>\(a-5) "Internet" means an interactive computer service or system or an information service, system, or access software provider that provides or enables computer access by multiple users to a computer server, and includes, but is not limited to, an information service, system, or access software provider that provides access to a network system commonly known as the Internet, or any comparable system or service and also includes, but is not limited to, a World Wide Web page, newsgroup, message board, mailing list, or chat area on any interactive computer service or system or other online service.</p><p class='subsection'>\(a-6) "Access" has the meaning ascribed to the term in Section 17-55.</p><p class='subsection'>\(a-7) "Computer" has the meaning ascribed to the term in Section 17-0.5.</p><p class='subsection'>\(b) A "lottery" is any scheme or procedure whereby one or more prizes are distributed by chance among persons who have paid or promised consideration for a chance to win such prizes, whether such scheme or procedure is called a lottery, raffle, gift, sale, or some other name, excluding savings promotion raffles authorized under Section 5g of the Illinois Banking Act, Section 7008 of the Savings Bank Act, Section 42.7 of the Illinois Credit Union Act, Section 5136B of the National Bank Act (12 U.S.C. 25a), or Section 4 of the Home Owners' Loan Act (12 U.S.C. 1463).</p><p class='subsection'>\(c) A "policy game" is any scheme or procedure whereby a person promises or guarantees by any instrument, bill, certificate, writing, token, or other device that any particular number, character, ticket, or certificate shall in the event of any contingency in the nature of a lottery entitle the purchaser or holder to receive money, property, or evidence of debt.</p><p>(Source: P.A. 101-31, eff. 6-28-19; 101-87, eff. 1-1-20; 102-558, eff. 8-20-21.)</p>### (720 ILCS 5/28-3) (from Ch. 38, par. 28-3)
## Sec. 28-3. Keeping a gambling place.
<p>A "gambling place" is any real estate, vehicle, boat, or any other property whatsoever used for the purposes of gambling other than gambling conducted in the manner authorized by the Illinois Gambling Act, the Sports Wagering Act, or the Video Gaming Act. Any person who knowingly permits any premises or property owned or occupied by him or under his control to be used as a gambling place commits a Class A misdemeanor. Each subsequent offense is a Class 4 felony. When any premises is determined by the circuit court to be a gambling place:</p><p class='subsection'>\(a) Such premises is a public nuisance and may be proceeded against as such, and</p><p class='subsection'>\(b) All licenses, permits or certificates issued by the State of Illinois or any subdivision or public agency thereof authorizing the serving of food or liquor on such premises shall be void; and no license, permit or certificate so cancelled shall be reissued for such premises for a period of 60 days thereafter; nor shall any person convicted of keeping a gambling place be reissued such license for one year from his conviction and, after a second conviction of keeping a gambling place, any such person shall not be reissued such license, and</p><p class='subsection'>\(c) Such premises of any person who knowingly permits thereon a violation of any Section of this Article shall be held liable for, and may be sold to pay any unsatisfied judgment that may be recovered and any unsatisfied fine that may be levied under any Section of this Article.</p><p>(Source: P.A. 101-31, Article 25, Section 25-915, eff. 6-28-19; 101-31, Article 35, Section 35-80, eff. 6-28-19; 102-558, eff. 8-20-21.)</p>### (720 ILCS 5/28-4) (from Ch. 38, par. 28-4)
## Sec. 28-4. Registration of Federal Gambling Stamps.
<p class='subsection'>\(a) Every person who has purchased a Federal Wagering Occupational Tax Stamp, as required by the United States under the applicable provisions of the Internal Revenue Code, or a Federal Gaming Device Tax Stamp, as required by the United States under the applicable provisions of the Internal Revenue Code, shall register forthwith such stamp or stamps with the county clerk's office in which he resides and the county clerk's office of each and every county in which he conducts any business. A violation of this Section is a Class B misdemeanor. A subsequent violation is a Class A misdemeanor.</p><p class='subsection'>\(b) To register a stamp as required by this Section, each individual stamp purchaser and each member of a firm or association which is a stamp purchaser and, if such purchaser is corporate, the registered agent of the purchasing corporation shall deliver the stamp to the county clerk for inspection and shall under oath or affirmation complete and sign a registration form which shall state the full name and residence and business address of each purchaser and of each member of a purchasing firm or association and of each person employed or engaged in gambling on behalf of such purchaser, shall state the registered agent and registered address of a corporate purchaser, shall state each place where gambling is to be performed by or on behalf of the purchaser, and shall state the duration of validity of the stamp and the federal registration number and tax return number thereof. Any false statement in the registration form is material and is evidence of perjury.</p><p class='subsection'>\(c) Within 3 days after such registration the county clerk shall by registered mail forward notice of such registration and a duplicate copy of each registration form to the Attorney General of this State, to the Chairman of the Illinois Liquor Control Commission, to the State's Attorney and Sheriff of each county wherein the stamp is registered, and to the principal official of the department of police of each city, village and incorporated town in this State wherein the stamp is registered or wherein the registrant maintains a business address.</p><p>(Source: P.A. 77-2638.)</p>### (720 ILCS 5/28-5) (from Ch. 38, par. 28-5)
## Sec. 28-5. Seizure of gambling devices and gambling funds.
<p class='subsection'>\(a) Every device designed for gambling which is incapable of lawful use or every device used unlawfully for gambling shall be considered a "gambling device", and shall be subject to seizure, confiscation and destruction by the Illinois State Police or by any municipal, or other local authority, within whose jurisdiction the same may be found. As used in this Section, a "gambling device" includes any slot machine, and includes any machine or device constructed for the reception of money or other thing of value and so constructed as to return, or to cause someone to return, on chance to the player thereof money, property or a right to receive money or property. With the exception of any device designed for gambling which is incapable of lawful use, no gambling device shall be forfeited or destroyed unless an individual with a property interest in said device knows of the unlawful use of the device.</p><p class='subsection'>\(b) Every gambling device shall be seized and forfeited to the county wherein such seizure occurs. Any money or other thing of value integrally related to acts of gambling shall be seized and forfeited to the county wherein such seizure occurs.</p><p class='subsection'>\(c) If, within 60 days after any seizure pursuant to subparagraph (b) of this Section, a person having any property interest in the seized property is charged with an offense, the court which renders judgment upon such charge shall, within 30 days after such judgment, conduct a forfeiture hearing to determine whether such property was a gambling device at the time of seizure. Such hearing shall be commenced by a written petition by the State, including material allegations of fact, the name and address of every person determined by the State to have any property interest in the seized property, a representation that written notice of the date, time and place of such hearing has been mailed to every such person by certified mail at least 10 days before such date, and a request for forfeiture. Every such person may appear as a party and present evidence at such hearing. The quantum of proof required shall be a preponderance of the evidence, and the burden of proof shall be on the State. If the court determines that the seized property was a gambling device at the time of seizure, an order of forfeiture and disposition of the seized property shall be entered: a gambling device shall be received by the State's Attorney, who shall effect its destruction, except that valuable parts thereof may be liquidated and the resultant money shall be deposited in the general fund of the county wherein such seizure occurred; money and other things of value shall be received by the State's Attorney and, upon liquidation, shall be deposited in the general fund of the county wherein such seizure occurred. However, in the event that a defendant raises the defense that the seized slot machine is an antique slot machine described in subparagraph (b) (7) of Section 28-1 of this Code and therefore he is exempt from the charge of a gambling activity participant, the seized antique slot machine shall not be destroyed or otherwise altered until a final determination is made by the Court as to whether it is such an antique slot machine. Upon a final determination by the Court of this question in favor of the defendant, such slot machine shall be immediately returned to the defendant. Such order of forfeiture and disposition shall, for the purposes of appeal, be a final order and judgment in a civil proceeding.</p><p class='subsection'>\(d) If a seizure pursuant to subparagraph (b) of this Section is not followed by a charge pursuant to subparagraph (c) of this Section, or if the prosecution of such charge is permanently terminated or indefinitely discontinued without any judgment of conviction or acquittal (1) the State's Attorney shall commence an in rem proceeding for the forfeiture and destruction of a gambling device, or for the forfeiture and deposit in the general fund of the county of any seized money or other things of value, or both, in the circuit court and (2) any person having any property interest in such seized gambling device, money or other thing of value may commence separate civil proceedings in the manner provided by law.</p><p class='subsection'>\(e) Any gambling device displayed for sale to a riverboat gambling operation, casino gambling operation, or organization gaming facility or used to train occupational licensees of a riverboat gambling operation, casino gambling operation, or organization gaming facility as authorized under the Illinois Gambling Act is exempt from seizure under this Section.</p><p class='subsection'>\(f) Any gambling equipment, devices, and supplies provided by a licensed supplier in accordance with the Illinois Gambling Act which are removed from a riverboat, casino, or organization gaming facility for repair are exempt from seizure under this Section.</p><p class='subsection'>\(g) The following video gaming terminals are exempt from seizure under this Section:</p><p class='paragraph'>\(1) Video gaming terminals for sale to a licensed distributor or operator under the Video Gaming Act.</p><p class='paragraph'>\(2) Video gaming terminals used to train licensed technicians or licensed terminal handlers.</p><p class='paragraph'>\(3) Video gaming terminals that are removed from a licensed establishment, licensed truck stop establishment, licensed large truck stop establishment, licensed fraternal establishment, or licensed veterans establishment for repair.</p><p class='subsection'>\(h) Property seized or forfeited under this Section is subject to reporting under the Seizure and Forfeiture Reporting Act.</p><p class='item'>\(i) Any sports lottery terminals provided by a central system provider that are removed from a lottery retailer for repair under the Sports Wagering Act are exempt from seizure under this Section.</p><p>(Source: P.A. 101-31, Article 25, Section 25-915, eff. 6-28-19; 101-31, Article 35, Section 35-80, eff. 6-28-19; 102-538, eff. 8-20-21; 102-558, eff. 8-20-21.)</p>### (720 ILCS 5/28-7) (from Ch. 38, par. 28-7)
## Sec. 28-7. Gambling contracts void.
<p class='subsection'>\(a) All promises, notes, bills, bonds, covenants, contracts, agreements, judgments, mortgages, or other securities or conveyances made, given, granted, drawn, or entered into, or executed by any person whatsoever, where the whole or any part of the consideration thereof is for any money or thing of value, won or obtained in violation of any Section of this Article are null and void.</p><p class='subsection'>\(b) Any obligation void under this Section may be set aside and vacated by any court of competent jurisdiction, upon a complaint filed for that purpose, by the person so granting, giving, entering into, or executing the same, or by his executors or administrators, or by any creditor, heir, legatee, purchaser or other person interested therein; or if a judgment, the same may be set aside on motion of any person stated above, on due notice thereof given.</p><p class='subsection'>\(c) No assignment of any obligation void under this Section may in any manner affect the defense of the person giving, granting, drawing, entering into or executing such obligation, or the remedies of any person interested therein.</p><p class='subsection'>\(d) This Section shall not prevent a licensed owner of a riverboat gambling operation, a casino gambling operation, or an organization gaming licensee under the Illinois Gambling Act and the Illinois Horse Racing Act of 1975 from instituting a cause of action to collect any amount due and owing under an extension of credit to a gambling patron as authorized under Section 11.1 of the Illinois Gambling Act.</p><p>(Source: P.A. 101-31, eff. 6-28-19.)</p>### (720 ILCS 5/28-8) (from Ch. 38, par. 28-8)
## Sec. 28-8. Gambling losses recoverable.
<p class='subsection'>\(a) Any person who by gambling shall lose to any other person, any sum of money or thing of value, amounting to the sum of $50 or more and shall pay or deliver the same or any part thereof, may sue for and recover the money or other thing of value, so lost and paid or delivered, in a civil action against the winner thereof, with costs, in the circuit court. No person who accepts from another person for transmission, and transmits, either in his own name or in the name of such other person, any order for any transaction to be made upon, or who executes any order given to him by another person, or who executes any transaction for his own account on, any regular board of trade or commercial, commodity or stock exchange, shall, under any circumstances, be deemed a "winner" of any moneys lost by such other person in or through any such transactions.</p><p class='subsection'>\(b) If within 6 months, such person who under the terms of Subsection 28-8(a) is entitled to initiate action to recover his losses does not in fact pursue his remedy, any person may initiate a civil action against the winner. The court or the jury, as the case may be, shall determine the amount of the loss. After such determination, the court shall enter a judgment of triple the amount so determined.</p><p class='subsection'>\(c) Gambling losses as a result of gambling conducted on a video gaming terminal licensed under the Video Gaming Act are not recoverable under this Section.</p><p>(Source: P.A. 98-31, eff. 6-24-13.)</p>### (720 ILCS 5/28-9) (from Ch. 38, par. 28-9)
## Sec. 28-9. At the option of the prosecuting attorney any prosecution under this Article may be commenced by an information as defined in Section 102-12 of the Code of Criminal Procedure of 1963.
<p>(Source: P.A. 76-1131 .)</p>