# Article 26.5. Harassing And Obscene Communications {.unnumbered}

<p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26.5-0.1)
## Sec. 26.5-0.1. Definitions.
<p>As used in this Article:</p><p>"Electronic communication" means any transfer of signs, signals, writings, images, sounds, data or intelligence of any nature transmitted in whole or in part by a wire, radio, electromagnetic, photoelectric or photo-optical system. "Electronic communication" includes transmissions through an electronic device including, but not limited to, a telephone, cellular phone, computer, or pager, which communication includes, but is not limited to, e-mail, instant message, text message, or voice mail.</p><p>"Family or household member" includes spouses, former spouses, parents, children, stepchildren and other persons related by blood or by present or prior marriage, persons who share or formerly shared a common dwelling, persons who have or allegedly share a blood relationship through a child, persons who have or have had a dating or engagement relationship, and persons with disabilities and their personal assistants. For purposes of this Article, neither a casual acquaintanceship nor ordinary fraternization between 2 individuals in business or social contexts shall be deemed to constitute a dating relationship.</p><p>"Harass" or "harassing" means knowing conduct which is not necessary to accomplish a purpose that is reasonable under the circumstances, that would cause a reasonable person emotional distress and does cause emotional distress to another.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26.5-1)
## Sec. 26.5-1. Transmission of obscene messages.
<p class='subsection'>\(a) A person commits transmission of obscene messages when he or she sends messages or uses language or terms which are obscene, lewd or immoral with the intent to offend by means of or while using a telephone or telegraph facilities, equipment or wires of any person, firm or corporation engaged in the transmission of news or messages between states or within the State of Illinois.</p><p class='subsection'>\(b) The trier of fact may infer intent to offend from the use of language or terms which are obscene, lewd or immoral.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26.5-2)
## Sec. 26.5-2. Harassment by telephone.
<p class='subsection'>\(a) A person commits harassment by telephone when he or she uses telephone communication for any of the following purposes:</p><p class='paragraph'>\(1) Making any comment, request, suggestion or proposal which is obscene, lewd, lascivious, filthy or indecent with an intent to offend;</p><p class='paragraph'>\(2) Making a telephone call, whether or not conversation ensues, with intent to abuse, threaten or harass any person at the called number;</p><p class='paragraph'>\(3) Making or causing the telephone of another repeatedly to ring, with intent to harass any person at the called number;</p><p class='paragraph'>\(4) Making repeated telephone calls, during which conversation ensues, solely to harass any person at the called number;</p><p class='paragraph'>\(5) Making a telephone call or knowingly inducing a person to make a telephone call for the purpose of harassing another person who is under 13 years of age, regardless of whether the person under 13 years of age consents to the harassment, if the defendant is at least 16 years of age at the time of the commission of the offense; or</p><p class='paragraph'>\(6) Knowingly permitting any telephone under one's control to be used for any of the purposes mentioned herein.</p><p class='subsection'>\(b) Every telephone directory published for distribution to members of the general public shall contain a notice setting forth a summary of the provisions of this Section. The notice shall be printed in type which is no smaller than any other type on the same page and shall be preceded by the word "WARNING". All telephone companies in this State shall cooperate with law enforcement agencies in using their facilities and personnel to detect and prevent violations of this Article.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26.5-3)
## Sec. 26.5-3. Harassment through electronic communications.
<p class='subsection'>\(a) A person commits harassment through electronic communications when he or she uses electronic communication for any of the following purposes:</p><p class='paragraph'>\(1) Making any comment, request, suggestion or proposal which is obscene with an intent to offend;</p><p class='paragraph'>\(2) Interrupting, with the intent to harass, the telephone service or the electronic communication service of any person;</p><p class='paragraph'>\(3) Transmitting to any person, with the intent to harass and regardless of whether the communication is read in its entirety or at all, any file, document, or other communication which prevents that person from using his or her telephone service or electronic communications device;</p><p class='paragraph'>\(4) Transmitting an electronic communication or knowingly inducing a person to transmit an electronic communication for the purpose of harassing another person who is under 13 years of age, regardless of whether the person under 13 years of age consents to the harassment, if the defendant is at least 16 years of age at the time of the commission of the offense;</p><p class='paragraph'>\(5) Threatening injury to the person or to the property of the person to whom an electronic communication is directed or to any of his or her family or household members; or</p><p class='paragraph'>\(6) Knowingly permitting any electronic communications device to be used for any of the purposes mentioned in this subsection (a).</p><p class='subsection'>\(b) Telecommunications carriers, commercial mobile service providers, and providers of information services, including, but not limited to, Internet service providers and hosting service providers, are not liable under this Section, except for willful and wanton misconduct, by virtue of the transmission, storage, or caching of electronic communications or messages of others or by virtue of the provision of other related telecommunications, commercial mobile services, or information services used by others in violation of this Section.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26.5-4)
## Sec. 26.5-4. Evidence inference.
<p>Evidence that a defendant made additional telephone calls or engaged in additional electronic communications after having been requested by a named complainant or by a family or household member of the complainant to stop may be considered as evidence of an intent to harass unless disproved by evidence to the contrary.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/26.5-5)
## Sec. 26.5-5. Sentence.
<p class='subsection'>\(a) Except as provided in subsection (b), a person who violates any of the provisions of Section 26.5-1, 26.5-2, or 26.5-3 of this Article is guilty of a Class B misdemeanor. Except as provided in subsection (b), a second or subsequent violation of Section 26.5-1, 26.5-2, or 26.5-3 of this Article is a Class A misdemeanor, for which the court shall impose a minimum of 14 days in jail or, if public or community service is established in the county in which the offender was convicted, 240 hours of public or community service.</p><p class='subsection'>\(b) In any of the following circumstances, a person who violates Section 26.5-1, 26.5-2, or 26.5-3 of this Article shall be guilty of a Class 4 felony:</p><p class='paragraph'>\(1) The person has 3 or more prior violations in the last 10 years of harassment by telephone, harassment through electronic communications, or any similar offense of any other state;</p><p class='paragraph'>\(2) The person has previously violated the harassment by telephone provisions, or the harassment through electronic communications provisions, or committed any similar offense in any other state with the same victim or a member of the victim's family or household;</p><p class='paragraph'>\(3) At the time of the offense, the offender was under conditions of pretrial release, probation, conditional discharge, mandatory supervised release or was the subject of an order of protection, in this or any other state, prohibiting contact with the victim or any member of the victim's family or household;</p><p class='paragraph'>\(4) In the course of the offense, the offender threatened to kill the victim or any member of the victim's family or household;</p><p class='paragraph'>\(5) The person has been convicted in the last 10 years of a forcible felony as defined in Section 2-8 of the Criminal Code of 1961 or the Criminal Code of 2012;</p><p class='paragraph'>\(6) The person violates paragraph (5) of Section</p><p>26.5-2 or paragraph (4) of Section 26.5-3; or</p><p class='paragraph'>\(7) The person was at least 18 years of age at the time of the commission of the offense and the victim was under 18 years of age at the time of the commission of the offense.</p><p class='subsection'>\(c) The court may order any person convicted under this Article to submit to a psychiatric examination.</p><p>(Source: P.A. 101-652, eff. 1-1-23 .)</p>