# Article 33f. Unlawful Use Of Body Armor {.unnumbered}

### (720 ILCS 5/33F-1) (from Ch. 38, par. 33F-1)
## Sec. 33F-1. Definitions.
<p>For purposes of this Article:</p><p class='subsection'>\(a) "Body Armor" means any one of the following:</p><p class='paragraph'>\(1) A military style flak or tactical assault vest which is made of Kevlar or any other similar material or metal, fiberglass, plastic, and nylon plates and designed to be worn over one's clothing for the intended purpose of stopping not only missile fragmentation from mines, grenades, mortar shells and artillery fire but also fire from rifles, machine guns, and small arms.</p><p class='paragraph'>\(2) Soft body armor which is made of Kevlar or any other similar material or metal or any other type of insert and which is lightweight and pliable and which can be easily concealed under a shirt.</p><p class='paragraph'>\(3) A military style recon/surveillance vest which is made of Kevlar or any other similar material and which is lightweight and designed to be worn over one's clothing.</p><p class='paragraph'>\(4) Protective casual clothing which is made of</p><p>Kevlar or any other similar material and which was originally intended to be used by undercover law enforcement officers or dignitaries and is designed to look like jackets, coats, raincoats, quilted or three piece suit vests.</p><p class='subsection'>\(b) "Dangerous weapon" means a Category I, Category II, or Category III weapon as defined in Section 33A-1 of this Code.</p><p>(Source: P.A. 91-696, eff. 4-13-00.)</p>### (720 ILCS 5/33F-2) (from Ch. 38, par. 33F-2)
## Sec. 33F-2. Unlawful use of body armor.
<p>A person commits the offense of unlawful use of body armor when he knowingly wears body armor and is in possession of a dangerous weapon, other than a firearm, in the commission or attempted commission of any offense.</p><p>(Source: P.A. 93-906, eff. 8-11-04.)</p>### (720 ILCS 5/33F-3) (from Ch. 38, par. 33F-3)
## Sec. 33F-3. Sentence.
<p>A person convicted of unlawful use of body armor for a first offense shall be guilty of a Class A misdemeanor and for a second or subsequent offense shall be guilty of a Class 4 felony.</p><p>(Source: P.A. 87-521.)</p>