# Article 18. Robbery {.unnumbered}

### (720 ILCS 5/18-1) (from Ch. 38, par. 18-1)
## Sec. 18-1. Robbery; aggravated robbery.
<p class='subsection'>\(a) Robbery. A person commits robbery when he or she knowingly takes property, except a motor vehicle covered by Section 18-3 or 18-4, from the person or presence of another by the use of force or by threatening the imminent use of force.</p><p class='subsection'>\(b) Aggravated robbery.</p><p class='paragraph'>\(1) A person commits aggravated robbery when he or she violates subsection (a) while indicating verbally or by his or her actions to the victim that he or she is presently armed with a firearm or other dangerous weapon, including a knife, club, ax, or bludgeon. This offense shall be applicable even though it is later determined that he or she had no firearm or other dangerous weapon, including a knife, club, ax, or bludgeon, in his or her possession when he or she committed the robbery.</p><p class='paragraph'>\(2) A person commits aggravated robbery when he or she knowingly takes property from the person or presence of another by delivering (by injection, inhalation, ingestion, transfer of possession, or any other means) to the victim without his or her consent, or by threat or deception, and for other than medical purposes, any controlled substance.</p><p class='subsection'>\(c) Sentence.</p><p>Robbery is a Class 2 felony, unless the victim is 60 years of age or over or is a person with a physical disability, or the robbery is committed in a school, day care center, day care home, group day care home, or part day child care facility, or place of worship, in which case robbery is a Class 1 felony. Aggravated robbery is a Class 1 felony.</p><p class='subsection'>\(d) Regarding penalties prescribed in subsection (c) for violations committed in a day care center, day care home, group day care home, or part day child care facility, the time of day, time of year, and whether children under 18 years of age were present in the day care center, day care home, group day care home, or part day child care facility are irrelevant.</p><p>(Source: P.A. 99-143, eff. 7-27-15.)</p>### (720 ILCS 5/18-2) (from Ch. 38, par. 18-2)
## Sec. 18-2. Armed robbery.
<p class='subsection'>\(a) A person commits armed robbery when he or she violates Section 18-1; and</p><p class='paragraph'>\(1) he or she carries on or about his or her person or is otherwise armed with a dangerous weapon other than a firearm; or</p><p class='paragraph'>\(2) he or she carries on or about his or her person or is otherwise armed with a firearm; or</p><p class='paragraph'>\(3) he or she, during the commission of the offense, personally discharges a firearm; or</p><p class='paragraph'>\(4) he or she, during the commission of the offense, personally discharges a firearm that proximately causes great bodily harm, permanent disability, permanent disfigurement, or death to another person.</p><p class='subsection'>\(b) Sentence.</p><p>Armed robbery in violation of subsection (a)(1) is a Class X felony. A violation of subsection (a)(2) is a Class X felony for which 15 years shall be added to the term of imprisonment imposed by the court. A violation of subsection (a)(3) is a Class X felony for which 20 years shall be added to the term of imprisonment imposed by the court. A violation of subsection (a)(4) is a Class X felony for which 25 years or up to a term of natural life shall be added to the term of imprisonment imposed by the court.</p><p>(Source: P.A. 91-404, eff. 1-1-00 .)</p>### (720 ILCS 5/18-3)
## Sec. 18-3. Vehicular hijacking.
<p class='subsection'>\(a) A person commits vehicular hijacking when he or she knowingly takes a motor vehicle from the person or the immediate presence of another by the use of force or by threatening the imminent use of force.</p><p class='subsection'>\(b) Sentence. Vehicular hijacking is a Class 1 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/18-4)
## Sec. 18-4. Aggravated vehicular hijacking.
<p class='subsection'>\(a) A person commits aggravated vehicular hijacking when he or she violates Section 18-3; and</p><p class='paragraph'>\(1) the person from whose immediate presence the motor vehicle is taken is a person with a physical disability or a person 60 years of age or over; or</p><p class='paragraph'>\(2) a person under 16 years of age is a passenger in the motor vehicle at the time of the offense; or</p><p class='paragraph'>\(3) he or she carries on or about his or her person, or is otherwise armed with a dangerous weapon, other than a firearm; or</p><p class='paragraph'>\(4) he or she carries on or about his or her person or is otherwise armed with a firearm; or</p><p class='paragraph'>\(5) he or she, during the commission of the offense, personally discharges a firearm; or</p><p class='paragraph'>\(6) he or she, during the commission of the offense, personally discharges a firearm that proximately causes great bodily harm, permanent disability, permanent disfigurement, or death to another person.</p><p class='subsection'>\(b) Sentence. Aggravated vehicular hijacking in violation of subsections (a)(1) or (a)(2) is a Class X felony. A violation of subsection (a)(3) is a Class X felony for which a term of imprisonment of not less than 7 years shall be imposed. A violation of subsection (a)(4) is a Class X felony for which 15 years shall be added to the term of imprisonment imposed by the court. A violation of subsection (a)(5) is a Class X felony for which 20 years shall be added to the term of imprisonment imposed by the court. A violation of subsection (a)(6) is a Class X felony for which 25 years or up to a term of natural life shall be added to the term of imprisonment imposed by the court.</p><p>(Source:</p><p>P.A. 99-143, eff. 7-27-15.)</p>### (720 ILCS 5/18-5)
## Sec. 18-5. (Repealed).
<p>(Source: P.A. 91-357, eff. 7-29-99. Repealed by P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/18-6)
<p class='subsection'>\(was 720 ILCS 5/12-11.1)</p>## Sec. 18-6. Vehicular invasion.
<p class='subsection'>\(a) A person commits vehicular invasion when he or she knowingly, by force and without lawful justification, enters or reaches into the interior of a motor vehicle while the motor vehicle is occupied by another person or persons, with the intent to commit therein a theft or felony.</p><p class='subsection'>\(b) Sentence. Vehicular invasion is a Class 1 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>