# Article 1. Title And Construction Of Act; {.unnumbered}

### (720 ILCS 5/1-1) (from Ch. 38, par. 1-1)
## Sec. 1-1. Short title.
<p>This Act may be cited as the</p><p>Criminal Code of 2012.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/1-2) (from Ch. 38, par. 1-2)
## Sec. 1-2. General purposes.
<p>The provisions of this Code shall be construed in accordance with the general purposes hereof, to:</p><p class='subsection'>\(a) Forbid and prevent the commission of offenses;</p><p class='subsection'>\(b) Define adequately the act and mental state which constitute each offense, and limit the condemnation of conduct as criminal when it is without fault;</p><p class='subsection'>\(c) Prescribe penalties which are proportionate to the seriousness of offenses and which permit recognition of differences in rehabilitation possibilities among individual offenders;</p><p class='subsection'>\(d) Prevent arbitrary or oppressive treatment of persons accused or convicted of offenses.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/1-3) (from Ch. 38, par. 1-3)
## Sec. 1-3. Applicability of common law.
<p>No conduct constitutes an offense unless it is described as an offense in this Code or in another statute of this State. However, this provision does not affect the power of a court to punish for contempt or to employ any sanction authorized by law for the enforcement of an order or civil judgment.</p><p>(Source: P.A. 79-1360.)</p>### (720 ILCS 5/1-4) (from Ch. 38, par. 1-4)
## Sec. 1-4. Civil remedies preserved.
<p>This Code does not bar, suspend, or otherwise affect any right or liability to damages, penalty, forfeiture, or other remedy authorized by law to be recovered or enforced in a civil action, for any conduct which this Code makes punishable; and the civil injury is not merged in the offense.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/1-5) (from Ch. 38, par. 1-5)
## Sec. 1-5. State criminal jurisdiction.
<p class='subsection'>\(a) A person is subject to prosecution in this State for an offense which he commits, while either within or outside the State, by his own conduct or that of another for which he is legally accountable, if:</p><p class='paragraph'>\(1) the offense is committed either wholly or partly within the State; or</p><p class='paragraph'>\(2) the conduct outside the State constitutes an attempt to commit an offense within the State; or</p><p class='paragraph'>\(3) the conduct outside the State constitutes a conspiracy to commit an offense within the State, and an act in furtherance of the conspiracy occurs in the State; or</p><p class='paragraph'>\(4) the conduct within the State constitutes an attempt, solicitation or conspiracy to commit in another jurisdiction an offense under the laws of both this State and such other jurisdiction.</p><p class='subsection'>\(b) An offense is committed partly within this State, if either the conduct which is an element of the offense, or the result which is such an element, occurs within the State. In a prosecution pursuant to paragraph (3) of subsection (a) of Section 9-1, the attempt or commission of a forcible felony other than second degree murder within this State is conduct which is an element of the offense for which a person is subject to prosecution in this State. In homicide, the "result" is either the physical contact which causes death, or the death itself; and if the body of a homicide victim is found within the State, the death is presumed to have occurred within the State.</p><p class='subsection'>\(c) An offense which is based on an omission to perform a duty imposed by the law of this State is committed within the State, regardless of the location of the offender at the time of the omission.</p><p>(Source: P.A. 91-357, eff. 7-29-99.)</p>### (720 ILCS 5/1-6) (from Ch. 38, par. 1-6)
## Sec. 1-6. Place of trial.
<p class='subsection'>\(a) Generally.</p><p>Criminal actions shall be tried in the county where the offense was committed, except as otherwise provided by law. The State is not required to prove during trial that the alleged offense occurred in any particular county in this State. When a defendant contests the place of trial under this Section, all proceedings regarding this issue shall be conducted under Section 114-1 of the Code of Criminal Procedure of 1963. All objections of improper place of trial are waived by a defendant unless made before trial.</p><p class='subsection'>\(b) Assailant and Victim in Different Counties.</p><p>If a person committing an offense upon the person of another is located in one county and his victim is located in another county at the time of the commission of the offense, trial may be had in either of said counties.</p><p class='subsection'>\(c) Death and Cause of Death in Different Places or Undetermined.</p><p>If cause of death is inflicted in one county and death ensues in another county, the offender may be tried in either county. If neither the county in which the cause of death was inflicted nor the county in which death ensued are known before trial, the offender may be tried in the county where the body was found.</p><p class='subsection'>\(d) Offense Commenced Outside the State.</p><p>If the commission of an offense commenced outside the State is consummated within this State, the offender shall be tried in the county where the offense is consummated.</p><p class='subsection'>\(e) Offenses Committed in Bordering Navigable Waters.</p><p>If an offense is committed on any of the navigable waters bordering on this State, the offender may be tried in any county adjacent to such navigable water.</p><p class='subsection'>\(f) Offenses Committed while in Transit.</p><p>If an offense is committed upon any railroad car, vehicle, watercraft or aircraft passing within this State, and it cannot readily be determined in which county the offense was committed, the offender may be tried in any county through which such railroad car, vehicle, watercraft or aircraft has passed.</p><p class='subsection'>\(g) Theft.</p><p>A person who commits theft of property may be tried in any county in which he exerted control over such property.</p><p class='subsection'>\(h) Bigamy.</p><p>A person who commits the offense of bigamy may be tried in any county where the bigamous marriage or bigamous cohabitation has occurred.</p><p class='item'>\(i) Kidnaping.</p><p>A person who commits the offense of kidnaping may be tried in any county in which his victim has traveled or has been confined during the course of the offense.</p><p class='subsection'>\(j) Pandering.</p><p>A person who commits the offense of pandering as set forth in subdivision (a)(2)(A) or (a)(2)(B) of Section 11-14.3 may be tried in any county in which the prostitution was practiced or in any county in which any act in furtherance of the offense shall have been committed.</p><p class='subsection'>\(k) Treason.</p><p>A person who commits the offense of treason may be tried in any county.</p><p class='subsection'>\(l) Criminal Defamation.</p><p>If criminal defamation is spoken, printed or written in one county and is received or circulated in another or other counties, the offender shall be tried in the county where the defamation is spoken, printed or written. If the defamation is spoken, printed or written outside this state, or the offender resides outside this state, the offender may be tried in any county in this state in which the defamation was circulated or received.</p><p class='subsection'>\(m) Inchoate Offenses.</p><p>A person who commits an inchoate offense may be tried in any county in which any act which is an element of the offense, including the agreement in conspiracy, is committed.</p><p class='subsection'>\(n) Accountability for Conduct of Another.</p><p>Where a person in one county solicits, aids, abets, agrees, or attempts to aid another in the planning or commission of an offense in another county, he may be tried for the offense in either county.</p><p class='subsection'>\(o) Child Abduction.</p><p>A person who commits the offense of child abduction may be tried in any county in which his victim has traveled, been detained, concealed or removed to during the course of the offense. Notwithstanding the foregoing, unless for good cause shown, the preferred place of trial shall be the county of the residence of the lawful custodian.</p><p class='subsection'>\(p) A person who commits the offense of narcotics racketeering may be tried in any county where cannabis or a controlled substance which is the basis for the charge of narcotics racketeering was used; acquired; transferred or distributed to, from or through; or any county where any act was performed to further the use; acquisition, transfer or distribution of said cannabis or controlled substance; any money, property, property interest, or any other asset generated by narcotics activities was acquired, used, sold, transferred or distributed to, from or through; or, any enterprise interest obtained as a result of narcotics racketeering was acquired, used, transferred or distributed to, from or through, or where any activity was conducted by the enterprise or any conduct to further the interests of such an enterprise.</p><p class='subsection'>\(q) A person who commits the offense of money laundering may be tried in any county where any part of a financial transaction in criminally derived property took place or in any county where any money or monetary instrument which is the basis for the offense was acquired, used, sold, transferred or distributed to, from or through.</p><p class='subsection'>\(r) A person who commits the offense of cannabis trafficking or controlled substance trafficking may be tried in any county.</p><p class='subsection'>\(s) A person who commits the offense of online sale of stolen property, online theft by deception, or electronic fencing may be tried in any county where any one or more elements of the offense took place, regardless of whether the element of the offense was the result of acts by the accused, the victim or by another person, and regardless of whether the defendant was ever physically present within the boundaries of the county.</p><p class='subsection'>\(t) A person who commits the offense of identity theft or aggravated identity theft may be tried in any one of the following counties in which: (1) the offense occurred;  (2) the information used to commit the offense was illegally used;  or (3) the victim resides.</p><p class='subsection'>\(u) A person who commits the offense of financial exploitation of an elderly person or a person with a disability may be tried in any one of the following counties in which: (1) any part of the offense occurred; or (2) the victim or one of the victims reside.</p><p>If a person is charged with more than one violation of identity theft or aggravated identity theft and those violations may be tried in more than one county, any of those counties is a proper venue for all of the violations.</p><p>(Source: P.A. 101-394, eff. 1-1-20 .)</p>### (720 ILCS 5/1-8) (from Ch. 38, par. 1-8)
## Sec. 1-8. Order of protection; status.
<p>Whenever relief sought under this Code is based on allegations of domestic violence, as defined in the Illinois Domestic Violence Act of 1986, the court, before granting relief, shall determine whether any order of protection has previously been entered in the instant proceeding or any other proceeding in which any party, or a child of any party, or both, if relevant, has been designated as either a respondent or a protected person.</p><p>(Source: P.A. 87-743.)</p>