# Article 21.1. Residential Picketing {.unnumbered}

### (720 ILCS 5/21.1-1) (from Ch. 38, par. 21.1-1)
## Sec. 21.1-1. Legislative finding and declaration.
<p>The Legislature finds and declares that men in a free society have the right to quiet enjoyment of their homes; that the stability of community and family life cannot be maintained unless the right to privacy and a sense of security and peace in the home are respected and encouraged; that residential picketing, however just the cause inspiring it, disrupts home, family and communal life; that residential picketing is inappropriate in our society, where the jealously guarded rights of free speech and assembly have always been associated with respect for the rights of others. For these reasons the Legislature finds and declares this Article to be necessary.</p><p>(Source: Laws 1967, p. 940.)</p>### (720 ILCS 5/21.1-2) (from Ch. 38, par. 21.1-2)
## Sec. 21.1-2. Residential picketing.
<p>A person commits residential picketing when he or she pickets before or about the residence or dwelling of any person, except when the residence or dwelling is used as a place of business. This Article does not apply to a person peacefully picketing his own residence or dwelling and does not prohibit the peaceful picketing of the place of holding a meeting or assembly on premises commonly used to discuss subjects of general public interest.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/21.1-3) (from Ch. 38, par. 21.1-3)
## Sec. 21.1-3. Sentence.
<p>Violation of Section 21.1-2 is a Class B misdemeanor.</p><p>(Source: P.A. 77-2638.)</p>