# Article 34. Construction And Effective Date {.unnumbered}

### (720 ILCS 5/34-1) (from Ch. 38, par. 34-1)
## Sec. 34-1. Effect of headings.
<p>Section, Article, and Title headings contained herein shall not be deemed to govern, limit, modify or in any manner affect the scope, meaning, or intent of the provisions of any Section, Article, or Title hereof.</p><p>(Source: P.A. 91-357, eff. 7-29-99.)</p>### (720 ILCS 5/34-2) (from Ch. 38, par. 34-2)
## Sec. 34-2. Partial invalidity.
<p>The invalidity of any provision of this Code shall not affect the validity of the remainder of this Code.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/34-3) (from Ch. 38, par. 34-3)
## Sec. 34-3. Savings provisions; continuation of prior Statutes.
<p>The provisions of Sections 2, 3 and 4 of "An Act to revise the law in relation to the construction of the Statutes", approved March 5, 1874, as amended, shall apply in all constructions of this Code.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/34-4) (from Ch. 38, par. 34-4)
## Sec. 34-4. Effective date.
<p>This Code shall take effect January 1, 1962.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/Tit. V heading)
<p>TITLE V.</p><p>ADDED ARTICLES</p>