# Article 20. Arson {.unnumbered}

### (720 ILCS 5/20-1) (from Ch. 38, par. 20-1)
## Sec. 20-1. Arson; residential arson; place of worship arson.
<p class='subsection'>\(a) A person commits arson when, by means of fire or explosive, he or she knowingly:</p><p class='paragraph'>\(1) Damages any real property, or any personal property having a value of $150 or more, of another without his or her consent; or</p><p class='paragraph'>\(2) With intent to defraud an insurer, damages any property or any personal property having a value of $150 or more.</p><p>Property "of another" means a building or other property, whether real or personal, in which a person other than the offender has an interest which the offender has no authority to defeat or impair, even though the offender may also have an interest in the building or property.</p><p class='subsection'>\(b) A person commits residential arson when he or she, in the course of committing arson, knowingly damages, partially or totally, any building or structure that is the dwelling place of another.</p><p class='subsection'>\(b-5) A person commits place of worship arson when he or she, in the course of committing arson, knowingly damages, partially or totally, any place of worship.</p><p class='subsection'>\(c) Sentence.</p><p>Arson is a Class 2 felony. Residential arson or place of worship arson is a Class 1 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/20-1.1) (from Ch. 38, par. 20-1.1)
## Sec. 20-1.1. Aggravated Arson.
<p class='subsection'>\(a) A person commits aggravated arson when in the course of committing arson he or she knowingly damages, partially or totally, any building or structure, including any adjacent building or structure, including all or any part of a school building, house trailer, watercraft, motor vehicle, or railroad car, and (1) he knows or reasonably should know that one or more persons are present therein or (2) any person suffers great bodily harm, or permanent disability or disfigurement as a result of the fire or explosion or (3) a fireman,  policeman, or correctional officer who is present at the scene acting in the line of duty is injured as a result of the fire or explosion. For purposes of this Section, property "of another" means a building or other property, whether real or personal, in which a person other than the offender has an interest that the offender has no authority to defeat or impair, even though the offender may also have an interest in the building or property; and "school building" means any public or private preschool, elementary or secondary school, community college, college, or university.</p><p class='subsection'>\(b) Sentence. Aggravated arson is a Class X felony.</p><p>(Source: P.A. 93-335, eff. 7-24-03; 94-127, eff. 7-7-05; 94-393, eff. 8-1-05.)</p><p>  </p>### (720 ILCS 5/20-1.2)
## Sec. 20-1.2. (Repealed).
<p>(Source: P.A. 90-787, eff. 8-14-98. Repealed by P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/20-1.3)
## Sec. 20-1.3. (Repealed).
<p>(Source: P.A. 93-169, eff. 7-10-03. Repealed by P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/20-1.4)
## Sec. 20-1.4. (Repealed).
<p>(Source: P.A. 93-969, eff. 1-1-05. Repealed by P.A. 94-556, eff. 9-11-2005 .)</p>### (720 ILCS 5/20-1.5)
## Sec. 20-1.5. (Repealed).
<p>(Source: P.A. 93-969, eff. 1-1-05. Repealed by P.A. 94-556, eff. 9-11-2005.)</p>### (720 ILCS 5/20-2) (from Ch. 38, par. 20-2)
## Sec. 20-2. Possession of explosives or explosive or incendiary devices.
<p class='subsection'>\(a) A person commits possession of explosives or explosive or incendiary devices in violation of this Section when he or she possesses, manufactures or transports any explosive compound, timing or detonating device for use with any explosive compound or incendiary device and either intends to use the explosive or device to commit any offense or knows that another intends to use the explosive or device to commit a felony.</p><p class='subsection'>\(b) Sentence.</p><p>Possession of explosives or explosive or incendiary devices is a Class 1 felony for which a person, if sentenced to a term of imprisonment, shall be sentenced to not less than 4 years and not more than 30 years.</p><p class='subsection'>\(c) (Blank).</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>