# Article 3. Rights Of Defendant {.unnumbered}

### (720 ILCS 5/3-1) (from Ch. 38, par. 3-1)
## Sec. 3-1. Presumption of innocence and proof of guilt.
<p>Every person is presumed innocent until proved guilty. No person shall be convicted of any offense unless his guilt thereof is proved beyond a reasonable doubt.</p><p>(Source: Laws 1961, p. 1983 .)</p>### (720 ILCS 5/3-2) (from Ch. 38, par. 3-2)
## Sec. 3-2. Affirmative defense.
<p class='subsection'>\(a) "Affirmative defense" means that unless the State's evidence raises the issue involving the alleged defense, the defendant, to raise the issue, must present some evidence thereon.</p><p class='subsection'>\(b) If the issue involved in an affirmative defense, other than insanity, is raised then the State must sustain the burden of proving the defendant guilty beyond a reasonable doubt as to that issue together with all the other elements of the offense. If the affirmative defense of insanity is raised, the defendant bears the burden of proving by clear and convincing evidence his insanity at the time of the offense.</p><p>(Source: P.A. 89-404, eff. 8-20-95; 90-593, eff. 6-19-98.)</p>### (720 ILCS 5/3-3) (from Ch. 38, par. 3-3)
## Sec. 3-3. Multiple prosecutions for same act.
<p class='subsection'>\(a) When the same conduct of a defendant may establish the commission of more than one offense, the defendant may be prosecuted for each such offense.</p><p class='subsection'>\(b) If the several offenses are known to the proper prosecuting officer at the time of commencing the prosecution and are within the jurisdiction of a single court, they must be prosecuted in a single prosecution, except as provided in Subsection (c), if they are based on the same act.</p><p class='subsection'>\(c) When 2 or more offenses are charged as required by Subsection (b), the court in the interest of justice may order that one or more of such charges shall be tried separately.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/3-4) (from Ch. 38, par. 3-4)
## Sec. 3-4. Effect of former prosecution.
<p class='subsection'>\(a) A prosecution is barred if the defendant was formerly prosecuted for the same offense, based upon the same facts, if that former prosecution:</p><p class='paragraph'>\(1) resulted in either a conviction or an acquittal or in a determination that the evidence was insufficient to warrant a conviction;</p><p class='paragraph'>\(2) was terminated by a final order or judgment, even if entered before trial, that required a determination inconsistent with any fact or legal proposition necessary to a conviction in the subsequent prosecution; or</p><p class='paragraph'>\(3) was terminated improperly after the jury was impaneled and sworn or, in a trial before a court without a jury, after the first witness was sworn but before findings were rendered by the trier of facts, or after a plea of guilty was accepted by the court.</p><p>A conviction of an included offense, other than through a plea of guilty, is an acquittal of the offense charged.</p><p class='subsection'>\(b) A prosecution is barred if the defendant was formerly prosecuted for a different offense, or for the same offense based upon different facts, if that former prosecution:</p><p class='paragraph'>\(1) resulted in either a conviction or an acquittal, and the subsequent prosecution is for an offense of which the defendant could have been convicted on the former prosecution; or was for an offense with which the defendant should have been charged on the former prosecution, as provided in Section 3-3 of this Code (unless the court ordered a separate trial of that charge); or was for an offense that involves the same conduct, unless each prosecution requires proof of a fact not required on the other prosecution, or the offense was not consummated when the former trial began;</p><p class='paragraph'>\(2) was terminated by a final order or judgment, even if entered before trial, that required a determination inconsistent with any fact necessary to a conviction in the subsequent prosecution; or</p><p class='paragraph'>\(3) was terminated improperly under the circumstances stated in subsection (a), and the subsequent prosecution is for an offense of which the defendant could have been convicted if the former prosecution had not been terminated improperly.</p><p class='subsection'>\(c) A prosecution is barred if the defendant was formerly prosecuted in a District Court of the United States or in a sister state for an offense that is within the concurrent jurisdiction of this State, if that former prosecution:</p><p class='paragraph'>\(1) resulted in either a conviction or an acquittal, and the subsequent prosecution is for the same conduct, unless each prosecution requires proof of a fact not required in the other prosecution, or the offense was not consummated when the former trial began; or</p><p class='paragraph'>\(2) was terminated by a final order or judgment, even if entered before trial, that required a determination inconsistent with any fact necessary to a conviction in the prosecution in this State.</p><p class='subsection'>\(d) A prosecution is not barred within the meaning of this Section 3-4, however, if the former prosecution:</p><p class='paragraph'>\(1) was before a court that lacked jurisdiction over the defendant or the offense; or</p><p class='paragraph'>\(2) was procured by the defendant without the knowledge of the proper prosecuting officer, and with the purpose of avoiding the sentence that otherwise might be imposed; or if subsequent proceedings resulted in the invalidation, setting aside, reversal, or vacating of the conviction, unless the defendant was thereby adjudged not guilty.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/3-5) (from Ch. 38, par. 3-5)
<p>(Text of Section before amendment by P.A. 102-982</p><p>)</p>## Sec. 3-5. General limitations.
<p class='subsection'>\(a) A prosecution for: (1) first degree murder, attempt to commit first degree murder, second degree murder, involuntary manslaughter, reckless homicide, a violation of subparagraph (F) of paragraph (1) of subsection (d) of Section 11-501 of the Illinois Vehicle Code for the offense of aggravated driving under the influence of alcohol, other drug or drugs, or intoxicating compound or compounds, or any combination thereof when the violation was a proximate cause of a death, leaving the scene of a motor vehicle accident involving death or personal injuries under Section 11-401 of the Illinois Vehicle Code, failing to give information and render aid under Section 11-403 of the Illinois Vehicle Code, concealment of homicidal death, treason, arson, residential arson, aggravated arson, forgery, child pornography under paragraph (1) of subsection (a) of Section 11-20.1, or aggravated child pornography under paragraph (1) of subsection (a) of Section 11-20.1B, or (2) any offense involving sexual conduct or sexual penetration, as defined by Section 11-0.1 of this Code may be commenced at any time.</p><p class='subsection'>\(a-5) A prosecution for theft of property exceeding $100,000 in value under Section 16-1, identity theft under subsection (a) of Section 16-30, aggravated identity theft under subsection (b) of Section 16-30, financial exploitation of an elderly person or a person with a disability under Section 17-56; theft by deception of a victim 60 years of age or older or a person with a disability under Section 16-1; or any offense set forth in Article 16H or Section 17-10.6 may be commenced within 7 years of the last act committed in furtherance of the crime.</p><p class='subsection'>\(b) Unless the statute describing the offense provides otherwise, or the period of limitation is extended by Section 3-6, a prosecution for any offense not designated in subsection (a) or (a-5) must be commenced within 3 years after the commission of the offense if it is a felony, or within one year and 6 months after its commission if it is a misdemeanor.</p><p>(Source: P.A. 101-130, eff. 1-1-20; 102-244, eff. 1-1-22 .)</p><p>(Text of Section after amendment by P.A. 102-982</p><p>)</p>## Sec. 3-5. General limitations.
<p class='subsection'>\(a) A prosecution for: (1) first degree murder, attempt to commit first degree murder, second degree murder, involuntary manslaughter, reckless homicide, a violation of subparagraph (F) of paragraph (1) of subsection (d) of Section 11-501 of the Illinois Vehicle Code for the offense of aggravated driving under the influence of alcohol, other drug or drugs, or intoxicating compound or compounds, or any combination thereof when the violation was a proximate cause of a death, leaving the scene of a motor vehicle crash involving death or personal injuries under Section 11-401 of the Illinois Vehicle Code, failing to give information and render aid under Section 11-403 of the Illinois Vehicle Code, concealment of homicidal death, treason, arson, residential arson, aggravated arson, forgery, child pornography under paragraph (1) of subsection (a) of Section 11-20.1, or aggravated child pornography under paragraph (1) of subsection (a) of Section 11-20.1B, or (2) any offense involving sexual conduct or sexual penetration, as defined by Section 11-0.1 of this Code may be commenced at any time.</p><p class='subsection'>\(a-5) A prosecution for theft of property exceeding $100,000 in value under Section 16-1, identity theft under subsection (a) of Section 16-30, aggravated identity theft under subsection (b) of Section 16-30, financial exploitation of an elderly person or a person with a disability under Section 17-56; theft by deception of a victim 60 years of age or older or a person with a disability under Section 16-1; or any offense set forth in Article 16H or Section 17-10.6 may be commenced within 7 years of the last act committed in furtherance of the crime.</p><p class='subsection'>\(b) Unless the statute describing the offense provides otherwise, or the period of limitation is extended by Section 3-6, a prosecution for any offense not designated in subsection (a) or (a-5) must be commenced within 3 years after the commission of the offense if it is a felony, or within one year and 6 months after its commission if it is a misdemeanor.</p><p>(Source: P.A. 101-130, eff. 1-1-20; 102-244, eff. 1-1-22; 102-982, eff. 7-1-23.)</p>### (720 ILCS 5/3-6) (from Ch. 38, par. 3-6)
## Sec. 3-6. Extended limitations.
<p>The period within which a prosecution must be commenced under the provisions of Section 3-5 or other applicable statute is extended under the following conditions:</p><p class='subsection'>\(a) A prosecution for theft involving a breach of a fiduciary obligation to the aggrieved person may be commenced as follows:</p><p class='paragraph'>\(1) If the aggrieved person is a minor or a person under legal disability, then during the minority or legal disability or within one year after the termination thereof.</p><p class='paragraph'>\(2) In any other instance, within one year after the discovery of the offense by an aggrieved person, or by a person who has legal capacity to represent an aggrieved person or has a legal duty to report the offense, and is not himself or herself a party to the offense; or in the absence of such discovery, within one year after the proper prosecuting officer becomes aware of the offense. However, in no such case is the period of limitation so extended more than 3 years beyond the expiration of the period otherwise applicable.</p><p class='subsection'>\(b) A prosecution for any offense based upon misconduct in office by a public officer or employee may be commenced within one year after discovery of the offense by a person having a legal duty to report such offense, or in the absence of such discovery, within one year after the proper prosecuting officer becomes aware of the offense. However, in no such case is the period of limitation so extended more than 3 years beyond the expiration of the period otherwise applicable.</p><p class='subsection'>\(b-5) When the victim is under 18 years of age at the time of the offense, a prosecution for involuntary servitude, involuntary sexual servitude of a minor, or trafficking in persons and related offenses under Section 10-9 of this Code may be commenced within 25 years of the victim attaining the age of 18 years.</p><p class='subsection'>\(b-6) When the victim is 18 years of age or over at the time of the offense, a prosecution for involuntary servitude, involuntary sexual servitude of a minor, or trafficking in persons and related offenses under Section 10-9 of this Code may be commenced within 25 years after the commission of the offense.</p><p class='subsection'>\(b-7) When the victim is under 18 years of age at the time of the offense, a prosecution for female genital mutilation may be commenced at any time.</p><p class='subsection'>\(c) (Blank).</p><p class='subsection'>\(d) A prosecution for child pornography, aggravated child pornography, indecent solicitation of a child, soliciting for a juvenile prostitute, juvenile pimping, exploitation of a child, or promoting juvenile prostitution except for keeping a place of juvenile prostitution may be commenced within one year of the victim attaining the age of 18 years. However, in no such case shall the time period for prosecution expire sooner than 3 years after the commission of the offense.</p><p class='subsection'>\(e) Except as otherwise provided in subdivision (j), a prosecution for any offense involving sexual conduct or sexual penetration, as defined in Section 11-0.1 of this Code, where the defendant was within a professional or fiduciary relationship or a purported professional or fiduciary relationship with the victim at the time of the commission of the offense may be commenced within one year after the discovery of the offense by the victim.</p><p class='subsection'>\(f) A prosecution for any offense set forth in Section 44 of the Environmental Protection Act may be commenced within 5 years after the discovery of such an offense by a person or agency having the legal duty to report the offense or in the absence of such discovery, within 5 years after the proper prosecuting officer becomes aware of the offense.</p><p class='subsection'>\(f-5) A prosecution for any offense set forth in Section 16-30 of this Code may be commenced within 5 years after the discovery of the offense by the victim of that offense.</p><p class='subsection'>\(g) (Blank).</p><p class='subsection'>\(h) (Blank).</p><p class='item'>\(i) Except as otherwise provided in subdivision (j), a prosecution for criminal sexual assault, aggravated criminal sexual assault, or aggravated criminal sexual abuse may be commenced at any time. If the victim consented to the collection of evidence using an Illinois State Police Sexual Assault Evidence Collection Kit under the Sexual Assault Survivors Emergency Treatment Act, it shall constitute reporting for purposes of this Section.</p><p>Nothing in this subdivision (i) shall be construed to shorten a period within which a prosecution must be commenced under any other provision of this Section.</p><p class='item'>\(i-5) A prosecution for armed robbery, home invasion, kidnapping, or aggravated kidnaping may be commenced within 10 years of the commission of the offense if it arises out of the same course of conduct and meets the criteria under one of the offenses in subsection (i) of this Section.</p><p class='subsection'>\(j) (1) When the victim is under 18 years of age at the time of the offense, a prosecution for criminal sexual assault, aggravated criminal sexual assault, predatory criminal sexual assault of a child, aggravated criminal sexual abuse, felony criminal sexual abuse, or female genital mutilation may be commenced at any time.</p><p class='paragraph'>\(2) When in circumstances other than as described in paragraph (1) of this subsection (j), when the victim is under 18 years of age at the time of the offense, a prosecution for failure of a person who is required to report an alleged or suspected commission of criminal sexual assault, aggravated criminal sexual assault, predatory criminal sexual assault of a child, aggravated criminal sexual abuse, or felony criminal sexual abuse under the Abused and Neglected Child Reporting Act may be commenced within 20 years after the child victim attains 18 years of age.</p><p class='paragraph'>\(3) When the victim is under 18 years of age at the time of the offense, a prosecution for misdemeanor criminal sexual abuse may be commenced within 10 years after the child victim attains 18 years of age.</p><p class='paragraph'>\(4) Nothing in this subdivision (j) shall be construed to shorten a period within which a prosecution must be commenced under any other provision of this Section.</p><p class='subsection'>\(j-5) A prosecution for armed robbery, home invasion, kidnapping, or aggravated kidnaping may be commenced at any time if it arises out of the same course of conduct and meets the criteria under one of the offenses in subsection (j) of this Section.</p><p class='subsection'>\(k) (Blank).</p><p class='subsection'>\(l) A prosecution for any offense set forth in Section 26-4 of this Code may be commenced within one year after the discovery of the offense by the victim of that offense.</p><p class='subsection'>\(l-5) A prosecution for any offense involving sexual conduct or sexual penetration, as defined in Section 11-0.1 of this Code, in which the victim was 18 years of age or older at the time of the offense, may be commenced within one year after the discovery of the offense by the victim when corroborating physical evidence is available. The charging document shall state that the statute of limitations is extended under this subsection (l-5) and shall state the circumstances justifying the extension. Nothing in this subsection (l-5) shall be construed to shorten a period within which a prosecution must be commenced under any other provision of this Section or Section 3-5 of this Code.</p><p class='subsection'>\(m) The prosecution shall not be required to prove at trial facts which extend the general limitations in Section 3-5 of this Code when the facts supporting extension of the period of general limitations are properly pled in the charging document. Any challenge relating to the extension of the general limitations period as defined in this Section shall be exclusively conducted under Section 114-1 of the Code of Criminal Procedure of 1963.</p><p class='subsection'>\(n) A prosecution for any offense set forth in subsection (a), (b), or (c) of Section 8A-3 or Section 8A-13 of the Illinois Public Aid Code, in which the total amount of money involved is $5,000 or more, including the monetary value of food stamps and the value of commodities under Section 16-1 of this Code may be commenced within 5 years of the last act committed in furtherance of the offense.</p><p>(Source: P.A. 101-18, eff. 1-1-20; 101-81, eff. 7-12-19; 101-130, eff. 1-1-20; 101-285, eff. 1-1-20; 102-558, eff. 8-20-21.)</p>### (720 ILCS 5/3-7) (from Ch. 38, par. 3-7)
## Sec. 3-7. Periods excluded from limitation.
<p class='subsection'>\(a) The period within which a prosecution must be commenced does not include any period in which:</p><p class='paragraph'>\(1) the defendant is not usually and publicly resident within this State; or</p><p class='paragraph'>\(2) the defendant is a public officer and the offense charged is theft of public funds while in public office; or</p><p class='paragraph'>\(3) a prosecution is pending against the defendant for the same conduct, even if the indictment or information which commences the prosecution is quashed or the proceedings thereon are set aside, or are reversed on appeal; or</p><p class='paragraph'>\(4) a proceeding or an appeal from a proceeding relating to the quashing or enforcement of a Grand Jury subpoena issued in connection with an investigation of a violation of a criminal law of this State is pending. However, the period within which a prosecution must be commenced includes any period in which the State brings a proceeding or an appeal from a proceeding specified in this paragraph (4); or</p><p class='paragraph'>\(5) a material witness is placed on active military duty or leave. In this paragraph (5), "material witness" includes, but is not limited to, the arresting officer, occurrence witness, or the alleged victim of the offense; or</p><p class='paragraph'>\(6) the victim of unlawful force or threat of imminent bodily harm to obtain information or a confession is incarcerated, and the victim's incarceration, in whole or in part, is a consequence of the unlawful force or threats; or</p><p class='paragraph'>\(7) the sexual assault evidence is collected and submitted to the Illinois State Police until the completion of the analysis of the submitted evidence.</p><p class='subsection'>\(a-5) The prosecution shall not be required to prove at trial facts establishing periods excluded from the general limitations in Section 3-5 of this Code when the facts supporting periods being excluded from the general limitations are properly pled in the charging document. Any challenge relating to periods of exclusion as defined in this Section shall be exclusively conducted under Section 114-1 of the Code of Criminal Procedure of 1963.</p><p class='subsection'>\(b) For the purposes of this Section:</p><p>"Completion of the analysis of the submitted evidence" means analysis of the collected evidence and conducting of laboratory tests and the comparison of the collected evidence with the genetic marker grouping analysis information maintained by the Illinois State Police under Section 5-4-3 of the Unified Code of Corrections and with the information contained in the Federal Bureau of Investigation's National DNA database.</p><p>"Sexual assault" has the meaning ascribed to it in</p><p>Section 1a of the Sexual Assault Survivors Emergency Treatment Act.</p><p>"Sexual assault evidence" has the meaning ascribed to it in Section 5 of the Sexual Assault Evidence Submission Act.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/3-8) (from Ch. 38, par. 3-8)
## Sec. 3-8. Limitation on offense based on series of acts.
<p>When an offense is based on a series of acts performed at different times, the period of limitation prescribed by this Article starts at the time when the last such act is committed.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/Tit. II heading)
<p>TITLE II.</p><p>PRINCIPLES OF CRIMINAL LIABILITY</p>