# Article 5. Parties To Crime {.unnumbered}

### (720 ILCS 5/5-1) (from Ch. 38, par. 5-1)
## Sec. 5-1. Accountability for conduct of another.
<p>A person is responsible for conduct which is an element of an offense if the conduct is either that of the person himself, or that of another and he is legally accountable for such conduct as provided in Section 5-2, or both.</p><p>(Source: Laws 1961, p. 1983 .)</p>### (720 ILCS 5/5-2) (from Ch. 38, par. 5-2)
## Sec. 5-2. When accountability exists.
<p>A person is legally accountable for the conduct of another when:</p><p class='subsection'>\(a) having a mental state described by the statute defining the offense, he or she causes another to perform the conduct, and the other person in fact or by reason of legal incapacity lacks such a mental state;</p><p class='subsection'>\(b) the statute defining the offense makes him or her so accountable; or</p><p class='subsection'>\(c) either before or during the commission of an offense, and with the intent to promote or facilitate that commission, he or she solicits, aids, abets, agrees, or attempts to aid that other person in the planning or commission of the offense.</p><p>When 2 or more persons engage in a common criminal design or agreement, any acts in the furtherance of that common design committed by one party are considered to be the acts of all parties to the common design or agreement and all are equally responsible for the consequences of those further acts. Mere presence at the scene of a crime does not render a person accountable for an offense; a person's presence at the scene of a crime, however, may be considered with other circumstances by the trier of fact when determining accountability.</p><p>A person is not so accountable, however, unless the statute defining the offense provides otherwise, if:</p><p class='paragraph'>\(1) he or she is a victim of the offense committed;</p><p class='paragraph'>\(2) the offense is so defined that his or her conduct was inevitably incident to its commission; or</p><p class='paragraph'>\(3) before the commission of the offense, he or she terminates his or her effort to promote or facilitate that commission and does one of the following: (i) wholly deprives his or her prior efforts of effectiveness in that commission, (ii) gives timely warning to the proper law enforcement authorities, or (iii) otherwise makes proper effort to prevent the commission of the offense.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/5-3) (from Ch. 38, par. 5-3)
## Sec. 5-3. Separate conviction of person accountable.
<p>A person who is legally accountable for the conduct of another which is an element of an offense may be convicted upon proof that the offense was committed and that he was so accountable, although the other person claimed to have committed the offense has not been prosecuted or convicted, or has been convicted of a different offense or degree of offense, or is not amenable to justice, or has been acquitted.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/5-4) (from Ch. 38, par. 5-4)
## Sec. 5-4. Responsibility of corporation.
<p class='subsection'>\(a) A corporation may be prosecuted for the commission of an offense if, but only if:</p><p class='paragraph'>\(1) The offense is a misdemeanor, or is defined by Sections 11-20, 11-20.1 or 24-1 of this Code, or Section 44 of the "Environmental Protection Act", approved June 29, 1970, as amended or is defined by another statute which clearly indicates a legislative purpose to impose liability on a corporation; and an agent of the corporation performs the conduct which is an element of the offense while acting within the scope of his or her office or employment and in behalf of the corporation, except that any limitation in the defining statute, concerning the corporation's accountability for certain agents or under certain circumstances, is applicable; or</p><p class='paragraph'>\(2) The commission of the offense is authorized, requested, commanded, or performed, by the board of directors or by a high managerial agent who is acting within the scope of his or her employment in behalf of the corporation.</p><p class='subsection'>\(b) A corporation's proof, by a preponderance of the evidence, that the high managerial agent having supervisory responsibility over the conduct which is the subject matter of the offense exercised due diligence to prevent the commission of the offense, is a defense to a prosecution for any offense to which Subsection (a) (1) refers, other than an offense for which absolute liability is imposed. This Subsection is inapplicable if the legislative purpose of the statute defining the offense is inconsistent with the provisions of this Subsection.</p><p class='subsection'>\(c) For the purpose of this Section:</p><p class='paragraph'>\(1) "Agent" means any director, officer, servant, employee, or other person who is authorized to act in behalf of the corporation.</p><p class='paragraph'>\(2) "High managerial agent" means an officer of the corporation, or any other agent who has a position of comparable authority for the formulation of corporate policy or the supervision of subordinate employees in a managerial capacity.</p><p>(Source: P.A. 85-1440.)</p>### (720 ILCS 5/5-5) (from Ch. 38, par. 5-5)
## Sec. 5-5. Accountability for conduct of corporation.
<p class='subsection'>\(a) A person is legally accountable for conduct which is an element of an offense and which, in the name or in behalf of a corporation, he performs or causes to be performed, to the same extent as if the conduct were performed in his own name or behalf.</p><p class='subsection'>\(b) An individual who has been convicted of an offense by reason of his legal accountability for the conduct of a corporation is subject to the punishment authorized by law for an individual upon conviction of such offense, although only a lesser or different punishment is authorized for the corporation.</p><p>(Source: Laws 1961, p. 1983.)</p>