# Article 29b. Money Laundering {.unnumbered}

### (720 ILCS 5/29B-0.5)
## Sec. 29B-0.5. Definitions.
<p>In this Article:</p><p>"Conduct" or "conducts" includes, in addition to its ordinary meaning, initiating, concluding, or participating in initiating or concluding a transaction.</p><p>"Criminally derived property" means: (1) any property, real or personal, constituting or derived from proceeds obtained, directly or indirectly, from activity that constitutes a felony under State, federal, or foreign law; or (2) any property represented to be property constituting or derived from proceeds obtained, directly or indirectly, from activity that constitutes a felony under State, federal, or foreign law.</p><p>"Director" means the Director of the Illinois State Police or his or her designated agents.</p><p>"Financial institution" means any bank; savings and loan association; trust company; agency or branch of a foreign bank in the United States; currency exchange; credit union; mortgage banking institution; pawnbroker; loan or finance company; operator of a credit card system; issuer, redeemer, or cashier of travelers checks, checks, or money orders; dealer in precious metals, stones, or jewels; broker or dealer in securities or commodities; investment banker; or investment company.</p><p>"Financial transaction" means a purchase, sale, loan, pledge, gift, transfer, delivery, or other disposition utilizing criminally derived property, and with respect to financial institutions, includes a deposit, withdrawal, transfer between accounts, exchange of currency, loan, extension of credit, purchase or sale of any stock, bond, certificate of deposit or other monetary instrument, use of safe deposit box, or any other payment, transfer or delivery by, through, or to a financial institution. "Financial transaction" also means a transaction which without regard to whether the funds, monetary instruments, or real or personal property involved in the transaction are criminally derived, any transaction which in any way or degree: (1) involves the movement of funds by wire or any other means; (2) involves one or more monetary instruments; or (3) the transfer of title to any real or personal property. The receipt by an attorney of bona fide fees for the purpose of legal representation is not a financial transaction for purposes of this Article.</p><p>"Form 4-64" means the Illinois State Police Notice/Inventory of Seized Property (Form 4-64).</p><p>"Knowing that the property involved in a financial transaction represents the proceeds of some form of unlawful activity" means that the person knew the property involved in the transaction represented proceeds from some form, though not necessarily which form, of activity that constitutes a felony under State, federal, or foreign law.</p><p>"Monetary instrument" means United States coins and currency; coins and currency of a foreign country; travelers checks; personal checks, bank checks, and money orders; investment securities; bearer negotiable instruments; bearer investment securities; or bearer securities and certificates of stock in a form that title passes upon delivery.</p><p>"Specified criminal activity" means any violation of Section 29D-15.1 and any violation of Article 29D of this Code.</p><p>"Transaction reporting requirement under State law" means any violation as defined under the Currency Reporting Act.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/29B-1) (from Ch. 38, par. 29B-1)
## Sec. 29B-1. Money laundering.
<p class='subsection'>\(a) A person commits the offense of money laundering:</p><p class='paragraph'>\(1) when, knowing that the property involved in a financial transaction represents the proceeds of some form of unlawful activity, he or she conducts or attempts to conduct the financial transaction which in fact involves criminally derived property:</p><p class='subparagraph'>\(A) with the intent to promote the carrying on of the unlawful activity from which the criminally derived property was obtained; or</p><p class='subparagraph'>\(B) where he or she knows or reasonably should know that the financial transaction is designed in whole or in part:</p><p class='item'>\(i) to conceal or disguise the nature, the location, the source, the ownership or the control of the criminally derived property; or</p><p class='item'>\(ii) to avoid a transaction reporting requirement under State law; or</p><p class='paragraph'>\(1.5) when he or she transports, transmits, or transfers, or attempts to transport, transmit, or transfer a monetary instrument:</p><p class='subparagraph'>\(A) with the intent to promote the carrying on of the unlawful activity from which the criminally derived property was obtained; or</p><p class='subparagraph'>\(B) knowing, or having reason to know, that the financial transaction is designed in whole or in part:</p><p class='item'>\(i) to conceal or disguise the nature, the location, the source, the ownership or the control of the criminally derived property; or</p><p class='item'>\(ii) to avoid a transaction reporting requirement under State law; or</p><p class='paragraph'>\(2) when, with the intent to:</p><p class='subparagraph'>\(A) promote the carrying on of a specified criminal activity as defined in this Article; or</p><p class='subparagraph'>\(B) conceal or disguise the nature, location, source, ownership, or control of property believed to be the proceeds of a specified criminal activity as defined in this Article; or</p><p>he or she conducts or attempts to conduct a financial transaction involving property he or she believes to be the proceeds of specified criminal activity or property used to conduct or facilitate specified criminal activity as defined in this Article.</p><p class='subsection'>\(b) (Blank).</p><p>      </p><p class='subsection'>\(c) Sentence.</p><p class='paragraph'>\(1) Laundering of criminally derived property of a value not exceeding $10,000 is a Class 3 felony;</p><p class='paragraph'>\(2) Laundering of criminally derived property of a value exceeding $10,000 but not exceeding $100,000 is a Class 2 felony;</p><p class='paragraph'>\(3) Laundering of criminally derived property of a value exceeding $100,000 but not exceeding $500,000 is a Class 1 felony;</p><p class='paragraph'>\(4) Money laundering in violation of subsection</p><p class='subsection'>\(a)(2) of this Section is a Class X felony;</p><p class='paragraph'>\(5) Laundering of criminally derived property of a value exceeding $500,000 is a Class 1 non-probationable felony;</p><p class='paragraph'>\(6) In a prosecution under clause (a)(1.5)(B)(ii) of this Section, the sentences are as follows:</p><p class='subparagraph'>\(A) Laundering of property of a value not exceeding $10,000 is a Class 3 felony;</p><p class='subparagraph'>\(B) Laundering of property of a value exceeding</p><p>$10,000 but not exceeding $100,000 is a Class 2 felony;</p><p class='subparagraph'>\(C) Laundering of property of a value exceeding</p><p>$100,000 but not exceeding $500,000 is a Class 1 felony;</p><p class='subparagraph'>\(D) Laundering of property of a value exceeding</p><p>$500,000 is a Class 1 non-probationable felony.</p><p>(Source: P.A. 99-480, eff. 9-9-15; 100-512, eff. 7-1-18; 100-699, eff. 8-3-18; 100-759, eff. 1-1-19; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-2)
## Sec. 29B-2. Evidence in money laundering prosecutions.
<p>In a prosecution under this Article, either party may introduce the following evidence pertaining to the issue of whether the property or proceeds were known to be some form of criminally derived property or from some form of unlawful activity:</p><p class='paragraph'>\(1) a financial transaction was conducted or structured or attempted in violation of the reporting requirements of any State or federal law;</p><p class='paragraph'>\(2) a financial transaction was conducted or attempted with the use of a false or fictitious name or a forged instrument;</p><p class='paragraph'>\(3) a falsely altered or completed written instrument or a written instrument that contains any materially false personal identifying information was made, used, offered, or presented, whether accepted or not, in connection with a financial transaction;</p><p class='paragraph'>\(4) a financial transaction was structured or attempted to be structured so as to falsely report the actual consideration or value of the transaction;</p><p class='paragraph'>\(5) a money transmitter, a person engaged in a trade or business, or any employee of a money transmitter or a person engaged in a trade or business, knows or reasonably should know that false personal identifying information has been presented and incorporates the false personal identifying information into any report or record;</p><p class='paragraph'>\(6) the criminally derived property is transported or possessed in a fashion inconsistent with the ordinary or usual means of transportation or possession of the property and where the property is discovered in the absence of any documentation or other indicia of legitimate origin or right to the property;</p><p class='paragraph'>\(7) a person pays or receives substantially less than face value for one or more monetary instruments; or</p><p class='paragraph'>\(8) a person engages in a transaction involving one or more monetary instruments, where the physical condition or form of the monetary instrument or instruments makes it apparent that they are not the product of bona fide business or financial transactions.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-3)
## Sec. 29B-3. Duty to enforce this Article.
<p class='subsection'>\(a) It is the duty of the Illinois State Police, and its agents, officers, and investigators, to enforce this Article, except those provisions otherwise specifically delegated, and to cooperate with all agencies charged with the enforcement of the laws of the United States, or of any state, relating to money laundering. Only an agent, officer, or investigator designated by the Director may be authorized in accordance with this Section to serve seizure notices, warrants, subpoenas, and summonses under the authority of this State.</p><p class='subsection'>\(b) An agent, officer, investigator, or peace officer designated by the Director may: (1) make seizure of property under this Article; and (2) perform other law enforcement duties as the Director designates. It is the duty of all State's Attorneys to prosecute violations of this Article and institute legal proceedings as authorized under this Article.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/29B-4)
## Sec. 29B-4. Protective orders and warrants for forfeiture purposes.
<p class='subsection'>\(a) Upon application of the State, the court may enter a restraining order or injunction, require the execution of a satisfactory performance bond, or take any other action to preserve the availability of property described in Section 29B-5 of this Article for forfeiture under this Article:</p><p class='paragraph'>\(1) upon the filing of an indictment, information, or complaint charging a violation of this Article for which forfeiture may be ordered under this Article and alleging that the property with respect to which the order is sought would be subject to forfeiture under this Article; or</p><p class='paragraph'>\(2) prior to the filing of the indictment, information, or complaint, if, after notice to persons appearing to have an interest in the property and opportunity for a hearing, the court determines that:</p><p class='subparagraph'>\(A) there is probable cause to believe that the</p><p>State will prevail on the issue of forfeiture and that failure to enter the order will result in the property being destroyed, removed from the jurisdiction of the court, or otherwise made unavailable for forfeiture; and</p><p class='subparagraph'>\(B) the need to preserve the availability of the property through the entry of the requested order outweighs the hardship on any party against whom the order is to be entered.</p><p>Provided, however, that an order entered under paragraph (2) of this Section shall be effective for not more than 90 days, unless extended by the court for good cause shown or unless an indictment, information, complaint, or administrative notice has been filed.</p><p class='subsection'>\(b) A temporary restraining order under this subsection (b) may be entered upon application of the State without notice or opportunity for a hearing when an indictment, information, complaint, or administrative notice has not yet been filed with respect to the property, if the State demonstrates that there is probable cause to believe that the property with respect to which the order is sought would be subject to forfeiture under this Article and that provision of notice will jeopardize the availability of the property for forfeiture. The temporary order shall expire not more than 30 days after the date on which it is entered, unless extended for good cause shown or unless the party against whom it is entered consents to an extension for a longer period. A hearing requested concerning an order entered under this subsection (b) shall be held at the earliest possible time and prior to the expiration of the temporary order.</p><p class='subsection'>\(c) The court may receive and consider, at a hearing held under this Section, evidence and information that would be inadmissible under the Illinois rules of evidence.</p><p class='subsection'>\(d) Under its authority to enter a pretrial restraining order under this Section, the court may order a defendant to repatriate any property that may be seized and forfeited and to deposit that property pending trial with the Illinois State Police or another law enforcement agency designated by the Illinois State Police. Failure to comply with an order under this Section is punishable as a civil or criminal contempt of court.</p><p class='subsection'>\(e) The State may request the issuance of a warrant authorizing the seizure of property described in Section 29B-5 of this Article in the same manner as provided for a search warrant. If the court determines that there is probable cause to believe that the property to be seized would be subject to forfeiture, the court shall issue a warrant authorizing the seizure of that property.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/29B-5)
## Sec. 29B-5. Property subject to forfeiture.
<p>The following are subject to forfeiture:</p><p class='paragraph'>\(1) any property, real or personal, constituting, derived from, or traceable to any proceeds the person obtained, directly or indirectly, as a result of a violation of this Article;</p><p class='paragraph'>\(2) any of the person's property used, or intended to be used, in any manner or part, to commit, or to facilitate the commission of, a violation of this Article;</p><p class='paragraph'>\(3) all conveyances, including aircraft, vehicles, or vessels, which are used, or intended for use, to transport, or in any manner to facilitate the transportation, sale, receipt, possession, or concealment of property described in paragraphs (1) and (2) of this Section, but:</p><p class='subparagraph'>\(A) no conveyance used by any person as a common carrier in the transaction of business as a common carrier is subject to forfeiture under this Section unless it appears that the owner or other person in charge of the conveyance is a consenting party or privy to a violation of this Article;</p><p class='subparagraph'>\(B) no conveyance is subject to forfeiture under this Article by reason of any act or omission which the owner proves to have been committed or omitted without his or her knowledge or consent;</p><p class='subparagraph'>\(C) a forfeiture of a conveyance encumbered by a bona fide security interest is subject to the interest of the secured party if he or she neither had knowledge of nor consented to the act or omission;</p><p class='paragraph'>\(4) all real property, including any right, title, and interest, including, but not limited to, any leasehold interest or the beneficial interest in a land trust, in the whole of any lot or tract of land and any appurtenances or improvements, which is used or intended to be used, in any manner or part, to commit, or in any manner to facilitate the commission of, any violation of this Article or that is the proceeds of any violation or act that constitutes a violation of this Article.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-6)
## Sec. 29B-6. Seizure.
<p class='subsection'>\(a) Property subject to forfeiture under this Article may be seized by the Director or any peace officer upon process or seizure warrant issued by any court having jurisdiction over the property. Seizure by the Director or any peace officer without process may be made:</p><p class='paragraph'>\(1) if the seizure is incident to a seizure warrant;</p><p class='paragraph'>\(2) if the property subject to seizure has been the subject of a prior judgment in favor of the State in a criminal proceeding, or in an injunction or forfeiture proceeding based upon this Article;</p><p class='paragraph'>\(3) if there is probable cause to believe that the property is directly or indirectly dangerous to health or safety;</p><p class='paragraph'>\(4) if there is probable cause to believe that the property is subject to forfeiture under this Article and the property is seized under circumstances in which a warrantless seizure or arrest would be reasonable; or</p><p class='paragraph'>\(5) in accordance with the Code of Criminal Procedure of 1963.</p><p class='subsection'>\(b) In the event of seizure under subsection (a) of this Section, forfeiture proceedings shall be instituted in accordance with this Article.</p><p class='subsection'>\(c) Actual physical seizure of real property subject to forfeiture requires the issuance of a seizure warrant. Nothing in this Article prohibits the constructive seizure of real property through the filing of a complaint for forfeiture in circuit court and the recording of a lis pendens against the real property that is subject to forfeiture without any hearing, warrant application, or judicial approval.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-7)
## Sec. 29B-7. Safekeeping of seized property pending disposition.
<p class='subsection'>\(a) If property is seized under this Article, the seizing agency shall promptly conduct an inventory of the seized property and estimate the property's value and shall forward a copy of the inventory of seized property and the estimate of the property's value to the Director. Upon receiving notice of seizure, the Director may:</p><p class='paragraph'>\(1) place the property under seal;</p><p class='paragraph'>\(2) remove the property to a place designated by the</p><p>Director;</p><p class='paragraph'>\(3) keep the property in the possession of the seizing agency;</p><p class='paragraph'>\(4) remove the property to a storage area for safekeeping or, if the property is a negotiable instrument or money and is not needed for evidentiary purposes, deposit it in an interest bearing account;</p><p class='paragraph'>\(5) place the property under constructive seizure by posting notice of pending forfeiture on it, by giving notice of pending forfeiture to its owners and interest holders, or by filing notice of pending forfeiture in any appropriate public record relating to the property; or</p><p class='paragraph'>\(6) provide for another agency or custodian, including an owner, secured party, or lienholder, to take custody of the property upon the terms and conditions set by the Director.</p><p class='subsection'>\(b) When property is forfeited under this Article, the Director shall sell all the property unless the property is required by law to be destroyed or is harmful to the public and shall distribute the proceeds of the sale, together with any moneys forfeited or seized, under Section 29B-26 of this Article.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-8)
## Sec. 29B-8. Notice to State's Attorney.
<p>The law enforcement agency seizing property for forfeiture under this Article shall, within 60 days after seizure, notify the State's Attorney for the county, either where an act or omission giving rise to the forfeiture occurred or where the property was seized, of the seizure of the property and the facts and circumstances giving rise to the seizure and shall provide the State's Attorney with the inventory of the property and its estimated value. If the property seized for forfeiture is a vehicle, the law enforcement agency seizing the property shall immediately notify the Secretary of State that forfeiture proceedings are pending regarding the vehicle. This notice shall be by Form 4-64.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-9)
## Sec. 29B-9. Preliminary review.
<p class='subsection'>\(a) Within 28 days of the seizure, the State shall seek a preliminary determination from the circuit court as to whether there is probable cause that the property may be subject to forfeiture.</p><p class='subsection'>\(b) The rules of evidence shall not apply to any proceeding conducted under this Section.</p><p class='subsection'>\(c) The court may conduct the review under subsection (a) of this Section simultaneously with a proceeding under Section 109-1 of the Code of Criminal Procedure of 1963 for a related criminal offense if a prosecution is commenced by information or complaint.</p><p class='subsection'>\(d) The court may accept a finding of probable cause at a preliminary hearing following the filing of an information or complaint charging a related criminal offense or following the return of indictment by a grand jury charging the related offense as sufficient evidence of probable cause as required under subsection (a) of this Section.</p><p class='subsection'>\(e) Upon a finding of probable cause as required under this Section, the circuit court shall order the property subject to the applicable forfeiture Act held until the conclusion of any forfeiture proceeding.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-10)
## Sec. 29B-10. Notice to owner or interest holder.
<p class='subsection'>\(a) The first attempted service of notice shall be commenced within 28 days of the latter of filing of the verified claim or the receipt of the notice from the seizing agency by Form 4-64. A complaint for forfeiture or a notice of pending forfeiture shall be served on a claimant if the owner's or interest holder's name and current address are known, then by either: (1) personal service; or (2) mailing a copy of the notice by certified mail, return receipt requested, and first class mail to that address.</p><p class='subsection'>\(b) If no signed return receipt is received by the State's Attorney within 28 days of mailing or no communication from the owner or interest holder is received by the State's Attorney documenting actual notice by the parties, the State's Attorney shall, within a reasonable period of time, mail a second copy of the notice by certified mail, return receipt requested, and first class mail to that address. If no signed return receipt is received by the State's Attorney within 28 days of the second mailing, or no communication from the owner or interest holder is received by the State's Attorney documenting actual notice by the parties, the State's Attorney shall have 60 days to attempt to serve the notice by personal service, including substitute service by leaving a copy at the usual place of abode with some person of the family or a person residing there, of the age of 13 years or upwards. If, after 3 attempts at service in this manner, no service of the notice is accomplished, the notice shall be posted in a conspicuous manner at the address and service shall be made by the posting. The attempts at service and the posting, if required, shall be documented by the person attempting service which shall be made part of a return of service returned to the State's Attorney. The State's Attorney may utilize any Sheriff or Deputy Sheriff, a peace officer, a private process server or investigator, or an employee, agent, or investigator of the State's Attorney's Office to attempt service without seeking leave of court.</p><p class='subsection'>\(c) After the procedures listed are followed, service shall be effective on the owner or interest holder on the date of receipt by the State's Attorney of a return receipt, or on the date of receipt of a communication from an owner or interest holder documenting actual notice, whichever is first in time, or on the date of the last act performed by the State's Attorney in attempting personal service. For purposes of notice under this Section, if a person has been arrested for the conduct giving rise to the forfeiture, the address provided to the arresting agency at the time of arrest shall be deemed to be that person's known address. Provided, however, if an owner or interest holder's address changes prior to the effective date of the notice of pending forfeiture, the owner or interest holder shall promptly notify the seizing agency of the change in address or, if the owner or interest holder's address changes subsequent to the effective date of the notice of pending forfeiture, the owner or interest holder shall promptly notify the State's Attorney of the change in address. If the property seized is a conveyance, notice shall also be directed to the address reflected in the office of the agency or official in which title to or interest in the conveyance is required by law to be recorded.</p><p class='subsection'>\(d) If the owner's or interest holder's address is not known, and is not on record as provided in this Section, service by publication for 3 successive weeks in a newspaper of general circulation in the county in which the seizure occurred shall suffice for service requirements.</p><p class='subsection'>\(e) Notice to any business entity, corporation, limited liability company, limited liability partnership, or partnership shall be completed by a single mailing of a copy of the notice by certified mail, return receipt requested, and first class mail to that address. This notice is complete regardless of the return of a signed return receipt.</p><p class='subsection'>\(f) Notice to a person whose address is not within the State shall be completed by a single mailing of a copy of the notice by certified mail, return receipt requested, and first class mail to that address. This notice is complete regardless of the return of a signed return receipt.</p><p class='subsection'>\(g) Notice to a person whose address is not within the United States shall be completed by a single mailing of a copy of the notice by certified mail, return receipt requested, and first class mail to that address. This notice is complete regardless of the return of a signed return receipt. If certified mail is not available in the foreign country where the person has an address, notice shall proceed by publication requirements under subsection (d) of this Section.</p><p class='subsection'>\(h) Notice to a person whom the State's Attorney reasonably should know is incarcerated within this State shall also include mailing a copy of the notice by certified mail, return receipt requested, and first class mail to the address of the detention facility with the inmate's name clearly marked on the envelope.</p><p class='item'>\(i) After a claimant files a verified claim with the State's Attorney and provides an address at which the claimant will accept service, the complaint shall be served and notice shall be complete upon the mailing of the complaint to the claimant at the address the claimant provided via certified mail, return receipt requested, and first class mail. No return receipt need be received, or any other attempts at service need be made to comply with service and notice requirements under this Section. This certified mailing, return receipt requested, shall be proof of service of the complaint on the claimant. If notice is to be shown by actual notice from communication with a claimant, then the State's Attorney shall file an affidavit as proof of service, providing details of the communication, which shall be accepted as proof of service by the court.</p><p class='subsection'>\(j) If the property seized is a conveyance, notice shall also be directed to the address reflected in the office of the agency or official in which title to or interest in the conveyance is required by law to be recorded by mailing a copy of the notice by certified mail, return receipt requested, to that address.</p><p class='subsection'>\(k) Notice served under this Article is effective upon personal service, the last date of publication, or the mailing of written notice, whichever is earlier.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-11)
## Sec. 29B-11. Replevin prohibited.
<p>Property taken or detained under this Article shall not be subject to replevin, but is deemed to be in the custody of the Director subject only to the order and judgments of the circuit court having jurisdiction over the forfeiture proceedings and the decisions of the State's Attorney under this Article.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-12)
## Sec. 29B-12. Non-judicial forfeiture.
<p>If non-real property that exceeds $20,000 in value excluding the value of any conveyance, or if real property is seized under the provisions of this Article, the State's Attorney shall institute judicial in rem forfeiture proceedings as described in Section 29B-13 of this Article within 28 days from receipt of notice of seizure from the seizing agency under Section 29B-8 of this Article. However, if non-real property that does not exceed $20,000 in value excluding the value of any conveyance is seized, the following procedure shall be used:</p><p class='paragraph'>\(1) If, after review of the facts surrounding the seizure, the State's Attorney is of the opinion that the seized property is subject to forfeiture, then, within 28 days after the receipt of notice of seizure from the seizing agency, the State's Attorney shall cause notice of pending forfeiture to be given to the owner of the property and all known interest holders of the property in accordance with Section 29B-10 of this Article.</p><p class='paragraph'>\(2) The notice of pending forfeiture shall include a description of the property, the estimated value of the property, the date and place of seizure, the conduct giving rise to forfeiture or the violation of law alleged, and a summary of procedures and procedural rights applicable to the forfeiture action.</p><p class='paragraph'>\(3)(A) Any person claiming an interest in property that is the subject of notice under paragraph (1) of this Section, must, in order to preserve any rights or claims to the property, within 45 days after the effective date of notice as described in Section 29B-10 of this Article, file a verified claim with the State's Attorney expressing his or her interest in the property. The claim shall set forth:</p><p class='item'>\(i) the caption of the proceedings as set forth on the notice of pending forfeiture and the name of the claimant;</p><p class='item'>\(ii) the address at which the claimant will accept mail;</p><p class='item'>\(iii) the nature and extent of the claimant's interest in the property;</p><p class='item'>\(iv) the date, identity of the transferor, and circumstances of the claimant's acquisition of the interest in the property;</p><p class='item'>\(v) the names and addresses of all other persons known to have an interest in the property;</p><p class='item'>\(vi) the specific provision of law relied on in asserting the property is not subject to forfeiture;</p><p class='item'>\(vii) all essential facts supporting each assertion; and</p><p class='item'>\(viii) the relief sought.</p><p class='subparagraph'>\(B) If a claimant files the claim, then the State's</p><p>Attorney shall institute judicial in rem forfeiture proceedings with the clerk of the court as described in Section 29B-13 of this Article within 28 days after receipt of the claim.</p><p class='paragraph'>\(4) If no claim is filed within the 28-day period as described in paragraph (3) of this Section, the State's Attorney shall declare the property forfeited and shall promptly notify the owner and all known interest holders of the property and the Director of the Illinois State Police of the declaration of forfeiture and the Director shall dispose of the property in accordance with law.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/29B-13)
## Sec. 29B-13. Judicial in rem procedures.
<p>If property seized under this Article is non-real property that exceeds $20,000 in value excluding the value of any conveyance, or is real property, or a claimant has filed a claim under paragraph (3) of Section 29B-12 of this Article, the following judicial in rem procedures shall apply:</p><p class='paragraph'>\(1) If, after a review of the facts surrounding the seizure, the State's Attorney is of the opinion that the seized property is subject to forfeiture, then, within 28 days of the receipt of notice of seizure by the seizing agency or the filing of the claim, whichever is later, the State's Attorney shall institute judicial forfeiture proceedings by filing a verified complaint for forfeiture. If authorized by law, a forfeiture shall be ordered by a court on an action in rem brought by a State's Attorney under a verified complaint for forfeiture.</p><p class='paragraph'>\(2) A complaint of forfeiture shall include:</p><p class='subparagraph'>\(A) a description of the property seized;</p><p class='subparagraph'>\(B) the date and place of seizure of the property;</p><p class='subparagraph'>\(C) the name and address of the law enforcement agency making the seizure; and</p><p class='subparagraph'>\(D) the specific statutory and factual grounds for the seizure.</p><p class='paragraph'>\(3) The complaint shall be served upon the person from whom the property was seized and all persons known or reasonably believed by the State to claim an interest in the property, as provided in Section 29B-10 of this Article. The complaint shall be accompanied by the following written notice:</p><p>"This is a civil court proceeding subject to the Code of Civil Procedure. You received this Complaint of Forfeiture because the State's Attorney's office has brought a legal action seeking forfeiture of your seized property. This complaint starts the court process where the State seeks to prove that your property should be forfeited and not returned to you. This process is also your opportunity to try to prove to a judge that you should get your property back. The complaint lists the date, time, and location of your first court date. You must appear in court on that day, or you may lose the case automatically. You must also file an appearance and answer. If you are unable to pay the appearance fee, you may qualify to have the fee waived. If there is a criminal case related to the seizure of your property, your case may be set for trial after the criminal case has been resolved. Before trial, the judge may allow discovery, where the State can ask you to respond in writing to questions and give them certain documents, and you can make similar requests of the State. The trial is your opportunity to explain what happened when your property was seized and why you should get the property back."</p><p class='paragraph'>\(4) Forfeiture proceedings under this Article shall be subject to the Code of Civil Procedure and the rules of evidence relating to civil actions shall apply to proceedings under this Article with the following exception. The parties shall be allowed to use, and the court shall receive and consider, all relevant hearsay evidence that relates to evidentiary foundation, chain of custody, business records, recordings, laboratory analysis, laboratory reports, and relevant hearsay related to the use of technology in the investigation that resulted in the seizure of property that is subject to the forfeiture action.</p><p class='paragraph'>\(5) Only an owner of or interest holder in the property may file an answer asserting a claim against the property in the action in rem. For purposes of this Section, the owner or interest holder shall be referred to as claimant. Upon motion of the State, the court shall first hold a hearing, in which a claimant shall establish by a preponderance of the evidence, that he or she has a lawful, legitimate ownership interest in the property and that it was obtained through a lawful source.</p><p class='paragraph'>\(6) The answer must be signed by the owner or interest holder under penalty of perjury and shall set forth:</p><p class='subparagraph'>\(A) the caption of the proceedings as set forth on the notice of pending forfeiture and the name of the claimant;</p><p class='subparagraph'>\(B) the address at which the claimant will accept mail;</p><p class='subparagraph'>\(C) the nature and extent of the claimant's interest in the property;</p><p class='subparagraph'>\(D) the date, identity of transferor, and circumstances of the claimant's acquisition of the interest in the property;</p><p class='subparagraph'>\(E) the names and addresses of all other persons known to have an interest in the property;</p><p class='subparagraph'>\(F) all essential facts supporting each assertion;</p><p class='subparagraph'>\(G) the precise relief sought; and</p><p class='subparagraph'>\(H) in a forfeiture action involving currency or its equivalent, a claimant shall provide the State with notice of his or her intent to allege that the currency or its equivalent is not related to the alleged factual basis for the forfeiture, and why.</p><p>The answer shall follow the rules under the Code of</p><p>Civil Procedure.</p><p class='paragraph'>\(7) The answer shall be filed with the court within</p><p>45 days after service of the civil in rem complaint.</p><p class='paragraph'>\(8) The hearing shall be held within 60 days after filing of the answer unless continued for good cause.</p><p class='paragraph'>\(9) At the judicial in rem proceeding, in the State's case in chief, the State shall show by a preponderance of the evidence that the property is subject to forfeiture. If the State makes such a showing, the claimant shall have the burden of production to set forth evidence that the property is not related to the alleged factual basis of the forfeiture. After this production of evidence, the State shall maintain the burden of proof to overcome this assertion. A claimant shall provide the State notice of its intent to allege that the currency or its equivalent is not related to the alleged factual basis of the forfeiture and why. As to conveyances, at the judicial in rem proceeding, in its case in chief, the State shall show by a preponderance of the evidence:</p><p class='subparagraph'>\(A) that the property is subject to forfeiture; and</p><p class='subparagraph'>\(B) at least one of the following:</p><p class='item'>\(i) that the claimant was legally accountable for the conduct giving rise to the forfeiture;</p><p class='item'>\(ii) that the claimant knew or reasonably should have known of the conduct giving rise to the forfeiture;</p><p class='item'>\(iii) that the claimant knew or reasonably should have known that the conduct giving rise to the forfeiture was likely to occur;</p><p class='item'>\(iv) that the claimant held the property for the benefit of, or as nominee for, any person whose conduct gave rise to its forfeiture;</p><p class='item'>\(v) that if the claimant acquired the interest through any person engaging in any of the conduct described above or conduct giving rise to the forfeiture:</p><p class='subsection'>\(a) the claimant did not acquire it as a bona fide purchaser for value; or</p><p class='subsection'>\(b) the claimant acquired the interest under the circumstances that the claimant reasonably should have known the property was derived from, or used in, the conduct giving rise to the forfeiture; or</p><p class='item'>\(vi) that the claimant is not the true owner of the property that is subject to forfeiture.</p><p class='paragraph'>\(10) If the State does not meet its burden to show that the property is subject to forfeiture, the court shall order the interest in the property returned or conveyed to the claimant and shall order all other property forfeited to the State. If the State does meet its burden to show that the property is subject to forfeiture, the court shall order all property forfeited to the State.</p><p class='paragraph'>\(11) A defendant convicted in any criminal proceeding is precluded from later denying the essential allegations of the criminal offense of which the defendant was convicted in any proceeding under this Article regardless of the pendency of an appeal from that conviction. However, evidence of the pendency of an appeal is admissible.</p><p class='paragraph'>\(12) On a motion by the parties, the court may stay civil forfeiture proceedings during the criminal trial for a related criminal indictment or information alleging a money laundering violation. Such a stay shall not be available pending an appeal. Property subject to forfeiture under this Article shall not be subject to return or release by a court exercising jurisdiction over a criminal case involving the seizure of the property unless the return or release is consented to by the State's Attorney.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-14)
## Sec. 29B-14. Innocent owner hearing.
<p class='subsection'>\(a) After a complaint for forfeiture has been filed and all claimants have appeared and answered, a claimant may file a motion with the court for an innocent owner hearing prior to trial. This motion shall be made and supported by sworn affidavit and shall assert the following along with specific facts that support each assertion:</p><p class='paragraph'>\(1) that the claimant filing the motion is the true owner of the conveyance as interpreted by case law;</p><p class='paragraph'>\(2) that the claimant was not legally accountable for the conduct giving rise to the forfeiture or acquiesced in the conduct;</p><p class='paragraph'>\(3) that the claimant did not solicit, conspire, or attempt to commit the conduct giving rise to the forfeiture;</p><p class='paragraph'>\(4) that the claimant did not know or did not have reason to know that the conduct giving rise to the forfeiture was likely to occur; and</p><p class='paragraph'>\(5) that the claimant did not hold the property for the benefit of, or as nominee for, any person whose conduct gave rise to its forfeiture, or if the claimant acquired the interest through any person, the claimant acquired it as a bona fide purchaser for value or acquired the interest without knowledge of the seizure of the property for forfeiture.</p><p class='subsection'>\(b) The claimant's motion shall include specific facts supporting these assertions.</p><p class='subsection'>\(c) Upon this filing, a hearing may only be conducted after the parties have been given the opportunity to conduct limited discovery as to the ownership and control of the property, the claimant's knowledge, or any matter relevant to the issues raised or facts alleged in the claimant's motion. Discovery shall be limited to the People's requests in these areas but may proceed by any means allowed in the Code of Civil Procedure.</p><p class='paragraph'>\(1) After discovery is complete and the court has allowed for sufficient time to review and investigate the discovery responses, the court shall conduct a hearing. At the hearing, the fact that the conveyance is subject to forfeiture shall not be at issue. The court shall only hear evidence relating to the issue of innocent ownership.</p><p class='paragraph'>\(2) At the hearing on the motion, it shall be the burden of the claimant to prove each of the assertions listed in subsection (a) of this Section by a preponderance of the evidence.</p><p class='paragraph'>\(3) If a claimant meets his or her burden of proof, the court shall grant the motion and order the property returned to the claimant. If the claimant fails to meet his or her burden of proof, then the court shall deny the motion and the forfeiture case shall proceed according to the Code of Civil Procedure.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-15)
## Sec. 29B-15. Burden and commencement of forfeiture action.
<p class='subsection'>\(a) Notwithstanding any other provision of this Article, the State's burden of proof at the trial of the forfeiture action shall be by clear and convincing evidence if:</p><p class='paragraph'>\(1) a finding of not guilty is entered as to all counts and all defendants in a criminal proceeding relating to the conduct giving rise to the forfeiture action; or</p><p class='paragraph'>\(2) the State receives an adverse finding at a preliminary hearing and fails to secure an indictment in a criminal proceeding relating to the factual allegations of the forfeiture action.</p><p class='subsection'>\(b) All property declared forfeited under this Article vests in the State on the commission of the conduct giving rise to forfeiture together with the proceeds of the property after that time. Except as otherwise provided in this Article, title to any property or proceeds subject to forfeiture subsequently transferred to any person remain subject to forfeiture and thereafter shall be ordered forfeited unless the person to whom the property was transferred makes an appropriate claim and has his or her claim adjudicated at the judicial in rem hearing.</p><p class='subsection'>\(c) A civil action under this Article shall be commenced within 5 years after the last conduct giving rise to forfeiture became known or should have become known or 5 years after the forfeitable property is discovered, whichever is later, excluding any time during which either the property or claimant is out of the State or in confinement or during which criminal proceedings relating to the same conduct are in progress.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-16)
## Sec. 29B-16. Joint tenancy or tenancy in common.
<p>If property is ordered forfeited under this Section from a claimant who held title to the property in joint tenancy or tenancy in common with another claimant, the court shall determine the amount of each owner's interest in the property according to principles of property law.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-17)
## Sec. 29B-17. Exception for bona fide purchasers.
<p>No property shall be forfeited under this Article from a person who, without actual or constructive notice that the property was the subject of forfeiture proceedings, obtained possession of the property as a bona fide purchaser for value. A person who purports to effect transfer of property after receiving actual or constructive notice that the property is subject to seizure or forfeiture is guilty of contempt of court and shall be liable to the State for a penalty in the amount of the fair market value of the property.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-18)
## Sec. 29B-18. Proportionality.
<p>Property that is forfeited shall be subject to an 8th Amendment to the United States Constitution disproportionate penalties analysis and the property forfeiture may be denied in whole or in part if the court finds that the forfeiture would constitute an excessive fine in violation of the 8th Amendment as interpreted by case law.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-19)
## Sec. 29B-19. Stay of time periods.
<p>If property is seized for evidence and for forfeiture, the time periods for instituting judicial and non-judicial forfeiture proceedings shall not begin until the property is no longer necessary for evidence.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-20)
## Sec. 29B-20. Settlement of claims.
<p>Notwithstanding other provisions of this Article, the State's Attorney and a claimant of seized property may enter into an agreed-upon settlement concerning the seized property in such an amount and upon such terms as are set out in writing in a settlement agreement. All proceeds from a settlement agreement shall be tendered to the Illinois State Police and distributed under Section 29B-26 of this Article.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/29B-21)
## Sec. 29B-21. Attorney's fees.
<p>Nothing in this Article applies to property that constitutes reasonable bona fide attorney's fees paid to an attorney for services rendered or to be rendered in the forfeiture proceeding or criminal proceeding relating directly thereto if the property was paid before its seizure and before the issuance of any seizure warrant or court order prohibiting transfer of the property and if the attorney, at the time he or she received the property, did not know that it was property subject to forfeiture under this Article.</p><p>(Source: P.A. 102-558, eff. 8-20-21.)</p>### (720 ILCS 5/29B-22)
## Sec. 29B-22. Construction.
<p class='subsection'>\(a) It is the intent of the General Assembly that the forfeiture provisions of this Article be liberally construed so as to effect their remedial purpose. The forfeiture of property and other remedies under this Article shall be considered to be in addition to, and not exclusive of, any sentence or other remedy provided by law.</p><p class='subsection'>\(b) The changes made to this Article by Public Act 100-512 and Public Act 100-699 are subject to Section 2 of the Statute on Statutes.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/29B-23)
## Sec. 29B-23. Judicial review.
<p>If property has been declared forfeited under Section 29B-12 of this Article, any person who has an interest in the property declared forfeited may, within 30 days after the effective date of the notice of the declaration of forfeiture, file a claim as described in paragraph (3) of Section 29B-12 of this Article. If a claim is filed under this Section, then the procedures described in Section of 29B-13 of this Article apply.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-24)
## Sec. 29B-24. Review of administrative decisions.
<p>All administrative findings, rulings, final determinations, findings, and conclusions of the State's Attorney's Office under this Article are final and conclusive decisions of the matters involved. Any person aggrieved by the decision may obtain review of the decision under the provisions of the Administrative Review Law and the rules adopted under that Law. Pending final decision on such review, the administrative acts, orders, and rulings of the State's Attorney's Office remain in full force and effect unless modified or suspended by order of court pending final judicial decision. Pending final decision on such review, the acts, orders, and rulings of the State's Attorney's Office remain in full force and effect, unless stayed by order of court. However, no stay of any decision of the administrative agency shall issue unless the person aggrieved by the decision establishes by a preponderance of the evidence that good cause exists for the stay. In determining good cause, the court shall find that the aggrieved party has established a substantial likelihood of prevailing on the merits and that granting the stay will not have an injurious effect on the general public.</p><p>(Source: P.A. 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/29B-25)
## Sec. 29B-25. Return of property, damages, and costs.
<p class='subsection'>\(a) The law enforcement agency that holds custody of property seized for forfeiture shall deliver property ordered by the court to be returned or conveyed to the claimant within a reasonable time not to exceed 7 days, unless the order is stayed by the trial court or a reviewing court pending an appeal, motion to reconsider, or other reason.</p><p class='subsection'>\(b) The law enforcement agency that holds custody of property is responsible for any damages, storage fees, and related costs applicable to property returned. The claimant shall not be subject to any charges by the State for storage of the property or expenses incurred in the preservation of the property. Charges for the towing of a conveyance shall be borne by the claimant unless the conveyance was towed for the sole reason of seizure for forfeiture. This Section does not prohibit the imposition of any fees or costs by a home rule unit of local government related to the impoundment of a conveyance under an ordinance enacted by the unit of government.</p><p class='subsection'>\(c) A law enforcement agency shall not retain forfeited property for its own use or transfer the property to any person or entity, except as provided under this Section. A law enforcement agency may apply in writing to the Director of the Illinois State Police to request that forfeited property be awarded to the agency for a specifically articulated official law enforcement use in an investigation. The Director shall provide a written justification in each instance detailing the reasons why the forfeited property was placed into official use and the justification shall be retained for a period of not less than 3 years.</p><p class='subsection'>\(d) A claimant or a party interested in personal property contained within a seized conveyance may file a request with the State's Attorney in a non-judicial forfeiture action, or a motion with the court in a judicial forfeiture action for the return of any personal property contained within a conveyance that is seized under this Article. The return of personal property shall not be unreasonably withheld if the personal property is not mechanically or electrically coupled to the conveyance, needed for evidentiary purposes, or otherwise contraband. Any law enforcement agency that returns property under a court order under this Section shall not be liable to any person who claims ownership to the property if it is returned to an improper party.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/29B-26)
## Sec. 29B-26. Distribution of proceeds.
<p>All moneys and the sale proceeds of all other property forfeited and seized under this Article shall be distributed as follows:</p><p class='paragraph'>\(1) 65% shall be distributed to the metropolitan enforcement group, local, municipal, county, or State law enforcement agency or agencies that conducted or participated in the investigation resulting in the forfeiture. The distribution shall bear a reasonable relationship to the degree of direct participation of the law enforcement agency in the effort resulting in the forfeiture, taking into account the total value of the property forfeited and the total law enforcement effort with respect to the violation of the law upon which the forfeiture is based. Amounts distributed to the agency or agencies shall be used for the enforcement of laws.</p><p class='paragraph'>\(2)(i) 12.5% shall be distributed to the Office of the State's Attorney of the county in which the prosecution resulting in the forfeiture was instituted, deposited in a special fund in the county treasury and appropriated to the State's Attorney for use in the enforcement of laws. In counties over 3,000,000 population, 25% shall be distributed to the Office of the State's Attorney for use in the enforcement of laws. If the prosecution is undertaken solely by the Attorney General, the portion provided under this subparagraph (i) shall be distributed to the Attorney General for use in the enforcement of laws.</p><p class='item'>\(ii) 12.5% shall be distributed to the Office of the</p><p>State's Attorneys Appellate Prosecutor and deposited in the Narcotics Profit Forfeiture Fund of that office to be used for additional expenses incurred in the investigation, prosecution, and appeal of cases arising under laws. The Office of the State's Attorneys Appellate Prosecutor shall not receive distribution from cases brought in counties with over 3,000,000 population.</p><p class='paragraph'>\(3) 10% shall be retained by the Illinois State</p><p>Police for expenses related to the administration and sale of seized and forfeited property.</p><p>Moneys and the sale proceeds distributed to the Illinois State Police under this Article shall be deposited in the Money Laundering Asset Recovery Fund created in the State treasury and shall be used by the Illinois State Police for State law enforcement purposes. All moneys and sale proceeds of property forfeited and seized under this Article and distributed according to this Section may also be used to purchase opioid antagonists as defined in Section 5-23 of the Substance Use Disorder Act.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/29B-27)
## Sec. 29B-27. Applicability; savings clause.
<p class='subsection'>\(a) The changes made to this Article by Public Act 100-512 and Public Act 100-699 only apply to property seized on and after July 1, 2018.</p><p class='subsection'>\(b) The changes made to this Article by Public Act 100-699 are subject to Section 4 of the Statute on Statutes.</p><p>(Source: P.A. 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>