# Article 33. Official Misconduct {.unnumbered}

### (720 ILCS 5/33-1) (from Ch. 38, par. 33-1)
## Sec. 33-1. Bribery.
<p>A person commits bribery when:</p><p class='subsection'>\(a) With intent to influence the performance of any act related to the employment or function of any public officer, public employee, juror or witness, he or she promises or tenders to that person any property or personal advantage which he or she is not authorized by law to accept; or</p><p class='subsection'>\(b) With intent to influence the performance of any act related to the employment or function of any public officer, public employee, juror or witness, he or she promises or tenders to one whom he or she believes to be a public officer, public employee, juror or witness, any property or personal advantage which a public officer, public employee, juror or witness would not be authorized by law to accept; or</p><p class='subsection'>\(c) With intent to cause any person to influence the performance of any act related to the employment or function of any public officer, public employee, juror or witness, he or she promises or tenders to that person any property or personal advantage which he or she is not authorized by law to accept; or</p><p class='subsection'>\(d) He or she receives, retains or agrees to accept any property or personal advantage which he or she is not authorized by law to accept knowing that the property or personal advantage was promised or tendered with intent to cause him or her to influence the performance of any act related to the employment or function of any public officer, public employee, juror or witness; or</p><p class='subsection'>\(e) He or she solicits, receives, retains, or agrees to accept any property or personal advantage pursuant to an understanding that he or she shall improperly influence or attempt to influence the performance of any act related to the employment or function of any public officer, public employee, juror or witness.</p><p>As used in this Section, "tenders" means any delivery or proffer made with the requisite intent.</p><p>Sentence. Bribery is a Class 2 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13; 98-756, eff. 7-16-14.)</p>### (720 ILCS 5/33-2) (from Ch. 38, par. 33-2)
## Sec. 33-2. Failure to report a bribe.
<p>Any public officer, public employee or juror who fails to report forthwith to the local State's Attorney, or in the case of a State employee to the Illinois State Police, any offer made to him in violation of Section 33-1 commits a Class A misdemeanor.</p><p>In the case of a State employee, the making of such report to the Illinois State Police shall discharge such employee from any further duty under this Section. Upon receiving any such report, the Illinois State Police shall forthwith transmit a copy thereof to the appropriate State's Attorney.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/33-3) (from Ch. 38, par. 33-3)
## Sec. 33-3. Official misconduct.
<p class='subsection'>\(a) A public officer or employee or special government agent commits misconduct when, in his official capacity or capacity as a special government agent, he or she commits any of the following acts:</p><p class='paragraph'>\(1) Intentionally or recklessly fails to perform any mandatory duty as required by law; or</p><p class='paragraph'>\(2) Knowingly performs an act which he knows he is forbidden by law to perform; or</p><p class='paragraph'>\(3) With intent to obtain a personal advantage for himself or another, he performs an act in excess of his lawful authority; or</p><p class='paragraph'>\(4) Solicits or knowingly accepts for the performance of any act a fee or reward which he knows is not authorized by law.</p><p class='subsection'>\(b) An employee of a law enforcement agency commits misconduct when he or she knowingly uses or communicates, directly or indirectly, information acquired in the course of employment, with the intent to obstruct, impede, or prevent the investigation, apprehension, or prosecution of any criminal offense or person. Nothing in this subsection (b) shall be construed to impose liability for communicating to a confidential resource, who is participating or aiding law enforcement, in an ongoing investigation.</p><p class='subsection'>\(c) A public officer or employee or special government agent convicted of violating any provision of this Section forfeits his or her office or employment or position as a special government agent. In addition, he or she commits a Class 3 felony.</p><p class='subsection'>\(d) For purposes of this Section:</p><p>"Special government agent" has the meaning ascribed to it in subsection (l) of Section 4A-101 of the Illinois Governmental Ethics Act.</p><p>(Source: P.A. 101-652, eff. 7-1-21 .)</p>### (720 ILCS 5/33-3.1)
## Sec. 33-3.1. Solicitation misconduct (State government).
<p class='subsection'>\(a) An employee of an executive branch constitutional officer commits solicitation misconduct (State government) when, at any time, he or she knowingly solicits or receives contributions, as that term is defined in Section 9-1.4 of the Election Code, from a person engaged in a business or activity over which the person has regulatory authority.</p><p class='subsection'>\(b) For the purpose of this Section, "employee of an executive branch constitutional officer" means a full-time or part-time salaried employee, full-time or part-time salaried appointee, or any contractual employee of any office, board, commission, agency, department, authority, administrative unit, or corporate outgrowth under the jurisdiction of an executive branch constitutional officer; and "regulatory authority" means having the responsibility to investigate, inspect, license, or enforce regulatory measures necessary to the requirements of any State or federal statute or regulation relating to the business or activity.</p><p class='subsection'>\(c) An employee of an executive branch constitutional officer, including one who does not have regulatory authority, commits a violation of this Section if that employee knowingly acts in concert with an employee of an executive branch constitutional officer who does have regulatory authority to solicit or receive contributions in violation of this Section.</p><p class='subsection'>\(d) Solicitation misconduct (State government) is a Class A misdemeanor. An employee of an executive branch constitutional officer convicted of committing solicitation misconduct (State government) forfeits his or her employment.</p><p class='subsection'>\(e) An employee of an executive branch constitutional officer who is discharged, demoted, suspended, threatened, harassed, or in any other manner discriminated against in the terms and conditions of employment because of lawful acts done by the employee or on behalf of the employee or others in furtherance of the enforcement of this Section shall be entitled to all relief necessary to make the employee whole.</p><p class='subsection'>\(f) Any person who knowingly makes a false report of solicitation misconduct (State government) to the Illinois State Police, the Attorney General, a State's Attorney, or any law enforcement official is guilty of a Class C misdemeanor.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/33-3.2)
## Sec. 33-3.2. Solicitation misconduct (local government).
<p class='subsection'>\(a) An employee of a chief executive officer of a local government commits solicitation misconduct (local government) when, at any time, he or she knowingly solicits or receives contributions, as that term is defined in Section 9-1.4 of the Election Code, from a person engaged in a business or activity over which the person has regulatory authority.</p><p class='subsection'>\(b) For the purpose of this Section, "chief executive officer of a local government" means an executive officer of a county, township or municipal government or any administrative subdivision under jurisdiction of the county, township, or municipal government including but not limited to: chairman or president of a county board or commission, mayor or village president, township supervisor, county executive, municipal manager, assessor, auditor, clerk, coroner, recorder, sheriff or State's Attorney; "employee of a chief executive officer of a local government" means a full-time or part-time salaried employee, full-time or part-time salaried appointee, or any contractual employee of any office, board, commission, agency, department, authority, administrative unit, or corporate outgrowth under the jurisdiction of a chief executive officer of a local government; and "regulatory authority" means having the responsibility to investigate, inspect, license, or enforce regulatory measures necessary to the requirements of any State, local, or federal statute or regulation relating to the business or activity.</p><p class='subsection'>\(c) An employee of a chief executive officer of a local government, including one who does not have regulatory authority, commits a violation of this Section if that employee knowingly acts in concert with an employee of a chief executive officer of a local government who does have regulatory authority to solicit or receive contributions in violation of this Section.</p><p class='subsection'>\(d) Solicitation misconduct (local government) is a Class A misdemeanor. An employee of a chief executive officer of a local government convicted of committing solicitation misconduct (local government) forfeits his or her employment.</p><p class='subsection'>\(e) An employee of a chief executive officer of a local government who is discharged, demoted, suspended, threatened, harassed, or in any other manner discriminated against in the terms and conditions of employment because of lawful acts done by the employee or on behalf of the employee or others in furtherance of the enforcement of this Section shall be entitled to all relief necessary to make the employee whole.</p><p class='subsection'>\(f) Any person who knowingly makes a false report of solicitation misconduct (local government) to the Illinois State Police, the Attorney General, a State's Attorney, or any law enforcement official is guilty of a Class C misdemeanor.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/33-4)
## Sec. 33-4. Peace officer or correctional officer; gang-related activity prohibited.
<p class='subsection'>\(a) It is unlawful for a peace officer or correctional officer to knowingly commit any act in furtherance of gang-related activities, except when acting in furtherance of an undercover law enforcement investigation.</p><p class='subsection'>\(b) In this Section, "gang-related" has the meaning ascribed to it in Section 10 of the Illinois Streetgang Terrorism Omnibus Prevention Act.</p><p class='subsection'>\(c) Sentence. A violation of this Section is a Class 3 felony.</p><p>(Source: P.A. 90-131, eff. 1-1-98 .)</p>### (720 ILCS 5/33-5)
## Sec. 33-5. Preservation of evidence.
<p class='subsection'>\(a) It is unlawful for a law enforcement agency or an agent acting on behalf of the law enforcement agency to intentionally fail to comply with the provisions of subsection (a) of Section 116-4 of the Code of Criminal Procedure of 1963.</p><p class='subsection'>\(b) Sentence. A person who violates this Section is guilty of a Class 4 felony.</p><p class='subsection'>\(c) For purposes of this Section, "law enforcement agency" has the meaning ascribed to it in subsection (e) of Section 116-4 of the Code of Criminal Procedure of 1963.</p><p>(Source: P.A. 91-871, eff. 1-1-01; 92-459, eff. 8-22-01.)</p>### (720 ILCS 5/33-6)
## Sec. 33-6. Bribery to obtain driving privileges.
<p class='subsection'>\(a) A person commits the offense of bribery to obtain driving privileges when:</p><p class='paragraph'>\(1) with intent to influence any act related to the issuance of any driver's license or permit by an employee of the Illinois Secretary of State's Office, or the owner or employee of any commercial driver training school licensed by the Illinois Secretary of State, or any other individual authorized by the laws of this State to give driving instructions or administer all or part of a driver's license examination, he or she promises or tenders to that person any property or personal advantage which that person is not authorized by law to accept; or</p><p class='paragraph'>\(2) with intent to cause any person to influence any act related to the issuance of any driver's license or permit by an employee of the Illinois Secretary of State's Office, or the owner or employee of any commercial driver training school licensed by the Illinois Secretary of State, or any other individual authorized by the laws of this State to give driving instructions or administer all or part of a driver's license examination, he or she promises or tenders to that person any property or personal advantage which that person is not authorized by law to accept; or</p><p class='paragraph'>\(3) as an employee of the Illinois Secretary of</p><p>State's Office, or the owner or employee of any commercial driver training school licensed by the Illinois Secretary of State, or any other individual authorized by the laws of this State to give driving instructions or administer all or part of a driver's license examination, solicits, receives, retains, or agrees to accept any property or personal advantage that he or she is not authorized by law to accept knowing that such property or personal advantage was promised or tendered with intent to influence the performance of any act related to the issuance of any driver's license or permit; or</p><p class='paragraph'>\(4) as an employee of the Illinois Secretary of</p><p>State's Office, or the owner or employee of any commercial driver training school licensed by the Illinois Secretary of State, or any other individual authorized by the laws of this State to give driving instructions or administer all or part of a driver's license examination, solicits, receives, retains, or agrees to accept any property or personal advantage pursuant to an understanding that he or she shall improperly influence or attempt to influence the performance of any act related to the issuance of any driver's license or permit.</p><p class='subsection'>\(b) Sentence. Bribery to obtain driving privileges is a Class 2 felony.</p><p>(Source: P.A. 96-740, eff. 1-1-10; 96-962, eff. 7-2-10.)</p>### (720 ILCS 5/33-7)
## Sec. 33-7. Public contractor misconduct.
<p class='subsection'>\(a) A public contractor; a person seeking a public contract on behalf of himself, herself, or another; an employee of a public contractor; or a person seeking a public contract on behalf of himself, herself, or another commits public contractor misconduct when, in the performance of, or in connection with, a contract with the State, a unit of local government, or a school district or in obtaining or seeking to obtain such a contract he or she commits any of the following acts:</p><p class='paragraph'>\(1) intentionally or knowingly makes, uses, or causes to be made or used a false record or statement to conceal, avoid, or decrease an obligation to pay or transmit money or property;</p><p class='paragraph'>\(2) knowingly performs an act that he or she knows he or she is forbidden by law to perform;</p><p class='paragraph'>\(3) with intent to obtain a personal advantage for himself, herself, or another, he or she performs an act in excess of his or her contractual responsibility;</p><p class='paragraph'>\(4) solicits or knowingly accepts for the performance of any act a fee or reward that he or she knows is not authorized by law; or</p><p class='paragraph'>\(5) knowingly or intentionally seeks or receives compensation or reimbursement for goods and services he or she purported to deliver or render, but failed to do so pursuant to the terms of the contract, to the unit of State or local government or school district.</p><p class='subsection'>\(b) Sentence. Any person who violates this Section commits a Class 3 felony. Any person convicted of this offense or a similar offense in any state of the United States which contains the same elements of this offense shall be barred for 10 years from the date of conviction from contracting with, employment by, or holding public office with the State or any unit of local government or school district. No corporation shall be barred as a result of a conviction under this Section of any employee or agent of such corporation if the employee so convicted is no longer employed by the corporation and (1) it has been finally adjudicated not guilty or (2) it demonstrates to the government entity with which it seeks to contract, and that entity finds, that the commission of the offense was neither authorized, requested, commanded, nor performed by a director, officer or high managerial agent on behalf of the corporation as provided in paragraph (2) of subsection (a) of Section 5-4 of this Code.</p><p class='subsection'>\(c) The Attorney General or the State's Attorney in the county where the principal office of the unit of local government or school district is located may bring a civil action on behalf of any unit of State or local government to recover a civil penalty from any person who knowingly engages in conduct which violates subsection (a) of this Section in treble the amount of the monetary cost to the unit of State or local government or school district involved in the violation. The Attorney General or State's Attorney shall be entitled to recover reasonable attorney's fees as part of the costs assessed to the defendant. This subsection (c) shall in no way limit the ability of any unit of State or local government or school district to recover moneys or damages regarding public contracts under any other law or ordinance. A civil action shall be barred unless the action is commenced within 6 years after the later of (1) the date on which the conduct establishing the cause of action occurred or (2) the date on which the unit of State or local government or school district knew or should have known that the conduct establishing the cause of action occurred.</p><p class='subsection'>\(d) This amendatory Act of the 96th General Assembly shall not be construed to create a private right of action.</p><p>(Source: P.A. 96-575, eff. 8-18-09.)</p>### (720 ILCS 5/33-8)
## Sec. 33-8. Legislative misconduct.
<p class='subsection'>\(a) A member of the General Assembly commits legislative misconduct when he or she knowingly accepts or receives, directly or indirectly, any money or other valuable thing, from any corporation, company or person, for any vote or influence he or she may give or withhold on any bill, resolution or appropriation, or for any other official act.</p><p class='subsection'>\(b) Sentence. Legislative misconduct is a Class 3 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/33-9)
## Sec. 33-9. Law enforcement misconduct.
<p class='subsection'>\(a) A law enforcement officer or a person acting under color of law commits law enforcement misconduct when, in the performance of his or her official duties with intent to prevent the apprehension or obstruct the prosecution or defense of any person, he or she:</p><p class='paragraph'>\(1) knowingly and intentionally misrepresents or fails to provide material facts describing an incident in any report or during any investigations regarding the law enforcement employee's conduct;</p><p class='paragraph'>\(2) knowingly and intentionally withholds any knowledge of the material misrepresentations of another law enforcement officer from the law enforcement employee's supervisor, investigator, or other person or entity tasked with holding the law enforcement officer accountable; or</p><p class='paragraph'>\(3) knowingly and intentionally fails to comply with paragraphs (3), (5), (6), and (7) of subsection (a) of Section 10-20 of the Law Enforcement Officer-Worn Body Camera Act.</p><p class='subsection'>\(b) Sentence. Law enforcement misconduct is a Class 3 felony.</p><p>(Source: P.A. 101-652, eff. 7-1-21; 102-28, eff. 6-25-21.)</p>### (720 ILCS 5/Tit. III Pt. F heading)
<p>PART F.</p><p>CERTAIN AGGRAVATED OFFENSES</p>