# Article 2. General Definitions {.unnumbered}

### (720 ILCS 5/2-0.5) (was 720 ILCS 5/2-.5)
## Sec. 2-0.5. Definitions.
<p>For the purposes of this Code, the words and phrases described in this Article have the meanings designated in this Article, except when a particular context clearly requires a different meaning.</p><p>(Source: P.A. 95-331, eff. 8-21-07.)</p>### (720 ILCS 5/2-1) (from Ch. 38, par. 2-1)
## Sec. 2-1. "Acquittal".
<p>"Acquittal" means a verdict or finding of not guilty of an offense, rendered by a legally constituted jury or by a court of competent jurisdiction authorized to try the case without a jury.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-2) (from Ch. 38, par. 2-2)
## Sec. 2-2. "Act".
<p>"Act" includes a failure or omission to take action.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-3) (from Ch. 38, par. 2-3)
## Sec. 2-3. "Another".
<p>"Another" means a person or persons as defined in this Code other than the offender.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-3.5)
## Sec. 2-3.5.
<p>"Community policing volunteer" means a person who is summoned or directed by a peace officer or any person actively participating in a community policing program and who is engaged in lawful conduct intended to assist any unit of government in enforcing any criminal or civil law. For the purpose of this Section, "community policing program" means any plan, system or strategy established by and conducted under the auspices of a law enforcement agency in which citizens participate with and are guided by the law enforcement agency and work with members of that agency to reduce or prevent crime within a defined geographic area.</p>
<p>(Source: P.A. 90-651, eff. 1-1-99.)</p>### (720 ILCS 5/2-3.6)
## Sec. 2-3.6. "Armed with a firearm".
<p>Except as otherwise provided in a specific Section, a person is considered "armed with a firearm" when he or she carries on or about his or her person or is otherwise armed with a firearm.</p><p>(Source: P.A. 91-404, eff. 1-1-00.)</p>### (720 ILCS 5/2-4) (from Ch. 38, par. 2-4)
## Sec. 2-4. "Conduct".
<p>"Conduct" means an act or a series of acts, and the accompanying mental state.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-5) (from Ch. 38, par. 2-5)
## Sec. 2-5. "Conviction".
<p>"Conviction" means a judgment of conviction or sentence entered upon a plea of guilty or upon a verdict or finding of guilty of an offense, rendered by a legally constituted jury or by a court of competent jurisdiction authorized to try the case without a jury.</p><p>(Source: Laws 1961, p. 1983 .)</p>### (720 ILCS 5/2-5.1)
## Sec. 2-5.1. Day care center.
<p>"Day care center" has the meaning ascribed to it in Section 2.09 of the Child Care Act of 1969.</p><p>(Source: P.A. 96-556, eff. 1-1-10.)</p>### (720 ILCS 5/2-5.2)
## Sec. 2-5.2. Day care home.
<p>"Day care home" has the meaning ascribed to it in Section 2.18 of the Child Care Act of 1969.</p><p>(Source: P.A. 96-556, eff. 1-1-10.)</p>### (720 ILCS 5/2-6) (from Ch. 38, par. 2-6)
## Sec. 2-6. "Dwelling".
<p class='subsection'>\(a) Except as otherwise provided in subsection (b) of this Section, "dwelling" means a building or portion thereof, a tent, a vehicle, or other enclosed space which is used or intended for use as a human habitation, home or residence.</p><p class='subsection'>\(b) For the purposes of Section 19-3 of this Code, "dwelling" means a house, apartment, mobile home, trailer, or other living quarters in which at the time of the alleged offense the owners or occupants actually reside or in their absence intend within a reasonable period of time to reside.</p><p>(Source: P.A. 84-1289.)</p>### (720 ILCS 5/2-6.5)
## Sec. 2-6.5. Emergency medical technician.
<p>"Emergency medical technician-ambulance", "emergency medical technician-intermediate", and "emergency medical technician-paramedic" have the meanings ascribed to them in the Emergency Medical Services (EMS) Systems Act.</p><p>(Source: P.A. 88-433.)</p>### (720 ILCS 5/2-6.6)
## Sec. 2-6.6. Emergency management worker.
<p>"Emergency management worker" shall include the following:</p><p class='subsection'>\(a) any person, paid or unpaid, who is a member of a local or county emergency services and disaster agency as defined by the Illinois Emergency Management Agency Act, or who is an employee of the Illinois Emergency Management Agency or the Federal Emergency Management Agency;</p><p class='subsection'>\(b) any employee or volunteer of the American Red Cross;</p><p class='subsection'>\(c) any employee of a federal, State, county, or local government agency assisting an emergency services and disaster agency, the Illinois Emergency Management Agency, or the Federal Emergency Management Agency through mutual aid or as otherwise requested or directed in time of disaster or emergency; and</p><p class='subsection'>\(d) any person volunteering or directed to assist an emergency services and disaster agency, the Illinois Emergency Management Agency, or the Federal Emergency Management Agency.</p><p>(Source: P.A. 94-243, eff. 1-1-06; 94-323, eff. 1-1-06; 95-331, eff. 8-21-07.)</p>### (720 ILCS 5/2-7) (from Ch. 38, par. 2-7)
## Sec. 2-7. "Felony".
<p>"Felony" means an offense for which a sentence to death or to a term of imprisonment in a penitentiary for one year or more is provided.</p><p>(Source: P.A. 77-2638.)</p>### (720 ILCS 5/2-7.1)
## Sec. 2-7.1. "Firearm" and "firearm ammunition".
<p>"Firearm" and "firearm ammunition" have the meanings ascribed to them in Section 1.1 of the Firearm Owners Identification Card Act.</p><p>(Source: P.A. 91-544, eff. 1-1-00.)</p>### (720 ILCS 5/2-7.5)
## Sec. 2-7.5. "Firearm".
<p>Except as otherwise provided in a specific Section, "firearm" has the meaning ascribed to it in Section 1.1 of the Firearm Owners Identification Card Act.</p><p>(Source: P.A. 95-331, eff. 8-21-07.)</p>### (720 ILCS 5/2-8) (from Ch. 38, par. 2-8)
## Sec. 2-8. "Forcible felony".
<p>"Forcible felony" means treason, first degree murder, second degree murder, predatory criminal sexual assault of a child, aggravated criminal sexual assault, criminal sexual assault, robbery, burglary, residential burglary, aggravated arson, arson, aggravated kidnaping, kidnaping, aggravated battery resulting in great bodily harm or permanent disability or disfigurement and any other felony which involves the use or threat of physical force or violence against any individual.</p><p>(Source: P.A. 88-277; 89-428, eff. 12-13-95; 89-462, eff. 5-29-96.)</p>### (720 ILCS 5/2-8.1)
## Sec. 2-8.1. Group day care home.
<p>"Group day care home" has the meaning ascribed to it in Section 2.20 of the Child Care Act of 1969.</p><p>(Source: P.A. 96-556, eff. 1-1-10.)</p>### (720 ILCS 5/2-9) (from Ch. 38, par. 2-9)
## Sec. 2-9. "Included offense".
<p>"Included offense" means an offense which</p><p class='subsection'>\(a) Is established by proof of the same or less than all of the facts or a less culpable mental state (or both), than that which is required to establish the commission of the offense charged, or</p><p class='subsection'>\(b) Consists of an attempt to commit the offense charged or an offense included therein.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-10) (from Ch. 38, par. 2-10)
## Sec. 2-10. "Includes".
<p>"Includes" or "including" means comprehending among other particulars, without limiting the generality of the foregoing word or phrase.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-10.1) (from Ch. 38, par. 2-10.1)
## Sec. 2-10.1.
<p>"Person with a severe or profound intellectual disability" means a person (i) whose intelligence quotient does not exceed 40 or (ii) whose intelligence quotient does not exceed 55 and who suffers from significant mental illness to the extent that the person's ability to exercise rational judgment is impaired. In any proceeding in which the defendant is charged with committing a violation of Section 10-2, 10-5, 11-1.30, 11-1.60, 11-14.4, 11-15.1, 11-19.1, 11-19.2, 11-20.1, 11-20.1B, 11-20.3, 12-4.3, 12-14, or 12-16, or subdivision (b)(1) of Section 12-3.05, of this Code against a victim who is alleged to be a person with a severe or profound intellectual disability, any findings concerning the victim's status as a person with a severe or profound intellectual disability, made by a court after a judicial admission hearing concerning the victim under Articles V and VI of Chapter IV of the Mental Health and Developmental Disabilities Code shall be admissible.</p>
<p>(Source: P.A. 98-756, eff. 7-16-14; 99-143, eff. 7-27-15.)</p>### (720 ILCS 5/2-10.2)
## Sec. 2-10.2. Laser or laser device.
<p>"Laser" or "laser device" means any small or hand-held battery powered device which converts incident electromagnetic radiation of mixed frequencies to one or more discrete frequencies of highly amplified and coherent visible radiation or light. Proof that a particular device casts a small red dot or other similar small and discrete image or small and discrete visual signal upon a target surface at least 15 feet away creates a rebuttable presumption that the device is a laser. Flashlights and similar lamps, lanterns, lights, and penlights are not laser devices.</p><p>(Source: P.A. 91-672, eff. 1-1-00.)</p>### (720 ILCS 5/2-10.3)
## Sec. 2-10.3. Laser gunsight.
<p>"Laser gunsight" means any battery powered laser device manufactured to function as a firearm aiming device or sold as a firearm aiming device.</p><p>(Source: P.A. 91-672, eff. 1-1-00.)</p>### (720 ILCS 5/2-11) (from Ch. 38, par. 2-11)
## Sec. 2-11. "Misdemeanor".
<p>"Misdemeanor" means any offense for which a sentence to a term of imprisonment in other than a penitentiary for less than one year may be imposed.</p><p>(Source: P.A. 77-2638.)</p>### (720 ILCS 5/2-11.1)
## Sec. 2-11.1. "Motor vehicle".
<p>"Motor vehicle" has the meaning ascribed to it in the Illinois Vehicle Code.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/2-12) (from Ch. 38, par. 2-12)
## Sec. 2-12. "Offense".
<p>"Offense" means a violation of any penal statute of this State.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-12.1)
## Sec. 2-12.1. Part day child care facility.
<p>"Part day child care facility" has the meaning ascribed to it in Section 2.10 of the Child Care Act of 1969.</p><p>(Source: P.A. 96-556, eff. 1-1-10.)</p>### (720 ILCS 5/2-13) (from Ch. 38, par. 2-13)
## Sec. 2-13. "Peace officer".
<p>"Peace officer" means (i) any person who by virtue of his office or public employment is vested by law with a duty to maintain public order or to make arrests for offenses, whether that duty extends to all offenses or is limited to specific offenses, or (ii) any person who, by statute, is granted and authorized to exercise powers similar to those conferred upon any peace officer employed by a law enforcement agency of this State.</p><p>For purposes of Sections concerning unlawful use of weapons, for the purposes of assisting an Illinois peace officer in an arrest, or when the commission of any offense under Illinois law is directly observed by the person, and statutes involving the false personation of a peace officer, false personation of a peace officer while carrying a deadly weapon, false personation of a peace officer in attempting or committing a felony, and false personation of a peace officer in attempting or committing a forcible felony, then officers, agents, or employees of the federal government commissioned by federal statute to make arrests for violations of federal criminal laws shall be considered "peace officers" under this Code, including, but not limited to, all criminal investigators of:</p><p class='paragraph'>\(1) the United States Department of Justice, the Federal Bureau of Investigation, and the Drug Enforcement Administration and all United States Marshals or Deputy United States Marshals whose duties involve the enforcement of federal criminal laws;</p><p class='paragraph'>\(1.5) the United States Department of Homeland Security, United States Citizenship and Immigration Services, United States Coast Guard, United States Customs and Border Protection, and United States Immigration and Customs Enforcement;</p><p class='paragraph'>\(2) the United States Department of the Treasury, the Alcohol and Tobacco Tax and Trade Bureau, and the United States Secret Service;</p><p class='paragraph'>\(3) the United States Internal Revenue Service;</p><p class='paragraph'>\(4) the United States General Services Administration;</p><p class='paragraph'>\(5) the United States Postal Service;</p><p class='paragraph'>\(6) (blank); and</p><p class='paragraph'>\(7) the United States Department of Defense.</p><p>(Source: P.A. 102-558, eff. 8-20-21.)</p>### (720 ILCS 5/2-14) (from Ch. 38, par. 2-14)
## Sec. 2-14. "Penal institution".
<p>"Penal institution" means a penitentiary, state farm, reformatory, prison, jail, house of correction, or other institution for the incarceration or custody of persons under sentence for offenses or awaiting trial or sentence for offenses.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-15) (from Ch. 38, par. 2-15)
## Sec. 2-15. "Person".
<p>"Person" means an individual, natural person, public or private corporation, government, partnership, unincorporated association, or other entity.</p><p>(Source: P.A. 97-597, eff. 1-1-12.)</p>### (720 ILCS 5/2-15.5)
## Sec. 2-15.5. "Personally discharged a firearm".
<p>A person is considered to have "personally discharged a firearm" when he or she, while armed with a firearm, knowingly and intentionally fires a firearm causing the ammunition projectile to be forcefully expelled from the firearm.</p><p>(Source: P.A. 91-404, eff. 1-1-00.)</p>### (720 ILCS 5/2-15a) (from Ch. 38, par. 2-15a)
## Sec. 2-15a. "Person with a physical disability".
<p>"Person with a physical disability" means a person who suffers from a permanent and disabling physical characteristic, resulting from disease, injury, functional disorder, or congenital condition.</p><p>(Source: P.A. 99-143, eff. 7-27-15.)</p>### (720 ILCS 5/2-15b)
## Sec. 2-15b.
<p>"Place of worship" means a church, synagogue, mosque, temple, or other building, structure, or place used primarily for religious worship and includes the grounds of a place of worship. </p>
<p>(Source: P.A. 91-360, eff. 7-29-99.)</p>### (720 ILCS 5/2-16) (from Ch. 38, par. 2-16)
## Sec. 2-16. "Prosecution".
<p>"Prosecution" means all legal proceedings by which a person's liability for an offense is determined, commencing with the return of the indictment or the issuance of the information, and including the final disposition of the case upon appeal.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-17) (from Ch. 38, par. 2-17)
## Sec. 2-17. "Public employee".
<p>"Public employee" means a person, other than a public officer, who is authorized to perform any official function on behalf of, and is paid by, the State or any of its political subdivisions.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-18) (from Ch. 38, par. 2-18)
## Sec. 2-18. "Public officer".
<p>"Public officer" means a person who is elected to office pursuant to statute, or who is appointed to an office which is established, and the qualifications and duties of which are prescribed, by statute, to discharge a public duty for the State or any of its political subdivisions.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-19) (from Ch. 38, par. 2-19)
## Sec. 2-19. "Reasonable belief".
<p>"Reasonable belief" or "reasonably believes" means that the person concerned, acting as a reasonable man, believes that the described facts exist.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-19.5)
## Sec. 2-19.5. "School" means a public, private, or parochial elementary or secondary school, community college, college, or university and includes the grounds of a school.
<p>(Source: P.A. 91-360, eff. 7-29-99.)</p>### (720 ILCS 5/2-20) (from Ch. 38, par. 2-20)
## Sec. 2-20. "Solicit".
<p>"Solicit" or "solicitation" means to command, authorize, urge, incite, request, or advise another to commit an offense.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-21) (from Ch. 38, par. 2-21)
## Sec. 2-21. "State".
<p>"State" or "this State" means the State of Illinois, and all land and water in respect to which the State of Illinois has either exclusive or concurrent jurisdiction, and the air space above such land and water. "Other state" means any state or territory of the United States, the District of Columbia and the Commonwealth of Puerto Rico.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/2-22) (from Ch. 38, par. 2-22)
## Sec. 2-22. "Statute".
<p>"Statute" means the Constitution or an Act of the General Assembly of this State.</p><p>(Source: Laws 1961, p. 1983.)</p>