# Article 12b. Sexually Explicit Video Games {.unnumbered}

<p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-1)
## Sec. 12B-1. Short title.
<p>This Article may be cited as the</p><p>Sexually Explicit Video Games Law.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-5)
## Sec. 12B-5. Findings.
<p>The General Assembly finds sexually explicit video games inappropriate for minors and that the State has a compelling interest in assisting parents in protecting their minor children from sexually explicit video games.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-10)
## Sec. 12B-10. Definitions. 
<p>For the purposes of this Article, the following terms have the following meanings:</p><p class='subsection'>\(a) "Video game retailer" means a person who sells or rents video games to the public.</p><p class='subsection'>\(b) "Video game" means an object or device that stores recorded data or instructions, receives data or instructions generated by a person who uses it, and, by processing the data or instructions, creates an interactive game capable of being played, viewed, or experienced on or through a computer, gaming system, console, or other technology.</p><p class='subsection'>\(c) "Minor" means a person under 18 years of age.</p><p class='subsection'>\(d) "Person" includes but is not limited to an individual, corporation, partnership, and association.</p><p class='subsection'>\(e) "Sexually explicit" video games include those that the average person, applying contemporary community standards would find, with respect to minors, is designed to appeal or pander to the prurient interest and depict or represent in a manner patently offensive with respect to minors, an actual or simulated sexual act or sexual contact, an actual or simulated normal or perverted sexual act or a lewd exhibition of the genitals or post-pubescent female breast.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-15)
## Sec. 12B-15. Restricted sale or rental of sexually explicit video games.
<p class='subsection'>\(a) A person who sells, rents, or permits to be sold or rented, any sexually explicit video game to any minor, commits a petty offense for which a fine of $1,000 may be imposed.</p><p class='subsection'>\(b) A person who sells, rents, or permits to be sold or rented any sexually explicit video game via electronic scanner must program the electronic scanner to prompt sales clerks to check identification before the sale or rental transaction is completed. A person who violates this subsection (b) commits a petty offense for which a fine of $1,000 may be imposed.</p><p class='subsection'>\(c) A person may not sell or rent, or permit to be sold or rented, any sexually explicit video game through a self-scanning checkout mechanism. A person who violates this subsection (c) commits a petty offense for which a fine of $1,000 may be imposed.</p><p class='subsection'>\(d) A retail sales clerk shall not be found in violation of this Section unless he or she has complete knowledge that the party to whom he or she sold or rented a sexually explicit video game was a minor and the clerk sold or rented the video game to the minor with the specific intent to do so.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-20)
## Sec. 12B-20. Affirmative defenses.
<p>In any prosecution arising under this Article, it is an affirmative defense:</p><p class='paragraph'>\(1) that the defendant was a family member of the minor for whom the video game was purchased. "Family member" for the purpose of this Section, includes a parent, sibling, grandparent, aunt, uncle, or first cousin;</p><p class='paragraph'>\(2) that the minor who purchased the video game exhibited a draft card, driver's license, birth certificate or other official or apparently official document purporting to establish that the minor was 18 years of age or older, which the defendant reasonably relied on and reasonably believed to be authentic;</p><p class='paragraph'>\(3) for the video game retailer, if the retail sales clerk had complete knowledge that the party to whom he or she sold or rented a violent video game was a minor and the clerk sold or rented the video game to the minor with the specific intent to do so; or</p><p class='paragraph'>\(4) that the video game sold or rented was pre-packaged and rated EC, E10+, E, or T by the Entertainment Software Ratings Board.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-25)
## Sec. 12B-25. Labeling of sexually explicit video games.
<p class='subsection'>\(a) Video game retailers shall label all sexually explicit video games as defined in this Act, with a solid white "18" outlined in black. The "18" shall have dimensions of no less than 2 inches by 2 inches. The "18" shall be displayed on the front face of the video game package.</p><p class='subsection'>\(b) A retailer who fails to comply with this Section is guilty of a petty offense punishable by a fine of $500 for the first 3 violations, and $1,000 for every subsequent violation.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-30)
## Sec. 12B-30. Posting notification of video games rating system.
<p class='subsection'>\(a) A retailer who sells or rents video games shall post a sign that notifies customers that a video game rating system, created by the Entertainment Software Ratings Board, is available to aid in the selection of a game. The sign shall be prominently posted in, or within 5 feet of, the area in which games are displayed for sale or rental, at the information desk if one exists, and at the point of purchase.</p><p class='subsection'>\(b) The lettering of each sign shall be printed, at a minimum, in 36-point type and shall be in black ink against a light colored background, with dimensions of no less than 18 by 24 inches.</p><p class='subsection'>\(c) A retailer's failure to comply with this Section is a petty offense punishable by a fine of $500 for the first 3 violations, and $1,000 for every subsequent violation.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>### (720 ILCS 5/12B-35)
## Sec. 12B-35. Availability of brochure describing rating system.
<p class='subsection'>\(a) A video game retailer shall make available upon request a brochure to customers that explains the Entertainment Software Ratings Board ratings system.</p><p class='subsection'>\(b) A retailer who fails to comply with this Section shall receive the punishment described in subsection (b) of Section 12B-25.</p><p>(Source: P.A. 94-315, eff. 1-1-06 .)</p>