# Article 31a. Interference With Penal Institution {.unnumbered}

### (720 ILCS 5/31A-0.1)
## Sec. 31A-0.1. Definitions.
<p>For the purposes of this Article:</p><p>"Deliver" or "delivery" means the actual, constructive or attempted transfer of possession of an item of contraband, with or without consideration, whether or not there is an agency relationship.</p><p>"Employee" means any elected or appointed officer, trustee or employee of a penal institution or of the governing authority of the penal institution, or any person who performs services for the penal institution pursuant to contract with the penal institution or its governing authority.</p><p>"Item of contraband" means any of the following:</p><p class='subsection'>\(i) "Alcoholic liquor" as that term is defined in Section 1-3.05 of the Liquor Control Act of 1934.</p><p class='subsection'>\(ii) "Cannabis" as that term is defined in subsection (a) of Section 3 of the Cannabis Control Act.</p><p class='subsection'>\(iii) "Controlled substance" as that term is defined in the Illinois Controlled Substances Act.</p><p class='subsection'>\(iii-a) "Methamphetamine" as that term is defined in the Illinois Controlled Substances Act or the Methamphetamine Control and Community Protection Act.</p><p class='subsection'>\(iv) "Hypodermic syringe" or hypodermic needle, or any instrument adapted for use of controlled substances or cannabis by subcutaneous injection.</p><p class='subsection'>\(v) "Weapon" means any knife, dagger, dirk, billy, razor, stiletto, broken bottle, or other piece of glass which could be used as a dangerous weapon. This term includes any of the devices or implements designated in subsections (a)(1), (a)(3) and (a)(6) of Section 24-1 of this Code, or any other dangerous weapon or instrument of like character.</p><p class='subsection'>\(vi) "Firearm" means any device, by whatever name known, which is designed to expel a projectile or projectiles by the action of an explosion, expansion of gas or escape of gas, including but not limited to:</p><p class='subparagraph'>\(A) any pneumatic gun, spring gun, or B-B gun which expels a single globular projectile not exceeding .18 inch in diameter; or</p><p class='subparagraph'>\(B) any device used exclusively for signaling or safety and required as recommended by the United States Coast Guard or the Interstate Commerce Commission; or</p><p class='subparagraph'>\(C) any device used exclusively for the firing of stud cartridges, explosive rivets or industrial ammunition; or</p><p class='subparagraph'>\(D) any device which is powered by electrical charging units, such as batteries, and which fires one or several barbs attached to a length of wire and which, upon hitting a human, can send out current capable of disrupting the person's nervous system in such a manner as to render him or her incapable of normal functioning, commonly referred to as a stun gun or taser.</p><p class='subsection'>\(vii) "Firearm ammunition" means any self-contained cartridge or shotgun shell, by whatever name known, which is designed to be used or adaptable to use in a firearm, including but not limited to:</p><p class='subparagraph'>\(A) any ammunition exclusively designed for use with a device used exclusively for signaling or safety and required or recommended by the United States Coast Guard or the Interstate Commerce Commission; or</p><p class='subparagraph'>\(B) any ammunition designed exclusively for use with a stud or rivet driver or other similar industrial ammunition.</p><p class='subsection'>\(viii) "Explosive" means, but is not limited to, bomb, bombshell, grenade, bottle or other container containing an explosive substance of over one-quarter ounce for like purposes such as black powder bombs and Molotov cocktails or artillery projectiles.</p><p class='subsection'>\(ix) "Tool to defeat security mechanisms" means, but is not limited to, handcuff or security restraint key, tool designed to pick locks, popper, or any device or instrument used to or capable of unlocking or preventing from locking any handcuff or security restraints, doors to cells, rooms, gates or other areas of the penal institution.</p><p class='subsection'>\(x) "Cutting tool" means, but is not limited to, hacksaw blade, wirecutter, or device, instrument or file capable of cutting through metal.</p><p class='subsection'>\(xi) "Electronic contraband" for the purposes of Section 31A-1.1 of this Article means, but is not limited to, any electronic, video recording device, computer, or cellular communications equipment, including, but not limited to, cellular telephones, cellular telephone batteries, videotape recorders, pagers, computers, and computer peripheral equipment brought into or possessed in a penal institution without the written authorization of the Chief Administrative Officer. "Electronic contraband" for the purposes of Section 31A-1.2 of this Article, means, but is not limited to, any electronic, video recording device, computer, or cellular communications equipment, including, but not limited to, cellular telephones, cellular telephone batteries, videotape recorders, pagers, computers, and computer peripheral equipment.</p><p>"Penal institution" means any penitentiary, State farm, reformatory, prison, jail, house of correction, police detention area, half-way house or other institution or place for the incarceration or custody of persons under sentence for offenses awaiting trial or sentence for offenses, under arrest for an offense, a violation of probation, a violation of parole, a violation of aftercare release, or a violation of mandatory supervised release, or awaiting a hearing on the setting of conditions of pretrial release or preliminary hearing; provided that where the place for incarceration or custody is housed within another public building this Article shall not apply to that part of the building unrelated to the incarceration or custody of persons.</p><p>(Source: P.A. 101-652, eff. 1-1-23 .)</p>### (720 ILCS 5/31A-1.1) (from Ch. 38, par. 31A-1.1)
## Sec. 31A-1.1. Bringing Contraband into a Penal Institution; Possessing Contraband in a Penal Institution.
<p class='subsection'>\(a) A person commits bringing contraband into a penal institution when he or she knowingly and without authority of any person designated or authorized to grant this authority (1) brings an item of contraband into a penal institution or (2) causes another to bring an item of contraband into a penal institution or (3) places an item of contraband in such proximity to a penal institution as to give an inmate access to the contraband.</p><p class='subsection'>\(b) A person commits possessing contraband in a penal institution when he or she knowingly possesses contraband in a penal institution, regardless of the intent with which he or she possesses it.</p><p class='subsection'>\(c) (Blank).</p><p class='subsection'>\(d) Sentence.</p><p class='paragraph'>\(1) Bringing into or possessing alcoholic liquor in a penal institution is a Class 4 felony.</p><p class='paragraph'>\(2) Bringing into or possessing cannabis in a penal institution is a Class 3 felony.</p><p class='paragraph'>\(3) Bringing into or possessing any amount of a controlled substance classified in Schedules III, IV or V of Article II of the Illinois Controlled Substances Act in a penal institution is a Class 2 felony.</p><p class='paragraph'>\(4) Bringing into or possessing any amount of a controlled substance classified in Schedules I or II of Article II of the Illinois Controlled Substances Act in a penal institution is a Class 1 felony.</p><p class='paragraph'>\(5) Bringing into or possessing a hypodermic syringe in a penal institution is a Class 1 felony.</p><p class='paragraph'>\(6) Bringing into or possessing a weapon, tool to defeat security mechanisms, cutting tool, or electronic contraband in a penal institution is a Class 1 felony.</p><p class='paragraph'>\(7) Bringing into or possessing a firearm, firearm ammunition, or explosive in a penal institution is a Class X felony.</p><p class='subsection'>\(e) It shall be an affirmative defense to subsection (b), that the possession was specifically authorized by rule, regulation, or directive of the governing authority of the penal institution or order issued under it.</p><p class='subsection'>\(f) It shall be an affirmative defense to subsection (a)(1) and subsection (b) that the person bringing into or possessing contraband in a penal institution had been arrested, and that person possessed the contraband at the time of his or her arrest, and that the contraband was brought into or possessed in the penal institution by that person as a direct and immediate result of his or her arrest.</p><p class='subsection'>\(g) Items confiscated may be retained for use by the Department of Corrections or disposed of as deemed appropriate by the Chief Administrative Officer in accordance with Department rules or disposed of as required by law.</p><p>(Source: P.A. 97-1108, eff. 1-1-13; 98-756, eff. 7-16-14.)</p>### (720 ILCS 5/31A-1.2) (from Ch. 38, par. 31A-1.2)
## Sec. 31A-1.2. Unauthorized bringing of contraband into a penal institution by an employee; unauthorized possessing of contraband in a penal institution by an employee; unauthorized delivery of contraband in a penal institution by an employee.
<p class='subsection'>\(a) A person commits unauthorized bringing of contraband into a penal institution by an employee when a person who is an employee knowingly and without authority of any person designated or authorized to grant this  authority:</p><p class='paragraph'>\(1) brings or attempts to bring an item of contraband into a penal institution, or</p><p class='paragraph'>\(2) causes or permits another to bring an item of contraband into a penal institution.</p><p class='subsection'>\(b) A person commits unauthorized possession of contraband in a penal institution by an employee when a person who is an employee knowingly and without authority of any person designated or authorized to grant this  authority possesses an item of contraband in a penal institution, regardless of the intent with which he or she possesses it.</p><p class='subsection'>\(c) A person commits unauthorized delivery of contraband in a penal institution by an employee when a person who is an employee knowingly and without authority of any person designated or authorized to grant this authority:</p><p class='paragraph'>\(1) delivers or possesses with intent to deliver an item of contraband to any inmate of a penal institution, or</p><p class='paragraph'>\(2) conspires to deliver or solicits the delivery of an item of contraband to any inmate of a penal institution, or</p><p class='paragraph'>\(3) causes or permits the delivery of an item of contraband to any inmate of a penal institution, or</p><p class='paragraph'>\(4) permits another person to attempt to deliver an item of contraband to any inmate of a penal institution.</p><p class='subsection'>\(d) For a violation of subsection (a) or (b) involving a cellular telephone or cellular telephone battery, the defendant must intend to provide the cellular telephone or cellular telephone battery to any inmate in a penal institution, or to use the cellular telephone or cellular telephone battery at the direction of an inmate or for the benefit of any inmate of a penal institution.</p><p class='subsection'>\(e) Sentence.</p><p class='paragraph'>\(1) A violation of paragraphs (a) or (b) of this</p><p>Section involving alcohol is a Class 4 felony. A violation of paragraph (a) or (b) of this Section involving cannabis is a Class 2 felony. A violation of paragraph (a) or (b) involving any amount of a controlled substance classified in Schedules III, IV or V of Article II of the Illinois Controlled Substances Act is a Class 1 felony. A violation of paragraph (a) or (b) of this Section involving any amount of a controlled substance classified in Schedules I or II of Article II of the Illinois Controlled Substances Act is a Class X felony. A violation of paragraph (a) or (b) involving a hypodermic syringe is a Class X felony. A violation of paragraph (a) or (b) involving a weapon, tool to defeat security mechanisms, cutting tool, or electronic contraband is a Class 1 felony. A violation of paragraph (a) or (b) involving a firearm, firearm ammunition, or explosive is a Class X felony.</p><p class='paragraph'>\(2) A violation of paragraph (c) of this Section involving alcoholic liquor is a Class 3 felony. A violation of paragraph (c) involving cannabis is a Class 1 felony. A violation of paragraph (c) involving any amount of a controlled substance classified in Schedules III, IV or V of Article II of the Illinois Controlled Substances Act is a Class X felony. A violation of paragraph (c) involving any amount of a controlled substance classified in Schedules I or II of Article II of the Illinois Controlled Substances Act is a Class X felony for which the minimum term of imprisonment shall be 8 years. A violation of paragraph (c) involving a hypodermic syringe is a Class X felony for which the minimum term of imprisonment shall be 8 years. A violation of paragraph (c) involving a weapon, tool to defeat security mechanisms, cutting tool, or electronic contraband is a Class X felony for which the minimum term of imprisonment shall be 10 years. A violation of paragraph (c) involving a firearm, firearm ammunition, or explosive is a Class X felony for which the minimum term of imprisonment shall be 12 years.</p><p class='subsection'>\(f) Items confiscated may be retained for use by the Department of Corrections or disposed of as deemed appropriate by the Chief Administrative Officer in accordance with Department rules or disposed of as required by law.</p><p class='subsection'>\(g) For a violation of subsection (a) or (b) involving alcoholic liquor, a weapon, firearm, firearm ammunition, tool to defeat security mechanisms, cutting tool, or electronic contraband, the items shall not be considered to be in a penal institution when they are secured in an employee's locked, private motor vehicle parked on the grounds of a penal institution.</p><p>(Source: P.A. 96-328, eff. 8-11-09; 96-1112, eff. 1-1-11; 96-1325, eff. 7-27-10; 97-333, eff. 8-12-11; 97-1108, eff. 1-1-13.)</p>