# Article 19. Burglary {.unnumbered}

### (720 ILCS 5/19-1) (from Ch. 38, par. 19-1)
## Sec. 19-1. Burglary.
<p class='subsection'>\(a) A person commits burglary when without authority he or she knowingly enters or without authority remains within a building, housetrailer, watercraft, aircraft, motor vehicle, railroad car, freight container, or any part thereof, with intent to commit therein a felony or theft. This offense shall not include the offenses set out in Section 4-102 of the Illinois Vehicle Code.</p><p class='subsection'>\(b) Sentence.</p><p>Burglary committed in, and without causing damage to, a watercraft, aircraft, motor vehicle, railroad car, freight container, or any part thereof is a Class 3 felony. Burglary committed in a building, housetrailer, or any part thereof or while causing damage to a watercraft, aircraft, motor vehicle, railroad car, freight container, or any part thereof is a Class 2 felony. A burglary committed in a school, day care center, day care home, group day care home, or part day child care facility, or place of worship is a Class 1 felony, except that this provision does not apply to a day care center, day care home, group day care home, or part day child care facility operated in a private residence used as a dwelling.</p><p class='subsection'>\(c) Regarding penalties prescribed in subsection (b) for violations committed in a day care center, day care home, group day care home, or part day child care facility, the time of day, time of year, and whether children under 18 years of age were present in the day care center, day care home, group day care home, or part day child care facility are irrelevant.</p><p>(Source: P.A. 102-546, eff. 1-1-22 .)</p>### (720 ILCS 5/19-2) (from Ch. 38, par. 19-2)
## Sec. 19-2. Possession of burglary tools.
<p class='subsection'>\(a) A person commits possession of burglary tools when he or she possesses any key, tool, instrument, device, or any explosive, suitable for use in breaking into a building, housetrailer, watercraft, aircraft, motor vehicle, railroad car, or any depository designed for the safekeeping of property, or any part thereof, with intent to enter that place and with intent to commit therein a felony or theft. The trier of fact may infer from the possession of a key designed for lock bumping an intent to commit a felony or theft; however, this inference does not apply to any peace officer or other employee of a law enforcement agency, or to any person or agency licensed under the Private Detective, Private Alarm, Private Security, Fingerprint Vendor, and Locksmith Act of 2004. For the purposes of this Section, "lock bumping" means a lock picking technique for opening a pin tumbler lock using a specially-crafted bumpkey.</p><p class='subsection'>\(a-5) A person also commits possession of burglary tools when he or she, knowingly and with the intent to enter the motor vehicle and with the intent to commit therein a felony or theft, possesses a device designed to:</p><p class='paragraph'>\(1) unlock or start a motor vehicle without the use or possession of the key to the motor vehicle; or</p><p class='paragraph'>\(2) capture or duplicate a signal from the key fob of a motor vehicle to unlock or start the motor vehicle without the use or possession of the key to the motor vehicle.</p><p class='subsection'>\(b) Sentence. Possession of burglary tools is a Class 4 felony.</p><p>(Source: P.A. 102-903, eff. 1-1-23 .)</p>### (720 ILCS 5/19-2.5)
## Sec. 19-2.5. Unlawful sale of burglary tools.
<p class='subsection'>\(a) For the purposes of this Section:</p><p>"Lock bumping" means a lock picking technique for opening a pin tumbler lock using a specially-crafted bumpkey.</p><p>"Motor vehicle" has the meaning ascribed to it in the</p><p>Illinois Vehicle Code.</p><p class='subsection'>\(b) A person commits the offense of unlawful sale of burglary tools when he or she knowingly sells or transfers any key, including a key designed for lock bumping, or a lock pick specifically manufactured or altered for use in breaking into a building, housetrailer, watercraft, aircraft, motor vehicle, railroad car, or any depository designed for the safekeeping of property, or any part of that property.</p><p class='subsection'>\(c) This Section does not apply to the sale or transfer of any item described in subsection (b) to any peace officer or other employee of a law enforcement agency, or to any person or agency licensed as a locksmith under the Private Detective, Private Alarm, Private Security, Fingerprint Vendor, and Locksmith Act of 2004, or to any person engaged in the business of towing vehicles, or to any person engaged in the business of lawful repossession of property who possesses a valid Repossessor-ICC Authorization Card.</p><p class='subsection'>\(d) Sentence. Unlawful sale of burglary tools is a Class 4 felony.</p><p>(Source: P.A. 96-1307, eff. 1-1-11.)</p>### (720 ILCS 5/19-3) (from Ch. 38, par. 19-3)
## Sec. 19-3. Residential burglary.
<p class='subsection'>\(a) A person commits residential burglary when he or she knowingly and without authority enters or knowingly and without authority remains within the dwelling place of another, or any part thereof, with the intent to commit therein a felony or theft. This offense includes the offense of burglary as defined in Section 19-1.</p><p class='subsection'>\(a-5) A person commits residential burglary when he or she falsely represents himself or herself, including but not limited to falsely representing himself or herself to be a representative of any unit of government or a construction, telecommunications, or utility company, for the purpose of gaining entry to the dwelling place of another, with the intent to commit therein a felony or theft or to facilitate the commission therein of a felony or theft by another.</p><p class='subsection'>\(b) Sentence. Residential burglary is a Class 1 felony.</p><p>(Source: P.A. 96-1113, eff. 1-1-11; 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/19-4) (from Ch. 38, par. 19-4)
## Sec. 19-4. Criminal trespass to a residence.
<p class='subsection'>\(a) (1) A person commits criminal trespass to a residence when, without authority, he or she knowingly enters or remains within any residence, including a house trailer that is the dwelling place of another.</p><p class='paragraph'>\(2) A person commits criminal trespass to a residence when, without authority, he or she knowingly enters the residence of another and knows or has reason to know that one or more persons is present or he or she knowingly enters the residence of another and remains in the residence after he or she knows or has reason to know that one or more persons is present.</p><p class='subsection'>\(a-5) For purposes of this Section, in the case of a multi-unit residential building or complex, "residence" shall only include the portion of the building or complex which is the actual dwelling place of any person and shall not include such places as common recreational areas or lobbies.</p><p class='subsection'>\(b) Sentence.</p><p class='paragraph'>\(1) Criminal trespass to a residence under paragraph</p><p class='paragraph'>\(1) of subsection (a) is a Class A misdemeanor.</p><p class='paragraph'>\(2) Criminal trespass to a residence under paragraph</p><p class='paragraph'>\(2) of subsection (a) is a Class 4 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13; 98-756, eff. 7-16-14.)</p>### (720 ILCS 5/19-5) (from Ch. 38, par. 19-5)
## Sec. 19-5. Criminal fortification of a residence or building.
<p class='subsection'>\(a) A person commits criminal fortification of a residence or building when, with the intent to prevent the lawful entry of a law enforcement officer or another, he or she maintains a residence or building in a fortified condition, knowing that the residence or building is used for the unlawful manufacture, storage with intent to deliver or manufacture, delivery, or trafficking of cannabis, controlled substances, or methamphetamine as defined in the Cannabis Control Act, the Illinois Controlled Substances Act, or the Methamphetamine Control and Community Protection Act.</p><p class='subsection'>\(b) "Fortified condition" means preventing or impeding entry through the use of steel doors, wooden planking, crossbars, alarm systems, dogs, video surveillance, motion sensing devices, booby traps, or other similar means. If video surveillance is the sole component of the fortified condition, the video surveillance must be with the intent to alert an occupant to the presence of a law enforcement officer for the purpose of interfering with the official duties of a law enforcement officer, allowing removal or destruction of evidence, or facilitating the infliction of harm to a law enforcement officer. For the purposes of this Section, "booby trap" means any device, including but not limited to any explosive device, designed to cause physical injury or the destruction of evidence, when triggered by an act of a person approaching, entering, or moving through a structure.</p><p class='subsection'>\(c) Sentence. Criminal fortification of a residence or building is a Class 3 felony.</p><p class='subsection'>\(d) This Section does not apply to the fortification of a residence or building used in the manufacture of methamphetamine as described in Sections 10 and 15 of the Methamphetamine Control and Community Protection Act.</p><p>(Source: P.A. 98-897, eff. 1-1-15 .)</p>### (720 ILCS 5/19-6)
<p class='subsection'>\(was 720 ILCS 5/12-11)</p>## Sec. 19-6. Home Invasion.
<p class='subsection'>\(a) A person who is not a peace officer acting in the line of duty commits home invasion when without authority he or she knowingly enters the dwelling place of another when he or she knows or has reason to know that one or more persons is present or he or she knowingly enters the dwelling place of another and remains in the dwelling place until he or she knows or has reason to know that one or more persons is present or who falsely represents himself or herself, including but not limited to, falsely representing himself or herself to be a representative of any unit of government or a construction, telecommunications, or utility company, for the purpose of gaining entry to the dwelling place of another when he or she knows or has reason to know that one or more persons are present and</p><p class='paragraph'>\(1) While armed with a dangerous weapon, other than a firearm, uses force or threatens the imminent use of force upon any person or persons within the dwelling place whether or not injury occurs, or</p><p class='paragraph'>\(2) Intentionally causes any injury, except as provided in subsection (a)(5), to any person or persons within the dwelling place, or</p><p class='paragraph'>\(3) While armed with a firearm uses force or threatens the imminent use of force upon any person or persons within the dwelling place whether or not injury occurs, or</p><p class='paragraph'>\(4) Uses force or threatens the imminent use of force upon any person or persons within the dwelling place whether or not injury occurs and during the commission of the offense personally discharges a firearm, or</p><p class='paragraph'>\(5) Personally discharges a firearm that proximately causes great bodily harm, permanent disability, permanent disfigurement, or death to another person within the dwelling place, or</p><p class='paragraph'>\(6) Commits, against any person or persons within that dwelling place, a violation of Section 11-1.20, 11-1.30, 11-1.40, 11-1.50, or 11-1.60 of this Code.</p><p class='subsection'>\(b) It is an affirmative defense to a charge of home invasion that the accused who knowingly enters the dwelling place of another and remains in the dwelling place until he or she knows or has reason to know that one or more persons is present either immediately leaves the premises or surrenders to the person or persons lawfully present therein without either attempting to cause or causing serious bodily injury to any person present therein.</p><p class='subsection'>\(c) Sentence. Home invasion in violation of subsection (a)(1), (a)(2) or (a)(6) is a Class X felony. A violation of subsection (a)(3) is a Class X felony for which 15 years shall be added to the term of imprisonment imposed by the court. A violation of subsection (a)(4) is a Class X felony for which 20 years shall be added to the term of imprisonment imposed by the court. A violation of subsection (a)(5) is a Class X felony for which 25 years or up to a term of natural life shall be added to the term of imprisonment imposed by the court.</p><p class='subsection'>\(d) For purposes of this Section, "dwelling place of another" includes a dwelling place where the defendant maintains a tenancy interest but from which the defendant has been barred by a divorce decree, judgment of dissolution of marriage, order of protection, or other court order.</p><p>(Source: P.A. 96-1113, eff. 1-1-11; 96-1551, eff. 7-1-11; 97-1108, eff. 1-1-13; 97-1150, eff. 1-25-13.)</p>