# Article 32. Interference With Judicial Procedure {.unnumbered}

### (720 ILCS 5/32-1) (from Ch. 38, par. 32-1)
## Sec. 32-1. Compounding a crime.
<p class='subsection'>\(a) A person commits compounding a crime when he or she knowingly receives or offers to another any consideration for a promise not to prosecute or aid in the prosecution of an offender.</p><p class='subsection'>\(b) Sentence. Compounding a crime is a petty offense.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/32-2) (from Ch. 38, par. 32-2)
## Sec. 32-2. Perjury.
<p class='subsection'>\(a) A person commits perjury when, under oath or affirmation, in a proceeding or in any other matter where by law the oath or affirmation is required, he or she makes a false statement, material to the issue or point in question, knowing the statement is false.</p><p class='subsection'>\(b) Proof of Falsity.</p><p>An indictment or information for perjury alleging that the offender, under oath, has knowingly made contradictory statements, material to the issue or point in question, in the same or in different proceedings, where the oath or affirmation is required, need not specify which statement is false. At the trial, the prosecution need not establish which statement is false.</p><p class='subsection'>\(c) Admission of Falsity.</p><p>Where the contradictory statements are made in the same continuous trial, an admission by the offender in that same continuous trial of the falsity of a contradictory statement shall bar prosecution therefor under any provisions of this Code.</p><p class='subsection'>\(d) A person shall be exempt from prosecution under subsection (a) of this Section if he or she is a peace officer who uses a false or fictitious name in the enforcement of the criminal laws, and this use is approved in writing as provided in Section 10-1 of "The Liquor Control Act of 1934", as amended, Section 5 of "An Act in relation to the use of an assumed name in the conduct or transaction of business in this State", approved July 17, 1941, as amended, or Section 2605-200 of the Illinois State Police Law. However, this exemption shall not apply to testimony in judicial proceedings where the identity of the peace officer is material to the issue, and he or she is ordered by the court to disclose his or her identity.</p><p class='subsection'>\(e) Sentence.</p><p>Perjury is a Class 3 felony.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/32-3) (from Ch. 38, par. 32-3)
## Sec. 32-3. Subornation of perjury.
<p class='subsection'>\(a) A person commits subornation of perjury when he or she knowingly procures or induces another to make a statement in violation of Section 32-2 which the person knows to be false.</p><p class='subsection'>\(b) Sentence.</p><p>Subornation of perjury is a Class 4 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/32-4) (from Ch. 38, par. 32-4)
## Sec. 32-4. Communicating with jurors and witnesses.
<p class='subsection'>\(a) A person who, with intent to influence any person whom he believes has been summoned as a juror, regarding any matter which is or may be brought before such juror, communicates, directly or indirectly, with such juror otherwise than as authorized by law commits a Class 4 felony.</p><p class='subsection'>\(b) A person who, with intent to deter any party or witness from testifying freely, fully and truthfully to any matter pending in any court, or before a Grand Jury, Administrative agency or any other State or local governmental unit, forcibly detains such party or witness, or communicates, directly or indirectly, to such party or witness any knowingly false information or a threat of injury or damage to the property or person of any individual or offers or delivers or threatens to withhold money or another thing of value to any individual commits a Class 3 felony.</p><p class='subsection'>\(c) A person who violates the Juror Protection Act commits a Class 4 felony.</p><p>(Source: P.A. 94-186, eff. 1-1-06.)</p>### (720 ILCS 5/32-4a) (from Ch. 38, par. 32-4a)
## Sec. 32-4a. Harassment of representatives for the child, jurors, witnesses and others.
<p class='subsection'>\(a) A person who, with intent to harass or annoy one who has served or is serving or who is a family member of a person who has served or is serving (1) as a juror because of the verdict returned by the jury in a pending legal proceeding or the participation of the juror in the verdict or (2) as a witness, or who may be expected to serve as a witness in a pending legal proceeding, or who was expected to serve as a witness but who did not serve as a witness because the charges against the defendant were dismissed or because the defendant pleaded guilty to the charges against him or her, because of the testimony or potential testimony of the witness or person who may be expected or may have been expected to serve as a witness, communicates directly or indirectly with the juror, witness or person who may be expected or may have been expected to serve as a witness, or family member of a juror or witness or person who may be expected or may have been expected to serve as a witness in such manner as to produce mental anguish or emotional distress or who conveys a threat of injury or damage to the property or person of any juror, witness or person who may be expected or may have been expected to serve as a witness, or family member of the juror or witness or person who may be expected or may have been expected to serve as a witness commits a Class 2 felony.</p><p class='subsection'>\(b) A person who, with intent to harass or annoy one who has served or is serving or who is a family member of a person who has served or is serving as a representative for the child, appointed under Section 506 of the Illinois Marriage and Dissolution of Marriage Act or Section 2-502 of the Code of Civil Procedure, because of the representative service of that capacity, communicates directly or indirectly with the representative or a family member of the representative in such manner as to produce mental anguish or emotional distress or who conveys a threat of injury or damage to the property or person of any representative or a family member of the representative commits a Class A misdemeanor.</p><p class='subsection'>\(c) For purposes of this Section, "family member" means a spouse, parent, child, stepchild or other person related by blood or by present marriage, a person who has, or allegedly has a child in common, and a person who shares or allegedly shares a blood relationship through a child.</p><p>(Source: P.A. 93-108, eff. 1-1-04; 93-818, eff. 7-27-04.)</p>### (720 ILCS 5/32-4b) (from Ch. 38, par. 32-4b)
## Sec. 32-4b. Bribery for excuse from jury duty.
<p class='subsection'>\(a) A jury commissioner or any other person acting on behalf of a jury commissioner commits bribery for excuse from jury duty, when he or she knowingly requests, solicits, suggests, or accepts financial compensation or any other form of consideration in exchange for a promise to excuse or for excusing any person from jury duty.</p><p class='subsection'>\(b) Sentence. Bribery for excuse from jury duty is a Class 3 felony. In addition to any other penalty provided by law, a jury commissioner convicted under this Section shall forfeit the performance bond required by Section 1 of "An Act in relation to jury commissioners and authorizing judges to appoint such commissioners and to make rules concerning their powers and duties", approved June 15, 1887, as amended, and shall be excluded from further service as a jury commissioner.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/32-4c)
## Sec. 32-4c. Witnesses; prohibition on accepting payments before judgment or verdict.
<p class='subsection'>\(a) A person who, after the commencement of a criminal prosecution, has been identified in the criminal discovery process as a person who may be called as a witness in a criminal proceeding shall not knowingly accept or receive, directly or indirectly, any payment or benefit in consideration for providing information obtained as a result of witnessing an event or occurrence or having personal knowledge of certain facts in relation to the criminal proceeding.</p><p class='subsection'>\(b) Sentence. A violation of this Section is a Class B misdemeanor for which the court may impose a fine not to exceed 3 times the amount of compensation requested, accepted, or received.</p><p class='subsection'>\(c) This Section remains applicable until the judgment of the court in the action if the defendant is tried by the court without a jury or the rendering of the verdict by the jury if the defendant is tried by jury in the action.</p><p class='subsection'>\(d) This Section does not apply to any of the following circumstances:</p><p class='paragraph'>\(1) Lawful compensation paid to expert witnesses, investigators, employees, or agents by a prosecutor, law enforcement agency, or an attorney employed to represent a person in a criminal matter.</p><p class='paragraph'>\(2) Lawful compensation or benefits provided to an informant by a prosecutor or law enforcement agency.</p><p class='paragraph'>\(2.5) Lawful compensation or benefits, or both, provided to an informant under a local anti-crime program, such as Crime Stoppers, We-Tip, and similar programs designed to solve crimes or that foster the detection of crime and encourage persons through the programs and otherwise to come forward with information about criminal activity.</p><p class='paragraph'>\(2.6) Lawful compensation or benefits, or both, provided by a private individual to another private individual as a reward for information leading to the arrest and conviction of specified offenders.</p><p class='paragraph'>\(3) Lawful compensation paid to a publisher, editor, reporter, writer, or other person connected with or employed by a newspaper, magazine, television or radio station or any other publishing or media outlet for disclosing information obtained from another person relating to an offense.</p><p class='subsection'>\(e) For purposes of this Section, "publishing or media outlet" means a news gathering organization that sells or distributes news to newspapers, television, or radio stations, or a cable or broadcast television or radio network that disseminates news and information.</p><p class='subsection'>\(f) The person identified as a witness may receive written notice from counsel for either the prosecution or defense of the fact that he or she has been identified as a witness who may be called in a criminal proceeding and his or her responsibilities and possible penalties under this Section. This Section shall be applicable only if the witness received the written notice referred to in this subsection.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/32-4d)
## Sec. 32-4d. Payment of jurors by parties prohibited.
<p class='subsection'>\(a) After a verdict has been rendered in a civil or criminal case, a person who was a plaintiff or defendant in the case may not knowingly offer or pay an award or other fee to a juror who was a member of the jury that rendered the verdict in the case.</p><p class='subsection'>\(b) After a verdict has been rendered in a civil or criminal case, a member of the jury that rendered the verdict may not knowingly accept an award or fee from the plaintiff or defendant in that case.</p><p class='subsection'>\(c) Sentence. A violation of this Section is a Class A misdemeanor.</p><p class='subsection'>\(d) This Section does not apply to the payment of a fee or award to a person who was a juror for purposes unrelated to the jury's verdict or to the outcome of the case.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/32-4e)
## Sec. 32-4e. Interfering with the duties of a judicial officer.
<p class='subsection'>\(a) A person may not give or offer to give benefits, promises, pecuniary compensation, or any other form of compensation, either directly or indirectly, to a judicial officer or a member of the judicial officer's immediate family with the intent to:</p><p class='paragraph'>\(1) induce such judicial officer to do, or fail to do, any act in violation of the lawful execution of his or her official duties; or</p><p class='paragraph'>\(2) induce such judicial officer to commit or aid in the commission of any fraud, or to collude in, allow, or make available the opportunity for the commission of any fraud on the State of Illinois.</p><p class='subsection'>\(b) A person may not give or offer to give benefits, promises, pecuniary compensation, or any other form of compensation, either directly or indirectly, to court employees and staff with the intent to interfere with the administration of the judicial process.</p><p class='subsection'>\(c) Sentence. A person who violates this Section commits a Class 2 felony.</p><p class='subsection'>\(d) Definitions. For purposes of this Section:</p><p>"Judicial officer" means a justice, judge, associate judge, or magistrate of a court of the United States of America or the State of Illinois.</p><p>"Immediate family" means a judicial officer's spouse or children.</p><p>(Source: P.A. 95-1035, eff. 6-1-09 .)</p>### (720 ILCS 5/32-4f)
## Sec. 32-4f. Retaliating against a Judge by false claim, slander of title, or malicious recording of fictitious liens.
<p>A person who files or causes to be filed, in any public record or in any private record that is generally available to the public, any false lien or encumbrance against the real or personal property of a Supreme, Appellate, Circuit, or Associate Judge of the State of Illinois with knowledge that such lien or encumbrance is false or contains any materially false, fictitious, or fraudulent statement or representation, and with the intent of retaliating against that Judge for the performance or non-performance of an official judicial duty, is guilty of a violation of this Section. A person is guilty of a Class A misdemeanor for a first offense and a Class 4 felony for a second or subsequent offense.</p><p>(Source: P.A. 95-1035, eff. 6-1-09 .)</p>### (720 ILCS 5/32-5) (from Ch. 38, par. 32-5)
## Sec. 32-5. (Repealed).
<p>(Source: P.A. 97-219, eff. 1-1-12. Repealed by P.A. 96-1551, eff. 7-1-11.)</p>### (720 ILCS 5/32-5.1) (from Ch. 38, par. 32-5.1)
## Sec. 32-5.1. (Repealed).
<p>(Source: P.A. 94-730, eff. 4-17-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.1-1)
## Sec. 32-5.1-1. (Repealed).
<p>(Source: P.A. 94-730, eff. 4-17-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.2) (from Ch. 38, par. 32-5.2)
## Sec. 32-5.2. (Repealed).
<p>(Source: P.A. 95-331, eff. 8-21-07. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.2-5)
## Sec. 32-5.2-5. (Repealed).
<p>(Source: P.A. 94-341, eff. 1-1-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.3)
## Sec. 32-5.3. (Repealed).
<p>(Source: P.A. 88-677, eff. 12-15-94. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.4)
## Sec. 32-5.4. (Repealed).
<p>(Source: P.A. 94-323, eff. 1-1-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.4-1)
## Sec. 32-5.4-1. (Repealed).
<p>(Source: P.A. 94-730, eff. 4-17-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.5)
## Sec. 32-5.5. (Repealed).
<p>(Source: P.A. 94-730, eff. 4-17-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.6)
## Sec. 32-5.6. (Repealed).
<p>(Source: P.A. 94-323, eff. 1-1-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-5.7)
## Sec. 32-5.7. (Repealed).
<p>(Source: P.A. 94-323, eff. 1-1-06. Repealed by P.A. 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/32-6) (from Ch. 38, par. 32-6)
## Sec. 32-6. Performance of unauthorized acts.
<p>A person who performs any of the following acts, knowing that his performance is not authorized by law, commits a Class 4 felony:</p><p class='subsection'>\(a) Conducts a marriage ceremony; or</p><p class='subsection'>\(b) Acknowledges the execution of any document which by law may be recorded; or</p><p class='subsection'>\(c) Becomes a surety for any party in any civil or criminal proceeding, before any court or public officer authorized to accept such surety.</p><p>(Source: P.A. 77-2638)</p>### (720 ILCS 5/32-7) (from Ch. 38, par. 32-7)
## Sec. 32-7. Simulating legal process.
<p class='subsection'>\(a) A person commits simulating legal process when he or she issues or delivers any document which he or she knows falsely purports to be or simulates any civil or criminal process.</p><p class='subsection'>\(b) Sentence. Simulating legal process is a Class B misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/32-8) (from Ch. 38, par. 32-8)
## Sec. 32-8. Tampering with public records.
<p class='subsection'>\(a) A person commits tampering with public records when he or she knowingly, without lawful authority, and with the intent to defraud any party, public officer or entity, alters, destroys, defaces, removes or conceals any public record.</p><p class='subsection'>\(b) (Blank).</p><p class='subsection'>\(c) A judge, circuit clerk or clerk of court, public official or employee, court reporter, or other person commits tampering with public records when he or she knowingly, without lawful authority, and with the intent to defraud any party, public officer or entity, alters, destroys, defaces, removes, or conceals any public record received or held by any judge or by a clerk of any court.</p><p class='subsection'>\(c-5) "Public record" expressly includes, but is not limited to, court records, or documents, evidence, or exhibits filed with the clerk of the court and which have become a part of the official court record, pertaining to any civil or criminal proceeding in any court.</p><p class='subsection'>\(d) Sentence. A violation of subsection (a) is a Class 4 felony. A violation of subsection (c) is a Class 3 felony. Any person convicted under subsection (c) who at the time of the violation was responsible for making, keeping, storing, or reporting the record for which the tampering occurred:</p><p class='paragraph'>\(1) shall forfeit his or her public office or public employment, if any, and shall thereafter be ineligible for both State and local public office and public employment in this State for a period of 5 years after completion of any term of probation, conditional discharge, or incarceration in a penitentiary including the period of mandatory supervised release;</p><p class='paragraph'>\(2) shall forfeit all retirement, pension, and other benefits arising out of public office or public employment as may be determined by the court in accordance with the applicable provisions of the Illinois Pension Code;</p><p class='paragraph'>\(3) shall be subject to termination of any professional licensure or registration in this State as may be determined by the court in accordance with the provisions of the applicable professional licensing or registration laws;</p><p class='paragraph'>\(4) may be ordered by the court, after a hearing in accordance with applicable law and in addition to any other penalty or fine imposed by the court, to forfeit to the State an amount equal to any financial gain or the value of any advantage realized by the person as a result of the offense; and</p><p class='paragraph'>\(5) may be ordered by the court, after a hearing in accordance with applicable law and in addition to any other penalty or fine imposed by the court, to pay restitution to the victim in an amount equal to any financial loss or the value of any advantage lost by the victim as a result of the offense.</p><p>For the purposes of this subsection (d), an offense under subsection (c) committed by a person holding public office or public employment shall be rebuttably presumed to relate to or arise out of or in connection with that public office or public employment.</p><p class='subsection'>\(e) Any party litigant who believes a violation of this Section has occurred may seek the restoration of the court record as provided in the Court Records Restoration Act. Any order of the court denying the restoration of the court record may be appealed as any other civil judgment.</p><p class='subsection'>\(f) When the sheriff or local law enforcement agency having jurisdiction declines to investigate, or inadequately investigates, the court or any interested party, shall notify the Illinois State Police of a suspected violation of subsection (a) or (c), who shall have the authority to investigate, and may investigate, the same, without regard to whether the local law enforcement agency has requested the Illinois State Police to do so.</p><p class='subsection'>\(g) If the State's Attorney having jurisdiction declines to prosecute a violation of subsection (a) or (c), the court or interested party shall notify the Attorney General of the refusal. The Attorney General shall, thereafter, have the authority to prosecute, and may prosecute, the violation, without a referral from the State's Attorney.</p><p class='subsection'>\(h) Prosecution of a violation of subsection (c) shall be commenced within 3 years after the act constituting the violation is discovered or reasonably should have been discovered.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/32-8.1)
## Sec. 32-8.1. Tampering with a certification by a public official.
<p class='subsection'>\(a) A person commits tampering with a certification by a public official when he or she knowingly, without lawful authority, and with the intent to defraud any individual, entity, public officer, or governmental unit, uses a certification or part of a certification by a public official, including but not limited to an apostille, the "great seal of the State of Illinois", or other similar certification, in connection with any document he or she knows or reasonably should know is not the original document for which the public official originally issued the certification.</p><p class='subsection'>\(b) Sentence. Tampering with a certification by a public official is a Class A misdemeanor for a first offense and a Class 4 felony for a second or subsequent offense.</p><p>(Source: P.A. 98-170, eff. 8-5-13.)</p>### (720 ILCS 5/32-9) (from Ch. 38, par. 32-9)
## Sec. 32-9. Tampering with public notice.
<p class='subsection'>\(a) A person commits tampering with public notice when he or she knowingly and without lawful authority alters, destroys, defaces, removes or conceals any public notice, posted according to law, during the time for which the notice was to remain posted.</p><p class='subsection'>\(b) Sentence. Tampering with public notice is a petty offense.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/32-10) (from Ch. 38, par. 32-10)
## Sec. 32-10. Violation of conditions of pretrial release.
<p class='subsection'>\(a) (Blank).</p><p class='subsection'>\(a-5) Any person who knowingly violates a condition of pretrial release by possessing a firearm in violation of his or her conditions of pretrial release commits a Class 4 felony for a first violation and a Class 3 felony for a second or subsequent violation.</p><p class='subsection'>\(b) Whoever, having been released pretrial under conditions for appearance before any court of this State, while charged with a criminal offense in which the victim is a family or household member as defined in Article 112A of the Code of Criminal Procedure of 1963, knowingly violates a condition of that release as set forth in Section 110-10, subsection (d) of the Code of Criminal Procedure of 1963, commits a Class A misdemeanor.</p><p class='subsection'>\(c) Whoever, having been released pretrial for appearance before any court of this State for a felony, Class A misdemeanor or a criminal offense in which the victim is a family or household member as defined in Article 112A of the Code of Criminal Procedure of 1963, is charged with any other felony, Class A misdemeanor, or a criminal offense in which the victim is a family or household member as defined in Article 112A of the Code of Criminal Procedure of 1963 while on this release, must appear before the court and may not be released by law enforcement under 109-1 of the Code of Criminal Procedure of 1963 prior to the court appearance.</p><p class='subsection'>\(d) Nothing in this Section shall interfere with or prevent the exercise by any court of its power to punish for contempt. Any sentence imposed for violation of this Section may be served consecutive to the sentence imposed for the charge for which pretrial release had been granted and with respect to which the defendant has been convicted.</p><p>(Source: P.A. 101-652, eff. 1-1-23; 102-1104, eff. 1-1-23.)</p>### (720 ILCS 5/32-11)
## Sec. 32-11. Barratry.
<p>If a person wickedly and willfully excites and stirs up actions or quarrels between the people of this State with a view to promote strife and contention, he or she is guilty of the petty offense of common barratry; and if he or she is an attorney at law, he or she shall be suspended from the practice of his or her profession, for any time not exceeding 6 months.</p><p>(Source: P.A. 89-234, eff. 1-1-96.)</p>### (720 ILCS 5/32-12)
## Sec. 32-12. Maintenance.
<p>If a person officiously intermeddles in an action that in no way belongs to or concerns that person, by maintaining or assisting either party, with money or otherwise, to prosecute or defend the action, with a view to promote litigation, he or she is guilty of maintenance and upon conviction shall be fined and punished as in cases of common barratry. It is not maintenance for a person to maintain the action of his or her relative or servant, or a poor person out of charity.</p><p>(Source: P.A. 89-234, eff. 1-1-96.)</p>### (720 ILCS 5/32-13)
## Sec. 32-13. Unlawful clouding of title.
<p class='subsection'>\(a) Any person who intentionally records or files or causes to be recorded or filed any document in the office of the recorder or registrar of titles of any county of this State that is a cloud on the title of land in this State, knowing that the theory upon which the purported cloud on title is based is not recognized as a legitimate legal theory by the courts of this State or of the United States, commits the offense of unlawful clouding of title.</p><p class='subsection'>\(b) Unlawful clouding of title is a Class A misdemeanor for a first offense if the cloud on the title has a value that does not exceed $10,000. Unlawful clouding of title is a Class 4 felony if the cloud on the title has a value that exceeds $10,000, or for a second or subsequent offense.</p><p class='subsection'>\(c) In addition to any other sentence that may be imposed, the court shall order any person convicted of a violation of this Section, or placed on supervision for a violation of this Section, to execute a release of the purported cloud on title as may be requested by or on behalf of any person whose property is encumbered or potentially encumbered by the document filed. Irrespective of whether or not a person charged under this Section is convicted of the offense of unlawful clouding of title, when the evidence demonstrates that, as a matter of law, the cloud on title is not a type of cloud recognized or authorized by the courts of this State or the United States, the court shall forthwith direct the recorder or registrar of titles to expunge the cloud.</p><p class='subsection'>\(c-5) This Section does not apply to an attorney licensed to practice law in this State who in good faith files a lien on behalf of his or her client and who in good faith believes that the validity of the lien is supported by statutory law, by a decision of a court of law, or by a good faith argument for an extension, modification, or reversal of existing court decisions relating to the validity of the lien.</p><p class='subsection'>\(d) For purposes of this Section, "cloud on title" or "cloud on the title" means an outstanding claim or encumbrance that, if valid, would affect or impair the title of the owner of an estate in land and on its face has that effect, but can be shown by extrinsic proof to be invalid or inapplicable to that estate.</p><p>(Source: P.A. 98-98, eff. 1-1-14.)</p>### (720 ILCS 5/32-14)
## Sec. 32-14. Unlawful manipulation of a judicial sale.
<p class='subsection'>\(a) A person commits the offense of unlawful manipulation of a judicial sale when he or she knowingly and by any means makes any contract with or engages in any combination or conspiracy with any other person who is, or but for a prior agreement is, a competitor of such person for the purpose of or with the effect of fixing, controlling, limiting, or otherwise manipulating (1) the participation of any person in, or (2) the making of bids, at any judicial sale.</p><p class='subsection'>\(b) Penalties. Unlawful manipulation of a judicial sale is a Class 3 felony. A mandatory fine shall be imposed for a violation, not to exceed $1,000,000 if the violator is a corporation, or, if the violator is any other person, $100,000. A second or subsequent violation is a Class 2 felony.</p><p class='subsection'>\(c) Injunctive and other relief. The State's Attorney shall bring suit in the circuit court to prevent and restrain violations of subsection (a). In such a proceeding, the court shall determine whether a violation has been committed, and shall enter such judgment as it considers necessary to remove the effects of any violation which it finds, and to prevent such violation from continuing or from being renewed in the future. The court, in its discretion, may exercise all powers necessary for this purpose, including, but not limited to, injunction and divestiture of property.</p><p class='subsection'>\(d) Private right of action. Any person who has been injured by a violation of subsection (a) may maintain an action in the Circuit Court for damages, or for an injunction, or both, against any person who has committed such violation. If, in an action for an injunction, the court issues an injunction, the plaintiff shall be awarded costs and reasonable attorney's fees. In an action for damages, the person injured shall be awarded 3 times the amount of actual damages. This State, counties, municipalities, townships, and any political subdivision organized under the authority of this State, and the United States, are considered a person having standing to bring an action under this subsection. Any action for damages under this subsection is forever barred unless commenced within 4 years after the cause of action accrued. In any action for damages under this subsection, the court may, in its discretion, award reasonable fees to the prevailing defendant upon a finding that the plaintiff acted in bad faith, vexatiously, wantonly, or for oppressive reasons.</p><p class='subsection'>\(e) Exclusion from subsequent judicial sales. Any person convicted of a violation of subsection (a) or any similar offense of any state or the United States shall be barred for 5 years from the date of conviction from participating as a bidding entity in any judicial sale. No corporation shall be barred from participating in a judicial sale as a result of a conviction under subsection (a) of any employee or agent of such corporation if the employee so convicted is no longer employed by the corporation and: (1) it has been finally adjudicated not guilty or (2) it demonstrates to the circuit court conducting such judicial sale and the court so finds that the commission of the offense was neither authorized, requested, commanded, nor performed by a director, officer or a high managerial agent in behalf of the corporation as provided in paragraph (2) of subsection (a) of Section 5-4 of this Code.</p><p class='subsection'>\(f) Definitions. As used in this Section, unless the context otherwise requires:</p><p>"Judicial sale" means any sale of real or personal property in accordance with a court order, including, but not limited to, judicial sales conducted pursuant to Section 15-1507 of the Code of Civil Procedure, sales ordered to satisfy judgments under Article XII of the Code of Civil Procedure, and enforcements of delinquent property taxes under Article 21 of the Property Tax Code.</p><p>"Person" means any natural person, or any corporation, partnership, or association of persons.</p><p>(Source: P.A. 100-201, eff. 8-18-17.)</p>### (720 ILCS 5/32-15)
## Sec. 32-15. (Repealed).
<p>(Source: P.A. 101-652, eff. 1-1-23. Repealed by P.A. 102-1104, eff. 1-1-23.)</p>