# Article 8. Solicitation, Conspiracy And Attempt {.unnumbered}

### (720 ILCS 5/8-1) (from Ch. 38, par. 8-1)
## Sec. 8-1. Solicitation and solicitation of murder.
<p class='subsection'>\(a) Solicitation. A person commits the offense of solicitation when, with intent that an offense be committed, other than first degree murder, he or she commands, encourages, or requests another to commit that offense.</p><p class='subsection'>\(b) Solicitation of murder. A person commits the offense of solicitation of murder when he or she commits solicitation with the intent that the offense of first degree murder be committed.</p><p class='subsection'>\(c) Sentence. A person convicted of solicitation may be fined or imprisoned or both not to exceed the maximum provided for the offense solicited, except that the penalty shall not exceed the corresponding maximum limit provided by subparagraph (c) of Section 8-4 of this Code. Solicitation of murder is a Class X felony, and a person convicted of solicitation of murder shall be sentenced to a term of imprisonment of not less than 15 years and not more than 30 years, except that a person convicted of solicitation of murder when the person solicited was a person under the age of 17 years shall be sentenced to a term of imprisonment of not less than 20 years and not more than 60 years.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/8-1.1)
## Sec. 8-1.1. (Repealed).
<p>(Source: P.A. 89-689, eff. 12-31-96. Repealed by P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/8-1.2) (from Ch. 38, par. 8-1.2)
## Sec. 8-1.2. Solicitation of murder for hire.
<p class='subsection'>\(a) A person commits the offense of solicitation of murder for hire when, with the intent that the offense of first degree murder be committed, he or she procures another to commit that offense pursuant to any contract, agreement, understanding, command, or request for money or anything of value.</p><p class='subsection'>\(b) Sentence. Solicitation of murder for hire is a Class X felony, and a person convicted of solicitation of murder for hire shall be sentenced to a term of imprisonment of not less than 20 years and not more than 40 years, except that a person convicted of solicitation of murder for hire when the person solicited was a person under the age of 17 years shall be sentenced to a term of imprisonment of not less than 25 years and not more than 60 years.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/8-2) (from Ch. 38, par. 8-2)
## Sec. 8-2. Conspiracy.
<p class='subsection'>\(a) Elements of the offense. A person commits the offense of conspiracy when, with intent that an offense be committed, he or she agrees with another to the commission of that offense. No person may be convicted of conspiracy to commit an offense unless an act in furtherance of that agreement is alleged and proved to have been committed by him or her or by a co-conspirator.</p><p class='subsection'>\(b) Co-conspirators. It is not a defense to conspiracy that the person or persons with whom the accused is alleged to have conspired:</p><p class='paragraph'>\(1) have not been prosecuted or convicted,</p><p class='paragraph'>\(2) have been convicted of a different offense,</p><p class='paragraph'>\(3) are not amenable to justice,</p><p class='paragraph'>\(4) have been acquitted, or</p><p class='paragraph'>\(5) lacked the capacity to commit an offense.</p><p class='subsection'>\(c) Sentence.</p><p class='paragraph'>\(1) Except as otherwise provided in this subsection or Code, a person convicted of conspiracy to commit:</p><p class='subparagraph'>\(A) a Class X felony shall be sentenced for a Class 1 felony;</p><p class='subparagraph'>\(B) a Class 1 felony shall be sentenced for a Class 2 felony;</p><p class='subparagraph'>\(C) a Class 2 felony shall be sentenced for a Class 3 felony;</p><p class='subparagraph'>\(D) a Class 3 felony shall be sentenced for a Class 4 felony;</p><p class='subparagraph'>\(E) a Class 4 felony shall be sentenced for a Class 4 felony; and</p><p class='subparagraph'>\(F) a misdemeanor may be fined or imprisoned or both not to exceed the maximum provided for the offense that is the object of the conspiracy.</p><p class='paragraph'>\(2) A person convicted of conspiracy to commit any of the following offenses shall be sentenced for a Class X felony:</p>### (A) aggravated insurance fraud conspiracy when the person is an organizer of the conspiracy (720 ILCS 5/46-4); or
### (B) aggravated governmental entity insurance fraud conspiracy when the person is an organizer of the conspiracy (720 ILCS 5/46-4).
<p class='paragraph'>\(3) A person convicted of conspiracy to commit any of the following offenses shall be sentenced for a Class 1 felony:</p>### (A) first degree murder (720 ILCS 5/9-1); or
### (B) aggravated insurance fraud (720 ILCS 5/46-3) or aggravated governmental insurance fraud (720 ILCS 5/46-3).
### (4) A person convicted of conspiracy to commit insurance fraud (720 ILCS 5/46-3) or governmental entity insurance fraud (720 ILCS 5/46-3) shall be sentenced for a Class 2 felony.
<p class='paragraph'>\(5) A person convicted of conspiracy to commit any of the following offenses shall be sentenced for a Class 3 felony:</p>### (A) soliciting for a prostitute (720 ILCS
<p>5/11-14.3(a)(1));</p>### (B) pandering (720 ILCS 5/11-14.3(a)(2)(A) or
<p>5/11-14.3(a)(2)(B));</p>### (C) keeping a place of prostitution (720 ILCS
<p>5/11-14.3(a)(1));</p>### (D) pimping (720 ILCS 5/11-14.3(a)(2)(C));
<p class='subparagraph'>\(E) unlawful use of weapons under Section</p>### 24-1(a)(1) (720 ILCS 5/24-1(a)(1));
<p class='subparagraph'>\(F) unlawful use of weapons under Section</p>### 24-1(a)(7) (720 ILCS 5/24-1(a)(7));
### (G) gambling (720 ILCS 5/28-1);
### (H) keeping a gambling place (720 ILCS 5/28-3);
### (I) registration of federal gambling stamps violation (720 ILCS 5/28-4);
### (J) look-alike substances violation (720 ILCS
<p>570/404);</p>### (K) miscellaneous controlled substance violation under Section 406(b) (720 ILCS 570/406(b)); or
<p class='subparagraph'>\(L) an inchoate offense related to any of the principal offenses set forth in this item (5).</p><p>(Source: P.A. 96-710, eff. 1-1-10; 96-1551, eff. 7-1-11 .)</p>### (720 ILCS 5/8-2.1)
## Sec. 8-2.1. Conspiracy against civil rights.
<p class='subsection'>\(a) Offense. A person commits conspiracy against civil rights when, without legal justification, he or she, with the intent to interfere with the free exercise of any right or privilege secured by the Constitution of the United States, the Constitution of the State of Illinois, the laws of the United States, or the laws of the State of Illinois by any person or persons, agrees with another to inflict physical harm on any other person or the threat of physical harm on any other person and either the accused or a co-conspirator has committed any act in furtherance of that agreement.</p><p class='subsection'>\(b) Co-conspirators. It shall not be a defense to conspiracy against civil rights that a person or persons with whom the accused is alleged to have conspired:</p><p class='paragraph'>\(1) has not been prosecuted or convicted; or</p><p class='paragraph'>\(2) has been convicted of a different offense; or</p><p class='paragraph'>\(3) is not amenable to justice; or</p><p class='paragraph'>\(4) has been acquitted; or</p><p class='paragraph'>\(5) lacked the capacity to commit an offense.</p><p class='subsection'>\(c) Sentence. Conspiracy against civil rights is a Class 4 felony for a first offense and a Class 2 felony for a second or subsequent offense.</p><p>(Source: P.A. 92-830, eff. 1-1-03.)</p>### (720 ILCS 5/8-3) (from Ch. 38, par. 8-3)
## Sec. 8-3. Defense.
<p>It is a defense to a charge of solicitation or conspiracy that if the criminal object were achieved the accused would not be guilty of an offense.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/8-4) (from Ch. 38, par. 8-4)
## Sec. 8-4. Attempt.
<p class='subsection'>\(a) Elements of the offense.</p><p>A person commits the offense of attempt when, with intent to commit a specific offense, he or she does any act that constitutes a substantial step toward the commission of that offense.</p><p class='subsection'>\(b) Impossibility.</p><p>It is not a defense to a charge of attempt that because of a misapprehension of the circumstances it would have been impossible for the accused to commit the offense attempted.</p><p class='subsection'>\(c) Sentence.</p><p>A person convicted of attempt may be fined or imprisoned or both not to exceed the maximum provided for the offense attempted but, except for an attempt to commit the offense defined in Section 33A-2 of this Code:</p><p class='paragraph'>\(1) the sentence for attempt to commit first degree murder is the sentence for a Class X felony, except that</p><p class='subparagraph'>\(A) an attempt to commit first degree murder when at least one of the aggravating factors specified in paragraphs (1), (2), and (12) of subsection (b) of Section 9-1 is present is a Class X felony for which the sentence shall be a term of imprisonment of not less than 20 years and not more than 80 years;</p><p class='subparagraph'>\(B) an attempt to commit first degree murder while armed with a firearm is a Class X felony for which 15 years shall be added to the term of imprisonment imposed by the court;</p><p class='subparagraph'>\(C) an attempt to commit first degree murder during which the person personally discharged a firearm is a Class X felony for which 20 years shall be added to the term of imprisonment imposed by the court;</p><p class='subparagraph'>\(D) an attempt to commit first degree murder during which the person personally discharged a firearm that proximately caused great bodily harm, permanent disability, permanent disfigurement, or death to another person is a Class X felony for which 25 years or up to a term of natural life shall be added to the term of imprisonment imposed by the court; and</p><p class='subparagraph'>\(E) if the defendant proves by a preponderance of the evidence at sentencing that, at the time of the attempted murder, he or she was acting under a sudden and intense passion resulting from serious provocation by the individual whom the defendant endeavored to kill, or another, and, had the individual the defendant endeavored to kill died, the defendant would have negligently or accidentally caused that death, then the sentence for the attempted murder is the sentence for a Class 1 felony;</p><p class='paragraph'>\(2) the sentence for attempt to commit a Class X felony is the sentence for a Class 1 felony;</p><p class='paragraph'>\(3) the sentence for attempt to commit a Class 1 felony is the sentence for a Class 2 felony;</p><p class='paragraph'>\(4) the sentence for attempt to commit a Class 2 felony is the sentence for a Class 3 felony; and</p><p class='paragraph'>\(5) the sentence for attempt to commit any felony other than those specified in items (1), (2), (3), and (4) of this subsection (c) is the sentence for a Class A misdemeanor.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/8-5) (from Ch. 38, par. 8-5)
## Sec. 8-5. Multiple convictions.
<p>No person shall be convicted of both the inchoate and the principal offense.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/8-6) (from Ch. 38, par. 8-6)
## Sec. 8-6. Offense.
<p>For the purposes of this Article, "offense" shall include conduct which if performed in another State would be criminal by the laws of that State and which conduct if performed in this State would be an offense under the laws of this State.</p><p>(Source: Laws 1961, p. 1983.)</p>### (720 ILCS 5/Tit. III Pt. B heading)
<p>PART B.</p><p>OFFENSES DIRECTED AGAINST THE PERSON</p>