# Article 36. Seizure And Forfeiture {.unnumbered}

<p>OF VESSELS, VEHICLES AND AIRCRAFT</p>### (720 ILCS 5/36-1) (from Ch. 38, par. 36-1)
<p>(Text of Section before amendment by P.A. 102-982</p><p>)</p>## Sec. 36-1. Property subject to forfeiture.
<p class='subsection'>\(a) Any vessel or watercraft, vehicle, or aircraft is subject to forfeiture under this Article if the vessel or watercraft, vehicle, or aircraft is used with the knowledge and consent of the owner in the commission of or in the attempt to commit as defined in Section 8-4 of this Code:</p><p class='paragraph'>\(1) an offense prohibited by Section 9-1 (first degree murder), Section 9-3 (involuntary manslaughter and reckless homicide), Section 10-2 (aggravated kidnaping), Section 11-1.20 (criminal sexual assault), Section 11-1.30 (aggravated criminal sexual assault), Section 11-1.40 (predatory criminal sexual assault of a child), subsection (a) of Section 11-1.50 (criminal sexual abuse), subsection (a), (c), or (d) of Section 11-1.60 (aggravated criminal sexual abuse), Section 11-6 (indecent solicitation of a child), Section 11-14.4 (promoting juvenile prostitution except for keeping a place of juvenile prostitution), Section 11-20.1 (child pornography), paragraph (a)(1), (a)(2), (a)(4), (b)(1), (b)(2), (e)(1), (e)(2), (e)(3), (e)(4), (e)(5), (e)(6), or (e)(7) of Section 12-3.05 (aggravated battery), Section 12-7.3 (stalking), Section 12-7.4 (aggravated stalking), Section 16-1 (theft if the theft is of precious metal or of scrap metal), subdivision (f)(2) or (f)(3) of Section 16-25 (retail theft), Section 18-2 (armed robbery), Section 19-1 (burglary), Section 19-2 (possession of burglary tools), Section 19-3 (residential burglary), Section 20-1 (arson; residential arson; place of worship arson), Section 20-2 (possession of explosives or explosive or incendiary devices), subdivision (a)(6) or (a)(7) of Section 24-1 (unlawful use of weapons), Section 24-1.2 (aggravated discharge of a firearm), Section 24-1.2-5 (aggravated discharge of a machine gun or a firearm equipped with a device designed or used for silencing the report of a firearm), Section 24-1.5 (reckless discharge of a firearm), Section 28-1 (gambling), or Section 29D-15.2 (possession of a deadly substance) of this Code;</p><p class='paragraph'>\(2) an offense prohibited by Section 21, 22, 23, 24 or 26 of the Cigarette Tax Act if the vessel or watercraft, vehicle, or aircraft contains more than 10 cartons of such cigarettes;</p><p class='paragraph'>\(3) an offense prohibited by Section 28, 29, or 30 of the Cigarette Use Tax Act if the vessel or watercraft, vehicle, or aircraft contains more than 10 cartons of such cigarettes;</p><p class='paragraph'>\(4) an offense prohibited by Section 44 of the</p><p>Environmental Protection Act;</p><p class='paragraph'>\(5) an offense prohibited by Section 11-204.1 of the</p><p>Illinois Vehicle Code (aggravated fleeing or attempting to elude a peace officer);</p><p class='paragraph'>\(6) an offense prohibited by Section 11-501 of the</p><p>Illinois Vehicle Code (driving while under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof) or a similar provision of a local ordinance, and:</p><p class='subparagraph'>\(A) during a period in which his or her driving privileges are revoked or suspended if the revocation or suspension was for:</p><p class='item'>\(i) Section 11-501 (driving under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof),</p><p class='item'>\(ii) Section 11-501.1 (statutory summary suspension or revocation),</p><p class='item'>\(iii) paragraph (b) of Section 11-401 (motor vehicle accidents involving death or personal injuries), or</p><p class='item'>\(iv) reckless homicide as defined in Section</p><p>9-3 of this Code;</p><p class='subparagraph'>\(B) has been previously convicted of reckless homicide or a similar provision of a law of another state relating to reckless homicide in which the person was determined to have been under the influence of alcohol, other drug or drugs, or intoxicating compound or compounds as an element of the offense or the person has previously been convicted of committing a violation of driving under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof and was involved in a motor vehicle accident that resulted in death, great bodily harm, or permanent disability or disfigurement to another, when the violation was a proximate cause of the death or injuries;</p><p class='subparagraph'>\(C) the person committed a violation of driving under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof under Section 11-501 of the Illinois Vehicle Code or a similar provision for the third or subsequent time;</p><p class='subparagraph'>\(D) he or she did not possess a valid driver's license or permit or a valid restricted driving permit or a valid judicial driving permit or a valid monitoring device driving permit; or</p><p class='subparagraph'>\(E) he or she knew or should have known that the vehicle he or she was driving was not covered by a liability insurance policy;</p><p class='paragraph'>\(7) an offense described in subsection (g) of Section</p><p>6-303 of the Illinois Vehicle Code;</p><p class='paragraph'>\(8) an offense described in subsection (e) of Section</p><p>6-101 of the Illinois Vehicle Code; or</p><p class='paragraph'>\(9)(A) operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof under Section 5-16 of the Boat Registration and Safety Act during a period in which his or her privileges to operate a watercraft are revoked or suspended and the revocation or suspension was for operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof; (B) operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof and has been previously convicted of reckless homicide or a similar provision of a law in another state relating to reckless homicide in which the person was determined to have been under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof as an element of the offense or the person has previously been convicted of committing a violation of operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof and was involved in an accident that resulted in death, great bodily harm, or permanent disability or disfigurement to another, when the violation was a proximate cause of the death or injuries; or (C) the person committed a violation of operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof under Section 5-16 of the Boat Registration and Safety Act or a similar provision for the third or subsequent time.</p><p class='subsection'>\(b) In addition, any mobile or portable equipment used in the commission of an act which is in violation of Section 7g of the Metropolitan Water Reclamation District Act shall be subject to seizure and forfeiture under the same procedures provided in this Article for the seizure and forfeiture of vessels or watercraft, vehicles, and aircraft, and any such equipment shall be deemed a vessel or watercraft, vehicle, or aircraft for purposes of this Article.</p><p class='subsection'>\(c) In addition, when a person discharges a firearm at another individual from a vehicle with the knowledge and consent of the owner of the vehicle and with the intent to cause death or great bodily harm to that individual and as a result causes death or great bodily harm to that individual, the vehicle shall be subject to seizure and forfeiture under the same procedures provided in this Article for the seizure and forfeiture of vehicles used in violations of clauses (1), (2), (3), or (4) of subsection (a) of this Section.</p><p class='subsection'>\(d) If the spouse of the owner of a vehicle seized for an offense described in subsection (g) of Section 6-303 of the Illinois Vehicle Code, a violation of subdivision (d)(1)(A), (d)(1)(D), (d)(1)(G), (d)(1)(H), or (d)(1)(I) of Section 11-501 of the Illinois Vehicle Code, or Section 9-3 of this Code makes a showing that the seized vehicle is the only source of transportation and it is determined that the financial hardship to the family as a result of the seizure outweighs the benefit to the State from the seizure, the vehicle may be forfeited to the spouse or family member and the title to the vehicle shall be transferred to the spouse or family member who is properly licensed and who requires the use of the vehicle for employment or family transportation purposes. A written declaration of forfeiture of a vehicle under this Section shall be sufficient cause for the title to be transferred to the spouse or family member. The provisions of this paragraph shall apply only to one forfeiture per vehicle. If the vehicle is the subject of a subsequent forfeiture proceeding by virtue of a subsequent conviction of either spouse or the family member, the spouse or family member to whom the vehicle was forfeited under the first forfeiture proceeding may not utilize the provisions of this paragraph in another forfeiture proceeding. If the owner of the vehicle seized owns more than one vehicle, the procedure set out in this paragraph may be used for only one vehicle.</p><p class='subsection'>\(e) In addition, property subject to forfeiture under Section 40 of the Illinois Streetgang Terrorism Omnibus Prevention Act may be seized and forfeited under this Article.</p><p>(Source: P.A. 99-78, eff. 7-20-15; 100-512, eff. 7-1-18 .)</p><p>(Text of Section after amendment by P.A. 102-982</p><p>)</p>## Sec. 36-1. Property subject to forfeiture.
<p class='subsection'>\(a) Any vessel or watercraft, vehicle, or aircraft is subject to forfeiture under this Article if the vessel or watercraft, vehicle, or aircraft is used with the knowledge and consent of the owner in the commission of or in the attempt to commit as defined in Section 8-4 of this Code:</p><p class='paragraph'>\(1) an offense prohibited by Section 9-1 (first degree murder), Section 9-3 (involuntary manslaughter and reckless homicide), Section 10-2 (aggravated kidnaping), Section 11-1.20 (criminal sexual assault), Section 11-1.30 (aggravated criminal sexual assault), Section 11-1.40 (predatory criminal sexual assault of a child), subsection (a) of Section 11-1.50 (criminal sexual abuse), subsection (a), (c), or (d) of Section 11-1.60 (aggravated criminal sexual abuse), Section 11-6 (indecent solicitation of a child), Section 11-14.4 (promoting juvenile prostitution except for keeping a place of juvenile prostitution), Section 11-20.1 (child pornography), paragraph (a)(1), (a)(2), (a)(4), (b)(1), (b)(2), (e)(1), (e)(2), (e)(3), (e)(4), (e)(5), (e)(6), or (e)(7) of Section 12-3.05 (aggravated battery), Section 12-7.3 (stalking), Section 12-7.4 (aggravated stalking), Section 16-1 (theft if the theft is of precious metal or of scrap metal), subdivision (f)(2) or (f)(3) of Section 16-25 (retail theft), Section 18-2 (armed robbery), Section 19-1 (burglary), Section 19-2 (possession of burglary tools), Section 19-3 (residential burglary), Section 20-1 (arson; residential arson; place of worship arson), Section 20-2 (possession of explosives or explosive or incendiary devices), subdivision (a)(6) or (a)(7) of Section 24-1 (unlawful use of weapons), Section 24-1.2 (aggravated discharge of a firearm), Section 24-1.2-5 (aggravated discharge of a machine gun or a firearm equipped with a device designed or used for silencing the report of a firearm), Section 24-1.5 (reckless discharge of a firearm), Section 28-1 (gambling), or Section 29D-15.2 (possession of a deadly substance) of this Code;</p><p class='paragraph'>\(2) an offense prohibited by Section 21, 22, 23, 24 or 26 of the Cigarette Tax Act if the vessel or watercraft, vehicle, or aircraft contains more than 10 cartons of such cigarettes;</p><p class='paragraph'>\(3) an offense prohibited by Section 28, 29, or 30 of the Cigarette Use Tax Act if the vessel or watercraft, vehicle, or aircraft contains more than 10 cartons of such cigarettes;</p><p class='paragraph'>\(4) an offense prohibited by Section 44 of the</p><p>Environmental Protection Act;</p><p class='paragraph'>\(5) an offense prohibited by Section 11-204.1 of the</p><p>Illinois Vehicle Code (aggravated fleeing or attempting to elude a peace officer);</p><p class='paragraph'>\(6) an offense prohibited by Section 11-501 of the</p><p>Illinois Vehicle Code (driving while under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof) or a similar provision of a local ordinance, and:</p><p class='subparagraph'>\(A) during a period in which his or her driving privileges are revoked or suspended if the revocation or suspension was for:</p><p class='item'>\(i) Section 11-501 (driving under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof),</p><p class='item'>\(ii) Section 11-501.1 (statutory summary suspension or revocation),</p><p class='item'>\(iii) paragraph (b) of Section 11-401 (motor vehicle crashes involving death or personal injuries), or</p><p class='item'>\(iv) reckless homicide as defined in Section</p><p>9-3 of this Code;</p><p class='subparagraph'>\(B) has been previously convicted of reckless homicide or a similar provision of a law of another state relating to reckless homicide in which the person was determined to have been under the influence of alcohol, other drug or drugs, or intoxicating compound or compounds as an element of the offense or the person has previously been convicted of committing a violation of driving under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof and was involved in a motor vehicle crash that resulted in death, great bodily harm, or permanent disability or disfigurement to another, when the violation was a proximate cause of the death or injuries;</p><p class='subparagraph'>\(C) the person committed a violation of driving under the influence of alcohol or other drug or drugs, intoxicating compound or compounds or any combination thereof under Section 11-501 of the Illinois Vehicle Code or a similar provision for the third or subsequent time;</p><p class='subparagraph'>\(D) he or she did not possess a valid driver's license or permit or a valid restricted driving permit or a valid judicial driving permit or a valid monitoring device driving permit; or</p><p class='subparagraph'>\(E) he or she knew or should have known that the vehicle he or she was driving was not covered by a liability insurance policy;</p><p class='paragraph'>\(7) an offense described in subsection (g) of Section</p><p>6-303 of the Illinois Vehicle Code;</p><p class='paragraph'>\(8) an offense described in subsection (e) of Section</p><p>6-101 of the Illinois Vehicle Code; or</p><p class='paragraph'>\(9)(A) operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof under Section 5-16 of the Boat Registration and Safety Act during a period in which his or her privileges to operate a watercraft are revoked or suspended and the revocation or suspension was for operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof; (B) operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof and has been previously convicted of reckless homicide or a similar provision of a law in another state relating to reckless homicide in which the person was determined to have been under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof as an element of the offense or the person has previously been convicted of committing a violation of operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof and was involved in an accident that resulted in death, great bodily harm, or permanent disability or disfigurement to another, when the violation was a proximate cause of the death or injuries; or (C) the person committed a violation of operating a watercraft under the influence of alcohol, other drug or drugs, intoxicating compound or compounds, or combination thereof under Section 5-16 of the Boat Registration and Safety Act or a similar provision for the third or subsequent time.</p><p class='subsection'>\(b) In addition, any mobile or portable equipment used in the commission of an act which is in violation of Section 7g of the Metropolitan Water Reclamation District Act shall be subject to seizure and forfeiture under the same procedures provided in this Article for the seizure and forfeiture of vessels or watercraft, vehicles, and aircraft, and any such equipment shall be deemed a vessel or watercraft, vehicle, or aircraft for purposes of this Article.</p><p class='subsection'>\(c) In addition, when a person discharges a firearm at another individual from a vehicle with the knowledge and consent of the owner of the vehicle and with the intent to cause death or great bodily harm to that individual and as a result causes death or great bodily harm to that individual, the vehicle shall be subject to seizure and forfeiture under the same procedures provided in this Article for the seizure and forfeiture of vehicles used in violations of clauses (1), (2), (3), or (4) of subsection (a) of this Section.</p><p class='subsection'>\(d) If the spouse of the owner of a vehicle seized for an offense described in subsection (g) of Section 6-303 of the Illinois Vehicle Code, a violation of subdivision (d)(1)(A), (d)(1)(D), (d)(1)(G), (d)(1)(H), or (d)(1)(I) of Section 11-501 of the Illinois Vehicle Code, or Section 9-3 of this Code makes a showing that the seized vehicle is the only source of transportation and it is determined that the financial hardship to the family as a result of the seizure outweighs the benefit to the State from the seizure, the vehicle may be forfeited to the spouse or family member and the title to the vehicle shall be transferred to the spouse or family member who is properly licensed and who requires the use of the vehicle for employment or family transportation purposes. A written declaration of forfeiture of a vehicle under this Section shall be sufficient cause for the title to be transferred to the spouse or family member. The provisions of this paragraph shall apply only to one forfeiture per vehicle. If the vehicle is the subject of a subsequent forfeiture proceeding by virtue of a subsequent conviction of either spouse or the family member, the spouse or family member to whom the vehicle was forfeited under the first forfeiture proceeding may not utilize the provisions of this paragraph in another forfeiture proceeding. If the owner of the vehicle seized owns more than one vehicle, the procedure set out in this paragraph may be used for only one vehicle.</p><p class='subsection'>\(e) In addition, property subject to forfeiture under Section 40 of the Illinois Streetgang Terrorism Omnibus Prevention Act may be seized and forfeited under this Article.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (720 ILCS 5/36-1.1)
## Sec. 36-1.1. Seizure.
<p class='subsection'>\(a) Any property subject to forfeiture under this Article may be seized and impounded by the Director of the Illinois State Police or any peace officer upon process or seizure warrant issued by any court having jurisdiction over the property.</p><p class='subsection'>\(b) Any property subject to forfeiture under this Article may be seized and impounded by the Director of the Illinois State Police or any peace officer without process if there is probable cause to believe that the property is subject to forfeiture under Section 36-1 of this Article and the property is seized under circumstances in which a warrantless seizure or arrest would be reasonable.</p><p class='subsection'>\(c) If the seized property is a conveyance, an investigation shall be made by the law enforcement agency as to any person whose right, title, interest, or lien is of record in the office of the agency or official in which title to or interest in the conveyance is required by law to be recorded.</p><p class='subsection'>\(d) After seizure under this Section, notice shall be given to all known interest holders that forfeiture proceedings, including a preliminary review, may be instituted and the proceedings may be instituted under this Article.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/36-1.2)
## Sec. 36-1.2. Receipt for seized property.
<p>If a law enforcement officer seizes property for forfeiture under this Article, the officer shall provide an itemized receipt to the person possessing the property or, in the absence of a person to whom the receipt could be given, shall leave the receipt in the place where the property was found, if possible.</p><p>(Source: P.A. 100-512, eff. 7-1-18 .)</p>### (720 ILCS 5/36-1.3)
## Sec. 36-1.3. Safekeeping of seized property pending disposition.
<p class='subsection'>\(a) Property seized under this Article is deemed to be in the custody of the Director of the Illinois State Police, subject only to the order and judgments of the circuit court having jurisdiction over the forfeiture proceedings and the decisions of the State's Attorney under this Article.</p><p class='subsection'>\(b) If property is seized under this Article, the seizing agency shall promptly conduct an inventory of the seized property and estimate the property's value and shall forward a copy of the inventory of seized property and the estimate of the property's value to the Director of the Illinois State Police. Upon receiving notice of seizure, the Director of the Illinois State Police may:</p><p class='paragraph'>\(1) place the property under seal;</p><p class='paragraph'>\(2) remove the property to a place designated by the</p><p>Director of the Illinois State Police;</p><p class='paragraph'>\(3) keep the property in the possession of the seizing agency;</p><p class='paragraph'>\(4) remove the property to a storage area for safekeeping;</p><p class='paragraph'>\(5) place the property under constructive seizure by posting notice of pending forfeiture on it, by giving notice of pending forfeiture to its owners and interest holders, or by filing notice of pending forfeiture in any appropriate public record relating to the property; or</p><p class='paragraph'>\(6) provide for another agency or custodian, including an owner, secured party, or lienholder, to take custody of the property upon the terms and conditions set by the seizing agency.</p><p class='subsection'>\(c) The seizing agency shall exercise ordinary care to protect the subject of the forfeiture from negligent loss, damage, or destruction.</p><p class='subsection'>\(d) Property seized or forfeited under this Article is subject to reporting under the Seizure and Forfeiture Reporting Act.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/36-1.4)
## Sec. 36-1.4. Notice to State's Attorney.
<p>The law enforcement agency seizing property for forfeiture under this Article shall, as soon as practicable but not later than 28 days after the seizure, notify the State's Attorney for the county in which an act or omission giving rise to the seizure occurred or in which the property was seized and the facts and circumstances giving rise to the seizure and shall provide the State's Attorney with the inventory of the property and its estimated value. The notice shall be by the delivery of Illinois State Police Notice/Inventory of Seized Property (Form 4-64). If the property seized for forfeiture is a vehicle, the law enforcement agency seizing the property shall immediately notify the Secretary of State that forfeiture proceedings are pending regarding the vehicle.</p><p>(Source: P.A. 100-512, eff. 7-1-18; 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/36-1.5)
## Sec. 36-1.5. Preliminary review.
<p class='subsection'>\(a) Within 14 days of the seizure, the State's Attorney of the county in which the seizure occurred shall seek a preliminary determination from the circuit court as to whether there is probable cause that the property may be subject to forfeiture.</p><p class='subsection'>\(b) The rules of evidence shall not apply to any proceeding conducted under this Section.</p><p class='subsection'>\(c) The court may conduct the review under subsection (a) of this Section simultaneously with a proceeding under Section 109-1 of the Code of Criminal Procedure of 1963 for a related criminal offense if a prosecution is commenced by information or complaint.</p><p class='subsection'>\(d) The court may accept a finding of probable cause at a preliminary hearing following the filing of an information or complaint charging a related criminal offense or following the return of indictment by a grand jury charging the related offense as sufficient evidence of probable cause as required under subsection (a) of this Section.</p><p class='subsection'>\(e) Upon making a finding of probable cause as required under this Section, the circuit court shall order the property subject to the provisions of the applicable forfeiture Act held until the conclusion of any forfeiture proceeding.</p><p>For seizures of conveyances, within 28 days of a finding of probable cause under subsection (a) of this Section, the registered owner or other claimant may file a motion in writing supported by sworn affidavits claiming that denial of the use of the conveyance during the pendency of the forfeiture proceedings creates a substantial hardship and alleges facts showing that the hardship was not due to his or her culpable negligence. The court shall consider the following factors in determining whether a substantial hardship has been proven:</p><p class='paragraph'>\(1) the nature of the claimed hardship;</p><p class='paragraph'>\(2) the availability of public transportation or other available means of transportation; and</p><p class='paragraph'>\(3) any available alternatives to alleviate the hardship other than the return of the seized conveyance.</p><p>If the court determines that a substantial hardship has been proven, the court shall then balance the nature of the hardship against the State's interest in safeguarding the conveyance. If the court determines that the hardship outweighs the State's interest in safeguarding the conveyance, the court may temporarily release the conveyance to the registered owner or the registered owner's authorized designee, or both, until the conclusion of the forfeiture proceedings or for such shorter period as ordered by the court provided that the person to whom the conveyance is released provides proof of insurance and a valid driver's license and all State and local registrations for operation of the conveyance are current. The court shall place conditions on the conveyance limiting its use to the stated hardship and providing transportation for employment, religious purposes, medical needs, child care, and restricting the conveyance's use to only those individuals authorized to use the conveyance by the registered owner. The use of the vehicle shall be further restricted to exclude all recreational and entertainment purposes. The court may order additional restrictions it deems reasonable and just on its own motion or on motion of the People. The court shall revoke the order releasing the conveyance and order that the conveyance be reseized by law enforcement if the conditions of release are violated or if the conveyance is used in the commission of any offense identified in subsection (a) of Section 6-205 of the Illinois Vehicle Code.</p><p>If the court orders the release of the conveyance during the pendency of the forfeiture proceedings, the court may order the registered owner or his or her authorized designee to post a cash security with the clerk of the court as ordered by the court. If cash security is ordered, the court shall consider the following factors in determining the amount of the cash security:</p><p class='subparagraph'>\(A) the full market value of the conveyance;</p><p class='subparagraph'>\(B) the nature of the hardship;</p><p class='subparagraph'>\(C) the extent and length of the usage of the conveyance;</p><p class='subparagraph'>\(D) the ability of the owner or designee to pay; and</p><p class='subparagraph'>\(E) other conditions as the court deems necessary to safeguard the conveyance.</p><p>If the conveyance is released, the court shall order that the registered owner or his or her designee safeguard the conveyance, not remove the conveyance from the jurisdiction, not conceal, destroy, or otherwise dispose of the conveyance, not encumber the conveyance, and not diminish the value of the conveyance in any way. The court shall also make a determination of the full market value of the conveyance prior to it being released based on a source or sources defined in 50 Ill. Adm. Code 919.80(c)(2)(A) or 919.80(c)(2)(B).</p><p>If the conveyance subject to forfeiture is released under this Section and is subsequently forfeited, the person to whom the conveyance was released shall return the conveyance to the law enforcement agency that seized the conveyance within 7 days from the date of the declaration of forfeiture or order of forfeiture. If the conveyance is not returned within 7 days, the cash security shall be forfeited in the same manner as the conveyance subject to forfeiture. If the cash security was less than the full market value, a judgment shall be entered against the parties to whom the conveyance was released and the registered owner, jointly and severally, for the difference between the full market value and the amount of the cash security. If the conveyance is returned in a condition other than the condition in which it was released, the cash security shall be returned to the surety who posted the security minus the amount of the diminished value, and that amount shall be forfeited in the same manner as the conveyance subject to forfeiture. Additionally, the court may enter an order allowing any law enforcement agency in the State of Illinois to seize the conveyance wherever it may be found in the State to satisfy the judgment if the cash security was less than the full market value of the conveyance.</p><p>(Source: P.A. 100-512, eff. 7-1-18; 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/36-1a) (from Ch. 38, par. 36-1a)
## Sec. 36-1a. (Repealed).
<p>(Source: P.A. 98-699, eff. 1-1-15. Repealed by P.A. 100-512, eff. 7-1-18 .)</p>### (720 ILCS 5/36-2) (from Ch. 38, par. 36-2)
## Sec. 36-2. Complaint for forfeiture.
<p class='subsection'>\(a) If the State's Attorney of the county in which such seizure occurs finds that the alleged violation of law giving rise to the seizure was incurred without willful negligence or without any intention on the part of the owner of the vessel or watercraft, vehicle, or aircraft or any person whose right, title, or interest is of record as described in Section 36-1 of this Article, to violate the law, or finds the existence of such mitigating circumstances as to justify remission of the forfeiture, he or she may cause the law enforcement agency having custody of the property to return the property to the owner within a reasonable time not to exceed 7 days. The State's Attorney shall exercise his or her discretion under this subsection (a) prior to or promptly after the preliminary review under Section 36-1.5.</p><p class='subsection'>\(b) If, after review of the facts surrounding the seizure, the State's Attorney is of the opinion that the seized property is subject to forfeiture and the State's Attorney does not cause the forfeiture to be remitted under subsection (a) of this Section, he or she shall bring an action for forfeiture in the circuit court within whose jurisdiction the seizure and confiscation has taken place by filing a verified complaint for forfeiture in the circuit court within whose jurisdiction the seizure occurred, or within whose jurisdiction an act or omission giving rise to the seizure occurred, subject to Supreme Court Rule 187. The complaint shall be filed as soon as practicable but not later than 28 days after the State's Attorney receives notice from the seizing agency as provided under Section 36-1.4 of this Article. A complaint of forfeiture shall include:</p><p class='paragraph'>\(1) a description of the property seized;</p><p class='paragraph'>\(2) the date and place of seizure of the property;</p><p class='paragraph'>\(3) the name and address of the law enforcement agency making the seizure; and</p><p class='paragraph'>\(4) the specific statutory and factual grounds for the seizure.</p><p>The complaint shall be served upon each person whose right, title, or interest is of record in the office of the Secretary of State, the Secretary of Transportation, the Administrator of the Federal Aviation Agency, or any other department of this State, or any other state of the United States if the vessel or watercraft, vehicle, or aircraft is required to be so registered, as the case may be, the person from whom the property was seized, and all persons known or reasonably believed by the State to claim an interest in the property, as provided in this Article. The complaint shall be accompanied by the following written notice:</p><p>"This is a civil court proceeding subject to the Code of Civil Procedure. You received this Complaint of Forfeiture because the State's Attorney's office has brought a legal action seeking forfeiture of your seized property. This complaint starts the court process where the State seeks to prove that your property should be forfeited and not returned to you. This process is also your opportunity to try to prove to a judge that you should get your property back. The complaint lists the date, time, and location of your first court date. You must appear in court on that day, or you may lose the case automatically. You must also file an appearance and answer. If you are unable to pay the appearance fee, you may qualify to have the fee waived. If there is a criminal case related to the seizure of your property, your case may be set for trial after the criminal case has been resolved. Before trial, the judge may allow discovery, where the State can ask you to respond in writing to questions and give them certain documents, and you can make similar requests of the State. The trial is your opportunity to explain what happened when your property was seized and why you should get the property back."</p><p class='subsection'>\(c) (Blank).</p><p class='subsection'>\(d) (Blank).</p><p class='subsection'>\(e) (Blank).</p><p class='subsection'>\(f) (Blank).</p><p class='subsection'>\(g) (Blank).</p><p class='subsection'>\(h) (Blank).</p><p>(Source: P.A. 99-78, eff. 7-20-15; 100-512, eff. 7-1-18; 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/36-2.1)
## Sec. 36-2.1. Notice to owner or interest holder.
<p> The first attempted service of notice shall be commenced within 28 days of the receipt of the notice from the seizing agency by Form 4-64. If the property seized is a conveyance, notice shall also be directed to the address reflected in the office of the agency or official in which title to or interest in the conveyance is required by law to be recorded. A complaint for forfeiture shall be served upon the property owner or interest holder in the following manner:</p><p class='paragraph'>\(1) If the owner's or interest holder's name and current address are known, then by either:</p><p class='subparagraph'>\(A) personal service; or</p><p class='subparagraph'>\(B) mailing a copy of the notice by certified mail, return receipt requested, and first class mail to that address.</p><p class='item'>\(i) If notice is sent by certified mail and no signed return receipt is received by the State's Attorney within 28 days of mailing, and no communication from the owner or interest holder is received by the State's Attorney documenting actual notice by said parties, the State's Attorney shall, within a reasonable period of time, mail a second copy of the notice by certified mail, return receipt requested, and first class mail to that address.</p><p class='item'>\(ii) If no signed return receipt is received by the State's Attorney within 28 days of the second attempt at service by certified mail, and no communication from the owner or interest holder is received by the State's Attorney documenting actual notice by said parties, the State's Attorney shall have 60 days to attempt to serve the notice by personal service, which also includes substitute service by leaving a copy at the usual place of abode with some person of the family or a person residing there, of the age of 13 years or upwards. If, after 3 attempts at service in this manner, no service of the notice is accomplished, then the notice shall be posted in a conspicuous manner at this address and service shall be made by the posting.</p><p>The attempts at service and the posting, if required, shall be documented by the person attempting service and said documentation shall be made part of a return of service returned to the State's Attorney.</p><p>The State's Attorney may utilize a Sheriff or</p><p>Deputy Sheriff, any peace officer, a private process server or investigator, or any employee, agent, or investigator of the State's Attorney's office to attempt service without seeking leave of court.</p><p>After the procedures are followed, service shall be effective on an owner or interest holder on the date of receipt by the State's Attorney of a return receipt, or on the date of receipt of a communication from an owner or interest holder documenting actual notice, whichever is first in time, or on the date of the last act performed by the State's Attorney in attempting personal service under item (ii) of this paragraph (1). If notice is to be shown by actual notice from communication with a claimant, then the State's Attorney shall file an affidavit providing details of the communication, which shall be accepted as sufficient proof of service by the court.</p><p>For purposes of notice under this Section, if a person has been arrested for the conduct giving rise to the forfeiture, the address provided to the arresting agency at the time of arrest shall be deemed to be that person's known address. Provided, however, if an owner or interest holder's address changes prior to the effective date of the complaint for forfeiture, the owner or interest holder shall promptly notify the seizing agency of the change in address or, if the owner or interest holder's address changes subsequent to the effective date of the notice of pending forfeiture, the owner or interest holder shall promptly notify the State's Attorney of the change in address; or if the property seized is a conveyance, to the address reflected in the office of the agency or official in which title to or interest in the conveyance is required by law to be recorded.</p><p class='paragraph'>\(2) If the owner's or interest holder's address is not known, and is not on record, then notice shall be served by publication for 3 successive weeks in a newspaper of general circulation in the county in which the seizure occurred.</p><p class='paragraph'>\(3) Notice to any business entity, corporation, limited liability company, limited liability partnership, or partnership shall be completed by a single mailing of a copy of the notice by certified mail, return receipt requested, and first class mail to that address. This notice is complete regardless of the return of a signed return receipt.</p><p class='paragraph'>\(4) Notice to a person whose address is not within the State shall be completed by a single mailing of a copy of the notice by certified mail, return receipt requested, and first class mail to that address. This notice is complete regardless of the return of a signed return receipt.</p><p class='paragraph'>\(5) Notice to a person whose address is not within the United States shall be completed by a single mailing of a copy of the notice by certified mail, return receipt requested, and first class mail to that address. This notice shall be complete regardless of the return of a signed return receipt. If certified mail is not available in the foreign country where the person has an address, then notice shall proceed by publication under paragraph (2) of this Section.</p><p class='paragraph'>\(6) Notice to any person whom the State's Attorney reasonably should know is incarcerated within the State shall also include mailing a copy of the notice by certified mail, return receipt requested, and first class mail to the address of the detention facility with the inmate's name clearly marked on the envelope.</p><p>(Source: P.A. 100-512, eff. 7-1-18; 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/36-2.2)
## Sec. 36-2.2. Replevin prohibited; return of personal property inside seized conveyance.
<p class='subsection'>\(a) Property seized under this Article shall not be subject to replevin, but is deemed to be in the custody of the Director of the Illinois State Police, subject only to the order and judgments of the circuit court having jurisdiction over the forfeiture proceedings and the decisions of the State's Attorney.</p><p class='subsection'>\(b) A claimant or a party interested in personal property contained within a seized conveyance may file a motion with the court in a judicial forfeiture action for the return of any personal property contained within a conveyance seized under this Article. The return of personal property shall not be unreasonably withheld if the personal property is not mechanically or electrically coupled to the conveyance, needed for evidentiary purposes, or otherwise contraband. A law enforcement agency that returns property under a court order under this Section shall not be liable to any person who claims ownership to the property if the property is returned to an improper party.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/36-2.5)
## Sec. 36-2.5. Judicial in rem procedures.
<p class='subsection'>\(a) The laws of evidence relating to civil actions shall apply to judicial in rem proceedings under this Article.</p><p class='subsection'>\(b) Only an owner of or interest holder in the property may file an answer asserting a claim against the property in the action in rem. For purposes of this Section, the owner or interest holder shall be referred to as claimant. A person not named in the forfeiture complaint who claims to have an interest in the property may petition to intervene as a claimant under Section 2-408 of the Code of Civil Procedure.</p><p class='subsection'>\(c) The answer shall be filed with the court within 45 days after service of the civil in rem complaint.</p><p class='subsection'>\(d) The trial shall be held within 60 days after filing of the answer unless continued for good cause.</p><p class='subsection'>\(e) In its case in chief, the State shall show by a preponderance of the evidence that:</p><p class='paragraph'>\(1) the property is subject to forfeiture; and</p><p class='paragraph'>\(2) at least one of the following:</p><p class='item'>\(i) the claimant knew or should have known that the conduct was likely to occur; or</p><p class='item'>\(ii) the claimant is not the true owner of the property that is subject to forfeiture.</p><p>In any forfeiture case under this Article, a claimant may present evidence to overcome evidence presented by the State that the property is subject to forfeiture.</p><p class='subsection'>\(f) Notwithstanding any other provision of this Section, the State's burden of proof at the trial of the forfeiture action shall be by clear and convincing evidence if:</p><p class='paragraph'>\(1) a finding of not guilty is entered as to all counts and all defendants in a criminal proceeding relating to the conduct giving rise to the forfeiture action; or</p><p class='paragraph'>\(2) the State receives an adverse finding at a preliminary hearing and fails to secure an indictment in a criminal proceeding related to the factual allegations of the forfeiture action.</p><p class='subsection'>\(g) If the State does not meet its burden of proof, the court shall order the interest in the property returned or conveyed to the claimant and shall order all other property in which the State does meet its burden of proof forfeited to the State. If the State does meet its burden of proof, the court shall order all property forfeited to the State.</p><p class='subsection'>\(h) A defendant convicted in any criminal proceeding is precluded from later denying the essential allegations of the criminal offense of which the defendant was convicted in any proceeding under this Article regardless of the pendency of an appeal from that conviction. However, evidence of the pendency of an appeal is admissible.</p><p class='item'>\(i) An acquittal or dismissal in a criminal proceeding shall not preclude civil proceedings under this Act; however, for good cause shown, on a motion by either party, the court may stay civil forfeiture proceedings during the criminal trial for a related criminal indictment or information alleging a violation of law authorizing forfeiture under Section 36-1 of this Article.</p><p class='subsection'>\(j) Title to all property declared forfeited under this Act vests in this State on the commission of the conduct giving rise to forfeiture together with the proceeds of the property after that time. Except as otherwise provided in this Article, any property or proceeds subsequently transferred to any person remain subject to forfeiture unless a person to whom the property was transferred makes an appropriate claim under or has the claim adjudicated at the judicial in rem hearing.</p><p class='subsection'>\(k) No property shall be forfeited under this Article from a person who, without actual or constructive notice that the property was the subject of forfeiture proceedings, obtained possession of the property as a bona fide purchaser for value. A person who purports to transfer property after receiving actual or constructive notice that the property is subject to seizure or forfeiture is guilty of contempt of court and shall be liable to the State for a penalty in the amount of the fair market value of the property.</p><p class='subsection'>\(l) A civil action under this Article shall be commenced within 5 years after the last conduct giving rise to forfeiture became known or should have become known or 5 years after the forfeitable property is discovered, whichever is later, excluding any time during which either the property or claimant is out of the State or in confinement or during which criminal proceedings relating to the same conduct are in progress.</p><p class='subsection'>\(m) If property is ordered forfeited under this Article from a claimant who held title to the property in joint tenancy or tenancy in common with another claimant, the court shall determine the amount of each owner's interest in the property according to principles of property law.</p><p>(Source: P.A. 100-512, eff. 7-1-18; 100-699, eff. 8-3-18; 100-1163, eff. 12-20-18.)</p>### (720 ILCS 5/36-2.7)
## Sec. 36-2.7. Innocent owner hearing.
<p class='subsection'>\(a) After a complaint for forfeiture has been filed and all claimants have appeared and answered, a claimant may file a motion with the court for an innocent owner hearing prior to trial. This motion shall be made and supported by sworn affidavit and shall assert the following along with specific facts that support each assertion:</p><p class='paragraph'>\(1) that the claimant filing the motion is the true owner of the conveyance as interpreted by case law; and</p><p class='paragraph'>\(2) that the claimant did not know or did not have reason to know the conduct giving rise to the forfeiture was likely to occur.</p><p>The claimant's motion shall include specific facts that support these assertions.</p><p class='subsection'>\(b) Upon the filing, a hearing may only be conducted after the parties have been given the opportunity to conduct limited discovery as to the ownership and control of the property, the claimant's knowledge, or any matter relevant to the issues raised or facts alleged in the claimant's motion. Discovery shall be limited to the People's requests in these areas but may proceed by any means allowed in the Code of Civil Procedure.</p><p class='subsection'>\(c) After discovery is complete and the court has allowed for sufficient time to review and investigate the discovery responses, the court shall conduct a hearing. At the hearing, the fact that the conveyance is subject to forfeiture shall not be at issue. The court shall only hear evidence relating to the issue of innocent ownership.</p><p class='subsection'>\(d) At the hearing on the motion, the claimant shall bear the burden of proving each of the assertions listed in subsection (a) of this Section by a preponderance of the evidence. If a claimant meets the burden of proof, the court shall grant the motion and order the conveyance returned to the claimant. If the claimant fails to meet the burden of proof, the court shall deny the motion and the forfeiture case shall proceed according to the Code of Civil Procedure.</p><p>(Source: P.A. 100-512, eff. 7-1-18; 100-699, eff. 8-3-18.)</p>### (720 ILCS 5/36-3) (from Ch. 38, par. 36-3)
## Sec. 36-3. Exemptions from forfeiture.
<p class='subsection'>\(a) No vessel or watercraft, vehicle, or aircraft used by any person as a common carrier in the transaction of business as such common carrier may be forfeited under the provisions of Section 36-2 unless the State proves by a preponderance of the evidence that (1) in the case of a railway car or engine, the owner, or (2) in the case of any other such vessel or watercraft, vehicle or aircraft, the owner or the master of such vessel or watercraft or the owner or conductor, driver, pilot, or other person in charge of such vehicle or aircraft was at the time of the alleged illegal act a consenting party or privy thereto.</p><p class='subsection'>\(b) No vessel or watercraft, vehicle, or aircraft shall be forfeited under the provisions of Section 36-2 of this Article by reason of any act or omission committed or omitted by any person other than such owner while such vessel or watercraft, vehicle, or aircraft was unlawfully in the possession of a person who acquired possession thereof in violation of the criminal laws of the United States, or of any state.</p><p>(Source: P.A. 100-512, eff. 7-1-18 .)</p>### (720 ILCS 5/36-3.1)
## Sec. 36-3.1. Proportionality.
<p>Property forfeited under this Article shall be subject to an 8th Amendment to the United States Constitution disproportionate penalties analysis, and the property forfeiture may be denied in whole or in part if the court finds that the forfeiture would constitute an excessive fine in violation of the 8th Amendment to the United States Constitution, as interpreted by case law.</p><p>(Source: P.A. 100-512, eff. 7-1-18 .)</p>### (720 ILCS 5/36-4) (from Ch. 38, par. 36-4)
## Sec. 36-4. Remission by Attorney General.
<p>Whenever any owner of, or other person interested in, a vessel or watercraft, vehicle, or aircraft seized under the provisions of this Act files with the Attorney General before the sale or destruction of such vessel or watercraft, vehicle, or aircraft, a petition for the remission of such forfeiture the Attorney General if he finds that such forfeiture was incurred without willful negligence or without any intention on the part of the owner or any person whose right, title or interest is of record as described in Section 36-1, to violate the law, or finds the existence of such mitigating circumstances as to justify the remission of forfeiture, may cause the same to be remitted upon such terms and conditions as he deems reasonable and just, or order discontinuance of any forfeiture proceeding relating thereto.</p><p>(Source: P.A. 98-699, eff. 1-1-15 .)</p>### (720 ILCS 5/36-5)
## Sec. 36-5. (Repealed).
<p>(Source: P.A. 98-1020, eff. 8-22-14. Repealed by P.A. 100-512, eff. 7-1-18 .)</p>### (720 ILCS 5/36-6)
## Sec. 36-6. Return of property, damages and costs.
<p class='subsection'>\(a) The law enforcement agency that holds custody of property seized for forfeiture shall return to the claimant, within a reasonable period of time not to exceed 7 days unless the order is stayed by the trial court or a reviewing court pending an appeal, motion to reconsider, or other reason after the court orders the property to be returned or conveyed to the claimant:</p><p class='paragraph'>\(1) property ordered by the court to be conveyed or returned to the claimant; and</p><p class='paragraph'>\(2) property ordered by the court to be conveyed or returned to the claimant under subsection (d) of Section 36-3.1 of this Article.</p><p class='subsection'>\(b) The law enforcement agency that holds custody of property seized under this Article is responsible for any damages, storage fees, and related costs applicable to property returned to a claimant under this Article. The claimant shall not be subject to any charges by the State for storage of the property or expenses incurred in the preservation of the property. Charges for the towing of a conveyance shall be borne by the claimant unless the conveyance was towed for the sole reason of seizure for forfeiture. This subsection does not prohibit the imposition of any fees or costs by a home rule unit of local government related to the impoundment of a conveyance under an ordinance enacted by the unit of government.</p><p>(Source: P.A. 100-512, eff. 7-1-18 .)</p>### (720 ILCS 5/36-7)
## Sec. 36-7. Distribution of proceeds; selling or retaining seized property prohibited.
<p class='subsection'>\(a) Except as otherwise provided in this Section, the court shall order that property forfeited under this Article be delivered to the Illinois State Police within 60 days.</p><p class='subsection'>\(b) The Illinois State Police or its designee shall dispose of all property at public auction and shall distribute the proceeds of the sale, together with any moneys forfeited or seized, under subsection (c) of this Section.</p><p class='subsection'>\(c) All moneys and the sale proceeds of all other property forfeited and seized under this Act shall be distributed as follows:</p><p class='paragraph'>\(1) 65% shall be distributed to the drug task force, metropolitan enforcement group, local, municipal, county, or State law enforcement agency or agencies that conducted or participated in the investigation resulting in the forfeiture. The distribution shall bear a reasonable relationship to the degree of direct participation of the law enforcement agency in the effort resulting in the forfeiture, taking into account the total value of the property forfeited and the total law enforcement effort with respect to the violation of the law upon which the forfeiture is based. Amounts distributed to the agency or agencies shall be used, at the discretion of the agency, for the enforcement of criminal laws; or for public education in the community or schools in the prevention or detection of the abuse of drugs or alcohol; or for security cameras used for the prevention or detection of violence, except that amounts distributed to the Secretary of State shall be deposited into the Secretary of State Evidence Fund to be used as provided in Section 2-115 of the Illinois Vehicle Code.</p><p>Any local, municipal, or county law enforcement agency entitled to receive a monetary distribution of forfeiture proceeds may share those forfeiture proceeds pursuant to the terms of an intergovernmental agreement with a municipality that has a population in excess of 20,000 if:</p><p class='subparagraph'>\(A) the receiving agency has entered into an intergovernmental agreement with the municipality to provide police services;</p><p class='subparagraph'>\(B) the intergovernmental agreement for police services provides for consideration in an amount of not less than $1,000,000 per year;</p><p class='subparagraph'>\(C) the seizure took place within the geographical limits of the municipality; and</p><p class='subparagraph'>\(D) the funds are used only for the enforcement of criminal laws; for public education in the community or schools in the prevention or detection of the abuse of drugs or alcohol; or for security cameras used for the prevention or detection of violence or the establishment of a municipal police force, including the training of officers, construction of a police station, the purchase of law enforcement equipment, or vehicles.</p><p class='paragraph'>\(2) 12.5% shall be distributed to the Office of the</p><p>State's Attorney of the county in which the prosecution resulting in the forfeiture was instituted, deposited in a special fund in the county treasury and appropriated to the State's Attorney for use, at the discretion of the State's Attorney, in the enforcement of criminal laws; or for public education in the community or schools in the prevention or detection of the abuse of drugs or alcohol; or at the discretion of the State's Attorney, in addition to other authorized purposes, to make grants to local substance abuse treatment facilities and half-way houses. In counties over 3,000,000 population, 25% will be distributed to the Office of the State's Attorney for use, at the discretion of the State's Attorney, in the enforcement of criminal laws; or for public education in the community or schools in the prevention or detection of the abuse of drugs or alcohol; or at the discretion of the State's Attorney, in addition to other authorized purposes, to make grants to local substance abuse treatment facilities and half-way houses. If the prosecution is undertaken solely by the Attorney General, the portion provided shall be distributed to the Attorney General for use in the enforcement of criminal laws governing cannabis and controlled substances or for public education in the community or schools in the prevention or detection of the abuse of drugs or alcohol.</p><p>12.5% shall be distributed to the Office of the</p><p>State's Attorneys Appellate Prosecutor and shall be used at the discretion of the State's Attorneys Appellate Prosecutor for additional expenses incurred in the investigation, prosecution and appeal of cases arising in the enforcement of criminal laws; or for public education in the community or schools in the prevention or detection of the abuse of drugs or alcohol. The Office of the State's Attorneys Appellate Prosecutor shall not receive distribution from cases brought in counties with over 3,000,000 population.</p><p class='paragraph'>\(3) 10% shall be retained by the Illinois State</p><p>Police for expenses related to the administration and sale of seized and forfeited property.</p><p class='subsection'>\(d) A law enforcement agency shall not retain forfeited property for its own use or transfer the property to any person or entity, except as provided under this Section. A law enforcement agency may apply in writing to the Director of the Illinois State Police to request that forfeited property be awarded to the agency for a specifically articulated official law enforcement use in an investigation. The Director of the Illinois State Police shall provide a written justification in each instance detailing the reasons why the forfeited property was placed into official use, and the justification shall be retained for a period of not less than 3 years.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (720 ILCS 5/36-9)
## Sec. 36-9. Reporting.
<p>Property seized or forfeited under this Article is subject to reporting under the Seizure and Forfeiture Reporting Act.</p><p>(Source: P.A. 100-512, eff. 7-1-18 .)</p>