# Article 33g. Illinois Street Gang {.unnumbered}

<p>AND RACKETEER INFLUENCED AND CORRUPT ORGANIZATIONS LAW</p><p>(Article scheduled to be repealed on June 11, 2023)</p><p>(Source: P.A. 97-686, eff. 6-11-12 .)</p>### (720 ILCS 5/33G-1)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-1. Short title.
<p>This Article may be cited as the Illinois Street Gang and Racketeer Influenced and Corrupt Organizations Law (or "RICO").</p><p>(Source: P.A. 97-686, eff. 6-11-12 .)</p>### (720 ILCS 5/33G-2)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-2. Legislative declaration.
<p>The substantial harm inflicted on the people and economy of this State by pervasive violent street gangs and other forms of enterprise criminality, is legitimately a matter of grave concern to the people of this State who have a basic right to be protected from that criminal activity and to be given adequate remedies to redress its harms. Whereas the current laws of this State provide inadequate remedies, procedures and punishments, the Illinois General Assembly hereby gives the supplemental remedies of the Illinois Street Gang and Racketeer Influenced and Corrupt Organizations Law full force and effect under law for the common good of this State and its people.</p><p>(Source: P.A. 97-686, eff. 6-11-12 .)</p>### (720 ILCS 5/33G-3)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-3. Definitions.
<p>As used in this Article:</p><p class='subsection'>\(a) "Another state" means any State of the United States (other than the State of Illinois), or the District of Columbia, or the Commonwealth of Puerto Rico, or any territory or possession of the United States, or any political subdivision, or any department, agency, or instrumentality thereof.</p><p class='subsection'>\(b) "Enterprise" includes:</p><p class='paragraph'>\(1) any partnership, corporation, association, business or charitable trust, or other legal entity; and</p><p class='paragraph'>\(2) any group of individuals or other legal entities, or any combination thereof, associated in fact although not itself a legal entity. An association in fact must be held together by a common purpose of engaging in a course of conduct, and it may be associated together for purposes that are both legal and illegal. An association in fact must:</p><p class='subparagraph'>\(A) have an ongoing organization or structure, either formal or informal;</p><p class='subparagraph'>\(B) the various members of the group must function as a continuing unit, even if the group changes membership by gaining or losing members over time; and</p><p class='subparagraph'>\(C) have an ascertainable structure distinct from that inherent in the conduct of a pattern of predicate activity.</p><p>As used in this Article, "enterprise" includes licit and illicit enterprises.</p><p class='subsection'>\(c) "Labor organization" includes any organization, labor union, craft union, or any voluntary unincorporated association designed to further the cause of the rights of union labor that is constituted for the purpose, in whole or in part, of collective bargaining or of dealing with employers concerning grievances, terms or conditions of employment, or apprenticeships or applications for apprenticeships, or of other mutual aid or protection in connection with employment, including apprenticeships or applications for apprenticeships.</p><p class='subsection'>\(d) "Operation or management" means directing or carrying out the enterprise's affairs and is limited to any person who knowingly serves as a leader, organizer, operator, manager, director, supervisor, financier, advisor, recruiter, supplier, or enforcer of an enterprise in violation of this Article.</p><p class='subsection'>\(e) "Predicate activity" means any act that is a Class 2 felony or higher and constitutes a violation or violations of any of the following provisions of the laws of the State of Illinois (as amended or revised as of the date the activity occurred or, in the instance of a continuing offense, the date that charges under this Article are filed in a particular matter in the State of Illinois) or any act under the law of another jurisdiction for an offense that could be charged as a Class 2 felony or higher in this State:</p><p class='paragraph'>\(1) under the Criminal Code of 1961 or the Criminal</p><p>Code of 2012: 8-1.2 (solicitation of murder for hire), 9-1 (first degree murder), 9-3.3 (drug-induced homicide), 10-1 (kidnapping), 10-2 (aggravated kidnapping), 10-3.1 (aggravated unlawful restraint), 10-4 (forcible detention), 10-5(b)(10) (child abduction), 10-9 (trafficking in persons, involuntary servitude, and related offenses), 11-1.20 (criminal sexual assault), 11-1.30 (aggravated criminal sexual assault), 11-1.40 (predatory criminal sexual assault of a child), 11-1.60 (aggravated criminal sexual abuse), 11-6 (indecent solicitation of a child), 11-6.5 (indecent solicitation of an adult), 11-14.3(a)(2)(A) and (a)(2)(B) (promoting prostitution), 11-14.4 (promoting juvenile prostitution), 11-18.1 (patronizing a minor engaged in prostitution; patronizing a juvenile prostitute), 12-3.05 (aggravated battery), 12-6.4 (criminal street gang recruitment), 12-6.5 (compelling organization membership of persons), 12-7.3 (stalking), 12-7.4 (aggravated stalking), 12-7.5 (cyberstalking), 12-11 or 19-6 (home invasion), 12-11.1 or 18-6 (vehicular invasion), 18-1 (robbery; aggravated robbery), 18-2 (armed robbery), 18-3 (vehicular hijacking), 18-4 (aggravated vehicular hijacking), 18-5 (aggravated robbery), 19-1 (burglary), 19-3 (residential burglary), 20-1 (arson; residential arson; place of worship arson), 20-1.1 (aggravated arson), 20-1.2 (residential arson), 20-1.3 (place of worship arson), 24-1.2 (aggravated discharge of a firearm), 24-1.2-5 (aggravated discharge of a machine gun or silencer equipped firearm), 24-1.8 (unlawful possession of a firearm by a street gang member), 24-3.2 (unlawful discharge of firearm projectiles), 24-3.9 (aggravated possession of a stolen firearm), 24-3A (gunrunning), 26-5 or 48-1 (dog-fighting), 29D-14.9 (terrorism), 29D-15 (soliciting support for terrorism), 29D-15.1 (causing a catastrophe), 29D-15.2 (possession of a deadly substance), 29D-20 (making a terrorist threat), 29D-25 (falsely making a terrorist threat), 29D-29.9 (material support for terrorism), 29D-35 (hindering prosecution of terrorism), 31A-1.2 (unauthorized contraband in a penal institution), or 33A-3 (armed violence);</p><p class='paragraph'>\(2) under the Cannabis Control Act: Sections 5</p><p class='subsection'>\(manufacture or delivery of cannabis), 5.1 (cannabis trafficking), or 8 (production or possession of cannabis plants), provided the offense either involves more than 500 grams of any substance containing cannabis or involves more than 50 cannabis sativa plants;</p><p class='paragraph'>\(3) under the Illinois Controlled Substances Act:</p><p>Sections 401 (manufacture or delivery of a controlled substance), 401.1 (controlled substance trafficking), 405 (calculated criminal drug conspiracy), or 405.2 (street gang criminal drug conspiracy); or</p><p class='paragraph'>\(4) under the Methamphetamine Control and Community</p><p>Protection Act: Sections 15 (methamphetamine manufacturing), or 55 (methamphetamine delivery).</p><p class='subsection'>\(f) "Pattern of predicate activity" means:</p><p class='paragraph'>\(1) at least 3 occurrences of predicate activity that are in some way related to each other and that have continuity between them, and that are separate acts. Acts are related to each other if they are not isolated events, including if they have similar purposes, or results, or participants, or victims, or are committed a similar way, or have other similar distinguishing characteristics, or are part of the affairs of the same enterprise. There is continuity between acts if they are ongoing over a substantial period, or if they are part of the regular way some entity does business or conducts its affairs; and</p><p class='paragraph'>\(2) which occurs after the effective date of this</p><p>Article, and the last of which falls within 3 years (excluding any period of imprisonment) after the first occurrence of predicate activity.</p><p class='subsection'>\(g) "Unlawful death" includes the following offenses: under the Code of 1961 or the Criminal Code of 2012: Sections 9-1 (first degree murder) or 9-2 (second degree murder).</p><p>(Source: P.A. 97-686, eff. 6-11-12; 97-1150, eff. 1-25-13 .)</p>### (720 ILCS 5/33G-4)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-4. Prohibited activities.
<p class='subsection'>\(a) It is unlawful for any person, who intentionally participates in the operation or management of an enterprise, directly or indirectly, to:</p><p class='paragraph'>\(1) knowingly do so, directly or indirectly, through a pattern of predicate activity;</p><p class='paragraph'>\(2) knowingly cause another to violate this Article; or</p><p class='paragraph'>\(3) knowingly conspire to violate this Article.</p><p>Notwithstanding any other provision of law, in any prosecution for a conspiracy to violate this Article, no person may be convicted of that conspiracy unless an overt act in furtherance of the agreement is alleged and proved to have been committed by him, her, or by a coconspirator, but the commission of the overt act need not itself constitute predicate activity underlying the specific violation of this Article.</p><p class='subsection'>\(b) It is unlawful for any person knowingly to acquire or maintain, directly or indirectly, through a pattern of predicate activity any interest in, or control of, to any degree, any enterprise, real property, or personal property of any character, including money.</p><p class='subsection'>\(c) Nothing in this Article shall be construed as to make unlawful any activity which is arguably protected or prohibited by the National Labor Relations Act, the Illinois Educational Labor Relations Act, the Illinois Public Labor Relations Act, or the Railway Labor Act.</p><p class='subsection'>\(d) The following organizations, and any officer or agent of those organizations acting in his or her official capacity as an officer or agent, may not be sued in civil actions under this Article:</p><p class='paragraph'>\(1) a labor organization; or</p><p class='paragraph'>\(2) any business defined in Division D, E, F, G, H, or I of the Standard Industrial Classification as established by the Occupational Safety and Health Administration, U.S. Department of Labor.</p><p class='subsection'>\(e) Any person prosecuted under this Article may be convicted and sentenced either:</p><p class='paragraph'>\(1) for the offense of conspiring to violate this</p><p>Article, and for any other particular offense or offenses that may be one of the objects of a conspiracy to violate this Article; or</p><p class='paragraph'>\(2) for the offense of violating this Article, and for any other particular offense or offenses that may constitute predicate activity underlying a violation of this Article.</p><p class='subsection'>\(f) The State's Attorney, or a person designated by law to act for him or her and to perform his or her duties during his or her absence or disability, may authorize a criminal prosecution under this Article. Prior to any State's Attorney authorizing a criminal prosecution under this Article, the State's Attorney shall adopt rules and procedures governing the investigation and prosecution of any offense enumerated in this Article. These rules and procedures shall set forth guidelines which require that any potential prosecution under this Article be subject to an internal approval process in which it is determined, in a written prosecution memorandum prepared by the State's Attorney's Office, that (1) a prosecution under this Article is necessary to ensure that the indictment adequately reflects the nature and extent of the criminal conduct involved in a way that prosecution only on the underlying predicate activity would not, and (2) a prosecution under this Article would provide the basis for an appropriate sentence under all the circumstances of the case in a way that a prosecution only on the underlying predicate activity would not. No State's Attorney, or person designated by law to act for him or her and to perform his or her duties during his or her absence or disability, may authorize a criminal prosecution under this Article prior to reviewing the prepared written prosecution memorandum. However, any internal memorandum shall remain protected from disclosure under the attorney-client privilege, and this provision does not create any enforceable right on behalf of any defendant or party, nor does it subject the exercise of prosecutorial discretion to judicial review.</p><p class='subsection'>\(g) A labor organization and any officer or agent of that organization acting in his or her capacity as an officer or agent of the labor organization are exempt from prosecution under this Article.</p><p>(Source: P.A. 97-686, eff. 6-11-12; 98-463, eff. 8-16-13 .)</p>### (720 ILCS 5/33G-5)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-5. Penalties.
<p>Under this Article, notwithstanding any other provision of law:</p><p class='subsection'>\(a) Any violation of subsection (a) of Section 33G-4 of this Article shall be sentenced as a Class X felony with a term of imprisonment of not less than 7 years and not more than 30 years, or the sentence applicable to the underlying predicate activity, whichever is higher, and the sentence imposed shall also include restitution, and/or a criminal fine, jointly and severally, up to $250,000 or twice the gross amount of any intended proceeds of the violation, if any, whichever is higher.</p><p class='subsection'>\(b) Any violation of subsection (b) of Section 33G-4 of this Article shall be sentenced as a Class X felony, and the sentence imposed shall also include restitution, and/or a criminal fine, jointly and severally, up to $250,000 or twice the gross amount of any intended proceeds of the violation, if any, whichever is higher.</p><p class='subsection'>\(c) Wherever the unlawful death of any person or persons results as a necessary or natural consequence of any violation of this Article, the sentence imposed on the defendant shall include an enhanced term of imprisonment of at least 25 years up to natural life, in addition to any other penalty imposed by the court, provided:</p><p class='paragraph'>\(1) the death or deaths were reasonably foreseeable to the defendant to be sentenced; and</p><p class='paragraph'>\(2) the death or deaths occurred when the defendant was otherwise engaged in the violation of this Article as a whole.</p><p class='subsection'>\(d) A sentence of probation, periodic imprisonment, conditional discharge, impact incarceration or county impact incarceration, court supervision, withheld adjudication, or any pretrial diversionary sentence or suspended sentence, is not authorized for a violation of this Article.</p><p>(Source: P.A. 97-686, eff. 6-11-12; 98-463, eff. 8-16-13 .)</p>### (720 ILCS 5/33G-6)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-6. Remedial proceedings, procedures, and forfeiture.
<p class='subsection'>\(a) Under this Article, the circuit court shall have jurisdiction to prevent and restrain violations of this Article by issuing appropriate orders, including:</p><p class='paragraph'>\(1) ordering any person to disgorge illicit proceeds obtained by a violation of this Article or divest himself or herself of any interest, direct or indirect, in any enterprise or real or personal property of any character, including money, obtained, directly or indirectly, by a violation of this Article;</p><p class='paragraph'>\(2) imposing reasonable restrictions on the future activities or investments of any person or enterprise, including prohibiting any person or enterprise from engaging in the same type of endeavor as the person or enterprise engaged in, that violated this Article; or</p><p class='paragraph'>\(3) ordering dissolution or reorganization of any enterprise, making due provision for the rights of innocent persons.</p><p class='subsection'>\(b) Any violation of this Article is subject to the remedies, procedures, and forfeiture as set forth in Article 29B of this Code.</p><p class='subsection'>\(c) Property seized or forfeited under this Article is subject to reporting under the Seizure and Forfeiture Reporting Act.</p><p>(Source: P.A. 100-512, eff. 7-1-18; 100-699, eff. 8-3-18; 101-81, eff. 7-12-19 .)</p>### (720 ILCS 5/33G-7)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-7. Construction.
<p>In interpreting the provisions of this Article, the court shall construe them in light of the applicable model jury instructions set forth in the Federal Criminal Jury Instructions for the Seventh Circuit (1999) for Title IX of Public Law 91-452, 84 Stat. 922 (as amended in Title 18, United States Code, Sections 1961 through 1968), except to the extent that they are inconsistent with the plain language of this Article.</p><p>(Source: P.A. 97-686, eff. 6-11-12; 98-463, eff. 8-16-13 .)</p>### (720 ILCS 5/33G-8)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-8. Limitations.
<p>Under this Article, notwithstanding any other provision of law, but otherwise subject to the periods of exclusion from limitation as provided in Section 3-7 of this Code, the following limitations apply:</p><p class='subsection'>\(a) Any action, proceeding, or prosecution brought under this Article must commence within 5 years of one of the following dates, whichever is latest:</p><p class='paragraph'>\(1) the date of the commission of the last occurrence of predicate activity in a pattern of that activity, in the form of an act underlying the alleged violation of this Article; or</p><p class='paragraph'>\(2) in the case of an action, proceeding, or prosecution, based upon a conspiracy to violate this Article, the date that the last objective of the alleged conspiracy was accomplished, defeated or abandoned (whichever is later); or</p><p class='paragraph'>\(3) the date any minor victim of the violation attains the age of 18 years or the date any victim of the violation subject to a legal disability thereafter gains legal capacity.</p><p class='subsection'>\(b) Any action, proceeding, or prosecution brought under this Article may be commenced at any time against all defendants if the conduct of any defendant, or any part of the overall violation, resulted in the unlawful death of any person or persons.</p><p>(Source: P.A. 97-686, eff. 6-11-12 .)</p>### (720 ILCS 5/33G-9)
<p>(Section scheduled to be repealed on June 11, 2023)</p>## Sec. 33G-9. Repeal.
<p>This Article is repealed on June 11, 2023.</p><p>(Source: P.A. 102-918, eff. 5-27-22.)</p>### (720 ILCS 5/Tit. IV heading)
<p>TITLE IV.</p><p>CONSTRUCTION, EFFECTIVE DATE AND REPEAL</p>