# Article 29a. Commercial Bribery {.unnumbered}

### (720 ILCS 5/29A-1) (from Ch. 38, par. 29A-1)
## Sec. 29A-1. A person commits commercial bribery when he confers, or offers or agrees to confer, any benefit upon any employee, agent or fiduciary without the consent of the latter's employer or principal, with intent to influence his conduct in relation to his employer's or principal's affairs.
<p>(Source: P.A. 76-1129 .)</p>### (720 ILCS 5/29A-2) (from Ch. 38, par. 29A-2)
## Sec. 29A-2. An employee, agent or fiduciary commits commercial bribe receiving when, without consent of his employer or principal, he solicits, accepts or agrees to accept any benefit from another person upon an agreement or understanding that such benefit will influence his conduct in relation to his employer's or principal's affairs.
<p>(Source: P.A. 76-1129 .)</p>### (720 ILCS 5/29A-3) (from Ch. 38, par. 29A-3)
## Sec. 29A-3. Sentence.
<p class='subsection'>\(a) If the benefit offered, conferred, or agreed to be conferred, solicited, accepted or agreed to be accepted is less than $500,000, commercial bribery or commercial bribe receiving is a Class A misdemeanor and the sentence shall include, but not be limited to, a fine not to exceed $5,000.</p><p class='subsection'>\(b) If the benefit offered, conferred, or agreed to be conferred, solicited, accepted, or agreed to be accepted in violation of this Article is $500,000 or more, the offender is guilty of a Class 3 felony.</p><p>(Source: P.A. 93-496, eff. 1-1-04.)</p>### (720 ILCS 5/29A-4)
## Sec. 29A-4. Corporate Crime Fund.
<p class='subsection'>\(a) In addition to any fines, penalties, and assessments otherwise authorized under this Code, any person convicted of a violation of this Article or Section 17-26 or 17-27 of this Code shall be assessed a penalty of not more than 3 times the value of all property involved in the criminal activity.</p><p class='subsection'>\(b) The penalties assessed under subsection (a) shall be deposited into the Corporate Crime Fund, a special fund hereby created in the State treasury. Moneys in the Fund shall be used to make restitution to a person who has suffered property loss as a result of violations of this Article. The court may determine the reasonable amount, terms, and conditions of the restitution. In determining the amount and method of payment of restitution, the court shall take into account all financial resources of the defendant.</p><p>(Source: P.A. 93-496, eff. 1-1-04.)</p>