# Article 29. Bribery In Contests {.unnumbered}

### (720 ILCS 5/29-1) (from Ch. 38, par. 29-1)
## Sec. 29-1. Offering a bribe.
<p class='subsection'>\(a) Any person who, with intent to influence any person participating in, officiating or connected with any professional or amateur athletic contest, sporting event or exhibition, gives, offers or promises any money, bribe or other thing of value or advantage to induce such participant, official or other person not to use his best efforts in connection with such contest, event or exhibition commits a Class 4 felony.</p><p class='subsection'>\(b) Any person who, with the intent to influence the decision of any individual, offers or promises any money, bribe or other thing of value or advantage to induce such individual to attend, refrain from attending or continue to attend a particular public or private institution of secondary education or higher education for the purpose of participating or not participating in interscholastic athletic competition for such institution commits a Class A misdemeanor. This Section does not apply to the: (1) offering or awarding to an individual any type of scholarship, grant or other bona fide financial aid or employment; (2) offering of any type of financial assistance by such individual's family; or (3) offering of any item of de minimis value by such institution's authorities if such item is of the nature of an item that is commonly provided to any or all students or prospective students.</p><p class='subsection'>\(c) Any person who gives any money, goods or other thing of value to an individual enrolled in an institution of higher education who participates in interscholastic competition and represents or attempts to represent such individual in future negotiations for employment with any professional sports team commits a Class A misdemeanor.</p><p>(Source: P.A. 85-665 .)</p>### (720 ILCS 5/29-2) (from Ch. 38, par. 29-2)
## Sec. 29-2. Accepting a bribe.
<p>Any person participating in, officiating or connected with any professional or amateur athletic contest, sporting event or exhibition who accepts or agrees to accept any money, bribe or other thing of value or advantage with the intent, understanding or agreement that he will not use his best efforts in connection with such contest, event or exhibition commits a Class 4 felony.</p><p>(Source: P.A. 77-2638.)</p>### (720 ILCS 5/29-3) (from Ch. 38, par. 29-3)
## Sec. 29-3. Failure to report offer of bribe.
<p>Any person participating, officiating or connected with any professional or amateur athletic contest, sporting event or exhibition who fails to report forthwith to his employer, the promoter of such contest, event or exhibition, a peace officer, or the local State's Attorney any offer or promise made to him in violation of Section 29-1 commits a Class A misdemeanor.</p><p>(Source: P.A. 77-2638.)</p>