# Article 48. Animals {.unnumbered}

<p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/48-1)
<p class='subsection'>\(was 720 ILCS 5/26-5)</p>## Sec. 48-1. Dog fighting.
<p>(For other provisions that may apply to dog fighting, see the Humane Care for Animals Act. For provisions similar to this Section that apply to animals other than dogs, see in particular Section 4.01 of the Humane Care for Animals Act.)</p><p class='subsection'>\(a) No person may own, capture, breed, train, or lease any dog which he or she knows is intended for use in any show, exhibition, program, or other activity featuring or otherwise involving a fight between the dog and any other animal or human, or the intentional killing of any dog for the purpose of sport, wagering, or entertainment.</p><p class='subsection'>\(b) No person may promote, conduct, carry on, advertise, collect money for or in any other manner assist or aid in the presentation for purposes of sport, wagering, or entertainment of any show, exhibition, program, or other activity involving a fight between 2 or more dogs or any dog and human, or the intentional killing of any dog.</p><p class='subsection'>\(c) No person may sell or offer for sale, ship, transport, or otherwise move, or deliver or receive any dog which he or she knows has been captured, bred, or trained, or will be used, to fight another dog or human or be intentionally killed for purposes of sport, wagering, or entertainment.</p><p class='subsection'>\(c-5) No person may solicit a minor to violate this Section.</p><p class='subsection'>\(d) No person may manufacture for sale, shipment, transportation, or delivery any device or equipment which he or she knows or should know is intended for use in any show, exhibition, program, or other activity featuring or otherwise involving a fight between 2 or more dogs, or any human and dog, or the intentional killing of any dog for purposes of sport, wagering, or entertainment.</p><p class='subsection'>\(e) No person may own, possess, sell or offer for sale, ship, transport, or otherwise move any equipment or device which he or she knows or should know is intended for use in connection with any show, exhibition, program, or activity featuring or otherwise involving a fight between 2 or more dogs, or any dog and human, or the intentional killing of any dog for purposes of sport, wagering or entertainment.</p><p class='subsection'>\(f) No person may knowingly make available any site, structure, or facility, whether enclosed or not, that he or she knows is intended to be used for the purpose of conducting any show, exhibition, program, or other activity involving a fight between 2 or more dogs, or any dog and human, or the intentional killing of any dog or knowingly manufacture, distribute, or deliver fittings to be used in a fight between 2 or more dogs or a dog and human.</p><p class='subsection'>\(g) No person may knowingly attend or otherwise patronize any show, exhibition, program, or other activity featuring or otherwise involving a fight between 2 or more dogs, or any dog and human, or the intentional killing of any dog for purposes of sport, wagering, or entertainment.</p><p class='subsection'>\(h) No person may tie or attach or fasten any live animal to any machine or device propelled by any power for the purpose of causing the animal to be pursued by a dog or dogs. This subsection (h) applies only when the dog is intended to be used in a dog fight.</p><p class='item'>\(i) Sentence.</p><p class='paragraph'>\(1) Any person convicted of violating subsection (a),</p><p class='subsection'>\(b), (c), or (h) of this Section is guilty of a Class 4 felony for a first violation and a Class 3 felony for a second or subsequent violation, and may be fined an amount not to exceed $50,000.</p><p class='paragraph'>\(1.5) A person who knowingly owns a dog for fighting purposes or for producing a fight between 2 or more dogs or a dog and human or who knowingly offers for sale or sells a dog bred for fighting is guilty of a Class 3 felony and may be fined an amount not to exceed $50,000, if the dog participates in a dogfight and any of the following factors is present:</p><p class='item'>\(i) the dogfight is performed in the presence of a person under 18 years of age;</p><p class='item'>\(ii) the dogfight is performed for the purpose of or in the presence of illegal wagering activity; or</p><p class='item'>\(iii) the dogfight is performed in furtherance of streetgang related activity as defined in Section 10 of the Illinois Streetgang Terrorism Omnibus Prevention Act.</p><p class='paragraph'>\(1.7) A person convicted of violating subsection</p><p class='subsection'>\(c-5) of this Section is guilty of a Class 4 felony.</p><p class='paragraph'>\(2) Any person convicted of violating subsection (d) or (e) of this Section is guilty of a Class 4 felony for a first violation. A second or subsequent violation of subsection (d) or (e) of this Section is a Class 3 felony.</p><p class='paragraph'>\(2.5) Any person convicted of violating subsection</p><p class='subsection'>\(f) of this Section is guilty of a Class 4 felony. Any person convicted of violating subsection (f) of this Section in which the site, structure, or facility made available to violate subsection (f) is located within 1,000 feet of a school, public park, playground, child care institution, day care center, part day child care facility, day care home, group day care home, or a facility providing programs or services exclusively directed toward persons under 18 years of age is guilty of a Class 3 felony for a first violation and a Class 2 felony for a second or subsequent violation.</p><p class='paragraph'>\(3) Any person convicted of violating subsection (g) of this Section is guilty of a Class 4 felony for a first violation. A second or subsequent violation of subsection (g) of this Section is a Class 3 felony. If a person under 13 years of age is present at any show, exhibition, program, or other activity prohibited in subsection (g), the parent, legal guardian, or other person who is 18 years of age or older who brings that person under 13 years of age to that show, exhibition, program, or other activity is guilty of a Class 3 felony for a first violation and a Class 2 felony for a second or subsequent violation.</p><p class='item'>\(i-5) A person who commits a felony violation of this Section is subject to the property forfeiture provisions set forth in Article 124B of the Code of Criminal Procedure of 1963.</p><p class='subsection'>\(j) Any dog or equipment involved in a violation of this Section shall be immediately seized and impounded under Section 12 of the Humane Care for Animals Act when located at any show, exhibition, program, or other activity featuring or otherwise involving a dog fight for the purposes of sport, wagering, or entertainment.</p><p class='subsection'>\(k) Any vehicle or conveyance other than a common carrier that is used in violation of this Section shall be seized, held, and offered for sale at public auction by the sheriff's department of the proper jurisdiction, and the proceeds from the sale shall be remitted to the general fund of the county where the violation took place.</p><p class='subsection'>\(l) Any veterinarian in this State who is presented with a dog for treatment of injuries or wounds resulting from fighting where there is a reasonable possibility that the dog was engaged in or utilized for a fighting event for the purposes of sport, wagering, or entertainment shall file a report with the Department of Agriculture and cooperate by furnishing the owners' names, dates, and descriptions of the dog or dogs involved. Any veterinarian who in good faith complies with the requirements of this subsection has immunity from any liability, civil, criminal, or otherwise, that may result from his or her actions. For the purposes of any proceedings, civil or criminal, the good faith of the veterinarian shall be rebuttably presumed.</p><p class='subsection'>\(m) In addition to any other penalty provided by law, upon conviction for violating this Section, the court may order that the convicted person and persons dwelling in the same household as the convicted person who conspired, aided, or abetted in the unlawful act that was the basis of the conviction, or who knew or should have known of the unlawful act, may not own, harbor, or have custody or control of any dog or other animal for a period of time that the court deems reasonable.</p><p class='subsection'>\(n) A violation of subsection (a) of this Section may be inferred from evidence that the accused possessed any device or equipment described in subsection (d), (e), or (h) of this Section, and also possessed any dog.</p><p class='subsection'>\(o) When no longer required for investigations or court proceedings relating to the events described or depicted therein, evidence relating to convictions for violations of this Section shall be retained and made available for use in training peace officers in detecting and identifying violations of this Section. Such evidence shall be made available upon request to other law enforcement agencies and to schools certified under the Illinois Police Training Act.</p><p class='subsection'>\(p) For the purposes of this Section, "school" has the meaning ascribed to it in Section 11-9.3 of this Code; and "public park", "playground", "child care institution", "day care center", "part day child care facility", "day care home", "group day care home", and "facility providing programs or services exclusively directed toward persons under 18 years of age" have the meanings ascribed to them in Section 11-9.4 of this Code.</p><p>(Source: P.A. 96-226, eff. 8-11-09; 96-712, eff. 1-1-10; 96-1000, eff. 7-2-10; 96-1091, eff. 1-1-11; 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/48-2)
## Sec. 48-2. Animal research and production facilities protection.
<p class='subsection'>\(a) Definitions.</p><p>"Animal" means every living creature, domestic or wild, but does not include man.</p><p>"Animal facility" means any facility engaging in legal scientific research or agricultural production of or involving the use of animals including any organization with a primary purpose of representing livestock production or processing, any organization with a primary purpose of promoting or marketing livestock or livestock products, any person licensed to practice veterinary medicine, any institution as defined in the Impounding and Disposition of Stray Animals Act, and any organization with a primary purpose of representing any such person, organization, or institution. "Animal facility" shall include the owner, operator, and employees of any animal facility and any premises where animals are located.</p><p>"Director" means the Director of the Illinois</p><p>Department of Agriculture or the Director's authorized representative.</p><p class='subsection'>\(b) Legislative Declaration. There has been an increasing number of illegal acts committed against animal research and production facilities involving injury or loss of life to humans or animals, criminal trespass and damage to property. These actions not only abridge the property rights of the owner of the facility, they may also damage the public interest by jeopardizing crucial scientific, biomedical, or agricultural research or production. These actions can also threaten the public safety by possibly exposing communities to serious public health concerns and creating traffic hazards. These actions may substantially disrupt or damage publicly funded research and can result in the potential loss of physical and intellectual property. Therefore, it is in the interest of the people of the State of Illinois to protect the welfare of humans and animals as well as productive use of public funds to require regulation to prevent unauthorized possession, alteration, destruction, or transportation of research records, test data, research materials, equipment, research and agricultural production animals.</p><p class='subsection'>\(c) It shall be unlawful for any person:</p><p class='paragraph'>\(1) to release, steal, or otherwise intentionally cause the death, injury, or loss of any animal at or from an animal facility and not authorized by that facility;</p><p class='paragraph'>\(2) to damage, vandalize, or steal any property in or on an animal facility;</p><p class='paragraph'>\(3) to obtain access to an animal facility by false pretenses for the purpose of performing acts not authorized by that facility;</p><p class='paragraph'>\(4) to enter into an animal facility with an intent to destroy, alter, duplicate, or obtain unauthorized possession of records, data, materials, equipment, or animals;</p><p class='paragraph'>\(5) by theft or deception knowingly to obtain control or to exert control over records, data, material, equipment, or animals of any animal facility for the purpose of depriving the rightful owner or animal facility of the records, material, data, equipment, or animals or for the purpose of concealing, abandoning, or destroying these records, material, data, equipment, or animals; or</p><p class='paragraph'>\(6) to enter or remain on an animal facility with the intent to commit an act prohibited under this Section.</p><p class='subsection'>\(d) Sentence.</p><p class='paragraph'>\(1) Any person who violates any provision of subsection (c) shall be guilty of a Class 4 felony for each violation, unless the loss, theft, or damage to the animal facility property exceeds $300 in value.</p><p class='paragraph'>\(2) If the loss, theft, or damage to the animal facility property exceeds $300 in value but does not exceed $10,000 in value, the person is guilty of a Class 3 felony.</p><p class='paragraph'>\(3) If the loss, theft, or damage to the animal facility property exceeds $10,000 in value but does not exceed $100,000 in value, the person is guilty of a Class 2 felony.</p><p class='paragraph'>\(4) If the loss, theft, or damage to the animal facility property exceeds $100,000 in value, the person is guilty of a Class 1 felony.</p><p class='paragraph'>\(5) Any person who, with the intent that any violation of any provision of subsection (c) be committed, agrees with another to the commission of the violation and commits an act in furtherance of this agreement is guilty of the same class of felony as provided in paragraphs (1) through (4) of this subsection for that violation.</p><p class='paragraph'>\(6) Restitution.</p><p class='subparagraph'>\(A) The court shall conduct a hearing to determine the reasonable cost of replacing materials, data, equipment, animals and records that may have been damaged, destroyed, lost or cannot be returned, and the reasonable cost of repeating any experimentation that may have been interrupted or invalidated as a result of a violation of subsection (c).</p><p class='subparagraph'>\(B) Any persons convicted of a violation shall be ordered jointly and severally to make restitution to the owner, operator, or both, of the animal facility in the full amount of the reasonable cost determined under paragraph (A).</p><p class='subsection'>\(e) Private right of action. Nothing in this Section shall preclude any animal facility injured in its business or property by a violation of this Section from seeking appropriate relief under any other provision of law or remedy including the issuance of a permanent injunction against any person who violates any provision of this Section. The animal facility owner or operator may petition the court to permanently enjoin the person from violating this Section and the court shall provide this relief.</p><p class='subsection'>\(f) The Director shall have authority to investigate any alleged violation of this Section, along with any other law enforcement agency, and may take any action within the Director's authority necessary for the enforcement of this Section. State's Attorneys, State police and other law enforcement officials shall provide any assistance required in the conduct of an investigation and prosecution. Before the Director reports a violation for prosecution he or she may give the owner or operator of the animal facility and the alleged violator an opportunity to present his or her views at an administrative hearing. The Director may adopt any rules and regulations necessary for the enforcement of this Section.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/48-3)
## Sec. 48-3. Hunter or fisherman interference.
<p class='subsection'>\(a) Definitions. As used in this Section:</p><p>"Aquatic life" means all fish, reptiles, amphibians, crayfish, and mussels the taking of which is authorized by the Fish and Aquatic Life Code.</p><p>"Interfere with" means to take any action that physically impedes, hinders, or obstructs the lawful taking of wildlife or aquatic life.</p><p>"Taking" means the capture or killing of wildlife or aquatic life and includes travel, camping, and other acts preparatory to taking which occur on lands or waters upon which the affected person has the right or privilege to take such wildlife or aquatic life.</p><p>"Wildlife" means any wildlife the taking of which is authorized by the Wildlife Code and includes those species that are lawfully released by properly licensed permittees of the Department of Natural Resources.</p><p class='subsection'>\(b) A person commits hunter or fisherman interference when he or she intentionally or knowingly:</p><p class='paragraph'>\(1) obstructs or interferes with the lawful taking of wildlife or aquatic life by another person with the specific intent to prevent that lawful taking;</p><p class='paragraph'>\(2) drives or disturbs wildlife or aquatic life for the purpose of disrupting a lawful taking of wildlife or aquatic life;</p><p class='paragraph'>\(3) blocks, impedes, or physically harasses another person who is engaged in the process of lawfully taking wildlife or aquatic life;</p><p class='paragraph'>\(4) uses natural or artificial visual, aural, olfactory, gustatory, or physical stimuli to affect wildlife or aquatic life behavior in order to hinder or prevent the lawful taking of wildlife or aquatic life;</p><p class='paragraph'>\(5) erects barriers with the intent to deny ingress or egress to or from areas where the lawful taking of wildlife or aquatic life may occur;</p><p class='paragraph'>\(6) intentionally interjects himself or herself into the line of fire or fishing lines of a person lawfully taking wildlife or aquatic life;</p><p class='paragraph'>\(7) affects the physical condition or placement of personal or public property intended for use in the lawful taking of wildlife or aquatic life in order to impair the usefulness of the property or prevent the use of the property;</p><p class='paragraph'>\(8) enters or remains upon or over private lands without the permission of the owner or the owner's agent, with the intent to violate this subsection;</p><p class='paragraph'>\(9) fails to obey the order of a peace officer to desist from conduct in violation of this subsection (b) if the officer observes the conduct, or has reasonable grounds to believe that the person has engaged in the conduct that day or that the person plans or intends to engage in the conduct that day on a specific premises; or</p><p class='paragraph'>\(10) uses a drone in a way that interferes with another person's lawful taking of wildlife or aquatic life. For the purposes of this paragraph (10), "drone" means any aerial vehicle that does not carry a human operator.</p><p class='subsection'>\(c) Exemptions; defenses.</p><p class='paragraph'>\(1) This Section does not apply to actions performed by authorized employees of the Department of Natural Resources, duly accredited officers of the U.S. Fish and Wildlife Service, sheriffs, deputy sheriffs, or other peace officers if the actions are authorized by law and are necessary for the performance of their official duties.</p><p class='paragraph'>\(2) This Section does not apply to landowners, tenants, or lease holders exercising their legal rights to the enjoyment of land, including, but not limited to, farming and restricting trespass.</p><p class='paragraph'>\(3) It is an affirmative defense to a prosecution for a violation of this Section that the defendant's conduct is protected by his or her right to freedom of speech under the constitution of this State or the United States.</p><p class='paragraph'>\(4) Any interested parties may engage in protests or other free speech activities adjacent to or on the perimeter of the location where the lawful taking of wildlife or aquatic life is taking place, provided that none of the provisions of this Section are being violated.</p><p class='subsection'>\(d) Sentence. A first violation of paragraphs (1) through (8) of subsection (b) is a Class B misdemeanor. A second or subsequent violation of paragraphs (1) through (8) of subsection (b) is a Class A misdemeanor for which imprisonment for not less than 7 days shall be imposed. A person guilty of a second or subsequent violation of paragraphs (1) through (8) of subsection (b) is not eligible for court supervision. A violation of paragraph (9) or (10) of subsection (b) is a Class A misdemeanor. A court shall revoke, for a period of one year to 5 years, any Illinois hunting, fishing, or trapping privilege, license or permit of any person convicted of violating any provision of this Section. For purposes of this subsection, a "second or subsequent violation" means a conviction under paragraphs (1) through (8) of subsection (b) of this Section within 2 years of a prior violation arising from a separate set of circumstances.</p><p class='subsection'>\(e) Injunctions; damages.</p><p class='paragraph'>\(1) Any court may enjoin conduct which would be in violation of paragraphs (1) through (8) or (10) of subsection (b) upon petition by a person affected or who reasonably may be affected by the conduct, upon a showing that the conduct is threatened or that it has occurred on a particular premises in the past and that it is not unreasonable to expect that under similar circumstances it will be repeated.</p><p class='paragraph'>\(2) A court shall award all resulting costs and damages to any person adversely affected by a violation of paragraphs (1) through (8) or (10) of subsection (b), which may include an award for punitive damages. In addition to other items of special damage, the measure of damages may include expenditures of the affected person for license and permit fees, travel, guides, special equipment and supplies, to the extent that these expenditures were rendered futile by prevention of the taking of wildlife or aquatic life.</p><p>(Source: P.A. 97-1108, eff. 1-1-13; 98-402, eff. 8-16-13.)</p>### (720 ILCS 5/48-4)
## Sec. 48-4. Obtaining certificate of registration by false pretenses.
<p class='subsection'>\(a) A person commits obtaining certificate of registration by false pretenses when he or she, by any false pretense, obtains from any club, association, society or company for improving the breed of cattle, horses, sheep, swine, or other domestic animals, a certificate of registration of any animal in the herd register, or other register of any club, association, society or company, or a transfer of the registration.</p><p class='subsection'>\(b) A person commits obtaining certificate of registration by false pretenses when he or she knowingly gives a false pedigree of any animal.</p><p class='subsection'>\(c) Sentence. Obtaining certificate of registration by false pretenses is a Class A misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/48-5)
## Sec. 48-5. Horse mutilation.
<p class='subsection'>\(a) A person commits horse mutilation when he or she cuts the solid part of the tail of any horse in the operation known as docking, or by any other operation performed for the purpose of shortening the tail, and whoever shall cause the same to be done, or assist in doing this cutting, unless the same is proved to be a benefit to the horse.</p><p class='subsection'>\(b) Sentence. Horse mutilation is a Class A misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/48-6)
## Sec. 48-6. Horse racing false entry.
<p class='subsection'>\(a) That in order to encourage the breeding of and improvement in trotting, running and pacing horses in the State, it is hereby made unlawful for any person or persons knowingly to enter or cause to be entered for competition, or knowingly to compete with any horse, mare, gelding, colt or filly under any other than its true name or out of its proper class for any purse, prize, premium, stake or sweepstakes offered or given by any agricultural or other society, association, person or persons in the State where the prize, purse, premium, stake or sweepstakes is to be decided by a contest of speed.</p><p class='subsection'>\(b) The name of any horse, mare, gelding, colt or filly, for the purpose of entry for competition or performance in any contest of speed, shall be the name under which the horse has publicly performed, and shall not be changed after having once so performed or contested for a prize, purse, premium, stake or sweepstakes, except as provided by the code of printed rules of the society or association under which the contest is advertised to be conducted.</p><p class='subsection'>\(c) The official records shall be received in all courts as evidence upon the trial of any person under the provisions of this Section.</p><p class='subsection'>\(d) Sentence. A violation of subsection (a) is a Class 4 felony.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/48-7)
## Sec. 48-7. Feeding garbage to animals.
<p class='subsection'>\(a) Definitions. As used in this Section:</p><p>"Department" means the Department of Agriculture of the State of Illinois.</p><p>"Garbage" has the same meaning as in the federal Swine Health Protection Act (7 U.S.C. 3802) and also includes putrescible vegetable waste. "Garbage" does not include the contents of the bovine digestive tract.</p><p>"Person" means any person, firm, partnership, association, corporation, or other legal entity, any public or private institution, the State, or any municipal corporation or political subdivision of the State.</p><p class='subsection'>\(b) A person commits feeding garbage to animals when he or she feeds or permits the feeding of garbage to swine or any animals or poultry on any farm or any other premises where swine are kept.</p><p class='subsection'>\(c) Establishments licensed under the Animal Mortality Act or under similar laws in other states are exempt from the provisions of this Section.</p><p class='subsection'>\(d) Nothing in this Section shall be construed to apply to any person who feeds garbage produced in his or her own household to animals or poultry kept on the premises where he or she resides except this garbage if fed to swine shall not contain particles of meat.</p><p class='subsection'>\(e) Sentence. Feeding garbage to animals is a Class B misdemeanor, and for the first offense shall be fined not less than $100 nor more than $500 and for a second or subsequent offense shall be fined not less than $200 nor more than $500 or imprisoned in a penal institution other than the penitentiary for not more than 6 months, or both.</p><p class='subsection'>\(f) A person violating this Section may be enjoined by the Department from continuing the violation.</p><p class='subsection'>\(g) The Department may make reasonable inspections necessary for the enforcement of this Section, and is authorized to enforce, and administer the provisions of this Section.</p><p>(Source: P.A. 102-216, eff. 1-1-22 .)</p>### (720 ILCS 5/48-8)
## Sec. 48-8. Service animal access.
<p class='subsection'>\(a) When a  person with a physical, mental, or intellectual disability requiring the use of a service animal is accompanied by a service animal or when a trainer of a service animal is accompanied by a service animal, neither the person nor the service animal shall be denied the right of entry and use of facilities of any public place of accommodation as defined in Section 5-101 of the Illinois Human Rights Act.</p><p>For the purposes of this Section, "service animal" means a dog or miniature horse trained or being trained as a hearing animal, a guide animal, an assistance animal, a seizure alert animal, a mobility animal, a psychiatric service animal, an autism service animal, or an animal trained for any other physical, mental, or intellectual disability. "Service animal" includes a miniature horse that a public place of accommodation shall make reasonable accommodation so long as the public place of accommodation takes into consideration: (1) the type, size, and weight of the miniature horse and whether the facility can accommodate its features; (2) whether the handler has sufficient control of the miniature horse; (3) whether the miniature horse is housebroken; and (4) whether the miniature horse's presence in the facility compromises legitimate safety requirements necessary for operation.</p><p class='subsection'>\(b) A person who knowingly violates this Section commits a Class C misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13; incorporates 97-956, eff. 8-14-12; 97-1150, eff. 1-25-13.)</p>### (720 ILCS 5/48-9)
## Sec. 48-9. Misrepresentation of stallion and jack pedigree.
<p class='subsection'>\(a) The owner or keeper of any stallion or jack kept for public service commits misrepresentation of stallion and jack pedigree when he or she misrepresents the pedigree or breeding of the stallion or jack, or represents that the animal, so kept for public service, is registered, when in fact it is not registered in a published volume of a society for the registry of standard and purebred animals, or who shall post or publish, or cause to be posted or published, any false pedigree or breeding of this animal.</p><p class='subsection'>\(b) Sentence. Misrepresentation of stallion and jack pedigree is a petty offense, and for a second or subsequent offense is a Class B misdemeanor.</p><p>(Source: P.A. 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/48-10)
## Sec. 48-10. Dangerous animals.
<p class='subsection'>\(a) Definitions. As used in this Section, unless the context otherwise requires:</p><p>"Dangerous animal" means a lion, tiger, leopard, ocelot, jaguar, cheetah, margay, mountain lion, lynx, bobcat, jaguarundi, bear, hyena, wolf or coyote. Dangerous animal does not mean any herptiles included in the Herptiles-Herps Act.</p><p>"Owner" means any person who (1) has a right of property in a dangerous animal or primate, (2) keeps or harbors a dangerous animal or primate, (3) has a dangerous animal or primate in his or her care, or (4) acts as custodian of a dangerous animal or primate.</p><p>"Person" means any individual, firm, association, partnership, corporation, or other legal entity, any public or private institution, the State, or any municipal corporation or political subdivision of the State.</p><p>"Primate" means a nonhuman member of the order primate, including but not limited to chimpanzee, gorilla, orangutan, bonobo, gibbon, monkey, lemur, loris, aye-aye, and tarsier.</p><p class='subsection'>\(b) Dangerous animal or primate offense. No person shall have a right of property in, keep, harbor, care for, act as custodian of or maintain in his or her possession any dangerous animal or primate except at a properly maintained zoological park, federally licensed exhibit, circus, college or university, scientific institution, research laboratory, veterinary hospital, hound running area, or animal refuge in an escape-proof enclosure.</p><p class='subsection'>\(c) Exemptions.</p><p class='paragraph'>\(1) This Section does not prohibit a person who had lawful possession of a primate before January 1, 2011, from continuing to possess that primate if the person registers the animal by providing written notification to the local animal control administrator on or before April 1, 2011. The notification shall include:</p><p class='subparagraph'>\(A) the person's name, address, and telephone number; and</p><p class='subparagraph'>\(B) the type of primate, the age, a photograph, a description of any tattoo, microchip, or other identifying information, and a list of current inoculations.</p><p class='paragraph'>\(2) This Section does not prohibit a person who has a permanent disability with a severe mobility impairment from possessing a single capuchin monkey to assist the person in performing daily tasks if:</p><p class='subparagraph'>\(A) the capuchin monkey was obtained from and trained at a licensed nonprofit organization described in Section 501(c)(3) of the Internal Revenue Code of 1986, the nonprofit tax status of which was obtained on the basis of a mission to improve the quality of life of severely mobility-impaired individuals; and</p><p class='subparagraph'>\(B) the person complies with the notification requirements as described in paragraph (1) of this subsection (c).</p><p class='subsection'>\(d) A person who registers a primate shall notify the local animal control administrator within 30 days of a change of address. If the person moves to another locality within the State, the person shall register the primate with the new local animal control administrator within 30 days of moving by providing written notification as provided in paragraph (1) of subsection (c) and shall include proof of the prior registration.</p><p class='subsection'>\(e) A person who registers a primate shall notify the local animal control administrator immediately if the primate dies, escapes, or bites, scratches, or injures a person.</p><p class='subsection'>\(f) It is no defense to a violation of subsection (b) that the person violating subsection (b) has attempted to domesticate the dangerous animal. If there appears to be imminent danger to the public, any dangerous animal found not in compliance with the provisions of this Section shall be subject to seizure and may immediately be placed in an approved facility. Upon the conviction of a person for a violation of subsection (b), the animal with regard to which the conviction was obtained shall be confiscated and placed in an approved facility, with the owner responsible for all costs connected with the seizure and confiscation of the animal. Approved facilities include, but are not limited to, a zoological park, federally licensed exhibit, humane society, veterinary hospital or animal refuge.</p><p class='subsection'>\(g) Sentence. Any person violating this Section is guilty of a Class C misdemeanor. Any corporation or partnership, any officer, director, manager or managerial agent of the partnership or corporation who violates this Section or causes the partnership or corporation to violate this Section is guilty of a Class C misdemeanor. Each day of violation constitutes a separate offense.</p><p>(Source: P.A. 98-752, eff. 1-1-15; 99-143, eff. 7-27-15.)</p>### (720 ILCS 5/48-11)
## Sec. 48-11. Unlawful use of an elephant in a traveling animal act.
<p class='subsection'>\(a) Definitions. As used in this Section:</p><p>"Mobile or traveling animal housing facility" means a transporting vehicle such as a truck, trailer, or railway car used to transport or house animals while traveling to an exhibition or other performance.</p><p>"Performance" means an exhibition, public showing, presentation, display, exposition, fair, animal act, circus, ride, trade show, petting zoo, carnival, parade, race, or other similar undertaking in which animals are required to perform tricks, give rides, or participate as accompaniments for entertainment, amusement, or benefit of a live audience.</p><p>"Traveling animal act" means any performance of animals where animals are transported to, from, or between locations for the purpose of a performance in a mobile or traveling animal housing facility.</p><p class='subsection'>\(b) A person commits unlawful use of an elephant in a traveling animal act when he or she knowingly allows for the participation of an African elephant (Loxodonta africana) or Asian elephant (Elephas maximus) protected under the federal Endangered Species Act of 1973 in a traveling animal act.</p><p class='subsection'>\(c) This Section does not apply to an exhibition of elephants at a non-mobile, permanent institution, or other facility.</p><p class='subsection'>\(d) Sentence. Unlawful use of an elephant in a traveling animal act is a Class A misdemeanor.</p><p>(Source: P.A. 100-90, eff. 1-1-18 .)</p>