# Article 31. Interference With Public Officers {.unnumbered}

### (720 ILCS 5/31-1) (from Ch. 38, par. 31-1)
## Sec. 31-1. Resisting or obstructing a peace officer, firefighter, or correctional institution employee.
<p class='subsection'>\(a) A person who knowingly:</p><p class='paragraph'>\(1) resists arrest, or</p><p class='paragraph'>\(2) obstructs the performance by one known to the person to be a peace officer, firefighter, or correctional institution employee of any authorized act within his or her official capacity commits a Class A misdemeanor.</p><p class='subsection'>\(a-5) In addition to any other sentence that may be imposed, a court shall order any person convicted of resisting or obstructing a peace officer, firefighter, or correctional institution employee to be sentenced to a minimum of 48 consecutive hours of imprisonment or ordered to perform community service for not less than 100 hours as may be determined by the court. The person shall not be eligible for probation in order to reduce the sentence of imprisonment or community service.</p><p class='subsection'>\(a-7) A person convicted for a violation of this Section whose violation was the proximate cause of an injury to a peace officer, firefighter, or correctional institution employee is guilty of a Class 4 felony.</p><p class='subsection'>\(b) For purposes of this Section, "correctional institution employee" means any person employed to supervise and control inmates incarcerated in a penitentiary, State farm, reformatory, prison, jail, house of correction, police detention area, half-way house, or other institution or place for the incarceration or custody of persons under sentence for offenses or awaiting trial or sentence for offenses, under arrest for an offense, a violation of probation, a violation of parole, a violation of aftercare release, a violation of mandatory supervised release, or awaiting a hearing or preliminary hearing on setting the conditions of pretrial release, or who are sexually dangerous persons or who are sexually violent persons; and "firefighter" means any individual, either as an employee or volunteer, of a regularly constituted fire department of a municipality or fire protection district who performs fire fighting duties, including, but not limited to, the fire chief, assistant fire chief, captain, engineer, driver, ladder person, hose person, pipe person, and any other member of a regularly constituted fire department. "Firefighter" also means a person employed by the Office of the State Fire Marshal to conduct arson investigations.</p><p class='subsection'>\(c) It is an affirmative defense to a violation of this Section if a person resists or obstructs the performance of one known by the person to be a firefighter by returning to or remaining in a dwelling, residence, building, or other structure to rescue or to attempt to rescue any person.</p><p class='subsection'>\(d) A person shall not be subject to arrest for resisting arrest under this Section unless there is an underlying offense for which the person was initially subject to arrest.</p><p>(Source: P.A. 101-652, eff. 1-1-23; 102-28, eff. 6-25-21 .)</p>### (720 ILCS 5/31-1a) (from Ch. 38, par. 31-1a)
## Sec. 31-1a. Disarming a peace officer or correctional institution employee.
<p class='subsection'>\(a) A person who, without the consent of a peace officer or correctional institution employee as defined in subsection (b) of Section 31-1, takes a weapon from a person known to him or her to be a peace officer or correctional institution employee, while the peace officer or correctional institution employee is engaged in the performance of his or her official duties or from an area within the peace officer's or correctional institution employee's immediate presence is guilty of a Class 1 felony.</p><p class='subsection'>\(b) A person who, without the consent of a peace officer or correctional institution employee as defined in subsection (b) of Section 31-1, attempts to take a weapon from a person known to him or her to be a peace officer or correctional institution employee, while the peace officer or correctional institution employee is engaged in the performance of his or her official duties or from an area within the peace officer's or correctional institution employee's immediate presence is guilty of a Class 2 felony.</p><p>(Source: P.A. 96-348, eff. 8-12-09.)</p>### (720 ILCS 5/31-3) (from Ch. 38, par. 31-3)
## Sec. 31-3. Obstructing service of process.
<p>Whoever knowingly resists or obstructs the authorized service or execution of any civil or criminal process or order of any court commits a Class B misdemeanor.</p><p>(Source: P.A. 77-2638.)</p>### (720 ILCS 5/31-4) (from Ch. 38, par. 31-4)
## Sec. 31-4. Obstructing justice.
<p class='subsection'>\(a) A person obstructs justice when, with intent to prevent the apprehension or obstruct the prosecution or defense of any person, he or she knowingly commits any of the following acts:</p><p class='paragraph'>\(1) Destroys, alters, conceals or disguises physical evidence, plants false evidence, furnishes false information; or</p><p class='paragraph'>\(2) Induces a witness having knowledge material to the subject at issue to leave the State or conceal himself or herself; or</p><p class='paragraph'>\(3) Possessing knowledge material to the subject at issue, he or she leaves the State or conceals himself; or</p><p class='paragraph'>\(4) If a parent, legal guardian, or caretaker of a child under 13 years of age reports materially false information to a law enforcement agency, medical examiner, coroner, State's Attorney, or other governmental agency during an investigation of the disappearance or death of a child under circumstances described in subsection (a) or (b) of Section 10-10 of this Code.</p><p class='subsection'>\(b) Sentence.</p><p class='paragraph'>\(1) Obstructing justice is a Class 4 felony, except as provided in paragraph (2) of this subsection (b).</p><p class='paragraph'>\(2) Obstructing justice in furtherance of streetgang related or gang-related activity, as defined in Section 10 of the Illinois Streetgang Terrorism Omnibus Prevention Act, is a Class 3 felony.</p><p>(Source: P.A. 97-1079, eff. 1-1-13.)</p>### (720 ILCS 5/31-4.5)
## Sec. 31-4.5. Obstructing identification.
<p class='subsection'>\(a) A person commits the offense of obstructing identification when he or she intentionally or knowingly furnishes a false or fictitious name, residence address, or date of birth to a peace officer who has:</p><p class='paragraph'>\(1) lawfully arrested the person;</p><p class='paragraph'>\(2) lawfully detained the person; or</p><p class='paragraph'>\(3) requested the information from a person that the peace officer has good cause to believe is a witness to a criminal offense.</p><p class='subsection'>\(b) Sentence. Obstructing identification is a Class A misdemeanor.</p><p>(Source: P.A. 96-335, eff. 1-1-10.)</p>### (720 ILCS 5/31-5) (from Ch. 38, par. 31-5)
## Sec. 31-5. Concealing or aiding a fugitive.
<p class='subsection'>\(a) Every person not standing in the relation of husband, wife, parent, child, brother or sister to the offender, who, with intent to prevent the apprehension of the offender, conceals his knowledge that an offense has been committed or harbors, aids or conceals the offender, commits a Class 4 felony.</p><p class='subsection'>\(b) Every person, 18 years of age or older, who, with intent to prevent the apprehension of the offender, aids or assists the offender, by some volitional act, in fleeing the municipality, county, State, country, or other defined jurisdiction in which the offender is to be arrested, charged, or prosecuted, commits a Class 4 felony.</p><p>(Source: P.A. 97-741, eff. 1-1-13.)</p>### (720 ILCS 5/31-6) (from Ch. 38, par. 31-6)
## Sec. 31-6. Escape; failure to report to a penal institution or to report for periodic imprisonment.
<p class='subsection'>\(a) A person convicted of a felony or charged with the commission of a felony, or charged with or adjudicated delinquent for an act which, if committed by an adult, would constitute a felony, who intentionally escapes from any penal institution or from the custody of an employee of that institution commits a Class 2 felony; however, a person convicted of a felony, or adjudicated delinquent for an act which, if committed by an adult, would constitute a felony, who knowingly fails to report to a penal institution or to report for periodic imprisonment at any time or knowingly fails to return from furlough or from work and day release or who knowingly fails to abide by the terms of home confinement is guilty of a Class 3 felony.</p><p class='subsection'>\(b) A person convicted of a misdemeanor or charged with the commission of a misdemeanor, or charged with or adjudicated delinquent for an act which, if committed by an adult, would constitute a misdemeanor, who intentionally escapes from any penal institution or from the custody of an employee of that institution commits a Class A misdemeanor; however, a person convicted of a misdemeanor, or adjudicated delinquent for an act which, if committed by an adult, would constitute a misdemeanor, who knowingly fails to report to a penal institution or to report for periodic imprisonment at any time or knowingly fails to return from furlough or from work and day release or who knowingly fails to abide by the terms of home confinement is guilty of a Class B misdemeanor.</p><p class='subsection'>\(b-1) A person in the custody of the Department of Human Services under the provisions of the Sexually Violent Persons Commitment Act under a detention order, commitment order, conditional release order, or other court order who intentionally escapes from any secure residential facility or from a Department employee or any of its agents commits a Class 2 felony.</p><p class='subsection'>\(c) A person in the lawful custody of a peace officer for the alleged commission of a felony offense or an act which, if committed by an adult, would constitute a felony, and who intentionally escapes from custody commits a Class 2 felony; however, a person in the lawful custody of a peace officer for the alleged commission of a misdemeanor offense or an act which, if committed by an adult, would constitute a misdemeanor, who intentionally escapes from custody commits a Class A misdemeanor.</p><p class='subsection'>\(c-5) A person in the lawful custody of a peace officer for an alleged violation of a term or condition of probation, conditional discharge, parole, aftercare release, or mandatory supervised release for a felony or an act which, if committed by an adult, would constitute a felony, who intentionally escapes from custody is guilty of a Class 2 felony.</p><p class='subsection'>\(c-6) A person in the lawful custody of a peace officer for an alleged violation of a term or condition of supervision, probation, or conditional discharge for a misdemeanor or an act which, if committed by an adult, would constitute a misdemeanor, who intentionally escapes from custody is guilty of a Class A misdemeanor.</p><p class='subsection'>\(d) A person who violates this Section while armed with a dangerous weapon commits a Class 1 felony.</p><p>(Source: P.A. 98-558, eff. 1-1-14; 98-770, eff. 1-1-15 .)</p>### (720 ILCS 5/31-7) (from Ch. 38, par. 31-7)
## Sec. 31-7. Aiding escape.
<p class='subsection'>\(a) Whoever, with intent to aid any prisoner in escaping from any penal institution, conveys into the institution or transfers to the prisoner anything for use in escaping commits a Class A misdemeanor.</p><p class='subsection'>\(b) Whoever knowingly aids a person convicted of a felony or charged with the commission of a felony, or charged with or adjudicated delinquent for an act which, if committed by an adult, would constitute a felony, in escaping from any penal institution or from the custody of any employee of that institution commits a Class 2 felony; however, whoever knowingly aids a person convicted of a felony or charged with the commission of a felony, or charged with or adjudicated delinquent for an act which, if committed by an adult, would constitute a felony, in failing to return from furlough or from work and day release is guilty of a Class 3 felony.</p><p class='subsection'>\(c) Whoever knowingly aids a person convicted of a misdemeanor or charged with the commission of a misdemeanor, or charged with or adjudicated delinquent for an act which, if committed by an adult, would constitute a misdemeanor, in escaping from any penal institution or from the custody of an employee of that institution commits a Class A misdemeanor; however, whoever knowingly aids a person convicted of a misdemeanor or charged with the commission of a misdemeanor, or charged with or adjudicated delinquent for an act which, if committed by an adult, would constitute a misdemeanor, in failing to return from furlough or from work and day release is guilty of a Class B misdemeanor.</p><p class='subsection'>\(d) Whoever knowingly aids a person in escaping from any public institution, other than a penal institution, in which he is lawfully detained, or from the custody of an employee of that institution, commits a Class A misdemeanor.</p><p class='subsection'>\(e) Whoever knowingly aids a person in the lawful custody of a peace officer for the alleged commission of a felony offense or an act which, if committed by an adult, would constitute a felony, in escaping from custody commits a Class 2 felony; however, whoever knowingly aids a person in the lawful custody of a peace officer for the alleged commission of a misdemeanor offense or an act which, if committed by an adult, would constitute a misdemeanor, in escaping from custody commits a Class A misdemeanor.</p><p class='subsection'>\(f) An officer or employee of any penal institution who recklessly permits any prisoner in his custody to escape commits a Class A misdemeanor.</p><p class='subsection'>\(f-5) With respect to a person in the lawful custody of a peace officer for an alleged violation of a term or condition of probation, conditional discharge, parole, aftercare release, or mandatory supervised release for a felony, whoever intentionally aids that person to escape from that custody is guilty of a Class 2 felony.</p><p class='subsection'>\(f-6) With respect to a person who is in the lawful custody of a peace officer for an alleged violation of a term or condition of supervision, probation, or conditional discharge for a misdemeanor, whoever intentionally aids that person to escape from that custody is guilty of a Class A misdemeanor.</p><p class='subsection'>\(g) A person who violates this Section while armed with a dangerous weapon commits a Class 2 felony.</p><p>(Source: P.A. 98-558, eff. 1-1-14.)</p>### (720 ILCS 5/31-8) (from Ch. 38, par. 31-8)
## Sec. 31-8. Refusing to aid an officer.
<p>Whoever upon command refuses or knowingly fails reasonably to aid a person known by him to be a peace officer in:</p><p class='subsection'>\(a) Apprehending a person whom the officer is authorized to apprehend; or</p><p class='subsection'>\(b) Preventing the commission by another of any offense, commits a petty offense.</p><p>(Source: P.A. 77-2638.)</p>### (720 ILCS 5/31-9)
## Sec. 31-9. Obstructing an emergency management worker.
<p>A person who knowingly obstructs the performance by one known to the person to be an emergency management worker of any authorized act within his or her official capacity commits a Class A misdemeanor.</p>
<p>(Source: P.A. 94-243, eff. 1-1-06.)</p>