# Article 25. Mob Action And Related Offenses {.unnumbered}

### (720 ILCS 5/25-1) (from Ch. 38, par. 25-1)
## Sec. 25-1. Mob action.
<p class='subsection'>\(a) A person commits mob action when he or she engages in any of the following:</p><p class='paragraph'>\(1) the knowing or reckless use of force or violence disturbing the public peace by 2 or more persons acting together and without authority of law;</p><p class='paragraph'>\(2) the knowing assembly of 2 or more persons with the intent to commit or facilitate the commission of a felony or misdemeanor; or</p><p class='paragraph'>\(3) the knowing assembly of 2 or more persons, without authority of law, for the purpose of doing violence to the person or property of anyone supposed to have been guilty of a violation of the law, or for the purpose of exercising correctional powers or regulative powers over any person by violence.</p><p class='subsection'>\(b) Sentence.</p><p class='paragraph'>\(1) Mob action in violation of paragraph (1) of subsection (a) is a Class 4 felony.</p><p class='paragraph'>\(2) Mob action in violation of paragraphs (2) and (3) of subsection (a) is a Class C misdemeanor.</p><p class='paragraph'>\(3) A participant in a mob action that by violence inflicts injury to the person or property of another commits a Class 4 felony.</p><p class='paragraph'>\(4) A participant in a mob action who does not withdraw when commanded to do so by a peace officer commits a Class A misdemeanor.</p><p class='paragraph'>\(5) In addition to any other sentence that may be imposed, a court shall order any person convicted of mob action to perform community service for not less than 30 and not more than 120 hours, if community service is available in the jurisdiction and is funded and approved by the county board of the county where the offense was committed. In addition, whenever any person is placed on supervision for an alleged offense under this Section, the supervision shall be conditioned upon the performance of the community service. This paragraph does not apply when the court imposes a sentence of incarceration.</p><p>(Source: P.A. 96-710, eff. 1-1-10; 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/25-1.1)
## Sec. 25-1.1. (Renumbered).
<p>(Source: Renumbered by P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/25-2) (from Ch. 38, par. 25-2)
## Sec. 25-2. (Renumbered).
<p>(Source: Renumbered by P.A. 96-710, eff. 1-1-10.)</p>### (720 ILCS 5/25-4)
## Sec. 25-4. Looting by individuals.
<p class='subsection'>\(a) A person commits looting when he or she knowingly without authority of law or the owner enters any home or dwelling or upon any premises of another, or enters any commercial, mercantile, business, or industrial building, plant, or establishment, in which normal security of property is not present by virtue of a hurricane, fire, or vis major of any kind or by virtue of a riot, mob, or other human agency, and obtains or exerts control over property of the owner.</p><p class='subsection'>\(b) Sentence. Looting is a Class 4 felony. In addition to any other penalty imposed, the court shall impose a sentence of at least 100 hours of community service as determined by the court and shall require the defendant to make restitution to the owner of the property looted pursuant to Section 5-5-6 of the Unified Code of Corrections.</p><p>(Source: P.A. 96-710, eff. 1-1-10; 97-1108, eff. 1-1-13.)</p>### (720 ILCS 5/25-5)
<p class='subsection'>\(was 720 ILCS 5/25-1.1)</p>## Sec. 25-5. Unlawful participation in streetgang related activity.
<p class='subsection'>\(a) A person commits unlawful participation in streetgang related activity  when he or she knowingly commits any act in furtherance of streetgang related activity as defined in Section 10 of the Illinois Streetgang Terrorism Omnibus Prevention Act after having been:</p><p class='paragraph'>\(1) sentenced to probation, conditional discharge, or supervision for a criminal offense with a condition of that sentence being to refrain from direct or indirect contact with a streetgang member or members;</p><p class='paragraph'>\(2) released on bond for any criminal offense with a condition of that bond being to refrain from direct or indirect contact with a streetgang member or members;</p><p class='paragraph'>\(3) ordered by a judge in any non-criminal proceeding to refrain from direct or indirect contact with a streetgang member or members; or</p><p class='paragraph'>\(4) released from the Illinois Department of</p><p>Corrections on a condition of parole or mandatory supervised release that he or she refrain from direct or indirect contact with a streetgang member or members.</p><p class='subsection'>\(b) Unlawful participation in streetgang related activity is a Class A misdemeanor.</p><p class='subsection'>\(c) (Blank).</p><p>(Source: P.A. 100-279, eff. 1-1-18 .)</p>### (720 ILCS 5/25-6)
<p class='subsection'>\(was 720 ILCS 5/25-2)</p>## Sec. 25-6. Removal of chief of police or sheriff for allowing a person in his or her custody to be lynched.
<p class='subsection'>\(a) If a prisoner is taken from the custody of any policeman or chief of police of any municipality and lynched, it shall be prima facie evidence of wrong-doing on the part of that chief of police and he or she shall be suspended. The mayor or chief executive of the municipality shall appoint an acting chief of police until he or she has ascertained whether the suspended chief of police had done all in his or her power to protect the life of the prisoner. If, upon hearing all evidence and argument, the mayor or chief executive finds that the chief of police had done his or her utmost to protect the prisoner, he or she may reinstate the chief of police; but, if he or she finds the chief of police guilty of not properly protecting the prisoner, a new chief of police shall be appointed. Any chief of police replaced is  not be eligible to serve again in that office.</p><p class='subsection'>\(b) If a prisoner is taken from the custody of any sheriff or his or her deputy and lynched, it is prima facie evidence of wrong-doing on the part of that sheriff and he or she shall be suspended. The Governor shall appoint an acting sheriff until he or she has ascertained whether the suspended sheriff had  done all in his or her power to protect the life of the prisoner. If, upon hearing all evidence and argument, the Governor finds that the sheriff had done his or her utmost to protect the prisoner, he or she shall reinstate the sheriff; but, if he or she finds the sheriff guilty of not properly protecting the prisoner, a new sheriff shall be duly elected or appointed, pursuant to the existing law provided for the filling of vacancies in that office. Any sheriff replaced is not eligible to serve again in that office.</p><p>(Source: P.A. 96-710, eff. 1-1-10.)</p>