# Article 24.5. Nitrous Oxide {.unnumbered}

### (720 ILCS 5/24.5-5)
## Sec. 24.5-5. Unlawful possession.
<p>Any person who possesses nitrous oxide or any substance containing nitrous oxide, with the intent to breathe, inhale, or ingest for the purpose of causing a condition of intoxication, elation, euphoria, dizziness, stupefaction, or dulling of the senses or for the purpose of, in any manner, changing, distorting, or disturbing the audio, visual, or mental processes, or who knowingly and with the intent to do so is under the influence of nitrous oxide or any material containing nitrous oxide is guilty of a Class A misdemeanor. A person who commits a second or subsequent violation of this Section is guilty of a Class 4 felony. This Section shall not apply to any person who is under the influence of nitrous oxide or any material containing nitrous oxide pursuant to an administration for the purpose of medical, surgical, or dental care by a person duly licensed to administer such an agent.</p><p>(Source: P.A. 91-366, eff. 1-1-00.)</p>### (720 ILCS 5/24.5-10)
## Sec. 24.5-10. Unlawful manufacture or delivery.
<p>Any person, firm, corporation, co-partnership, limited liability company, or association that intentionally manufactures, delivers, or possesses with intent to manufacture or deliver nitrous oxide for any purpose prohibited under Section 24.5-5 is guilty of a Class 3 felony.</p><p>(Source: P.A. 91-366, eff. 1-1-00.)</p>