# Ch. 12, Article VI. Miscellaneous Requirements {.unnumbered}

### (625 ILCS 5/12-600) (from Ch. 95 1/2, par. 12-600)
## Sec. 12-600. (Repealed).
<p>(Source: P.A. 86-498. Repealed by P.A. 90-89, eff. 1-1-98.)</p>### (625 ILCS 5/12-601) (from Ch. 95 1/2, par. 12-601)
## Sec. 12-601. Horns and warning devices.
<p class='subsection'>\(a) Every motor vehicle when operated upon a highway shall be equipped with a horn in good working order and capable of emitting sound audible under normal conditions from a distance of not less than 200 feet, but no horn or other warning device shall emit an unreasonable loud or harsh sound or a whistle. The driver of a motor vehicle shall when reasonably necessary to insure safe operation give audible warning with his horn but shall not otherwise use such horn when upon a highway.</p><p class='subsection'>\(b) No vehicle shall be equipped with nor shall any person use upon a vehicle any siren, whistle, or bell, except as otherwise permitted in this Section. Any authorized emergency vehicle or organ transport vehicle as defined in Chapter 1 of this Code or a vehicle operated by a fire chief, deputy fire chief, assistant fire chief, or the Director or Coordinator of a municipal or county emergency services and disaster agency may be equipped with a siren, whistle, or bell capable of emitting sound audible under normal conditions from a distance of not less than 500 feet, but such siren, whistle, or bell shall not be used except when such vehicle is operated in response to an emergency call or in the immediate pursuit of an actual or suspected violator of the law in either of which events the driver of such vehicle shall sound such siren, whistle, or bell when necessary to warn pedestrians and other drivers of the approach thereof.</p><p class='subsection'>\(c) Trackless trolley coaches, as defined by Section 1-206 of this Code, and replica trolleys, as defined by Section 1-171.04 of this Code, may be equipped with a bell or bells in lieu of a horn, and may, in addition to the requirements of subsection (a) of this Section, use a bell or bells for the purpose of indicating arrival or departure at designated stops during the hours of scheduled operation.</p><p>(Source: P.A. 102-448, eff. 1-1-22 .)</p>### (625 ILCS 5/12-601.1)
## Sec. 12-601.1. Traffic control signal preemption devices.
<p class='subsection'>\(a) As used in this Section, "traffic control signal preemption device" means any device, either mechanical or electrical, that emits a pulse of light or other signal that, when received by a detector attached to a traffic control signal, changes that traffic control signal to a green light or, if the traffic control signal is already green, extends the duration of the green light.</p><p class='subsection'>\(b) Except as provided in subsection (d), a traffic control signal preemption device may not be installed on a motor vehicle, may not be transported in the passenger compartment of a motor vehicle, and may not be operated by the driver or passenger of a motor vehicle.</p><p>Violation of this subsection (b) is a Class A misdemeanor, punishable by a fine of $1,000 in addition to any other penalty that may be imposed.</p><p class='subsection'>\(c) A retailer or manufacturer may not sell a traffic control signal preemption device to any person or entity for any intended use other than operation as permitted under subsection (d).</p><p>Violation of this subsection (c) is a Class A misdemeanor, punishable by a fine of $5,000 for each sale of each device, in addition to any other penalty that may be imposed.</p><p class='subsection'>\(d) Installation of a traffic control signal preemption device is permitted on the following vehicles, and operation of the device is permitted as follows:</p><p class='paragraph'>\(1) Police department vehicles, when responding to a</p><p>bona fide emergency, when used in combination with red or blue oscillating, rotating, or flashing lights.</p><p class='paragraph'>\(2) Law enforcement vehicles of State or local authorities, when responding to a bona fide emergency, when used in combination with red oscillating, rotating, or flashing lights.</p><p class='paragraph'>\(3) Vehicles of local fire departments, fire protection districts, and State or federal firefighting vehicles, when responding to a bona fide emergency, when used in combination with red oscillating, rotating, or flashing lights.</p><p class='paragraph'>\(4) Vehicles that are designed and used exclusively as ambulances or rescue vehicles, when responding to a bona fide emergency, when used in combination with red oscillating, rotating, or flashing lights.</p><p class='paragraph'>\(5) Vehicles that are equipped and used exclusively as organ transport vehicles, when the transportation is declared an emergency by a member of the transplant team or a representative of the organ procurement organization, when used in combination with red oscillating, rotating, or flashing lights.</p><p class='paragraph'>\(6) Vehicles of the Illinois Emergency Management Agency and vehicles of the Department of Nuclear Safety, when responding to a bona fide emergency, when used in combination with red oscillating, rotating, or flashing lights.</p><p class='paragraph'>\(7) Commuter buses owned by any political subdivision</p><p>of this State, operated either by the political subdivision or its lessee or agent, and offering short-haul for-hire regularly scheduled passenger transportation service, over regular routes with fixed schedules, within metropolitan and suburban areas, when used to extend the duration of an already green light to meet schedules.</p><p class='paragraph'>\(8) Vehicles used for snow removal owned by any political subdivision of this State, operated either by the political subdivision or its lessee or agent, when used during a snow emergency in combination with yellow or amber oscillating, rotating, or flashing lights, when used to extend the duration of an already green light.</p><p class='subsection'>\(e) This Section does not prohibit use by motorcycles of electronic or magnetic safety devices designed to allow traffic control signal systems to recognize or detect motorcycles. (Source: P.A. 102-842, eff. 1-1-23 .)</p>### (625 ILCS 5/12-601.2)
## Sec. 12-601.2. (Repealed).
<p>(Source: P.A. 94-373, eff. 1-1-06. Repealed by P.A. 99-576, eff. 7-15-16.)</p>### (625 ILCS 5/12-602) (from Ch. 95 1/2, par. 12-602)
## Sec. 12-602. Mufflers, prevention of noise.
<p>Every motor vehicle driven or operated upon the highways of this State shall at all times be equipped with an adequate muffler or exhaust system in constant operation and properly maintained to prevent any excessive or unusual noise. No such muffler or exhaust system shall be equipped with a cutout, bypass or similar device. No person shall modify the exhaust system of a motor vehicle in a manner which will amplify or increase the noise of such vehicle above that emitted by the muffler originally installed on the vehicle, and such original muffler shall comply with all the requirements of this Section.</p><p>(Source: P.A. 77-37.)</p>### (625 ILCS 5/12-602.1)
## Sec. 12-602.1. Excessive engine braking noise signs.
<p class='subsection'>\(a) A county or municipality may post signs that prohibit the driver of a commercial vehicle, as defined in Section 1-111.8 of this Code, from operating or actuating any engine braking system that emits excessive noise. The Department of Transportation may erect and maintain the signs on interstate highways near weigh stations that are adjacent to residential areas or communities.</p><p class='subsection'>\(b) The sign shall state, "EXCESSIVE ENGINE BRAKING NOISE PROHIBITED". The Department of Transportation shall adopt rules providing for the erection and placement of these signs.</p><p class='subsection'>\(c) This Section does not apply to the use of an engine braking system that has an adequate sound muffling system in proper working order that prevents excessive noise.</p><p class='subsection'>\(d) It is a defense to this Section that the driver used an engine braking system that emits excessive noise in an emergency to avoid a collision with a person or another vehicle on the highway.</p><p class='subsection'>\(e) A violation of this Section is an equipment violation punishable by a fine of $75.</p><p>(Source: P.A. 96-523, eff. 1-1-10.)</p>### (625 ILCS 5/12-603) (from Ch. 95 1/2, par. 12-603)
## Sec. 12-603. Seat safety belts.
<p class='subsection'>\(a) No person shall sell any 1965 or later model motor vehicle of the first division unless the front seat of such motor vehicle is equipped with 2 sets of seat safety belts. Motorcycles are exempted from the provisions of this Section.</p><p class='subsection'>\(b) No person shall operate any 1965 or later model motor vehicle of the first division that is titled or licensed by the Secretary of State unless the front seat of such motor vehicle is equipped with 2 sets of seat safety belts.</p><p class='subsection'>\(b-5) No person under the age of 18 years shall operate any motor vehicle, except a motor driven cycle or motorcycle, with more than one passenger in the front seat of the motor vehicle and no more passengers in the back seats than the number of available seat safety belts, except that each driver under the age of 18 years operating a second division vehicle having a gross vehicle weight rating of 8,000 pounds or less that contains only a front seat may operate the vehicle with more than one passenger in the front seat, provided that each passenger is wearing a properly adjusted and fastened seat safety belt.</p><p class='subsection'>\(c) (Blank).</p><p class='subsection'>\(d) The Department shall establish performance specifications for seat safety belts and for the attachment and installation thereof.</p><p>(Source: P.A. 89-120, eff. 7-7-95; 90-89, eff. 1-1-98; 90-369, eff. 1-1-98; 90-655, eff. 7-30-98.)</p>### (625 ILCS 5/12-603.1) (from Ch. 95 1/2, par. 12-603.1)
## Sec. 12-603.1. Driver and passenger required to use safety belts, exceptions and penalty.
<p class='subsection'>\(a) Each driver and passenger of a motor vehicle operated on a street or highway in this State shall wear a properly adjusted and fastened seat safety belt. A child less than 8 years of age shall be protected as required pursuant to the Child Passenger Protection Act. Each driver of a motor vehicle transporting a child 8 years of age or more, but less than 16 years of age, shall secure the child in a properly adjusted and fastened seat safety belt as required under the Child Passenger Protection Act. Each driver of a motor vehicle transporting a passenger who is unable, due to infirmity, illness, or age, to properly adjust and fasten a seat safety belt and is not exempted from wearing a seat safety belt under subsection (b) shall secure the passenger in a properly adjusted and fastened seat safety belt as required under this Section.</p><p class='subsection'>\(b) Paragraph (a) shall not apply to any of the following:</p><p class='paragraph'>\1. A driver or passenger frequently stopping and</p><p>leaving the vehicle or delivering property from the vehicle, if the speed of the vehicle between stops does not exceed 15 miles per hour.</p><p class='paragraph'>\2. A driver or passenger possessing a written statement from a physician that such person is unable, for medical or physical reasons, to wear a seat safety belt.</p><p class='paragraph'>\3. A driver or passenger possessing an official certificate or license endorsement issued by the appropriate agency in another state or country indicating that the driver is unable for medical, physical, or other valid reasons to wear a seat safety belt.</p><p class='paragraph'>\4. A driver operating a motor vehicle in reverse. 5. A motor vehicle with a model year prior to 1965.</p><p class='paragraph'>\6. A motorcycle or motor driven cycle.</p><p class='paragraph'>\7. A moped.</p><p class='paragraph'>\8. A motor vehicle which is not required to be</p><p>equipped with seat safety belts under federal law.</p><p class='paragraph'>\9. A motor vehicle operated by a rural letter carrier of the United States postal service while performing duties as a rural letter carrier.</p><p>10. A driver or passenger of an authorized emergency vehicle, except this exception does not apply to vehicles of the fire department; vehicles of the Office of the State Fire Marshal; or ambulances, unless the delivery of life-saving measures prohibits the use of a seat safety belt.</p><p>11. A back seat passenger of a taxicab. (c) Failure to wear a seat safety belt in violation of this Section shall not be considered evidence of negligence, shall not limit the liability of an insurer, and shall not diminish any recovery for damages arising out of the ownership, maintenance, or operation of a motor vehicle.</p><p class='subsection'>\(d) A violation of this Section shall be a petty offense and subject to a fine not to exceed $25.</p><p class='subsection'>\(e) (Blank).</p><p class='subsection'>\(f) A law enforcement officer may not search or inspect a motor vehicle, its contents, the driver, or a passenger solely because of a violation of this Section.</p><p>(Source: P.A. 97-16, eff. 1-1-12; 97-333, eff. 8-12-11; 98-451, eff. 8-16-13.)</p>### (625 ILCS 5/12-604)
## Sec. 12-604. (Repealed).
<p>(Source: P.A. 88-415. Repealed by P.A. 94-185, eff. 1-1-06.)</p>### (625 ILCS 5/12-604.1)
<p>(Text of Section before amendment by P.A. 102-982 )</p>## Sec. 12-604.1. Video devices.
<p class='subsection'>\(a) A person may not operate a motor vehicle if a television receiver, a video monitor, a television or video screen, or any other similar means of visually displaying a television broadcast or video signal that produces entertainment or business applications is operating and is located in the motor vehicle at any point forward of the back of the driver's seat, or is operating and visible to the driver while driving the motor vehicle.</p><p class='subsection'>\(a-5) A person commits aggravated use of a video device when he or she violates subsection (a) and in committing the violation he or she was involved in a motor vehicle accident that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation was a proximate cause of the injury or death.</p><p class='subsection'>\(b) This Section does not apply to the following equipment, whether or not permanently installed in a vehicle:</p><p class='paragraph'>\(1) a vehicle information display;</p><p class='paragraph'>\(2) a global positioning display;</p><p class='paragraph'>\(3) a mapping or navigation display;</p><p class='paragraph'>\(4) a visual display used to enhance or supplement</p><p>the driver's view forward, behind, or to the sides of a motor vehicle for the purpose of maneuvering the vehicle;</p><p class='paragraph'>\(5) television-type receiving equipment used exclusively for safety or traffic engineering studies; or</p><p class='paragraph'>\(6) a television receiver, video monitor, television or video screen, or any other similar means of visually displaying a television broadcast or video signal, if that equipment has an interlock device that, when the motor vehicle is driven, disables the equipment for all uses except as a visual display as described in paragraphs (1) through (5) of this subsection (b).</p><p class='subsection'>\(c) This Section does not apply to a mobile, digital terminal installed in an authorized emergency vehicle, a motor vehicle providing emergency road service or roadside assistance, or to motor vehicles utilized for public transportation. (d) This Section does not apply to a television receiver, video monitor, television or video screen, or any other similar means of visually displaying a television broadcast or video signal if: (i) the equipment is permanently installed in the motor vehicle; and (ii) the moving entertainment images that the equipment displays are not visible to the driver while the motor vehicle is in motion.</p><p class='subsection'>\(d-5) This Section does not apply to a video event recorder, as defined in Section 1-218.10 of this Code, installed in a contract carrier vehicle.</p><p class='subsection'>\(e) Except as provided in subsection (f) of this Section, a person convicted of violating this Section is guilty of a petty offense and shall be fined not more than $100 for a first offense, not more than $200 for a second offense within one year of a previous conviction, and not more than $250 for a third or subsequent offense within one year of 2 previous convictions.</p><p class='subsection'>\(f) A person convicted of violating subsection (a-5) commits a Class A misdemeanor if the violation resulted in great bodily harm, permanent disability, or disfigurement to another. A person convicted of violating subsection (a-5) commits a Class 4 felony if the violation resulted in the death of another person.</p><p>(Source: P.A. 98-507, eff. 1-1-14; 99-689, eff. 1-1-17 .)</p><p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 12-604.1. Video devices.
<p class='subsection'>\(a) A person may not operate a motor vehicle if a television receiver, a video monitor, a television or video screen, or any other similar means of visually displaying a television broadcast or video signal that produces entertainment or business applications is operating and is located in the motor vehicle at any point forward of the back of the driver's seat, or is operating and visible to the driver while driving the motor vehicle.</p><p class='subsection'>\(a-5) A person commits aggravated use of a video device when he or she violates subsection (a) and in committing the violation he or she was involved in a motor vehicle crash that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation was a proximate cause of the injury or death.</p><p class='subsection'>\(b) This Section does not apply to the following equipment, whether or not permanently installed in a vehicle:</p><p class='paragraph'>\(1) a vehicle information display;</p><p class='paragraph'>\(2) a global positioning display;</p><p class='paragraph'>\(3) a mapping or navigation display;</p><p class='paragraph'>\(4) a visual display used to enhance or supplement</p><p>the driver's view forward, behind, or to the sides of a motor vehicle for the purpose of maneuvering the vehicle;</p><p class='paragraph'>\(5) television-type receiving equipment used exclusively for safety or traffic engineering studies; or</p><p class='paragraph'>\(6) a television receiver, video monitor, television or video screen, or any other similar means of visually displaying a television broadcast or video signal, if that equipment has an interlock device that, when the motor vehicle is driven, disables the equipment for all uses except as a visual display as described in paragraphs (1) through (5) of this subsection (b).</p><p class='subsection'>\(c) This Section does not apply to a mobile, digital terminal installed in an authorized emergency vehicle, a motor vehicle providing emergency road service or roadside assistance, or to motor vehicles utilized for public transportation. (d) This Section does not apply to a television receiver, video monitor, television or video screen, or any other similar means of visually displaying a television broadcast or video signal if: (i) the equipment is permanently installed in the motor vehicle; and (ii) the moving entertainment images that the equipment displays are not visible to the driver while the motor vehicle is in motion.</p><p class='subsection'>\(d-5) This Section does not apply to a video event recorder, as defined in Section 1-218.10 of this Code, installed in a contract carrier vehicle.</p><p class='subsection'>\(e) Except as provided in subsection (f) of this Section, a person convicted of violating this Section is guilty of a petty offense and shall be fined not more than $100 for a first offense, not more than $200 for a second offense within one year of a previous conviction, and not more than $250 for a third or subsequent offense within one year of 2 previous convictions.</p><p class='subsection'>\(f) A person convicted of violating subsection (a-5) commits a Class A misdemeanor if the violation resulted in great bodily harm, permanent disability, or disfigurement to another. A person convicted of violating subsection (a-5) commits a Class 4 felony if the violation resulted in the death of another person.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/12-604.3)
## Sec. 12-604.3. Video event recorder notice.
<p>A contract carrier vehicle carrying passengers that is equipped with a video event recorder shall have a notice posted in a visible location stating that a passenger's conversation may be recorded. Any data recorded by a video event recorder shall be the sole property of the registered owner or lessee of the contract carrier vehicle.</p><p>(Source: P.A. 99-689, eff. 1-1-17 .)</p>### (625 ILCS 5/12-605) (from Ch. 95 1/2, par. 12-605)
## Sec. 12-605. Taxicabs-Bullet proof shields.
<p>In municipalities with 1,000,000 or more population, any taxicab manufactured, owned or operated after September 1, 1970, and regularly operated in such a municipality must have a bullet proof shield completely separating the driver's seat from the back seat.</p><p>(Source: P.A. 80-911.)</p>### (625 ILCS 5/12-605.1) (from Ch. 95 1/2, par. 12-605.1)
## Sec. 12-605.1. (a) On or after two years from the effective date of this Act, no bus which was first placed in service after July 1, 1969, or which has undergone complete renovation and restoration since July 1, 1969 shall be operated as a part of any local mass transit system in this State unless the vehicle is equipped with radio facilities permitting two-way vocal communications between the bus and a local transit control office. This Section does not apply to buses used for charter service, school buses, intrastate carriers while not providing transportation services pursuant to contracts with any local mass transit system, private non-profit carriers receiving assistance under Section 16(b)2 of the Urban Mass Transportation Act of 1964 as amended, carriers receiving assistance pursuant to Article III of the Downstate Public Transportation Act, or interstate carriers and buses owned by a private local mass transit system;
<p class='subsection'>\(b) A local mass transit system operating a bus not in compliance with the requirements of subsection (a) shall not be in violation of that subsection, provided that the bus is brought into compliance within a reasonable time (in no event to exceed 1 week) following written notification to the mass transit system of the fact that the bus is not in compliance.</p><p>(Source: P.A. 90-89, eff. 1-1-98.)</p>### (625 ILCS 5/12-605.2) (from Ch. 95 1/2, par. 12-605.2)
## Sec. 12-605.2. Beginning 30 days after the effective date of this amendatory Act of 1988, no person shall consume any food or drink, excluding any medicine, upon any bus operated as a part of any local mass transit system in this State. This Section does not apply to buses used for charter service, school buses, intrastate carriers while not providing transportation services pursuant to contracts with any local mass transit system, and private non-profit carriers.
<p>Persons found guilty of violating this Section shall be fined $100.</p><p>(Source: P.A. 90-89, eff. 1-1-98.)</p>### (625 ILCS 5/12-606) (from Ch. 95 1/2, par. 12-606)
## Sec. 12-606. Tow trucks; identification; equipment; insurance.
<p class='subsection'>\(a) Every tow truck, except those owned by governmental agencies, shall have displayed on each side thereof, a sign with letters not less than 2 inches in height, contrasting in color to that of the background, stating the full legal name, complete address (including street address and city), and telephone number of the owner or operator thereof. This information shall be permanently affixed to the sides of the tow truck.</p><p class='subsection'>\(b) Every tow truck shall be equipped with:</p><p class='paragraph'>\(1) One or more brooms and shovels;</p><p class='paragraph'>\(2) One or more trash cans of at least 5 gallon</p><p>capacity; and</p><p class='paragraph'>\(3) One fire extinguisher. This extinguisher shall be either:</p><p class='item'>\(i) of the dry chemical or carbon dioxide type with an aggregate rating of at least 4-B, C units, and bearing the approval of a laboratory qualified by the Division of Fire Prevention for this purpose; or</p><p class='item'>\(ii) One that meets the requirements of the Federal Motor Carrier Safety Regulations of the United States Department of Transportation for fire extinguishers on commercial motor vehicles.</p><p class='subsection'>\(c) Every owner or operator and driver of a tow truck shall comply with Section 11-1413 of this Code and shall remove or cause to be removed all glass and debris, except any (i) hazardous substance as defined in Section 3.215 of the Environmental Protection Act, (ii) hazardous waste as defined in Section 3.220 of the Environmental Protection Act, and (iii) medical samples or waste, including but not limited to any blood samples, used syringes, other used medical supplies, or any other potentially infectious medical waste as defined in Section 3.360 of the Environmental Protection Act, deposited upon any street or highway by the disabled vehicle being serviced, and shall in addition, spread dirt or sand or oil absorbent upon that portion of any street or highway where oil or grease has been deposited by the disabled vehicle being serviced.</p><p class='subsection'>\(d) Every tow truck operator shall in addition file an indemnity bond, insurance policy, or other proof of insurance in a form to be prescribed by the Secretary for: garagekeepers liability insurance, in an amount no less than a combined single limit of $500,000, and truck (auto) liability insurance in an amount no less than a combined single limit of $500,000, on hook coverage or garagekeepers coverage in an amount of no less than $25,000 which shall indemnify or insure the tow truck operator for the following:</p><p class='paragraph'>\(1) Bodily injury or damage to the property of others.</p><p class='paragraph'>\(2) Damage to any vehicle towed by the tower.</p><p class='paragraph'>\(3) In case of theft, loss of, or damage to any</p><p>vehicle stored, garagekeepers legal liability coverage in an amount of no less than $25,000.</p><p class='paragraph'>\(4) In case of injury to or occupational illness of the tow truck driver or helper, workers compensation insurance meeting the minimum requirements of the Workers' Compensation Act.</p><p>Any such bond or policy shall be issued only by a bonding or insuring firm authorized to do business as such in the State of Illinois, and a certificate of such bond or policy shall be carried in the cab of each tow truck. (e) The bond or policy required in subsection (d) shall provide that the insurance carrier may cancel it by serving previous notice, as required by Sections 143.14 and 143.16 of the Illinois Insurance Code, in writing, either personally or by registered mail, upon the owner or operator of the motor vehicle and upon the Secretary of State. Whenever any such bond or policy shall be so cancelled, the Secretary of State shall mark the policy "Cancelled" and shall require such owner or operator either to furnish a new bond or policy, in accordance with this Act.</p><p>(Source: P.A. 100-863, eff. 8-14-18.)</p>### (625 ILCS 5/12-607) (from Ch. 95 1/2, par. 12-607)
## Sec. 12-607. Suspension System.
<p class='subsection'>\(a) It shall be unlawful to operate a motor vehicle on any highway of this State when the suspension system has been modified from the original manufactured design by lifting the body from the chassis in excess of 3 inches or to cause the horizontal line from the front to the rear bumper to vary over 3 inches in height when measured from a level surface of the highway to the lower edge of the bumper, except that it is unlawful to operate a street rod or custom vehicle when the suspension system has been modified from the original manufactured design so that the horizontal line from the front to the rear bumper varies over 7 inches in height when measured from a level surface of the highway to the lower edge of the bumper.</p><p class='subsection'>\(b) Nothing in this Section shall prevent the installation of manufactured heavy duty equipment to include shock absorbers and overload springs, nor shall anything contained in this Section prevent a person to operate a motor vehicle on any highway of this State with normal wear of the suspension system if normal wear does not affect the control or safe operation of the vehicle. This Section shall not apply to motor vehicles designed or modified primarily for off-highway racing purposes while such vehicles are in tow or to motorcycles or motor driven cycles.</p><p>(Source: P.A. 92-668, eff. 1-1-03.)</p>### (625 ILCS 5/12-607.1) (from Ch. 95 1/2, par. 12-607.1)
## Sec. 12-607.1. Frame and floor height.
<p class='subsection'>\(a) No person shall operate upon a highway a first division vehicle which has a clearance between the frame and ground in excess of 22 inches. The lowest portion of the body floor shall not be more than 4 inches above the top of the frame. No such vehicle shall be modified to cause the vehicle body or chassis to come in contact with the ground, expose the fuel tank to damage from collision or cause the wheels to come in contact with the body under normal operation.</p><p class='subsection'>\(b) No person shall operate upon a highway a second division vehicle which has a clearance between the frame and ground which is in excess of the limits specified within this subsection for its gross vehicle weight rating (GVWR) category. For the purpose of this section, GVWR means the manufacturer's gross vehicle weight rating whether or not the vehicle is modified by the use of parts not originally installed by the manufacturer. The stacking or attaching of vehicle frames (one frame on top of or beneath another frame) is prohibited. No portion of the body floor shall be raised above the frame.</p><p class='paragraph'>\(1) The frame height of second division vehicles, whose GVWR is under 4,500 pounds, shall be no more than 24 inches.</p><p class='paragraph'>\(2) The frame height of second division vehicles, whose GVWR is more than 4,500 pounds and less than 7,500 pounds, shall be no more than 26 inches.</p><p class='paragraph'>\(3) The frame height of second division vehicles, whose GVWR is more than 7,500 pounds and less than 10,000 pounds, shall be no more than 28 inches.</p><p class='subsection'>\(c) Under subsections (a) or (b) of this Section, measurements shall be made when a vehicle is unladen on a level surface at the lowest point from the bottom of the original vehicle manufacturer's longitudinal frame rail between the front axle and second axle on the vehicle.</p><p class='subsection'>\(d) This Section does not apply to specially designed or modified motor vehicles when operated off the highways. Such motor vehicles may be transported upon the highway only by use of a trailer or semitrailer. The specially designed or modified motor vehicle may also be transported upon another vehicle, providing that the entire weight of the specifically designed or modified vehicle is resting upon the transporting vehicle.</p><p class='subsection'>\(e) Any violation of this Section is a Class C misdemeanor. A second conviction under this Section shall be punished with a fine of not less than $500. An officer making an arrest under this Section shall order the vehicle driver to remove the vehicle from the highway. A person convicted under this Section shall be ordered to bring his vehicle into compliance with this Section.</p><p>(Source: P.A. 90-89, eff. 1-1-98.)</p>### (625 ILCS 5/12-608) (from Ch. 95 1/2, par. 12-608)
## Sec. 12-608. Bumpers.
<p class='subsection'>\(a) It shall be unlawful to operate any motor vehicle with a gross vehicle weight rating of 9,000 pounds or less or any motor vehicle registered as a recreational vehicle under this Code on any highway of this State unless such motor vehicle is equipped with both a front and rear bumper.</p><p>Except as indicated below, maximum bumper heights of such motor vehicles shall be determined by weight category of gross vehicle weight rating (GVWR) measured from a level surface to the highest point of the bottom of the bumper when the vehicle is unloaded and the tires are inflated to the manufacturer's recommended pressure.</p><p>Maximum bumper heights are as follows:</p><p>Maximum Front</p><p>Maximum Rear</p><p>Bumper height</p><p>Bumper Height</p><p> All motor vehicles of the first</p><p>division except multipurpose</p><p>22 inches 22 inches</p><p> Multipurpose passenger vehicles</p><p> and all other motor vehicles:</p><p>4,500 lbs. and under GVWR</p><p>24 inches</p><p>26 inches</p><p>4,501 lbs. through 7,500</p><p>lbs. GVWR</p><p>27 inches 29 inches</p><p>7,501 lbs. through 9,000</p><p>lbs. GVWR</p><p>28 inches 30 inches</p><p>It is unlawful to operate upon any highway of this State any vehicle with a front bumper height that exceeds 28 inches or a rear bumper height that exceeds 30 inches, regardless of the GVWR of the vehicle, except those vehicles covered by Chapter 18b of this Code.</p><p>For any vehicle with bumpers or attaching components which have been modified or altered from the original manufacturer's design in order to conform with the maximum bumper requirements of this section, the bumper height shall be measured from a level surface to the bottom of the vehicle frame rail at the most forward and rearward points of the frame rail. The bumper on any vehicle so modified or altered shall be at least 4.5 inches in vertical height and extend no less than the width of the respective wheel tracks outermost distance.</p><p>However, nothing in this Section shall prevent the installation of bumper guards.</p><p class='subsection'>\(b) This Section shall not apply to street rods, custom vehicles, motor vehicles designed or modified primarily for off-highway purposes while such vehicles are in tow or to motorcycles or motor driven cycles, nor to motor vehicles registered as antique vehicles or expanded-use antique vehicles when the original design of such antique vehicles or expanded-use antique vehicles did not include bumpers. The provisions of this Section shall not apply to any motor vehicle driven during the first 1000 recorded miles of that vehicle, when such vehicle is owned or operated by a manufacturer, dealer or transporter displaying a special plate or plates as described in Chapter 3 of this Code while such vehicle is (1) being delivered from the manufacturing or assembly plant directly to the purchasing dealer or distributor, or from one dealership or distributor to another; (2) being moved by the most direct route from one location to another for the purpose of installing special bodies or equipment; or (3) being driven for purposes of demonstration by a prospective buyer with the dealer or his agent present in the cab of the vehicle during the demonstration.</p><p>The dealer shall, prior to the receipt of any deposit made or any contract signed by the buyer to secure the purchase of a vehicle, inform such buyer, by written statement signed by the purchaser to indicate acknowledgement of the contents thereof, of the legal requirements of this Section regarding front and rear bumpers if such vehicle is not to be equipped with bumpers at the time of delivery.</p><p class='subsection'>\(c) Any violation of this Section is a Class C misdemeanor. A second conviction under this Section shall be punishable with a fine of not less than $500. An officer making an arrest under this Section shall order the vehicle driver to remove the vehicle from the highway. A person convicted under this Section shall be ordered to bring his vehicle into compliance with this Section.</p><p>(Source: P.A. 97-412, eff. 1-1-12.)</p>### (625 ILCS 5/12-609) (from Ch. 95 1/2, par. 12-609)
## Sec. 12-609. (a) No official or employee of the State, any political subdivision thereof, any county, municipality, or local authority, and no owner or employee of any new vehicle dealer, used vehicle dealer, or vehicle auctioneer shall sell, trade or otherwise dispose of any motor vehicle bearing equipment, markings, or other indicia of police authority unless, prior to delivery of the vehicle, the equipment and markings have been sufficiently altered or obliterated to remove the appearance of such authority.
<p class='subsection'>\(b) A person may not operate on the highways of this State a vehicle bearing the equipment, markings, or other indicia of police authority, unless the vehicle is an authorized emergency vehicle as defined in Section 1-105 of this Code.</p><p class='subsection'>\(c) This Section does not apply to vehicles bearing indicia of police authority that are antique vehicles, as defined in Section 1-102.1, and are registered as antique vehicles, as provided in Section 3-804.</p><p class='subsection'>\(c-5) Nothing in this Section shall prohibit a manufacturer of authorized emergency vehicle equipment, markings, or other indicia, or the manufacturer's representative or authorized vendor, from temporarily mounting the equipment, markings, or other indicia on a vehicle for demonstration purposes only. If the equipment, markings, or other indicia are not covered while the vehicle is operated upon a highway, the vehicle shall display signage indicating that the vehicle is out of service or not an emergency vehicle. The signage shall be displayed on all sides of the vehicle in letters at least 2 inches tall and one-half inch wide.</p><p class='subsection'>\(d) Any police officer is authorized to seize any vehicle that is in violation of this Section and to impound that vehicle, at the owner's expense, until any equipment, markings, or other indicia of police authority have been sufficiently removed, altered, or obliterated to remove the appearance of police authority.</p><p class='subsection'>\(e) A person convicted of violating this Section is guilty of a petty offense and subject to a fine of not less than $500 and not more than $1,000.</p><p>(Source: P.A. 97-1173, eff. 1-1-14 .)</p>### (625 ILCS 5/12-610) (from Ch. 95 1/2, par. 12-610)
## Sec. 12-610. Headset receivers.
<p class='subsection'>\(a) Except as provided under Section 11-1403.3, no driver of a motor vehicle on the highways of this State shall wear headset receivers while driving.</p><p class='subsection'>\(b) This Section does not prohibit the use of a headset type receiving equipment used exclusively for safety or traffic engineering studies, by law enforcement personnel on duty, or emergency medical services and fire service personnel.</p><p class='subsection'>\(c) This Section does not prohibit the use of any single sided headset type receiving and transmitting equipment designed to be used in or on one ear which is used exclusively for providing two-way radio vocal communications by an individual in possession of a current and valid novice class or higher amateur radio license issued by the Federal Communications Commission and an amateur radio operator special registration plate or digital registration plate issued under Section 3-607 of this Code.</p><p class='subsection'>\(d) This Section does not prohibit the use of a single-sided headset or earpiece with a cellular or other mobile telephone.</p><p>(Source: P.A. 101-395, eff. 8-16-19.)</p>### (625 ILCS 5/12-610.1)
<p>(Text of Section before amendment by P.A. 102-982 )</p>## Sec. 12-610.1. Wireless telephones.
<p class='subsection'>\(a) As used in this Section, "wireless telephone" means a device that is capable of transmitting or receiving telephonic communications without a wire connecting the device to the telephone network.</p><p class='subsection'>\(b) A person under the age of 19 years who holds an instruction permit issued under Section 6-105 or 6-107.1, or a person under the age of 19 years who holds a graduated license issued under Section 6-107, may not drive a vehicle on a roadway while using a wireless phone.</p><p class='subsection'>\(b-5) A person under the age of 19 commits aggravated use of a wireless telephone when he or she violates subsection (b) and in committing the violation he or she was involved in a motor vehicle accident that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation was a proximate cause of the injury or death.</p><p class='subsection'>\(c) This Section does not apply to a person under the age of 19 years using a wireless telephone for emergency purposes, including, but not limited to, an emergency call to a law enforcement agency, health care provider, fire department, or other emergency services agency or entity.</p><p class='subsection'>\(d) If a graduated driver's license holder over the age of 18 committed an offense against traffic regulations governing the movement of vehicles or any violation of Section 6-107 or Section 12-603.1 of this Code in the 6 months prior to the graduated driver's license holder's 18th birthday, and was subsequently convicted of the violation, the provisions of paragraph (b) shall continue to apply until such time as a period of 6 consecutive months has elapsed without an additional violation and subsequent conviction of an offense against traffic regulations governing the movement of vehicles or any violation of Section 6-107 or Section 12-603.1 of this Code.</p><p class='subsection'>\(e) A person, regardless of age, may not use a wireless telephone at any time while operating a motor vehicle on a roadway in a school speed zone established under Section 11-605, on a highway in a construction or maintenance speed zone established under Section 11-605.1, or within 500 feet of an emergency scene. As used in this Section, "emergency scene" means a location where an authorized emergency vehicle as defined by Section 1-105 of this Code is present and has activated its oscillating, rotating, or flashing lights. This subsection (e) does not apply to (i) a person engaged in a highway construction or maintenance project for which a construction or maintenance speed zone has been established under Section 11-605.1, (ii) a person using a wireless telephone for emergency purposes, including, but not limited to, law enforcement agency, health care provider, fire department, or other emergency services agency or entity, (iii) a law enforcement officer or operator of an emergency vehicle when performing the officer's or operator's official duties, (iv) a person using a wireless telephone in voice-operated mode, which may include the use of a headset, (v) a person using a wireless telephone by pressing a single button to initiate or terminate a voice communication, or (vi) a person using an electronic communication device for the sole purpose of reporting an emergency situation and continued communication with emergency personnel during the emergency situation.</p><p class='subsection'>\(e-5) A person commits aggravated use of a wireless telephone when he or she violates subsection (e) and in committing the violation he or she was involved in a motor vehicle accident that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation was a proximate cause of the injury or death.</p><p class='subsection'>\(f) A person convicted of violating subsection (b-5) or (e-5) commits a Class A misdemeanor if the violation resulted in great bodily harm, permanent disability, or disfigurement to another. A person convicted of violating subsection (b-5) or (e-5) commits a Class 4 felony if the violation resulted in the death of another person.</p><p>(Source: P.A. 97-828, eff. 7-20-12; 97-830, eff. 1-1-13; 98-463, eff. 8-16-13; 98-507, eff. 1-1-14.)</p><p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 12-610.1. Wireless telephones.
<p class='subsection'>\(a) As used in this Section, "wireless telephone" means a device that is capable of transmitting or receiving telephonic communications without a wire connecting the device to the telephone network.</p><p class='subsection'>\(b) A person under the age of 19 years who holds an instruction permit issued under Section 6-105 or 6-107.1, or a person under the age of 19 years who holds a graduated license issued under Section 6-107, may not drive a vehicle on a roadway while using a wireless phone.</p><p class='subsection'>\(b-5) A person under the age of 19 commits aggravated use of a wireless telephone when he or she violates subsection (b) and in committing the violation he or she was involved in a motor vehicle crash that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation was a proximate cause of the injury or death.</p><p class='subsection'>\(c) This Section does not apply to a person under the age of 19 years using a wireless telephone for emergency purposes, including, but not limited to, an emergency call to a law enforcement agency, health care provider, fire department, or other emergency services agency or entity.</p><p class='subsection'>\(d) If a graduated driver's license holder over the age of 18 committed an offense against traffic regulations governing the movement of vehicles or any violation of Section 6-107 or Section 12-603.1 of this Code in the 6 months prior to the graduated driver's license holder's 18th birthday, and was subsequently convicted of the violation, the provisions of paragraph (b) shall continue to apply until such time as a period of 6 consecutive months has elapsed without an additional violation and subsequent conviction of an offense against traffic regulations governing the movement of vehicles or any violation of Section 6-107 or Section 12-603.1 of this Code.</p><p class='subsection'>\(e) A person, regardless of age, may not use a wireless telephone at any time while operating a motor vehicle on a roadway in a school speed zone established under Section 11-605, on a highway in a construction or maintenance speed zone established under Section 11-605.1, or within 500 feet of an emergency scene. As used in this Section, "emergency scene" means a location where an authorized emergency vehicle as defined by Section 1-105 of this Code is present and has activated its oscillating, rotating, or flashing lights. This subsection (e) does not apply to (i) a person engaged in a highway construction or maintenance project for which a construction or maintenance speed zone has been established under Section 11-605.1, (ii) a person using a wireless telephone for emergency purposes, including, but not limited to, law enforcement agency, health care provider, fire department, or other emergency services agency or entity, (iii) a law enforcement officer or operator of an emergency vehicle when performing the officer's or operator's official duties, (iv) a person using a wireless telephone in voice-operated mode, which may include the use of a headset, (v) a person using a wireless telephone by pressing a single button to initiate or terminate a voice communication, or (vi) a person using an electronic communication device for the sole purpose of reporting an emergency situation and continued communication with emergency personnel during the emergency situation.</p><p class='subsection'>\(e-5) A person commits aggravated use of a wireless telephone when he or she violates subsection (e) and in committing the violation he or she was involved in a motor vehicle crash that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation was a proximate cause of the injury or death.</p><p class='subsection'>\(f) A person convicted of violating subsection (b-5) or (e-5) commits a Class A misdemeanor if the violation resulted in great bodily harm, permanent disability, or disfigurement to another. A person convicted of violating subsection (b-5) or (e-5) commits a Class 4 felony if the violation resulted in the death of another person.</p><p>(Source: P.A. 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/12-610.2)
<p>(Text of Section before amendment by P.A. 102-982 )</p>## Sec. 12-610.2. Electronic communication devices.
<p class='subsection'>\(a) As used in this Section:</p><p>"Electronic communication device" means an electronic device, including, but not limited to, a hand-held wireless telephone, hand-held personal digital assistant, or a portable or mobile computer, but does not include a global positioning system or navigation system or a device that is physically or electronically integrated into the motor vehicle.</p><p class='subsection'>\(b) A person may not operate a motor vehicle on a roadway while using an electronic communication device, including using an electronic communication device to watch or stream video.</p><p class='subsection'>\(b-5) A person commits aggravated use of an electronic communication device when he or she violates subsection (b) and in committing the violation he or she is involved in a motor vehicle accident that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation is a proximate cause of the injury or death.</p><p class='subsection'>\(c) A violation of this Section is an offense against traffic regulations governing the movement of vehicles. A person who violates this Section shall be fined a maximum of $75 for a first offense, $100 for a second offense, $125 for a third offense, and $150 for a fourth or subsequent offense, except that a person who violates subsection (b-5) shall be assessed a minimum fine of $1,000.</p><p class='subsection'>\(d) This Section does not apply to:</p><p class='paragraph'>\(1) a law enforcement officer or operator of an</p><p>emergency vehicle while performing his or her official duties;</p><p class='paragraph'>\(1.5) a first responder, including a volunteer first responder, while operating his or her own personal motor vehicle using an electronic communication device for the sole purpose of receiving information about an emergency situation while en route to performing his or her official duties;</p><p class='paragraph'>\(2) a driver using an electronic communication device for the sole purpose of reporting an emergency situation and continued communication with emergency personnel during the emergency situation;</p><p class='paragraph'>\(3) a driver using an electronic communication device in hands-free or voice-operated mode, which may include the use of a headset;</p><p class='paragraph'>\(4) a driver of a commercial motor vehicle reading a message displayed on a permanently installed communication device designed for a commercial motor vehicle with a screen that does not exceed 10 inches tall by 10 inches wide in size;</p><p class='paragraph'>\(5) a driver using an electronic communication device while parked on the shoulder of a roadway;</p><p class='paragraph'>\(6) a driver using an electronic communication device when the vehicle is stopped due to normal traffic being obstructed and the driver has the motor vehicle transmission in neutral or park;</p><p class='paragraph'>\(7) a driver using two-way or citizens band radio services;</p><p class='paragraph'>\(8) a driver using two-way mobile radio transmitters or receivers for licensees of the Federal Communications Commission in the amateur radio service;</p><p class='paragraph'>\(9) a driver using an electronic communication device by pressing a single button to initiate or terminate a voice communication; or</p><p class='paragraph'>\(10) a driver using an electronic communication device capable of performing multiple functions, other than a hand-held wireless telephone or hand-held personal digital assistant (for example, a fleet management system, dispatching device, citizens band radio, or music player) for a purpose that is not otherwise prohibited by this Section.</p><p class='subsection'>\(e) A person convicted of violating subsection (b-5) commits a Class A misdemeanor if the violation resulted in great bodily harm, permanent disability, or disfigurement to another. A person convicted of violating subsection (b-5) commits a Class 4 felony if the violation resulted in the death of another person. (Source: P.A. 101-81, eff. 7-12-19; 101-90, eff. 7-1-20; 101-297, eff. 1-1-20; 102-558, eff. 8-20-21.)</p><p>(Text of Section after amendment by P.A. 102-982 )</p>## Sec. 12-610.2. Electronic communication devices.
<p class='subsection'>\(a) As used in this Section:</p><p>"Electronic communication device" means an electronic device, including, but not limited to, a hand-held wireless telephone, hand-held personal digital assistant, or a portable or mobile computer, but does not include a global positioning system or navigation system or a device that is physically or electronically integrated into the motor vehicle.</p><p class='subsection'>\(b) A person may not operate a motor vehicle on a roadway while using an electronic communication device, including using an electronic communication device to watch or stream video.</p><p class='subsection'>\(b-5) A person commits aggravated use of an electronic communication device when he or she violates subsection (b) and in committing the violation he or she is involved in a motor vehicle crash that results in great bodily harm, permanent disability, disfigurement, or death to another and the violation is a proximate cause of the injury or death.</p><p class='subsection'>\(c) A violation of this Section is an offense against traffic regulations governing the movement of vehicles. A person who violates this Section shall be fined a maximum of $75 for a first offense, $100 for a second offense, $125 for a third offense, and $150 for a fourth or subsequent offense, except that a person who violates subsection (b-5) shall be assessed a minimum fine of $1,000.</p><p class='subsection'>\(d) This Section does not apply to:</p><p class='paragraph'>\(1) a law enforcement officer or operator of an</p><p>emergency vehicle while performing his or her official duties;</p><p class='paragraph'>\(1.5) a first responder, including a volunteer first responder, while operating his or her own personal motor vehicle using an electronic communication device for the sole purpose of receiving information about an emergency situation while en route to performing his or her official duties;</p><p class='paragraph'>\(2) a driver using an electronic communication device for the sole purpose of reporting an emergency situation and continued communication with emergency personnel during the emergency situation;</p><p class='paragraph'>\(3) a driver using an electronic communication device in hands-free or voice-operated mode, which may include the use of a headset;</p><p class='paragraph'>\(4) a driver of a commercial motor vehicle reading a message displayed on a permanently installed communication device designed for a commercial motor vehicle with a screen that does not exceed 10 inches tall by 10 inches wide in size;</p><p class='paragraph'>\(5) a driver using an electronic communication device while parked on the shoulder of a roadway;</p><p class='paragraph'>\(6) a driver using an electronic communication device when the vehicle is stopped due to normal traffic being obstructed and the driver has the motor vehicle transmission in neutral or park;</p><p class='paragraph'>\(7) a driver using two-way or citizens band radio services;</p><p class='paragraph'>\(8) a driver using two-way mobile radio transmitters or receivers for licensees of the Federal Communications Commission in the amateur radio service;</p><p class='paragraph'>\(9) a driver using an electronic communication device by pressing a single button to initiate or terminate a voice communication; or</p><p class='paragraph'>\(10) a driver using an electronic communication device capable of performing multiple functions, other than a hand-held wireless telephone or hand-held personal digital assistant (for example, a fleet management system, dispatching device, citizens band radio, or music player) for a purpose that is not otherwise prohibited by this Section.</p><p class='subsection'>\(e) A person convicted of violating subsection (b-5) commits a Class A misdemeanor if the violation resulted in great bodily harm, permanent disability, or disfigurement to another. A person convicted of violating subsection (b-5) commits a Class 4 felony if the violation resulted in the death of another person. (Source: P.A. 101-81, eff. 7-12-19; 101-90, eff. 7-1-20; 101-297, eff. 1-1-20; 102-558, eff. 8-20-21; 102-982, eff. 7-1-23.)</p>### (625 ILCS 5/12-610.5)
## Sec. 12-610.5. (Repealed).
<p>(Source: P.A. 97-672, eff. 7-1-12. Repealed by P.A. 97-743, eff. 1-1-13.)</p>### (625 ILCS 5/12-611) (from Ch. 95 1/2, par. 12-611)
## Sec. 12-611. No driver of any motor vehicle within this State shall operate or permit operation of any sound amplification system which can be heard outside the vehicle from 75 or more feet when the vehicle is being operated upon a highway, unless such system is being operated to request assistance or warn of a hazardous situation.
<p>This Section does not apply to authorized emergency vehicles.</p><p>Any violation of the provisions of this Section shall be a petty offense punishable by a fine not to exceed $50.</p><p>(Source: P.A. 91-919, eff. 1-1-01.)</p>### (625 ILCS 5/12-612)
## Sec. 12-612. False or secret compartment in a vehicle.
<p class='subsection'>\(a) Offenses. It is unlawful for any person:</p><p class='paragraph'>\(1) to own or operate with criminal intent any</p><p>vehicle he or she knows to contain a false or secret compartment that is used or has been used to conceal a firearm as prohibited by paragraph (a)(4) of Section 24-1 or paragraph (a)(1) of Section 24-1.6 of the Criminal Code of 2012, or controlled substance as prohibited by the Illinois Controlled Substances Act or the Methamphetamine Control and Community Protection Act; or</p><p class='paragraph'>\(2) to install, create, build, or fabricate in any vehicle a false or secret compartment knowing that another person intends to use the compartment to conceal a firearm as prohibited by paragraph (a)(4) of Section 24-1 of the Criminal Code of 2012, or controlled substance as prohibited by the Illinois Controlled Substances Act or the Methamphetamine Control and Community Protection Act.</p><p class='subsection'>\(b) Definitions. For purposes of this Section: (1) "False or secret compartment" means an enclosure</p><p>integrated into a vehicle that is a modification of the vehicle as built by the original manufacturer.</p><p class='paragraph'>\(2) "Vehicle" means any of the following vehicles without regard to whether the vehicles are private or commercial, including, but not limited to, cars, trucks, buses, aircraft, and watercraft.</p><p class='subsection'>\(c) Forfeiture. Any vehicle containing a false or secret compartment used in violation of this Section, as well as any items within that compartment, shall be subject to seizure by the Illinois State Police or by any municipal or other local law enforcement agency within whose jurisdiction that property is found as provided in Sections 36-1 and 36-2 of the Criminal Code of 2012. The removal of the false or secret compartment from the vehicle, or the promise to do so, shall not be the basis for a defense to forfeiture of the motor vehicle under Section 36-2 of the Criminal Code of 2012 and shall not be the basis for the court to release the vehicle to the owner. (d) Sentence. A violation of this Section is a Class 4 felony. The sentence imposed for violation of this Section shall be served consecutively to any other sentence imposed in connection with the firearm, controlled substance, or other contraband concealed in the false or secret compartment.</p><p class='subsection'>\(e) For purposes of this Section, a new owner is not responsible for any conduct that occurred or knowledge of conduct that occurred prior to transfer of title.</p><p>(Source: P.A. 102-538, eff. 8-20-21.)</p>### (625 ILCS 5/12-613)
## Sec. 12-613. Possession and use of radar or laser jamming devices prohibited.
<p class='subsection'>\(a) Except as provided in subsection (b), a person may not operate or be in actual physical control of a motor vehicle while the motor vehicle is equipped with any instrument designed to interfere with microwaves or lasers at frequencies used by police radar for the purpose of monitoring vehicular speed.</p><p class='subsection'>\(b) A person operating a motor vehicle who possesses within the vehicle a radar or laser jamming device that is contained in a locked opaque box or similar container, or that is not in the passenger compartment of the vehicle, and that is not in operation, is not in violation of this Section.</p><p class='subsection'>\(c) Any person found guilty of violating this Section is guilty of a petty offense. A minimum fine of $50 shall be imposed for a first offense and a minimum fine of $100 for a second or subsequent offense.</p><p class='subsection'>\(d) The radar or laser jamming device or mechanism shall be seized by the law enforcement officer at the time of the violation. This Section does not authorize the permanent forfeiture to the State of any radar or laser jamming device or mechanism. The device or mechanism shall be taken and held for the period when needed as evidence. When no longer needed for evidence, the defendant may petition the court for the return of the device or mechanism. The defendant, however, must prove to the court by a preponderance of the evidence that the device or mechanism will be used only for a legitimate and lawful purpose.</p><p class='subsection'>\(e) A law enforcement officer may not stop or search any motor vehicle or the driver of any motor vehicle solely on the basis of a violation or suspected violation of this Section.</p><p>(Source: P.A. 94-594, eff. 1-1-06; 95-331, eff. 8-21-07.)</p>